name: Lint & Build Code Base

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Lint & Build Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn

      - name: Apply Patches
        run: npx patch-package

      - name: Lint Code Base
        run: yarn lint

      - name: Unit tests
        run: yarn test:ci

      # - name: Android build
      #   run: yarn android:buildProd

      # - name: iOS Build
      #   run: yarn ios:prod

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
