export enum BLOCKLIST_APP_CATEGORY {
  GAME = "Game",
  NEWS = "News",
  SOCIAL = "Social",
  MISC = "Misc",
}

export const CATEGORY_TO_FILTER_GROUP: Record<string, BLOCKLIST_APP_CATEGORY> = {
  // Social group
  SOCIAL: BLOCKLIST_APP_CATEGORY.SOCIAL,
  DATING: BLOCKLIST_APP_CATEGORY.SOCIAL,
  MESSAGING: BLOCKLIST_APP_CATEGORY.SOCIAL,

  // Games group
  GAME: BLOCKLIST_APP_CATEGORY.GAME,

  // News group
  NEWS: BLOCKLIST_APP_CATEGORY.NEWS,
  NEWS_AND_MAGAZINES: BLOCKLIST_APP_CATEGORY.NEWS,
};
