import { i18n } from "@/localization";

export const APIURLS = {
  accountSync: "user/account-sync",
  userSettings: (userTimeZone) => `user-settings?timezone=${userTimeZone}`,
  completedActivity: "completed-activity",
  syncCompletedActivities: "completed-activity/sync",
  userDetails: "user/details",
  userCurrentActivityProps: "user/details/current-activity-props",
  forceCompleteCurrentSequence: (activity_sequence_id, cancel_habits_for_today) =>
    `completed-activity-sequence/${activity_sequence_id}/force-complete-current-sequence?cancel_habits_for_today=${cancel_habits_for_today}`,
  userLocalDeviceSettings: "user-local-device-settings",
  updateUserSettings: "user-settings",
  device: "device",
  devicePushRegistration: "device/push-registration",
  pusherAuth: "pusher/user-auth",
  focusMode: "focus-mode",
  userFocusModes: "user/focus-modes",
  blockingSchedules: "blocking-schedules",
  blockingScheduleDetail: (schedule_id) => `blocking-schedules/${schedule_id}`,
  focusModeStart: (focus_mode_id) => `focus-mode/${focus_mode_id}/start`,
  focusModeFinish: (focus_mode_id) => `focus-mode/${focus_mode_id}/finish`,
  focusModeUpdateScheduledFinish: (focus_mode_id) => `/focus-mode/${focus_mode_id}/update_scheduled_finish`,
  tracks: "tracks",
  toDo: "to-do",
  toDoSearch: "to-do/search",
  defaultHabitPackList: `habit-packs?featured_for_onboarding=true&breaks_only=false&language=${i18n.language}`,
  installDefaultHabitPack: (pack_id) => `habit-packs/default?pack_id=${pack_id}`,
  installHabitPack: (pack_id) => `habit-packs/${pack_id}/install`,
  userInstalledHabitPacks: "habit-packs/user-packs",
  userData: "user-data",
  userSubscription: "user/subscription",
  appLogsGetUploadUrl: (filename, mimetype) => `app-logs/upload-logs-url?filename=${filename}&mimetype=${mimetype}`,
  appLogsNotifyUploadSuccess: "app-logs/notify-upload-success",
  skipHabitActivity: "completed-activity/skip",
  longTermGoals: "user/long-term-goals",
  userConsent: "user/consent",
  events: "events",
  syncSignupUserPlatform: "course/sync-platform-courses",
  forgotPassword: "auth/reset-password",
  sendEmailVerification: "auth/send-email-verification",
  updateUsername: "user/username",
  studyParticipants: {
    addParticipantDetails: "study-participants/add-participant-details",
    verifyParticipantCode: "study-participants/verify-participant-code",
    linkUserToParticipantCode: "study-participants/link-user-to-participant-code",
    getCodeActivationStatus: (participantCode) =>
      `study-participants/get-code-activation-status?participantCode=${participantCode}`,
    getParticipantLastReceivedData: "study-participants/get-participant-last-received-data",
    markCompleteQuestionnaire: "study-participants/mark-complete-questionnaire",
    saveFlankerTestResult: "study-participants/save-flanker-test-result",
    markCompleteEoSQuestionnaire: "study-participants/mark-eos-questionnaire-completed",
  },
  getTaskStatus: (taskId) => `async-task/${taskId}`,
  usageDataSync: "usage-data/sync",
  healthDataSync: "health-metrics/sync",
  generateUploadImageUrl: "usage-data/generate-upload-image-url",
  processUploadedImage: "usage-data/usage-image-uploaded",
  generateTodoUploadImageUrl: "to-do/generate-upload-image-url",
  todoImageUploaded: "to-do/todo-image-uploaded",
  generateTodoUploadAudioUrl: "to-do/generate-upload-audio-url",
  todoAudioUploaded: "to-do/todo-audio-uploaded",
  routineSuggestion: `activity-library/routine-suggestions/async`,
  adjustHabitsWithAI: "activity-library/adjust-habits-with-ai",
  createHabitsWithAIAsync: "activity-library/habits/ai/async",
  videoMetadata: "video-metadata",
  habitImportGenerateUploadUrl: "activity-library/habits/import/generate-upload-url",
  habitImportAsync: "activity-library/habits/import/async",
  focusModeDetail: "focus-mode",
  calendarEvents: (platform) => `calendar/${platform}/events`,
  calendarData: (platform) => `calendar/${platform}/calendar-datas`,
  focusModeTags: "focus-mode/tags",
  userOnboardingStats: "user/stats/onboarding",
};
