export default {
  languageName: "Cheerleader English",
  baseLanguage: "en",
  error: {
    invalidVideoUrl: "Oh no! That YouTube video URL isn't right! 📹",
    videoNotFound: "Uh-oh! We couldn't find that video!",
  },
  habitSetting: {
    routineSelection: "Routine 🌟",
    requirement: "Take action to rock this habit! 💪",
    youtubeVideo: "YouTube or Vimeo video 🎥",
    youtubeVideoDescription: "Add a video to get motivated! 📹",
    enableTimer: "Enable timer ⏳",
  },
  common: {
    learnMore: "Let's dive in and learn more! 💪",
    doItLater: "No worries, we’ll do it later! You got this! 🌟",
    skip: "Skip ⏭️",
    goToSleep: "Time to snooze, superstar! 😴",
    areYouSure: "Are you toootally sure? 🤔",
    loading: "Loading... Get pumped! 🚀",
    connectionError: "Uh-oh! Connection error! 🌐",
    morning: "morning",
    evening: "evening",
    welcome: "Welcome, rockstar! 🎉",
    somethingWrong: "Oh no! Something went wrong! 😱",
    logout: "Time to log out, superstar! 👋",
    ok: "OK, let’s go! 👍",
    ok_ellipsis: "OK, let’s go...",
    okay: "Okay, let’s go! 👍",
    confirm: "You got it! Confirmed! ✅",
    next: "On to the next, let’s go! 🚀",
    cancel: "Cancel?",
    proceed: "Proceed! 🏆",
    resume: "Resume ! 🎉",
    retry: "Retry! 🔄",
    submit: "Submit! 🚀",
    verify: "Verify, let’s keep it secure! 🔒",
    finished: "You did it! Finished! 🎊",
    sec: "sec",
    focusBear: "focus bear",
    tomorrow: "tomorrow",
    today: "today",
    save: "Save it, superstar! 💾",
    startRoutine: "Let’s kick off this routine! 🚀",
    continue: "Keep it going! 💪",
    end: "End",
    startActivity: "Start your fabulous {activityName}! 🎈",
    startTimerActivity: "Start that timer for {time} {unit} of {activityName}! ⏳",
    Success: "Success! We did it! 🎉",
    save_changes: "Save those changes! 💾",
    saving: "Saving... ⏳",
    next_time_format: "[{day} at] h:mm A",
    sure: "Absolutely! 👍",
    uploadScreenShots: "Upload those screenshots, superstar! 📸\n(Optional)",
    session_expired: "Session expired!",
    login_again: "Please log in again, superstar! 🚀",
    continue_activity_name: "Keep going with {activityName}! 🎉",
    no_thanks: "No thanks? That's cool! ✌️",
    saveHabitSuccessfully: "You saved your habit successfully! 🎊",
    granted: "All set!",
    notGranted: "Not quite there yet",
  },
  lateNoMore: {
    title: "Meeting Reminders",
    calendarIntegration: "Calendar Integration",
    calendarTooltip: "To enable meeting detection you can connect your phone's calendar or your Google calendar",
    googleCalendar: "Google Calendar",
    connected: "Connected",
    notConnected: "Not connected",
    enableReminders: "Reminder Notifications",
    calendarPermission: "Device Calendar",
    calendarPermissionAlreadyGranted:
      "Device Calendar is connected. You can revoke access at any time via your phone's settings",
    calendarPermissionDenied: "Please grant calendar access permission in your phone's settings",
    openSettings: "Open settings",
    addReminder: "Add reminder",
    durationBefore: "{duration} before",
    whenMeetingStarts: "When meeting starts",
    requireMeetingUrl: "Events with Meetings Only",
    requireMeetingUrlDescription: "Only include events that have a meeting URL attached",
    // Notification messages
    notification1: "Meeting starting soon! 🐻✨",
    notification2: "Get ready to head to your meeting! ⏰🌟",
    notification3: "Your meeting is waiting! 📅💪",
    notificationBody: "'{title}' starts {time}!",
    now: "now",
    // Meeting Preparation UI
    yourMeetingStartsIn: "Meeting in <highlight>{countdown}</highlight>. Let's get ready!",
    yourMeetingIsOngoing: "There's an ongoing meeting. Join <highlight>now</highlight>!",
    upcomingMeeting: "Upcoming event",
    mentallyPrepare: "1. Mentally prepare for the meeting",
    howDoYouWantToShowUp: "How do you want to show up?",
    placeholderHowToShowUp: "Calm, listening, open-minded, collaborative...",
    joinOnTime: "2. Join on time",
    ignoreMeeting: "Ignore meeting",
    startMeeting: "Join meeting",
    noUpcomingMeetings: "No upcoming meetings",
    noMeetingsDescription: "We didn't find any meetings scheduled in the next few hours.",
    // Calendar source indicators
    googleCalendarSource: "Source: Google calendar",
    deviceCalendarSource: "Source: On-device calendar",
  },
  settings: {
    debugLog: "Enable detailed logging?",
    debugLogDescription: "Only turn this on if the support team asks you to, it might slow things down! ⚠️",
    title: "Settings ⚙️",
    addApps: "Add apps, let’s focus!",
    clearBlocklist: "Clear that blocklist! ✨",
    confirmClearBlocklist: "Are you sure you want to clear the blocklist? 🤔",
    strictness: "Strictness level: Let’s get serious! 💪",
    shareLogsWithSupport: "Share logs 🤝",
    reason_required: "Please enter a reason, superstar! ✍️",
    enter_a_reason: "Why do you want to delete your account? Let’s chat! 💬",
    contact_desc: "Can we contact you to help fix those pesky issues? 📞",
    editFriction: "Friction ⚙️",
    password: "Password 🔑",
    account: "Your account 🛠️",
    permissions: "Permissions🛡️ ",
    language: "Language 🗣️",
    useSystemLanguage: "Use system language!",
    supportedLanguages: "Supported languages 🌍",
    overlay_permission: "Overlay Permission 🔧",
    usage_permission: "Usage Permission 📊",
    notification_permission: "Notification Permission 🔔",
    screen_time_permission: "Screen Time Permission ⏳",
    DND_permission: "Do Not Disturb Permission 🤫",
    DND: "Do Not Disturb! 🤫",
    warning: "Warning! ⚠️",
    DND_permissionWarning:
      "DND mode must be manually disabled if it's already enabled. It cannot be turned off automatically if DND permissions are not granted. ⚠️",
    help: "Help 📢",
    report_problem: "Report a problem, let’s fix it! 🛠️",
    discord_server: "Join our Discord server, let’s chat! 💬",
    videoTutorials: "Check out our video tutorials, let’s learn! 🎥",
    experimental: "Experimental 🚀",
    customization: "Customization 🎨",
    general: "General",
    allowed: "Allowed 🎉",
    notAllowed: "Not granted 🚫",
    userid: "User ID 🆔",
    copy: "Copy that! 📋",
    copied: "Copied! 🎉",
    verifyEmail: "Verify your email! 🔒",
    editNickname: "Let's get you a cool nickname! ✨",
  },
  focus: {
    title: "Focus ⏲️",
    focusLimitReachedTitle: "Focus limit reached, but you’re amazing! 🌟",
    focusLimitReachedMessage:
      "In the free version, you can only focus for up to 25 minutes. Upgrade to premium if you want longer focus sessions! 🚀",
    upgrade: "Upgrade to unlock more awesomeness! 🎉",
  },
  home: {
    setupHabitsDescription: "Setup your habits to start your day, superstar! 🌟",
    getMotivated: "Let's get motivated!",
    habitName: "What’s your habit name, superstar? 🌟",
    newHabit: "New habit, let’s create it! 🎉",
    duration: "Duration",
    editHabit: "Edit habit",
    addHabit: "Add habit",
    deleteThisHabit: "Delete this habit? Are you sure? 🤔",
    deleteHabit: "Delete habit {name}, let’s do it! 🚫",
    afterCutoffTimeDescription: "None of your habits are available because it's past the cutoff time! ⏰",
    cutOffToolTip:
      "You've configured cutoff times for your habits so that they're not accessible after {cutOffTime}. You can modify this in Change timing! ⏳",
    unlockToProceed: "Unlock to proceed, let’s keep going! 🔑",
    title: "Habits ✅",
    morningRitual: "Your morning ritual, let’s shine! ☀️",
    eveningRitual: "Your evening ritual, let’s wind down! 🌙",
    time_to_earn_screen_time: `Do your morning routine habits to set yourself up for an awesome day! 🌟`,
    evening_routine_text: "You'll be ready for a great night's sleep when you're done! 😴",
    upcoming_below_new_activities:
      "Below are the habits you need to accomplish in the next upcoming routine to use your mobile! 📱",
    start: "Start",
    mins: "mins",
    secs: "secs",
    re_activate: "Re-Activate, let’s get back in the game! 🎉",
    force_deactivate_postpone_and_start_routine: "Routine has been postponed! Resume routine? 🤔",
    userCompletedMorningRoutineHeading:
      "Well done for finishing your morning routine! 🎉 Look forward to helping you with your evening routine! {routineTime} 🌙",
    postOnboardingRoutineHeading:
      "Welcome onboard! 🎉 Look forward to helping you with your {routineName} routine {routineTime}! 🌟",
    userCompletedEveningRoutineHeading:
      "Well done for finishing your evening routine! 🎊 Look forward to helping you with your morning routine! {routineTime} ☀️",
    wantLogout: "Do you want to log out? Let’s chat! 🤔",
    noDataFound: "You haven't set up any habits yet. Tap <fix>here</fix> to add habits! 🎉",
    routineFetchingError:
      "We encountered an issue while retrieving routine data. Please try again later or reach out to us for assistance! 📞",
    hi: "Hi {nickname}! 👋",
    goodMorningFocusTime: "Good Morning! Let’s shine! ☀️", // unused
    goodEveningFocusTime: "Good Evening! Let’s wind down! 🌙", // unused
    allActivitiesCompleted: "No habits left to complete! You did it! 🎉",
    startRoutineNow: "Do My {routineName} Routine, let’s go! 🚀",
    passwordForSettingsTitles: "Enter password to proceed, superstar! 🔑",
    manageAlwaysAllowedAppsDesc:
      "During your morning/evening routine and when you are focusing on your computer, all apps on your phone apart from the Always Allowed Apps will be blocked. We suggest only allowing apps like SMS, phone and apps you need for work so you don't get distracted during your habits/work! 📱",
    manageAlwaysBlockedAppsDesc:
      "During your morning/evening routine and when you are focusing on your computer, all the apps in your block list will be blocked. We suggest blocking social media, gaming, email and news apps so you don't get distracted during your habits/work! 🚫",
    overlayPermission: "overlayPermission",
    usagePermission: "usagePermission",
    editHabits: "Edit Habits 🔧",
    editYourHabits: "Edit your habits 🔧",
    stats: "Stats 📊",
    motivationMsg: "Get Motivated! 💪",
    play: "Play",
    pause: "Pause",
    customizeHabits: "Edit routines ↕️",
    deleteAccount: "Delete Account?",
    accountDataHasBeen: "Account data has been deleted successfully! Thanks for using Focus Bear! 🎉",
    blockSuperDistractingApps: "Block super distracting sites/apps, let’s focus! 🚫",
    skipHabitDesc: "Skip this habit today? Let’s keep it moving! ✋",
    screenTimePermissionNotAllowedWarningText:
      "Screentime permission is needed to block apps, start a habit again to allow permissions! 🚫",
    OverlayPermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Overlay permission not granted. Fix it! 🔧",
    ScreenTimePermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Screen Time permission not granted. Fix it! 🔧",
    UsagePermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Usage permission not granted. Fix it! 🔧",
    noAllowedAppSelectedWarning:
      "Warning: you haven't configured your block list yet so distractions won't be blocked. Edit Blocklist! 🚫",
    habitLimitMessage:
      "Free users can only access up to 3 habits per routine. Please upgrade to unlock more habits! 🎉",
    routineOptionsTooltip: "This menu lets you edit your routine or change its timing. You’ve got this! 🎯",
  },
  postpone: {
    doYouReallyWantTo: "Do you really want a timeout? 🤔",
    blockingPausedForDuration: "Taking a quick {duration} timeout! You've got this! 🎯",
    blockingPausedIndefinitely: "Break time until you're ready to crush it again! 🌟",
    pauseBlocking: "Let's pause! ⏸✋",
    pauseDisabledStrictMode: "Super Strict Mode is on! Stay strong, you’ve got this!",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Get back in the game! 🏃‍♀️",
    choosePostponeTime: "How long do you need, superstar? ⏱️",
    indefinite: "Pause until I'm ready to rock again! 🎸",
    youHavePausedTimesToday_zero: "This is your first time pausing today! 🎉",
    youHavePausedTimesToday_one: "You have paused once today! 🌟",
    youHavePausedTimesToday_other: "You have already paused {count} times today! ✨",
    countdown: "You can pause again after {countdown}",
    areYouSureIndefinite:
      "Taking an open-ended break? Remember champion - that urgent task might only need 15 tiny minutes to wait! Keep crushing those habits! 🌟",
    doHabits: "Let's crush these habits! 💪",
    longTermGoalsDesc: "Remember your amazing goals with Focus Bear, superstar! 🌟",
    lowQualityUsageDesc: "Heads up champion! You've spent {duration} on distracting apps today! Let's refocus! 🎯",
    write: "Let’s express! ✍️",
  },
  passwordForSettings: {
    invalid_password: "Oops! Password is invalid! 🔑",
    resetAfter24Hours: "Reset requested. Your password will be disabled after 24 hours.",
  },
  signIn: {
    logIn: "Log in and get started! 🚀",
    enterEmailHint: "Email Address",
    enterPasswordHint: "Password",
    invalidCredentials: "Invalid Username/Password, let’s try again! 🤔",
    enterEmailError: "Please enter email, superstar! 📧",
    enterValidEmailError: "Please enter valid email, let’s go! 📧",
    enterPasswordError: "Please enter password, keep it safe! 🔑",
    dontHaveAccount: "Don't have an account?",
    forgotPassword: "Forgot Password?",
    signup: "Sign up",
    googleSignIn: "Continue with Google",
    alreadyHaveAccount: "I already have a Focus Bear account",
  },
  forgotPassword: {
    forgotPasswordTitle: "Forgot Password",
    backToSignIn: "Back To Sign In",
  },
  signUp: {
    signUp: "Sign Up",
    tosAndPP: "I agree to the <bold>Terms of Service</bold> and <bold1>Privacy Policy</bold1>",
    alreadyHaveAccount: "Already have an account?",
    passwordMatchError: "Password and confirm password does not match",
    acceptTerms: "Please agree to the Terms of Service and Privacy Policy to continue",
    passwordHintError: `Password Must Contain:
    • At least 8 characters
    • Numbers (0-9)
    • Lowercase letters (a-z)
    • Uppercase letters (A-Z)
    • Special characters (!@#$%^&*)`,
    invalidSignup: "Invalid sign up",
    userExists: "The user already exists.",
    terms: "Terms",
    privacy: "Privacy",
    or: "OR",
  },
  profile: {
    logout: "Logout",
  },
  routineDetail: {
    activity: "Activity",
    not_playable_video: "Not able to play video 😢",
    done: "I'm done",
    video: "Video",
    images: "Images",
    checklist: "Checklist",
    note: "Note",
  },
  quickBreak: {
    quickBreak: "Quick Breaks, let’s recharge! 🔋",
    quickStretch: "Stretch time! 💪",
    stretch: "Let’s stretch! 💪",
    drinkWater: "Drink Water, stay hydrated! 💧",
    water: "Water 💧",
    deepBreathing: "Deep Breathing, let’s relax! 🌬️",
    breathe: "Breathe 🌬️",
    saveQuickBreakSuccessfully: "Your changes are saved successfully, yay! 🎊",
    editQuickBreaks: "Edit Your Awesome Quick Breaks! 🌟",
    quickBreakName: "Quick break name, let's go! 🚀",
    currentSelection: "Current selection, looking good! 👍",
  },
  complete: {
    backToHome: "Back to Home, let’s celebrate! 🎉",
    logQuantity: "Log Quantity of activity, let’s track it! 📊",
    finishedCheck: "finished! 🎉",
    habitNotCompleted: "habit not completed! 😱 Try again tomorrow! 🌟",
    finishedAndEarnedMorning: "Finished! ✅ You've earned your screen time! 🎉",
    finishedAndEarnedEvening: "Finished! ✅ You've earned a good night's sleep. See you tomorrow morning! 🌙",
    why_skip: "Why do you want to skip? 🤔",
    already_did: "I already did it! 🎉",
    cannot_today: "Can't do it today ✋",
    quantity_input_error: "Number needs to be between {min} and {max}. Let’s get it right! 🤔",
    freemiumLimitReached: "Sorry, you can only complete 3 habits with a free plan. Let’s upgrade! 🎉",
  },
  reason: {
    canShare: "Can you share why you're pausing indefinitely? 💬",
    shareFeedback: "Share your feedback",
    everythingIsOk: "Uh oh - hope everything is ok! Giving you access now! 🌟",
    appBrokenDesc: "Really sorry about that! Would you mind telling us what happened? 💬",
    somethingElseDesc: "Ok! Is there any feedback you want to share with us? 💬",
    gotEmergency: "I've got an emergency",
    appBroken: "The app is broken",
    somethingElse: "Something else",
  },
  nativeModule: {
    backgroundService: "Focus bear background service to help you focus, let’s do this! 🐻",
  },
  notification: {
    scheduleNotificationTitleForResumeRoutine: "Resume your routine, superstar! 🎉",
    scheduleNotificationDescriptionForResumeRoutine: "It is time to focus on your routine, let’s go! 🚀",
    floatingModuleActivityCompleteNotificationtitle: "Activity Completed, you did it! 🎉",
    floatingModuleRoutineCompleteNotificationtitle: "Routine Completed, let’s celebrate! 🎊",
    morningRoutineCompletedNotificationDescription: "Morning routine completed! You're crushing it! 🌟",
    eveningRoutineCompletedNotificationDescription: "Evening routine completed! Sleep well! 🌙",
    customRoutineCompletedNotificationDescription: "{{routineName}} completed! Amazing work! 🎉",
  },
  focusMode: {
    blockingPermissionNeeded: "P-E-R-M! You need it!",
    noBlockingAppsSelected: "Pick apps! Let’s go!",
    confirmSuperStrictMode:
      "Ready for Super Strict Mode? You’ll be locked in until the timer’s done—focus time, yay! 🎯",
    focusTitle: "Start a focus session!",
    superStrictToolTip:
      "Committed to this focus session? Enable super strict mode and you won't be able to turn focusing off or pause app blocking until the timer is up! ⏳",
    superStrictMode: "Super strict mode, let’s focus!",
    brainDump: "Brain dump",
    brainDumpToolTip: "Write down any distracting thoughts here. It will help you focus better! ✍️",
    postFocusCongrats_0: "Nice work! You crushed it! 🎉",
    postFocusCongrats_1: "Hey, great job finishing that! What’s up next? 🚀",
    postFocusCongrats_2: "You did it! Feel free to take a breather now! 🌬️",
    postFocusCongrats_3: "Well done! You're really getting things done! 🎉",
    postFocusCongrats_4: "Awesome job! What’s the next thing on your radar? 🌟",
    postFocusCongrats_5: "You made it through! Time to tackle the next one? 🚀",
    postFocusCongrats_6: "Great focus! Go grab a drink or a snack! 🍹",
    postFocusCongrats_7: "Nice! You’re making serious progress! 🎉",
    postFocusCongrats_8: "Well done! Time to stretch your legs a bit? 🦵",
    postFocusCongrats_9: "You did great! Let’s keep that momentum going! 🚀",
    startFocusSession: "Start a focus session, let’s go! 🎯",
    noIntentionWasFound: "No intention entered, let’s set one! 🎯",
    distractionAlertTitle: "Focus Mode, let’s stay on track! 🚀",
    userIntention: "Focus Goal",
    noDistractingThoughtsWasFound: "No distracting thoughts entered, let’s keep it focused! 🚫",
    userIntentionTextInputPlaceholder: "What do you want to work on? Let’s go! ✍️",
    startFocusing: "Start Focusing, let’s do this! 🚀",
    hours: "h",
    minutes: "m",
    duration: {
      hours: "{hours} hours",
      minutes: "{minutes} minutes",
      seconds: "{seconds} seconds",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "You got this! Deep work time, let’s shine! 🌟",
    endSession: "End Session 🚫",
    completeFocus: "Complete Focus, you did it! 🎉",
    userDumpThoughTextInputDescription: "Write down any distracting thoughts here, let’s clear them out! ✍️",
    exitFocusMode: "End focus session early, let’s chat! 🤔",
    exitFocusModeDescription: "Can you share why you’re ending this session?",
    reason: "Reason",
    selectReason: "Select a reason",
    congratulations: "Congratulations! You did it! 🎉",
    focusDoneTitle: "YOU DID IT!",
    focusDoneDescription: "You remained focused for, let’s celebrate! 🎉",
    focusDoneDescription1: "What was your intention? Let’s reflect! 🤔",
    focusDoneDescription4: "What were your distracting thoughts? Let’s clear them out! ✍️",
    focusDoneDescription2: "What did you achieve during this time? Let’s celebrate! 🎉",
    focusDonePlaceholderDescription2: "Enter what you achieved with our help, let’s share! ✍️",
    focusDoneDescription3: "Did you have any distractions? Let’s talk! 🤔",
    focusDonePlaceholderDescription3: "Enter any distractions you had, let’s clear them out! ✍️",
    endEarlyReasonDescription1: "I have an emergency",
    endEarlyReasonDescription2: "Focus mode is not working properly",
    endEarlyReasonDescription3: "I have achieved what I wanted to",
    endEarlyReasonDescription4: "I need a break",
    runningFocusModeDesc: "A focus session is running 🚀",
    extendFocusDuration: "Extend Focus Duration⏳",
    shortenFocusDuration: "Shorten Focus Duration⏱️",
    selectExtendFocusDuration: "How much longer do you want to focus for? 🤔",
    selectShortenFocusDuration: "How much time do you want to shorten? 🤔",
    extendFocus: "Extend",
    shortenFocus: "Shorten",
    adjustFocusDuration: "Adjust Focus Duration",
    chooseAdjustmentOption: "Would you like to extend or shorten your focus session? 🤔",
    editFocusDuration: "When would you like to wrap up your focus session? 🌟",
  },
  networkError: {
    noNetworkAlertTitle: "Internet disconnected, let's reconnect! 🌐",
    retrying: "But we're still trying! ⏳",

    connectionError: "Uh-oh! Unstable internet connection! 🌐",
    apiError: "Something went wrong! 😕",
    internalError: "Oh no! Internal error! 😱",
  },
  manageAllowedApps: {
    searchPlaceholder: "Search installed apps 🔍",
  },
  addNoteModule: {
    addNote: "Add Note",
    placeholder: "Add Note Here...",
    saveNote: "Save Note",
    automaticallySave: "Your note will be saved automatically",
  },
  permissionWarning: {
    usageAccessTitle: "We need Usage Access permission to help block distractions",
    deviceUsagedescription:
      'To allow us to block distracting apps when you\'re focusing/doing your habits, we need "usage access" permissions so we can see which app you are using',
    overlayTitle: "We need Overlay permission to help block distractions",
    overlayDescription:
      'To allow us to block distracting apps when you\'re focusing/doing your habits, we need "Overlay" permissions so we can see which app you are using and show distraction alert for not allowed apps',
    privacyNoteTitle: "Privacy note",
    privacyNoteDesc: "We don't log which apps or websites you use. we just use it for blocking in real time.",
    grantAccess: "Allow",
  },
  onboarding: {
    nextStep: {
      upNext: "Coming up next: {step} 🚀",
      focusSession: "Focus mode: ENGAGED! 🔥",
      microBreak: "Quick break to keep your energy high!",
      allDone: "Woohoo! You did it all! 🎉",
    },
    onboarding: "Onboarding",
    letsDoIt: "Let's do it, superstar! 🚀",
    replay: "Replay, let’s go again! 🔄",
    instructionVideo: "Instruction Video, let’s learn! 🎥",
    welcomeAboard: "Welcome aboard! 🎉 Let’s rock this! 🌟",
    lookingForwardToHelp: "Looking forward to helping you form healthy habits and get more deep work done! 💪",
    getStarted: "Get Started",
    allDone: "All Done!",
    installDesktopApp: "Install the desktop app, let’s sync it up! 💻",
    installDesktopAppDesc:
      "Focus Bear works on Mac and Windows too. If you've got a computer, download the app from <bold>focusbear.io</bold> to sync your focus sessions and habits! 💻",
    cutoffTimeWarning: "Get off tech time should be after the finish work time ({time}).",
    setupHabitsTitle: "Setup habits to focus better, superstar! 🌟",
    setupHabitsCta: "Setup habits! 🚀",
    habitsPirateCopy: "Good habits keep your focus sharp all day, champ! 💪",
    habitImportPirateCopy: "I'll use me sea magic to bring your habits aboard!",
    habits: {
      sleep: "Sleep 😴",
      meditate: "Meditate 🧘",
      exercise: "Exercise 💪",
    },
    habitList: {
      nayLabel: "Nay - Give me some ideas Cap’n 🏴‍☠️",
      ayeLabel: "Aye - I already have some habits 🏴‍☠️",
    },
  },
  blockingPermissionIntro: {
    holdOnTitle: "Hold on a minute, superstar! ✋",
    captainBearMessage: "Arr... if you want to focus better, you've got to get your habits shipshape first! 🏴‍☠️",
  },
  goals: {
    boostProductivity: "🚀 Boost productivity (work, study, tasks), let’s get it done! 💪",
    improveMentalHealth: "🧘 Improve mental well-being (stress, sleep), let’s relax! 🌙",
    improvePhysicalHealth: "🏋️‍♂️ Focus on health & fitness (exercise, nutrition), let’s get strong! 💪",
    manageTask: "🏡 Manage home tasks (cleaning, chores), let’s keep it tidy! 🧹",
    otherSpecify: "✏️ Other (please specify: __), let’s hear it! 💬",
    strengthenRelationShip: "❤️ Strengthen relationships (family, friends), let’s connect! 🤝",
    achievement_placeholder: "Tell us your goal, let’s achieve it! 🎯",
    enableFeatures: "Enable features, let’s unlock more! 🔑",
    doOurBest: "We're here to help you reach your goals. Which Focus Bear features would you like to turn on? 🎉",
    achievementWithFocusBearDesc: "What are your main goals? Let’s achieve them! 🎯",
    help_me_develop: "Build healthy habits, let’s do it! 💪",
    help_me_stay: "Stay focused at work, let’s keep it going! 🚀",
    help_me_develop_tooltip:
      "Focus Bear can guide you through healthy habits (meditation, exercise, journaling etc.) in your morning and evening routine! 🌟",
    help_me_stay_focused_tooltip:
      "Focus Bear will block distractions while you're working so you can get deep work done! 🚀",
    organize_tasks_using_ai: "Organize your tasks using AI",
    organize_tasks_using_ai_tooltip: "Focus Bear can organize your tasks using AI",
    what_are_you_hoping_focus_bear_can_do: "What are you hoping Focus Bear can do?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Tell us what you're hoping Focus Bear can do",
    explore_the_app_first: "Explore the app first",
    setup_habits: "Set up habits",
    setup_habits_question: "Do you want to set up your habits now (takes ~3 minutes) or explore the app first?",
  },
  habit: {
    habitPack: "Choose your habits, let’s rock! 🎉",
  },
  setupTime: {
    setStartupTime: "Choose Your Start Time, let’s get going! ⏰",
    chooseTheAbsoluteEarliest: "What time do you wake up? Let’s rise! ☀️",
    setShutdownTime: "When do you finish working/studying? Let’s wrap it up! ⏳",
    setSleepTime: "What time do you want to go to sleep? Let’s rest! 🌙",
    sleepTimeDesc:
      "Between {shutdown_time} and {sleep_time} you can relax on your phone, after {sleep_time} Focus Bear will help you wind down for the evening. Distracting apps will be blocked so you can sleep well! 🌙",
  },
  blockList: {
    title: "Make your phone safe during habits/focus sessions",
    subTitleAndroidBlockList: "Choose distracting apps to block while you're doing habits or focusing",
    buttonAndroidBlockList: "Choose distractions",
    subTitleIos: "Choose distracting apps to block while you're doing habits or focusing",
    buttonIos: "Choose distractions",
  },
  editFriction: {
    frictionTooltipDescription:
      'You\'re a very disciplined person of course but occasionally you might be tempted to skip your habits or stop blocking distractions on a whim. You can set up extra "friction" to help slow down those impulsive thoughts. If you enable high friction mode, it will ask you to wait a few seconds before you stop blocking distractions! ⏳',
    frictionForSkippingHabits: "Friction for skipping habits, let’s keep it real! 🚫",
    reallyEasy: "Really easy - I want to be able to skip habits/breaks in a hurry! ✋",
    makeItHardToSkip: "Make it hard to skip - otherwise I'll end up skipping habits + breaks most of the time! 💪",
    appBlocking: "Block distractions, let’s keep it focused! 🚫",
    blockDuringDaytime: "Block distracting apps during the work day, let’s stay on track! 🚫",
    reallyEasyDescription: "You'll be able to immediately stop blocking distractions ✋",
    makeItHardToSkipDescription:
      "To avoid impulsively turning off blocks, Focus Bear can show a short countdown timer to encourage you to reconsider whether you should be accessing distracting apps. 💪",
  },
  strictness: {
    setPassword: "Set a password 🔑",
    setPasswordDescription:
      "If you're struggling to stick to your habits, get a housemate/partner to set a password. You won't be able to skip habits without the password! 🔒",
    enterConfirmPasswordHint: "Confirm Password, let’s keep it safe! 🔑",
    askForPassword: "Ask for password",
    whenRequirePasswordDescription: "When do you want to require a password? Let’s decide! 🤔",
    changingSettings: "Changing settings, let’s keep it organized! 🔧",
    postponingMorningRoutine: "Postponing/Skipping morning routine ☀️",
    postponingEveningRoutine: "Postponing/Skipping evening routine 🌙",
    postponingAfterCuttOffTime: "Postponing/Skipping evening routine after cutoff time ✋",
    usingPhoneLateNight: "Using your phone late at night 🌃",
    relaxFocusMode: "Allow using relax focus mode 🌙",
    suggestion: "Idea!",
  },
  subscription: {
    personalizedHabit: "Personalized habit routines",
    productivityBoosting: "Productivity-boosting breaks",
    customizedFocus: "Customizable focus modes",
    automaticGoals: "Automatic goals tracking",
    cancel: "Cancel auto-renewal",
    subscription: "Subscription 🔑",
    trialActive:
      "Your trial lasts for {day} more day(s). Do not worry, you will not be charged when the trial ends and no credit card required upfront",
    getSubscriptionPlan: "Get our subscription plan to use the app and unlock all features",
    subscriptionPlanPrice: "Continue for only <bold>{amount}</bold>/month",
    benefit: "Benefits includes",
    doesSubscriptionAutoRenew: "Does my subscription auto renew?",
    subscriptionAutoRenew:
      "Subscription will automatically renew and you will be charge at the end of each period. You can disable it at anytime with just one click in the store",
    thankYouForSubscribing:
      "Thank you for subscribing, you can now use all features of Focus Bear\n\nYour subscription will expire in <bold>{day}</bold> days",
  },
  editHabit: {
    okay: "Okay, let’s keep it going! 👍",
    error: "Error, let’s fix it! 🛠️",
    unableToSaveSettings:
      "Something went wrong! Very sorry! Our engineering team has been notified and we'll fix it ASAP! If you don't hear from us within 24hrs, please email support@focusbear.io and we'll get things fixed for you! 📧",
    goingBack:
      "You are about to go back to the Settings menu. If you have made any changes, please tap the 'Save Habits' button! 💾",
    continue: "Continue, let’s keep it moving! 🚀",
    cancel: "Cancel, let’s rethink! ✋",
    warning: "Warning! ⚠️",
    restartingIn: "Restarting Focus Bear in {seconds}... Let’s get it done! 🚀",
  },
  shareLogs: {
    pleaseWriteFeedback: "Please write feedback message, let’s hear it! 💬",
    enterFeedBack: "Enter your feedback ✍️",
    logsShared: "Thank you for sharing! Feedback has been shared with support, teamwork makes the dream work! 🤝",
  },
  impact_reporting: {
    title: "Analyse Your Sleep and Mood, let’s track it! 🌙",
    description:
      "Would you like to track your sleep and mood to see if Focus Bear is making a positive difference in your life? This would help us too by giving us (anonymous) data about the impact of our app! 🌟",
    subtitle: "Data we'll collect 📊",
    bulletPoints: "● Hours of sleep\n● Your mood and energy level\n● How productive you felt at the end of the day",
    okSure: "Ok sure, let’s do it! 👍",
    noThanks: "No thanks ✋",
  },
  privacyModal: {
    heading: "Privacy and Security",
    notShareData: "We take your privacy and security very seriously and will never share your data ever.",
    doNotLog: "• We do not log how much time you spend on websites or apps.",
    chooseToBlock:
      "• If you want to block distracting apps, we need to store the names of those installed apps in our database so that your settings will sync across all your devices.",
    dataEncrypted: "• Your data is encrypted and we don't let anyone else see it.",
    moreDetails:
      "For more details, refer to our <bold>privacy policy</bold> or feel free to email support@focusbear.io",
    accept: "Accept",
  },
  pushNotiPermission: {
    title: "Enable Notifications",
    description: "Let us remind you to stay on track with your habits and show up on time for those meetings! 🚀",
  },
  distractionBlockingReason: {
    notLoggedIn: "Blocking disabled: You're not logged in, let’s log in! 🚀",
    postponeActivated: "Blocking disabled: Postpone activated, let’s take a break! ✋",
    focusModeActivated: "Blocking enabled: Focus mode activated, let’s stay on track! 🚀",
    firstDay: "Blocking disabled: First day - routine not activated yet, let’s get started! 🎉",
    otherReason: "Blocking enabled: It's time to do your routine, let’s go! 🚀",
    daytimeBlockingEnabled:
      "Blocking enabled: morning routine is complete but daytime blocking enabled, let’s keep it focused! 🚫",
    defaultCase: "Blocking disabled: Distraction blocking is disabled, let’s activate it! 🚫",
    withinCutoffTimeAndShutdownTime: "Blocking disabled: you've got free time until {cutoff_time}, let’s enjoy! 🎉",
    permissionNotGranted: "Blocking disabled: Permissions not granted (enable it in settings), let’s fix it! 🔧",
    afterCutoffTime: "Blocking enabled: It's time to wind down before you sleep, let’s relax! 🌙",
    afterCutoffTimeAndEveningRoutineFinished: "Blocking enabled: It's time to sleep, let’s rest! 🌙",
    detailedCutOffSleepTimeBlockingReason:
      "Distractions are blocked from {cutoff_time} so you can sleep. Your morning routine is set to start at {startup_time}. After you finish your morning routine, blocking stops! 🌙",
  },
  blocking: {
    blockingType: "Blocking Type",
    allowList: "Allow List",
    blockList: "Block List",
    allowListDescription:
      "Choose apps that are allowed while you're doing your habits or focusing. Everything else will be blocked.",
    blockListDescription:
      "Choose the distracting apps that should be blocked while you're doing your habits or focusing. Everything else will be allowed.",
    appBlockList: "Apps Blocklist",
    blockAtLeastOne: "Please select at least one app to stop yourself being distracted",
    socialFilterTitle: "Social",
    newsFilterTitle: "News",
    gamesFilterTitle: "Games",
    miscFilterTitle: "Misc",
    recommendedSectionListTitle: "Recommended apps to block",
    otherSectionListTitle: "Other Apps",
    freeAppLimitTitle: "5 apps max in free mode, darling. Want more? You know where the upgrade button is. 😉",
    freeAppLimitDesc:
      "Free version gives you 5 blocks. Want more power? Go Pro, support our hustle, and unlock features that actually get things done. Productivity looks good on you. 😉",
  },
  permissionExplanation: {
    title: "Set up permissions for distraction blocking",
    description: "Focus Bear can block distractions while:",
    workTask: "• you're working/studying so you get s#*% done ⚒️",
    routineTask: "• you're doing your morning and evening routine so you do your habits 🧘",
    sleepTask: "• you're sleeping so you actually sleep 😴",
    toggleOption: "By default, you can turn off distraction blocking at any time.",
    friendOption: "(But you can also choose to have a friend set a password to make it harder)",
    necessaryPermission:
      "Usage permission: To detect if you open a distracting app\n\nOverlay permission: This is what does the distraction blocking",
  },
  grantPermission: {
    title: "We'll need your permission to block apps!",
    description: "Don't worry you can pause distraction blocking at any time",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Keep blocking enabled, let’s keep it focused! 🚫",
    description: "Allow Focus Bear to keep blocking apps in the background by removing battery optimization! 🔋",
    warning: "This will use slightly more battery (but not very much), let’s keep it powered up! 🔋",
    keepFocusBearPoweredUp: "Keep Focus Bear powered up, let’s keep it going! 🔋",
  },
  launcher: {
    title: "Apps",
    morning: "🔆 Morning",
    evening: "🌙 Evening",
    play: "🥳 Play",
    work: "🔨 Work",
    setAppLabel: "Choose a category for {appName}, let’s organize! 📋",
    search: "Search apps, let’s find them! 🔍",
    noAppsFound: "No apps found 📋",
    setAsDefaultLauncher: "Default Launcher",
    restricted: "Restricted, let’s focus on your routine! 🚫",
    restrictedMessage: "{appName} is being restricted, please focus on your routine! 🚫",
    stopBlocking: "Stop blocking, let’s take a break! ✋",
    openAppMenuToolTip: "Tap here to open the app menu, let’s go! 🎉",
  },
  DND: {
    duringFocusSessions: "During Focus Sessions",
    duringHabits: "During Habits & Sleep",
  },
  bearsona: {
    choose: "Choose a Bearsona",
    useCustomLanguage: "Use {customLanguage}, let’s make it fun!",
    confirmUseCustomLanguage: "Cheer me on!",
  },
  breathingExercise: {
    title: "Yay! Breathing Time!",
    description: "You got this! Take a breath, clear your mind, and then crush whatever comes next—go you!",
    dontWantToOpen: "Nah, let's skip {appName}!",
    wantToOpen: "Yup, take me to {appName}!",
    motivational: "Whoa! You really wanna open {appName}? Let's pause for a sec!",
  },
  simpleHome: {
    setupBlockingApp: "Set up app blocking and stay on track! (Recommended!)",
    setupBlockingUrl: "Set up website blocking too! (Optional, but awesome!)",
    title: "Give Focus Bear a Go!",
    focusSessionCheckboxTitle: "You did your first focus session!",
    microBreakCheckboxTitle: "You took a happy little break!",
    focusScreenTitle: "Hop into a Focus Session!",
    focusSessionCheckboxDesc: "Let’s dive into deep work!",
    microBreakCheckboxDesc: "Breathe it out and feel great!",
  },
  loading: {
    loading: "Loading... Get pumped! 🚀",
    breathingExercise:
      "While you wait, let's do a box breathing exercise! Breathe in for 3 seconds, hold for 3, breathe out for 3, hold for 3 - you got this! 💪",
    loadingHabit: "Loading your amazing habit library! 🌟",
    pleaseWaitLoadHabit:
      "We'll recommend habits based on what matters to you! Based on your goals, we'll suggest helpful habits from our curated library to get you started - let's do this! 🎉",
  },
  appUsage: {
    timeUsedAfterCutoff:
      "You used your phone for <bold>{duration}</bold> during your sleep window last night. 🌙📱\n\nWanna boost your bedtime superpowers and make it easier to resist phone time?",
    timeUsedAfterCutoffTitle: "Phone Time After Bedtime!",
  },
  streakCelebration: {
    title: "{streakTypeName} streak! 🎉",
    morning: "Morning routine",
    evening: "Evening routine",
    focus: "Focus session",
    message: "You're absolutely crushing it! Keep shining! ✨",
    day: "day",
    days: "days",
  },
};
