export default {
  languageName: "Jester English",
  baseLanguage: "en",
  error: {
    invalidVideoUrl: "That YouTube link? A jester's jest, it is not!",
    videoNotFound: "No moving picture found at that link! (Are you sure?)",
  },
  habitSetting: {
    routineSelection: "Pick a jig!",
    requirement: "The deed to do, to make the habit true!",
    youtubeVideo: "YouTube or Vimeo jape?",
    youtubeVideoDescription: "A merry video to watch whilst the deed is done!",
    enableTimer: "Tick-tock! Use the timer, or not!",
  },
  common: {
    learnMore: "Why yes! Let’s tickle the brain with knowledge! 🤹",
    doItLater: "Later, my liege! The fool shall return! 🎭",
    email: "Scroll of Messages",
    goToSleep: "Off to dreamland, my regent!",
    areYouSure: "Truly, truly? Are you *quite* sure, my friend?",
    loading: "Humming and hawing...",
    connectionError: "The gremlins got the wires! (No connection!)",
    morning: "cock-a-doodle-doo!",
    evening: "owl-a-hoot-hoot!",
    welcome: "Well met, and welcome to the show!",
    somethingWrong: "Odds bodkins! Something's amiss!",
    logout: "Begone! (But do come back!)",
    ok: "Aye!",
    ok_ellipsis: "Aye...",
    confirm: "Verily!",
    next: "Onward!",
    cancel: "Cancel",
    proceed: "Forsooth, proceed!",
    resume: "Pick up the thread!",
    retry: "Try again",
    submit: "Send forth!",
    verify: "Prove Thyself!",
    finished: "Finish! The end!",
    sec: "sec",
    focusBear: "focus bear",
    tomorrow: "On the morrow!",
    today: "This very day!",
    save: "Keep it safe!",
    startRoutine: "Begin the merry-go-round!",
    continue: "Keep it going!",
    end: "That's all, folks!",
    startActivity: "Huzzah! Time for {activityName}!",
    startTimerActivity: "Tick-tock! {time} {unit} of {activityName}!",
    Success: "A triumph! Well done!",
    save_changes: "Lock it in!",
    saving: "Squirreling it away...",
    next_time_format: "[{day} at] h:mm A",
    sure: "As you wish!",
    uploadScreenShots: "Pictures, if you please!",
    session_expired: "Poof! Your time's run out!",
    login_again: "Back in the game, if you please!",
    continue_activity_name: "Carry on with {activityName}!",
    no_thanks: "Nay, I thank thee!",
    saveHabitSuccessfully: "Changes are saved successfully, as if by magic",
    granted: "You said yes!",
    notGranted: "You said no (how rude)",
  },
  lateNoMore: {
    title: "Meeting Reminders",
    calendarIntegration: "Calendar Integration",
    calendarTooltip: "To enable meeting detection you can connect your phone's calendar or your Google calendar",
    googleCalendar: "Google Calendar",
    connected: "Connected",
    notConnected: "Not connected",
    enableReminders: "Enable Reminders",
    calendarPermission: "Device Calendar",
    calendarPermissionAlreadyGranted:
      "Device Calendar is connected. You can revoke access at any time via your phone's settings",
    calendarPermissionDenied: "Please grant calendar access permission in your phone's settings",
    openSettings: "Open settings",
    addReminder: "Add reminder",
    durationBefore: "{duration} before",
    whenMeetingStarts: "When meeting starts",
    requireMeetingUrl: "Events with Meetings Only",
    requireMeetingUrlDescription: "Only include events that have a meeting URL attached",
    // Notification messages
    notification1: "Hark! A meeting approaches! 🐻",
    notification2: "Time to get ready for thy meeting! ⏰",
    notification3: "Thy meeting awaits! 📅",
    notificationBody: "'{title}' starts {time}",
    now: "now",
    // Meeting Preparation UI
    yourMeetingStartsIn: "Meeting in <highlight>{countdown}</highlight>. Let's get ready!",
    yourMeetingIsOngoing: "There's an ongoing meeting. Join <highlight>now</highlight>!",
    upcomingMeeting: "Upcoming event",
    mentallyPrepare: "1. Mentally prepare for the meeting",
    howDoYouWantToShowUp: "How do you want to show up?",
    placeholderHowToShowUp: "Calm, listening, open-minded, collaborative...",
    joinOnTime: "2. Join on time",
    ignoreMeeting: "Ignore meeting",
    startMeeting: "Join meeting",
    noUpcomingMeetings: "No upcoming meetings",
    noMeetingsDescription: "We didn't find any meetings scheduled in the next few hours.",
    // Calendar source indicators
    googleCalendarSource: "Source: Google calendar",
    deviceCalendarSource: "Source: On-device calendar",
  },
  settings: {
    title: "Settings",
    addApps: "Banish More Apps to the Dungeon!",
    clearBlocklist: "Empty the Dungeon?",
    confirmClearBlocklist: "Truly empty the whole dungeon?",
    strictness: "How stern shall we be?",
    reason_required: "Tell us why, or face the pie!",
    enter_a_reason: "Pray, tell, why wouldst thou delete thine account?",
    contact_desc: "May we bother you to help mend what's broken?",
    editFriction: "The Slippery Slope!",
    password: "The Secret Word!",
    account: "Your Royal Account",
    permissions: "Royal Permissions",
    language: "Tongue-Twisters",
    useSystemLanguage: "Speak as the King speaks!",
    supportedLanguages: "Tongues we understand",
    overlay_permission: "Permission to Peek!",
    usage_permission: "Permission to Spy!",
    notification_permission: "Permission to Shout!",
    screen_time_permission: "Permission to Watch the Clock!",
    DND_permission: "Do Not Disturb Permission (Shhh!)",
    DND: "Shhh! (Do Not Disturb)",
    warning: "Beware! Dragons!",
    DND_permissionWarning:
      "If 'Do Not Disturb' is ON, you must turn it OFF yourself! We can't do it magically without permission, alas!",
    help: "Cry for Help!",
    report_problem: "Tattle on a Trouble!",
    discord_server: "Discord Server",
    videoTutorials: "Video Tutorials",
    experimental: "Mad Science!",
    customization: "Dress-Up Time!",
    general: "The Usual Stuff",
    allowed: "Welcome!",
    notAllowed: "Banned!",
    userid: "Your Royal ID",
    copy: "Copy",
    copied: "Copied",
    verifyEmail: "Verify thy email!",
    emailVerificationResent: "Huzzah! Thy email verification hath been sent again!",
    editNickname: "What's thy silly little name, noble fool?",
  },
  focus: {
    title: "Focus",
    focusLimitReachedTitle: "Focus Limit! No More!",
    focusLimitReachedMessage:
      "Free players only get 25 minutes of focus! Want more? Become a royal! (Upgrade, that is).",
  },
  home: {
    setupHabitsDescription: "Setup thy habits to start thy day, noble fool!",
    getMotivated: "Juggle your doubts away!",
    habitName: "Habit's Nickname",
    newHabit: "A brand new jig!",
    duration: "How long?",
    editHabit: "Tweak the Habit!",
    addHabit: "Add a new jig!",
    deleteThisHabit: "Banish this habit to the dungeon?",
    deleteHabit: "Banish habit {name}?",
    afterCutoffTimeDescription: "No habits allowed! 'Tis past the cutoff time! (Shhh!)",
    cutOffToolTip: "You've set the cutoff time to {cutOffTime}. No habits after that! (Change it in 'Timing Tweaks').",
    unlockToProceed: "Unlock, if you dare!",
    title: "Jigs",
    morningRitual: "Your Morning Jig!",
    eveningRitual: "Your Evening Jig!",
    time_to_earn_screen_time: `Do your morning jigs to set yourself up for a day of marvels`,
    evening_routine_text:
      "Here be the habits of your evening jig. You'll be ready for a slumber of kings when you're done",
    upcoming_below_new_activities:
      "Below are the dances you need to do, to earn the right to use your magic scrying stone",
    start: "Let the games begin!",
    mins: "min",
    secs: "sec",
    re_activate: "Wake it up again!",
    force_deactivate_postpone_and_start_routine: "Jig's been delayed!\nResume the jig?",
    userCompletedMorningRoutineHeading:
      "Huzzah! You've finished your morning jig. We await your evening performance  {routineTime}",
    postOnboardingRoutineHeading: "Welcome, traveler! We await your {routineName} jig {routineTime}",
    userCompletedEveningRoutineHeading: "Bravo! You've finished your evening jig. See you {routineTime}",
    wantLogout: "Dost thou wish to depart?",
    noDataFound: "No habits here yet! Tap <fix>this spot</fix> to add some jigs.",
    routineFetchingError:
      "We tripped over a jester's hat fetching your routine! Try again, or send for the royal messengers (support)!",
    hi: "Greetings, {nickname}!",
    goodMorningFocusTime: "Top o' the morn to ya!",
    goodEveningFocusTime: "Good even, and may your stars be bright!",
    allActivitiesCompleted: "No more jigs to jig!",
    startRoutineNow: "Do My {routineName} Jig Now!",
    passwordForSettingsTitles: "Speak the secret word to pass!",
    manageAlwaysAllowedAppsDesc:
      "During your jigs and when you're focusing on your computer, all apps but the Always Allowed will be locked away. We suggest only allowing things like SMS, phone, and work apps, lest you be tempted by frivolity!",
    manageAlwaysBlockedAppsDesc:
      "During your jigs and when you're focusing, apps in the dungeon will be locked! We suggest banishing social media, games, email, and news, lest they steal your focus!",
    overlayPermission: "overlayPermission",
    usagePermission: "usagePermission",
    editHabits: "Edit Habits",
    editYourHabits: "Tweak your jigs!",
    stats: "The Royal Records!",
    motivationMsg: "Get Ye Inspired!",
    play: "Make merry!",
    pause: "Hold your horses!",
    customizeHabits: "Modify the routine!",
    deleteAccount: "Banish Thine Account?",
    accountDataHasBeen: "Account banished! Thanks for playing with Focus Bear.",
    blockSuperDistractingApps: "Banish the most tempting distractions!",
    skipHabitDesc: "Skip this jig today?",
    screenTimePermissionNotAllowedWarningText:
      "Screentime permission needed to lock apps! Start a jig again to grant it!",
    OverlayPermissionNotGrantedWarning:
      "Warning! Distraction blocking asleep! Overlay permission not given. Fix it, I say!",
    ScreenTimePermissionNotGrantedWarning:
      "Warning! Distraction blocking asleep! Screen Time permission not given. Fix it, I say!",
    UsagePermissionNotGrantedWarning:
      "Warning! Distraction blocking asleep! Usage permission not given. Fix it, I say!",
    noAllowedAppSelectedWarning:
      "Warning! You haven't set up your dungeon yet! Edit the Blocklist, lest distractions run wild!",
    habitLimitMessage:
      "Free users only get 3 habits per routine. Please upgrade to unlock more habits, and become the true habit king.",
    routineOptionsTooltip: "Behold! This menu edits thy routine—or changeth its timing, most royally.",
  },
  postpone: {
    doYouReallyWantTo: "Ho ho! Seeking a break from our merry dance?",
    blockingPausedForDuration: "A pause! {duration} minutes of jolly freedom!",
    blockingPausedIndefinitely: "The curtain falls until you bid it rise again!",
    pauseBlocking: "Blocking pause!",
    pauseDisabledStrictMode: "Nay, good traveler! Super Strict Mode forbids such mischief!",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Back to Our Revelry!",
    choosePostponeTime: "How long shall we pause our merry show?",
    youHavePausedTimesToday_zero: "Ho ho! Your first pause of the day!",
    youHavePausedTimesToday_one: "You've had one pause today, you merry soul!",
    youHavePausedTimesToday_other: "You've had {count} breaks today, you foolish soul!",
    countdown: "Patience! The next pause comes after {countdown}!",
    areYouSureIndefinite:
      "Ha! An endless break you seek? Remember, dear fool - even the most pressing matters can wait 15 minutes while we finish our merry dance!",
    doHabits: "Nay, let's keep the show rolling!",
    longTermGoalsDesc: "Ho ho! Let me remind thee of thy noble quest:",
    lowQualityUsageDesc: "Alas! {duration} wasted on frivolous apps today! Such foolishness!",
    write: "Scribble a note...",
  },
  passwordForSettings: {
    invalid_password: "Wrong secret word!",
    resetAfter24Hours: "Reset requested. Your password will be disabled after 24 hours.",
  },
  signIn: {
    logIn: "Enter the Realm!",
    enterEmailHint: "Your Email Address (the magical one!)",
    enterPasswordHint: "Your Secret Password",
    invalidCredentials: "Wrong username or password! Try again, knave!",
    enterEmailError: "Prithee, enter your email!",
    enterValidEmailError: "A *proper* email, if you please!",
    enterPasswordError: "Prithee, enter your password!",
    dontHaveAccount: "No account? Make haste!",
    forgotPassword: "Forgot the secret word?",
    signup: "Join the Revelry!",
    googleSignIn: "Enter with Google's Magic!",
    alreadyHaveAccount: "I already have a Focus Bear account (a wise choice!)",
  },
  forgotPassword: {
    forgotPasswordTitle: "Forgot the Password?",
    backToSignIn: "Back to the Entrance!",
  },
  signUp: {
    signUp: "Join Up!",
    tosAndPP: "I agree to the <bold>Terms of Service</bold> and <bold1>Privacy Policy</bold1>",
    alreadyHaveAccount: "Already have an account? Then enter!",
    passwordMatchError: "Passwords don't match! Try again, you clumsy oaf!",
    acceptTerms: "Please agree to the Terms of Service and Privacy Policy to continue",
    passwordHintError: `Password Must Be:
    • At least 8 characters (like a good on should be!)
    • Numbers (0-9)
    • Lowercase letters (a-z)
    • Uppercase letters (A-Z)
    • Special squiggles (!@#$%^&*)`,
    invalidSignup: "Something's amiss! Can't sign up!",
    userExists: "That jester's already here!",
    terms: "Terms",
    privacy: "Privacy",
    or: "OR",
  },
  profile: {
    logout: "Flee the Castle!",
  },
  routineDetail: {
    activity: "The Deed!",
    not_playable_video: "That video's a dud!",
    done: "I've done it! (Applause!)",
    video: "A Moving Picture!",
    images: "Pretty Pictures!",
    checklist: "Things to Tick Off!",
    note: "A Scribble!",
  },
  quickBreak: {
    quickBreak: "Quick Frolics!",
    quickStretch: "Wiggle About",
    stretch: "Stretch Thyself!",
    drinkWater: "Drink! (Glug, glug!)",
    water: "Gulp Thy Goblet!",
    deepBreathing: "Breathe Deep! (In and out!)",
    breathe: "Fill the Bellows!",
    saveQuickBreakSuccessfully: "Thy changes are saved, as if by magic!",
    editQuickBreaks: "Tweak Thy Little Merriments",
    quickBreakName: "Name of thy swift pause",
    currentSelection: "Thy chosen trinket",
  },
  complete: {
    backToHome: "Back to the Castle!",
    logQuantity: "How much did you do?",
    finishedCheck: "done and dusted!",
    habitNotCompleted: "not done yet! ❌ (Oh dear! Try again tomorrow!)",
    finishedAndEarnedMorning: "Done! ✅ You've earned your screen time, like a true knight!",
    finishedAndEarnedEvening: "Done! ✅ You've earned a good night's sleep.  See you at sunrise!",
    why_skip: "Why skip, eh?",
    already_did: "I did it already! (Sneaky!)",
    cannot_today: "Can't do it today! (Alas!)",
    quantity_input_error: "A number twixt {min} and {max}, if you please!",
    freemiumLimitReached: "Alas, only 3 habits for free! Upgrade to be a true habit master.",
  },
  reason: {
    canShare: "Tell us why you're running away!",
    shareFeedback: "Share feedback",
    everythingIsOk: "Oh dear! We hope all is well. Go forth, then!",
    appBrokenDesc: "Woe is us! Prithee, tell us what went awry!",
    somethingElseDesc: "Alrighty then. Any words of wisdom for the royal court?",
    gotEmergency: "I've got a dragon to fight! (Or something like that)",
    appBroken: "The app's gone bonkers!",
    somethingElse: "Something else entirely!",
  },
  notification: {
    backgroundService: "Focus Bear's secret helper, toiling in the background!",
    scheduleNotificationTitleForResumeRoutine: "Back to the jig!",
    scheduleNotificationDescriptionForResumeRoutine: "'Tis time to focus on your merry dance!",
    floatingModuleActivityCompleteNotificationtitle: "One jig down!",
    floatingModuleRoutineCompleteNotificationtitle: "The whole jig is done!",
    morningRoutineCompletedNotificationDescription: "Morning jig complete! What a merry start to the day!",
    eveningRoutineCompletedNotificationDescription: "Evening jig complete! Sleep soundly, and dream of jesters!",
    customRoutineCompletedNotificationDescription: "{{routineName}} jig done! You've outdone yourself, fool!",
  },
  focusMode: {
    blockingPermissionNeeded: "No blocketh without thy blessing!",
    noBlockingAppsSelected: "Picketh apps or be gone!",
    confirmSuperStrictMode: "Are you *sure*? Once this mode starts, you’re locked in 'til the curtain falls!",
    focusTitle: "Start a Focus Fiesta!",
    superStrictToolTip:
      "Truly committed? Enable Super Strict Mode, and you won't be able to stop focusing or pause app blocking until the clock chimes! (No backsies!)",
    superStrictMode: "Super Strict Mode (For the truly brave!)",
    brainDump: "Brain dump",
    brainDumpToolTip: "Write down any silly thoughts that pop into your head while you're focusing!",
    postFocusCongrats_0: "Huzzah! You conquered it!",
    postFocusCongrats_1: "Bravo! What's the next quest?",
    postFocusCongrats_2: "You did it! Take a breather, you magnificent jester!",
    postFocusCongrats_3: "Well done! You're on a roll!",
    postFocusCongrats_4: "Awesome job! What's next on your royal to-do list?",
    postFocusCongrats_5: "You made it! Onward to the next adventure?",
    postFocusCongrats_6: "Great focus! Go grab a goblet of something refreshing!",
    postFocusCongrats_7: "Splendid! You're making progress fit for a king!",
    postFocusCongrats_8: "Well done! Time to stretch your legs, like a courtly dancer!",
    postFocusCongrats_9: "You did great! Keep the jester's spirit alive!",
    startFocusSession: "Commence the Focusing!",
    noIntentionWasFound: "No grand plan entered!",
    distractionAlertTitle: "Focus Mode (No Frivolity!)",
    userIntention: "Your Quest",
    noDistractingThoughtsWasFound: "No silly thoughts entered!",
    userIntentionTextInputPlaceholder: "What great deed will you accomplish?",
    startFocusing: "Let the Focusing Begin!",
    hours: "h",
    minutes: "m",
    duration: {
      hours: "{hours} hours",
      minutes: "{minutes} minutes",
      seconds: "{seconds} seconds",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "You've got this!\nTime for Deep Work (like a dwarf in a mine!)",
    endSession: "End the Session (Enough focusing!)",
    completeFocus: "Finish the Focus!",
    userDumpThoughTextInputDescription: "Write down any silly thoughts that dare to intrude!",
    exitFocusMode: "End the focus early? (For shame!)",
    exitFocusModeDescription: "Tell us why you're abandoning your post!",
    reason: "Your Excuse",
    selectReason: "Pick an excuse (a good one!)",
    congratulations: "Huzzah and well met!",
    focusDoneTitle: "YOU DID IT! (A triumph!)",
    focusDoneDescription: "You focused like a hawk for",
    focusDoneDescription1: "What was your grand plan?",
    focusDoneDescription4: "What silly thoughts popped up?",
    focusDoneDescription2: "What marvels did you achieve?",
    focusDonePlaceholderDescription2: "Enter your achievements, for all to admire!",
    focusDoneDescription3: "Were you tempted by distractions?",
    focusDonePlaceholderDescription3: "Tell us of any temptations you faced!",
    endEarlyReasonDescription1: "I have a dire emergency! (A real one!)",
    endEarlyReasonDescription2: "Focus mode is acting the fool!",
    endEarlyReasonDescription3: "I've achieved my goal! (Huzzah!)",
    endEarlyReasonDescription4: "I need a break! (My brain is full!)",
    runningFocusModeDesc: "A focus session is underway! (Keep it up!)",
    extendFocusDuration: "Extend the Focus!",
    selectExtendFocusDuration: "How much longer will you focus, brave knight?",
    extendFocus: "Extend! (Like a telescope!)",
    shortenFocusDuration: "Shorten the Focus!",
    selectShortenFocusDuration: "How much time shall you shorten, wise fool?",
    shortenFocus: "Shorten! (Like a shrinking potion!)",
    adjustFocusDuration: "Adjust the Focus Duration",
    chooseAdjustmentOption: "Would you like to extend or reduce your focus session, oh mighty jester?",
    editFocusDuration: "When dost thou wish to conclude thy focusing quest?",
  },
  networkError: {
    noNetworkAlertTitle: "The messenger pigeons are lost!",
    retrying: "Trying once more",

    connectionError: "Alas! Unstable internet connection!",
    apiError: "Something's gone awry!",
    internalError: "An internal error has occurred! (Oh dear!)",
  },
  manageAllowedApps: {
    searchPlaceholder: "Seek out your installed apps!",
  },
  addNoteModule: {
    addNote: "Scribble a Note!",
    placeholder: "Jot it down here...",
    saveNote: "Keep the Note!",
    automaticallySave: "Your note will be saved, as if by a helpful imp!",
  },
  permissionWarning: {
    usageAccessTitle: "We need Usage Access to keep distractions at bay!",
    deviceUsagedescription:
      "To banish distracting apps while you're focusing or jigging, we need 'usage access' to see which app you're using (like a watchful guard!).",
    overlayTitle: "We need Overlay permission to do our blocking magic!",
    overlayDescription:
      "To block those pesky distractions, we need 'Overlay' permission. It lets us see what app you're using and show a warning for the naughty ones!",
    privacyNoteTitle: "A Secret Note about Secrets",
    privacyNoteDesc: "We don't spy on which apps or websites you visit. We only use it for blocking, in the moment!",
    grantAccess: "Grant Access! (Do it!)",
  },
  onboarding: {
    nextStep: {
      upNext: "And next in the royal circus: {step} 🎪",
      focusSession: "Focus now! The jest must rest!",
      microBreak: "A tiny pause for thy dancing toes!",
      allDone: "Ta-da! The fool has triumphed!",
    },
    onboarding: "The Grand Tour!",
    letsDoIt: "Let's get this show on the road!",
    replay: "See it Again!",
    instructionVideo: "A Moving Picture Guide!",
    welcomeAboard: "Welcome to the Circus!",
    lookingForwardToHelp:
      "We're eager to help you build good habits and get lots of important things done (like a busy bee!).",
    getStarted: "Begin the Adventure!",
    allDone: "All finished! (Huzzah!)",
    installDesktopApp: "Install the Computer Contraption!",
    installDesktopAppDesc:
      "Focus Bear works on Macs and Windows too! If you've got a computer, download the app from <bold>focusbear.io</bold> to keep your focus and jigs in sync (like a well-oiled clockwork!).",
    cutoffTimeWarning: "No-Tech Time should be *after* you finish your work ({time}).  Make it so!",
  },
  goals: {
    boostProductivity: "🚀 Boost your get-stuff-done-ness! (Work, study, chores!)",
    improveMentalHealth: "🧘 Find your inner peace! (Less stress, more sleep!)",
    improvePhysicalHealth: "🏋️‍♂️ Get fit as a fiddle! (Exercise, good food!)",
    manageTask: "🏡 Tame your castle! (Cleaning, chores!)",
    otherSpecify: "✏️ Something else? Tell us! __",
    strengthenRelationShip: "❤️ Build stronger bonds! (Family, friends!)",
    achievement_placeholder: "Tell us your quest!",
    enableFeatures: "Turn on the Magic!",
    doOurBest: "We're here to help you reach your goals! Which Focus Bear powers would you like to use?",
    achievementWithFocusBearDesc: "What are your biggest dreams?",
    help_me_develop: "Build good habits (like a master builder!)",
    help_me_stay: "Stay focused at work (like a hawk!)",
    help_me_develop_tooltip:
      "Focus Bear can guide you through healthy jigs (meditation, exercise, scribbling, etc.) in your morning and evening revels.",
    help_me_stay_focused_tooltip:
      "Focus Bear will banish distractions while you're working, so you can get truly important things done!",
    organize_tasks_using_ai: "Organize your tasks using AI",
    organize_tasks_using_ai_tooltip: "Focus Bear can organize your tasks using AI",
    what_are_you_hoping_focus_bear_can_do: "What are you hoping Focus Bear can do?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Tell us what you're hoping Focus Bear can do",
    explore_the_app_first: "Explore the app first",
    setup_habits: "Set up habits",
    setup_habits_question: "Do you want to set up your habits now (takes ~3 minutes) or explore the app first?",
  },
  habit: {
    habitPack: "Choose your Jigs!",
  },
  setupTime: {
    setStartupTime: "Choose Your Start Time",
    chooseTheAbsoluteEarliest: "When do you rise and shine?",
    setShutdownTime: "When do you finish working or studying (for the day, at least!)?",
    setSleepTime: "When do you wish to slumber?",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}: Time for merry-making",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}: Evening jig and then to slumber",
    distractionBlockDesc: "Distractions banished - time to prepare for slumber!",
  },
  blockList: {
    title: "Make your phone safe for jigs and focus!",
    subTitleAndroidBlockList: "Choose the naughty apps to block while you're jigging or focusing.",
    buttonAndroidBlockList: "Choose the distractions!",
    subTitleIos: "Choose the naughty apps to block while you're jigging or focusing.",
    buttonIos: "Choose the distractions!",
  },
  editFriction: {
    frictionTooltipDescription:
      "You're a disciplined soul, of course, but sometimes you might be tempted to skip jigs or stop blocking on a whim. You can set up extra 'friction' to slow down those silly thoughts! High friction mode will make you wait a few blinks before you stop blocking.",
    frictionForSkippingHabits: "Friction for skipping jigs",
    reallyEasy: "Really easy - I want to be able to skip jigs in a jiffy!",
    makeItHardToSkip:
      "Make it hard to skip - otherwise I'll end up skipping jigs + breaks most of the time (like a naughty knave!)",
    appBlocking: "Block distractions (like a fortress!)",
    blockDuringDaytime: "Block distracting apps during the workday (no slacking!)",
    reallyEasyDescription: "You'll be able to immediately stop blocking distractions (like a jester on a sugar high!)",
    makeItHardToSkipDescription:
      "To avoid impulsively turning off blocks, Focus Bear can show a short countdown timer to encourage you to reconsider whether you should be accessing distracting apps (like a wise old sage!).",
  },
  strictness: {
    setPassword: "Set a secret word!",
    setPasswordDescription:
      "If you're struggling to stick to your jigs, get a friend to set a password. You won't be able to skip without it! (Muahaha!)",
    enterConfirmPasswordHint: "Confirm the Secret Word (again!)",
    askForPassword: "Demand the Password",
    whenRequirePasswordDescription: "When do you want to require the secret word?",
    changingSettings: "Changing the Royal Decrees",
    postponingMorningRoutine: "Delaying/Skipping the Morning Jig",
    postponingEveningRoutine: "Delaying/Skipping the Evening Jig",
    postponingAfterCuttOffTime: "Delaying/Skipping the Evening Jig after the cutoff time (past your bedtime!)",
    usingPhoneLateNight: "Using your phone late at night (when you should be slumbering!)",
    relaxFocusMode: "Allow using relax focus mode (for the weak-willed!)",
    suggestion: "Tip!",
  },
  subscription: {
    upgrade: "Become Royal!",
    personalizedHabit: "Personalized jigs!",
    productivityBoosting: "Breaks that boost your get-stuff-done-ness!",
    customizedFocus: "Customizable focus modes (for the discerning jester!)",
    automaticGoals: "Automatic goal tracking (like magic!)",
    cancel: "Cancel auto-renewal (if you must!)",
    subscription: "Royal Subscription",
    trialActive:
      "Your trial lasts for {day} more day(s). Fear not, you won't be charged when it ends, and no gold is required upfront!",
    getSubscriptionPlan:
      "Get our subscription plan to use the app and unlock all the features (become a true jester master!)",
    subscriptionPlanPrice: "Continue for only <bold>{amount}</bold>/month (a pittance!)",
    benefit: "Perks include:",
    doesSubscriptionAutoRenew: "Does my subscription renew itself?",
    subscriptionAutoRenew:
      "Subscription will renew itself, like a magical beanstalk, and you'll be charged at the end of each period. You can disable it anytime with a single click in the store (like breaking a spell!).",
    thankYouForSubscribing:
      "Thank you for subscribing! You may now use all of Focus Bear's features, like a true king or queen!\n\nYour subscription will expire in <bold>{day}</bold> days (mark your calendars!).",
  },
  editHabit: {
    okay: "Right-o!",
    error: "Alack!",
    unableToSaveSettings:
      "Something's gone terribly wrong! Our royal engineers have been notified and will fix it lickety-split. If you don't hear from us within 24 hours, send a raven to support@focusbear.io, and we'll sort you out!",
    goingBack:
      "You're about to return to the Settings menu. If you've made any changes, tap the 'Save Habits' button, lest they be lost forever!",
    continue: "Carry on!",
    cancel: "Hold your horses!",
    warning: "Hark! A warning!",
    restartingIn: "Restarting Focus Bear in {seconds} blinks of an eye...",
  },
  shareLogs: {
    pleaseWriteFeedback: "Prithee, write your message of feedback!",
    enterFeedBack: "Enter your words of wisdom (or woe)!",
    logsShared: "Thank you! The scrolls have been sent to the royal support team!",
  },
  impact_reporting: {
    title: "Analyze Your Sleep and Mood (Like a Royal Astrologer!)",
    description:
      "Would you like to track your sleep and mood to see if Focus Bear is bringing you joy and good fortune? This would also help us (anonymously) see the impact of our app, like gazing into a crystal ball!",
    subtitle: "Data we'll gather (like precious jewels!)",
    bulletPoints:
      "● Hours of slumber\n● Your mood and energy (high or low!)\n● How productive you felt at the end of the day (like a royal tally!)",
    okSure: "Aye, I'm game!",
    noThanks: "Nay, I thank thee!",
  },
  privacyModal: {
    heading: "Secrets and Safety",
    notShareData: "We guard your secrets fiercely and will never share them, ever!",
    doNotLog: "• We do *not* spy on how long you spend on websites or apps. (That's your business!)",
    chooseToBlock:
      "• If you want to banish distracting apps, we need to store the names of those installed apps in our database, so your settings will be the same across all your devices (like magic!).",
    dataEncrypted: "• Your data is locked away with powerful enchantments, and we don't let anyone else peek!",
    moreDetails: "For more details, consult our <bold>Secrets Policy</bold> or send a raven to support@focusbear.io",
    accept: "I understand!",
  },
  pushNotiPermission: {
    title: "Allow notifications",
    description:
      "We'll let you know when it's time for your jigs and *lots* of reminders before a meeting, so you won't be tardy!",
  },
  distractionBlockingReason: {
    notLoggedIn: "Blocking off: You're not signed in!",
    postponeActivated: "Blocking off: Delayed for a bit!",
    focusModeActivated: "Blocking on: Focus time! (No distractions!)",
    firstDay: "Blocking off: First day - jigs not yet started!",
    otherReason: "Blocking on: Time for your merry routine!",
    daytimeBlockingEnabled: "Blocking on: Morning jig complete, but daytime blocking is on! (No slacking!)",
    defaultCase: "Blocking off: Distraction blocking is taking a nap.",
    withinCutoffTimeAndShutdownTime:
      "Blocking off: You've got free time until {cutoff_time} (then it's wind-down time!).",
    permissionNotGranted: "Blocking off: Permissions not granted! (Fix it in the Royal Settings!)",
    afterCutoffTime: "Blocking on: Time to wind down before slumber!",
    afterCutoffTimeAndEveningRoutineFinished: "Blocking on: Time for beddy-byes!",
    detailedCutOffSleepTimeBlockingReason:
      "Distractions are banished from {cutoff_time} so you can sleep soundly. Your morning jig starts at {startup_time}. After you finish your morning jig, the blocking stops (until next time!).",
  },
  blocking: {
    blockingType: "Blocking Style",
    allowList: "The Welcome List",
    blockList: "The Banishment List",
    allowListDescription:
      "Choose the apps that are *allowed* while you're jigging or focusing. Everything else will be banished!",
    blockListDescription:
      "Choose the distracting apps to *banish* while you're jigging or focusing. Everything else is welcome!",
    appBlockList: "Dungeon of Apps",
    blockAtLeastOne: "Prithee, select at least one app to banish, lest you be distracted!",
    socialFilterTitle: "Chit-Chat Apps",
    newsFilterTitle: "Newsy Apps",
    gamesFilterTitle: "Gamey Apps",
    miscFilterTitle: "Odds and Ends",
    recommendedSectionListTitle: "Apps we suggest banishing",
    otherSectionListTitle: "Other Apps (Choose wisely!)",
    freeAppLimitTitle: "Alas and alack! Only five apps may be banished in the free edition, good sirs and madams!",
    freeAppLimitDesc:
      "In this merry free version, thou canst only pick five apps to block, oh wise one! Toss a coin for Focus Bear Pro, and thou shalt help us craft wondrous new features to tickle thy productivity fancy! 🙂",
  },
  permissionExplanation: {
    title: "Set up permissions for banishing distractions!",
    description: "Focus Bear can banish distractions while:",
    workTask: "• you're working/studying, so you get things done! ⚒️",
    routineTask: "• you're doing your morning and evening jigs, so you do your habits! 🧘",
    sleepTask: "• you're slumbering, so you actually sleep! 😴",
    toggleOption: "By default, you can turn off distraction blocking whenever you like (but be warned!).",
    friendOption: "(Or, you can have a friend set a secret word to make it harder! A jester's trick!)",
    necessaryPermission:
      "Usage permission: To see if you open a naughty app!\n\nOverlay permission: This is the magic that does the blocking!",
  },
  grantPermission: {
    title: "We'll need permission banish apps!",
    description:
      "Fear not, you can turn off distraction blocking whenever you wish (though we might judge you slightly!).",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Keep the blocking going!",
    description:
      "Allow Focus Bear to keep banishing apps in the background by removing battery optimization (don't let the battery goblins win!).",
    warning: "This will use a *tiny* bit more battery (but hardly any, we promise!).",
    keepFocusBearPoweredUp: "Keep Focus Bear strong!",
  },
  launcher: {
    title: "Apps",
    morning: "🔆 Morning!",
    evening: "🌙 Evening!",
    play: "🥳 Frolic!",
    work: "🔨 Toil!",
    setAppLabel: "Choose a category for {appName} (what kind of beast is it?)",
    search: "Seek out apps!",
    noAppsFound: "No apps found! (Are you sure you have any?)",
    setAsDefaultLauncher: "Default Launcher (The King of Launchers!)",
    restricted: "Banished!",
    restrictedMessage: "{appName} is banished! Focus on your jig!",
    stopBlocking: "Cease the blocking!",
    openAppMenuToolTip: "Tap here to open the app menu (a secret passage!)",
  },
  DND: {
    duringFocusSessions: "During Focus Fiestas",
    duringHabits: "During Jigs & Slumber",
  },
  bearsona: {
    choose: "Choose a Bearsona",
    useCustomLanguage: "Use {customLanguage} (A bear of many tongues!)",
    confirmUseCustomLanguage: "Jester English, please!",
  },
  breathingExercise: {
    title: "A Breathful Jest!",
    description: "Before thou dost frolic into the realm of distractions, prithee, grant thy mind a moment’s peace!",
    dontWantToOpen: "Ha! {appName}? Not today!",
    wantToOpen: "To {appName}, and beyond! 🤹",
    motivational: "Hark! Dost thou truly wish to summon {appName}?",
  },
  simpleHome: {
    setupBlockingApp: "Set forth the banishment of naughty apps (a royal decree!)",
    setupBlockingUrl: "Blocketh the web too! (If thine heart desires)",
    title: "Have a laugh with Focus Bear!",
    focusSessionCheckboxTitle: "First focus feat—achieved!",
    microBreakCheckboxTitle: "Wiggled through a mini break!",
    focusScreenTitle: "Time for some tomfoolery—Focus!",
    focusSessionCheckboxDesc: "Time to tango with tasks!",
    microBreakCheckboxDesc: "Take a breather, clown-style!",
  },
  loading: {
    loading: "Hark! The gears are turning...",
    breathingExercise:
      "Whilst thou waitest, try a merry box breathing exercise! Breathe in for 3 seconds, hold for 3, breathe out for 3, hold for 3 - a jester's dance for thy lungs!",
    loadingHabit: "Loading thy habit library, good sir/madam!",
    pleaseWaitLoadHabit:
      "We'll recommend habits based on what matters to thee! Based on thy goals, we'll suggest helpful habits from our curated library to get thee started - a jester's promise!",
  },
  appUsage: {
    timeUsedAfterCutoff:
      "Thou didst tap thy phone for <bold>{duration}</bold> during yon snooze window! 😴📲\n\nShall we summon more tricks to stop thee from scrolling while dreamin'?",
    timeUsedAfterCutoffTitle: "Midnight Mischief Detected!",
  },
  streakCelebration: {
    title: "Hark! A {streakTypeName} streak!",
    morning: "Morning ritual",
    evening: "Evening ritual",
    focus: "Focus session",
    message: "Thou art ablaze with greatness! Carry on, noble one!",
    day: "day",
    days: "days",
  },
};
