export default {
  languageName: "Pirate English",
  baseLanguage: "en",
  error: {
    invalidVideoUrl: "Arrr, that be no proper YouTube video URL!",
    videoNotFound: "Blimey! We couldn't find that video!",
  },
  habitSetting: {
    routineSelection: "Routine",
    requirement: "What needs to be done to finish yer habit?",
    youtubeVideo: "YouTube or Vimeo video",
    youtubeVideoDescription: "Add a YouTube video to guide ye through yer habit.",
    enableTimer: "Enable timer",
  },
  common: {
    learnMore: "Arrr, learn the secrets, matey!",
    doItLater: "Aye, later it be, ya scallywag",
    email: "Ye Ol' Email",
    goToSleep: "Hit the hay, ye scallywag!",
    areYouSure: "Be ye sure, matey?",
    loading: "Hold yer horses...",
    connectionError: "Blimey! No connection!",
    morning: "mornin'",
    evening: "evenin'",
    welcome: "Ahoy, Matey!",
    somethingWrong: "Somethin' went wrong, shiver me timbers!",
    logout: "Abandon Ship",
    ok: "Aye",
    ok_ellipsis: "Aye...",
    confirm: "Aye, Aye!",
    next: "Sail On",
    cancel: "Belay That",
    proceed: "Make Way!",
    resume: "Carry On",
    retry: "Try Again",
    submit: "Send It",
    no: "Nay",
    verify: "Prove Yer Worth",
    finished: "All done",
    sec: "sec",
    focusBear: "Focus Bear",
    tomorrow: "morrow",
    today: "t'day",
    save: "Save, me hearty!",
    startRoutine: "Batten Down The Hatches!",
    continue: "Keep Goin'",
    end: "Avast",
    startActivity: "Weigh Anchor on {activityName}",
    startTimerActivity: "Start {time} {unit} {activityName}",
    Success: "Booty Acquired!",
    save_changes: "Secure the Loot",
    saving: "Stowin'...",
    next_time_format: "[{day} at] h:mm A",
    sure: "Aye",
    uploadScreenShots: "Show us yer maps (Optional)",
    session_expired: "Time's up, scallywag",
    login_again: "Log in again, ye hear?",
    continue_activity_name: "Keep at {activityName}",
    no_thanks: "Nay, I be good",
    saveHabitSuccessfully: "Yer changes be saved, success!",
    granted: "Aye, granted!",
    notGranted: "Nay, not granted",
  },
  lateNoMore: {
    title: "Meetin' Reminders",
    calendarIntegration: "Calendar Integration",
    calendarTooltip: "To enable meeting detection you can connect your phone's calendar or your Google calendar",
    googleCalendar: "Google Calendar",
    connected: "Connected",
    notConnected: "Not connected",
    enableReminders: "Enable Reminders",
    calendarPermission: "Device Calendar",
    calendarPermissionAlreadyGranted:
      "Device Calendar is connected. You can revoke access at any time via your phone's settings",
    calendarPermissionDenied: "Please grant calendar access permission in your phone's settings",
    openSettings: "Open settings",
    addReminder: "Add reminder",
    durationBefore: "{duration} before",
    whenMeetingStarts: "When meeting starts",
    requireMeetingUrl: "Events with Meetings Only",
    requireMeetingUrlDescription: "Only include events that have a meeting URL attached",
    // Notification messages
    notification1: "Meetin' be approachin', matey! 🏴‍☠️",
    notification2: "Time to set sail for yer meetin'! ⚓",
    notification3: "Yer meetin' awaits, arrr! 🗡️",
    notificationBody: "'{title}' be startin {time}",
    now: "now",
    // Meeting Preparation UI
    yourMeetingStartsIn: "Meeting in <highlight>{countdown}</highlight>. Let's get ready!",
    yourMeetingIsOngoing: "There's an ongoing meeting. Join <highlight>now</highlight>!",
    upcomingMeeting: "Upcoming event",
    mentallyPrepare: "1. Mentally prepare for the meeting",
    howDoYouWantToShowUp: "How do you want to show up?",
    placeholderHowToShowUp: "Calm, listening, open-minded, collaborative...",
    joinOnTime: "2. Join on time",
    ignoreMeeting: "Ignore meeting",
    startMeeting: "Join meeting",
    noUpcomingMeetings: "No upcoming meetings",
    noMeetingsDescription: "We didn't find any meetings scheduled in the next few hours.",
    // Calendar source indicators
    googleCalendarSource: "Source: Google calendar",
    deviceCalendarSource: "Source: On-device calendar",
  },
  settings: {
    title: "Ship's Registry",
    addApps: "Send apps to the brig",
    clearBlocklist: "Scuttle the Blocklist",
    confirmClearBlocklist: "Confirm ye be scuttlin' the Blocklist?",
    strictness: "Ruthlessness level",
    reason_required: "Ye must tell us why!",
    enter_a_reason: "Why d'ye want to abandon ship and delete yer account?",
    contact_desc: "May we send a raven with questions to fix the problems ye experienced?",
    editFriction: "Change the Friction",
    password: "Secret Code",
    account: "Pirate Profile",
    permissions: "Ship's Permissions",
    language: "Ship's Tongue",
    useSystemLanguage: "Use ship's language",
    supportedLanguages: "Languages we speak",
    overlay_permission: "Overlay Authorization",
    usage_permission: "Permission to board yer apps",
    notification_permission: "Let the parrots squawk",
    screen_time_permission: "Screen Time Authorization",
    DND_permission: "Silence the Crew Permission",
    DND: "Silence the Crew",
    warning: "Avast Ye!",
    DND_permissionWarning:
      "Ye must manually disable DND if it be enabled. It can't be turned off automatically if DND permissions be not granted.",
    help: "Need a Hand?",
    report_problem: "Report a Kraken",
    videoTutorials: "Video Learnin'",
    experimental: "Uncharted Waters",
    customization: "Ship's Decorations",
    general: "Ship's Business",
    allowed: "Pass Granted",
    notAllowed: "No Passage",
    userid: "Pirate ID",
    copy: "Copy",
    copied: "Copied",
    verifyEmail: "Verify yer email!",
    emailVerificationResent: "Arrr! Yer email verification be sent again!",
    editNickname: "Edit yer nickname, make it swashbucklin'",
  },
  focus: {
    title: "Focus",
    focusLimitReachedTitle: "Focus Limit Reached",
    focusLimitReachedMessage:
      "In the free version, ye can only focus for up to 25 minutes. Pay th' gold doubloons if ye want longer focus sessions.",
  },
  home: {
    setupHabitsDescription: "Setup yer habits to start yer day.",
    getMotivated: "Hoist yer spirit, ye scallywag!",
    habitName: "Habit name",
    newHabit: "New habit arrr",
    duration: "Duration",
    editHabit: "Edit habit",
    addHabit: "Add habit",
    deleteThisHabit: "Scuttle this habit",
    deleteHabit: "Scuttle habit {name}",
    afterCutoffTimeDescription: "None o' yer habits be available 'cause it be past the cutoff time",
    cutOffToolTip:
      "Ye configured cutoff times fer yer habits so they're not accessible after {cutOffTime}.\nYe can modify this in Change timing",
    unlockToProceed: "Unlock to proceed",
    title: "Habits",
    morningRitual: "Yer mornin' ritual",
    eveningRitual: "Yer evenin' ritual",
    time_to_earn_screen_time: `Do yer mornin' routine habits to set yerself up for a great day`,
    evening_routine_text: "Ye be ready for a good night's sleep when ye be done",
    upcoming_below_new_activities:
      "Below be the habits ye need to accomplish in next upcoming routine to use yer mobile.",
    start: "Set Sail!",
    mins: "mins",
    secs: "secs",
    re_activate: "Re-Activate",
    force_deactivate_postpone_and_start_routine: "The Routine be delayed!\n Resume the Routine?",
    userCompletedMorningRoutineHeading:
      "Well done fer finishin' yer mornin' routine. Look forward to helpin' ye with yer evenin' routine {routineTime}",
    postOnboardingRoutineHeading:
      "Welcome aboard! Look forward to helpin' ye with yer {routineName} routine {routineTime}",
    userCompletedEveningRoutineHeading:
      "Well done fer finishin' yer evenin' routine. Look forward to helpin' ye with yer mornin' routine {routineTime}",
    wantLogout: "Do ye want to abandon ship?",
    noDataFound: "Ye haven't set up any habits yet. Tap <fix>here</fix> to add some, me hearty.",
    routineFetchingError:
      "We encountered an issue while retrievin' yer routine. Try again later or send us a message fer assistance",
    hi: "Ahoy {nickname}!",
    goodMorningFocusTime: "Good Mornin'!",
    goodEveningFocusTime: "Good Evenin'!",
    allActivitiesCompleted: "No habits left to do",
    startRoutineNow: "Execute me {routineName} Orders",
    passwordForSettingsTitles: "Enter the Code to proceed",
    manageAlwaysAllowedAppsDesc:
      "During yer mornin'/evenin' routine and when ye be focusin' on yer computer, all apps on yer phone apart from the Always Allowed Apps will be blocked. We suggest only allowin' apps like SMS, phone and apps ye need for work so ye don't get distracted during yer habits/work.",
    manageAlwaysBlockedAppsDesc:
      "Durin' yer mornin'/evenin' routine and when ye be focusin' on yer computer, all the apps in yer block list will be blocked. We suggest blockin' social media, gamin', email and news apps so ye don't get distracted during yer habits/work.",
    overlayPermission: "overlayPermission",
    usagePermission: "usagePermission",
    editHabits: "Change Habits",
    editYourHabits: "Change the Ship's Habits",
    stats: "Stats",
    motivationMsg: "Get Motivated",
    play: "Play",
    pause: "Pause",
    customizeHabits: "Edit routines",
    deleteAccount: "Delete Account?",
    accountDataHasBeen: "Account data has been deleted, success. Thanks fer usin' Focus Bear.",
    blockSuperDistractingApps: "Block super distractin' sites/apps",
    skipHabitDesc: "Skip this habit t'day",
    screenTimePermissionNotAllowedWarningText:
      "Screentime permission be needed to block apps, start a habit again to allow permissions",
    OverlayPermissionNotGrantedWarning:
      "Warning: distraction blockin' not activated. Overlay permission not granted. Fix.",
    ScreenTimePermissionNotGrantedWarning:
      "Warnin': distraction blockin' not activated. Screen Time permission not granted. Fix.",
    UsagePermissionNotGrantedWarning: "Warnin': distraction blockin' not activated. Usage permission not granted. Fix.",
    noAllowedAppSelectedWarning:
      "Warnin': ye haven't configured yer block list yet so distractions won't be blocked. Edit Blocklist",
    habitLimitMessage: "Free users can only access up to 3 habits per routine. Please upgrade to unlock more habits.",
    routineOptionsTooltip: "This here menu lets ye edit yer routine or change its timin', savvy?",
  },
  postpone: {
    doYouReallyWantTo: "Ye really want to drop anchor?",
    blockingPausedForDuration: "Blockin' paused fer {duration}",
    blockingPausedIndefinitely: "Blockin' paused 'til ye hoist the sails again",
    pauseBlocking: "Pause blockin'",
    pauseDisabledStrictMode: "Nay, sailor! Super Strict Mode don’t allow ye to pause yer blockin",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Hoist the Sails",
    choosePostponeTime: "How long ye want to weigh anchor?",
    indefinite: "Drop anchor 'til I say otherwise",
    youHavePausedTimesToday_zero: "This be yer first time pausin' today, matey!",
    youHavePausedTimesToday_one: "Ye've already dropped anchor once today, ye landlubber!",
    youHavePausedTimesToday_other: "Blimey! Ye've already dropped anchor {count} times today!",
    countdown: "Ye'll have to wait {countdown} before ye can pause.",
    areYouSureIndefinite:
      "Be ye sure about droppin' anchor indefinitely? Ye can if ye must, but often an urgent task can wait 15 minutes 'til ye finish yer habits, savvy?",
    doHabits: "I'll stick to me habits",
    longTermGoalsDesc: "Remember what ye be strivin' fer with Focus Bear, ye scurvy dog:",
    lowQualityUsageDesc: "Ye've wasted {duration} on distractin' apps today, ye landlubber!",
    write: "Write yer thoughts...",
  },
  passwordForSettings: {
    invalid_password: "Password be invalid",
    resetAfter24Hours: "Reset requested. Your password will be disabled after 24 hours.",
  },
  signIn: {
    logIn: "Back aboard!",
    enterEmailHint: "Email Address",
    enterPasswordHint: "Password",
    invalidCredentials: "Invalid Username/Password",
    enterEmailError: "Please enter email",
    enterValidEmailError: "Please enter valid email",
    enterPasswordError: "Please enter password",
    dontHaveAccount: "Don't have an account?",
    forgotPassword: "Forgot Password?",
    signup: "Sign up",
    googleSignIn: "Sail in with Google",
    continueWithGoogle: "Sail in with Google",
    startWithApple: "Board with Apple",
    startWithEmail: "Enlist with email",
    backToSignInMethod: "Back to choose how to board",
    alreadyHaveAccount: "I already have a Focus Bear account",
  },
  forgotPassword: {
    forgotPasswordSuccess: "A password reset letter be sent to yer email address",
    forgotPasswordErrorThirdParty:
      "Looks like ye signed up with a third-party service. Continue with yer Google or Apple account.",
    forgotPasswordNotVerified: "Ye need to verify yer email address to reset yer password.",
    forgotPasswordEmailNotFound: "Email not found",
    forgotPasswordTitle: "Forgot Password",
    backToSignIn: "Back To Sign In",
    resetPassword: "Reset Password",
    hangTightYouCanTryAgainInSeconds: "Hold fast! Ye can try again in {second} seconds.",
    weveEmailedYouALinkToResetYourPassword: "We’ve sent ye a link to reset yer password.",
  },
  signUp: {
    backToSignUpMethod: "Back to choose how to sign up",
    verifyEmail: "Check yer inbox",
    verifyEmailMessage: "We just sent ye a verification email. Click th’ link to verify yer account.",
    signUp: "Join the crew",
    emailSignup: "Enlist with email",
    continueWithNoAccount: "Join as a stowaway (anonymous)",
    tosAndPP: "I agree to the <bold>Terms of Service</bold> and <bold1>Privacy Policy</bold1>",
    alreadyHaveAccount: "Already have an account?",
    passwordMatchError: "Password and confirm password don't be matchin'",
    acceptTerms: "Please agree to the Terms of Service and Privacy Policy to continue",
    passwordHintError: `Password Must Be:
    • At least 8 characters
    • Numbers (0-9)
    • Lowercase letters (a-z)
    • Uppercase letters (A-Z)
    • Special characters (!@#$%^&*)`,
    invalidSignup: "Invalid sign up",
    userExists: "The user already exists.",
    terms: "Terms",
    privacy: "Privacy",
    or: "OR",
  },
  profile: {
    logout: "Abandon Ship",
  },
  routineDetail: {
    activity: "Activity",
    not_playable_video: "Can't play th' video.",
    done: "I be done",
    video: "Video",
    images: "Images",
    checklist: "Checklist",
    note: "Note",
  },
  quickBreak: {
    quickBreak: "Short Reprieves",
    quickStretch: "Sea Legs Stretch",
    stretch: "Stretch Yer Bones",
    drinkWater: "Drink yer Fill!",
    water: "Water Ration",
    deepBreathing: "Heave yer Chest!",
    breathe: "Deep Lungfuls",
    saveQuickBreakSuccessfully: "Yer changes be saved, savvy!",
    editQuickBreaks: "Adjust Yer Quick Breather",
    quickBreakName: "Name o' the quick breather",
    currentSelection: "What ye've chosen",
  },
  complete: {
    backToHome: "Return to the Main Deck,",
    logQuantity: "Log Quantity of activity",
    finishedCheck: "finished! ✅",
    habitNotCompleted: "haven't completed ❌ Try again t'morrow!",
    finishedAndEarnedMorning: "finished! ✅ Ye've earned yer screen time",
    finishedAndEarnedEvening: "finished! ✅ Ye've earned a good night's sleep. See ye t'morrow mornin'!",
    why_skip: "Why ye be skippin'?",
    already_did: "I've already done it, arr!",
    cannot_today: "Can't do it t'day",
    quantity_input_error: "Number needs to be between {min} and {max}.",
    freemiumLimitReached: "Sorry, you can only complete 3 habits with a free plan.",
  },
  reason: {
    canShare: "Can ye share why ye be pausin'?",
    shareFeedback: "Share feedback",
    everythingIsOk: "Uh oh - hope everythin' be ok. Givin' ye access now.",
    appBrokenDesc: "Really sorry about that. Would ye mind tellin' us what happened?",
    somethingElseDesc: "Ok. Be there any feedback ye want to share with us?",
    gotEmergency: "I've got an emergency",
    appBroken: "The app be broken",
    somethingElse: "Somethin' else",
  },
  notification: {
    backgroundService: "Focus bear background service to help ye focus",
    scheduleNotificationTitleForResumeRoutine: "Resume yer routine",
    scheduleNotificationDescriptionForResumeRoutine: "It be time to focus on yer routine",
    floatingModuleActivityCompleteNotificationtitle: "Task Done, Shipmate!",
    floatingModuleRoutineCompleteNotificationtitle: "Routine Completed, Captain!",
    morningRoutineCompletedNotificationDescription: "Mornin' routine completed. Fine work, shipmate!",
    eveningRoutineCompletedNotificationDescription: "Evenin' routine completed. Sleep well!",
    customRoutineCompletedNotificationDescription: "Arr, {{routineName}} be done! Well sailed, matey!",
  },
  focusMode: {
    blockingPermissionNeeded: "Ye need to grant permissions, matey!",
    noBlockingAppsSelected: "Pick yer apps to block, arrr!",
    confirmSuperStrictMode:
      "Ye sure ye want t’ enter Super Strict Mode? Once aboard, there's no jumpin’ ship ‘til the clock runs out!",
    focusTitle: "Set a course for deep work!",
    superStrictToolTip:
      "Committed to this focus session? Enable super strict mode and ye won't be able to turn focusin' off nor pause yer app blockin' until the timer be up.",
    superStrictMode: "Super strict (no quarter given!)",
    brainDump: "Brain dump",
    brainDumpToolTip: "Write down any distractin' thoughts here so ye can focus on yer work.",
    postFocusCongrats_0: "Nice work! Ye crushed it!",
    postFocusCongrats_1: "Hey, great job finishin' that! What's up next?",
    postFocusCongrats_2: "Ye did it! Feel free to take a breather now.",
    postFocusCongrats_3: "Well done! Ye're really gettin' things done!",
    postFocusCongrats_4: "Awesome job! What's the next thing on yer radar?",
    postFocusCongrats_5: "Ye made it through! Time to tackle the next one?",
    postFocusCongrats_6: "Great focus! Go grab a drink or a snack!",
    postFocusCongrats_7: "Nice! Ye’re makin' serious progress!",
    postFocusCongrats_8: "Well done! Time to stretch yer legs a bit?",
    postFocusCongrats_9: "Ye did great! Let’s keep that momentum goin'!",
    startFocusSession: "Start a focus session, ye scurvy dog!",
    noIntentionWasFound: "No intention entered",
    distractionAlertTitle: "Focus Mode",
    userIntention: "Focus Goal",
    noDistractingThoughtsWasFound: "No distractin' thoughts entered",
    userIntentionTextInputPlaceholder: "What ye be wanting to achieve?",
    startFocusing: "Set sail!",
    hours: "h",
    minutes: "m",
    duration: {
      hours: "{hours} hours",
      minutes: "{minutes} minutes",
      seconds: "{seconds} seconds",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "Ye got this!\nDeep work time",
    endSession: "End the Voyage,",
    completeFocus: "Focus Achieved,",
    userDumpThoughTextInputDescription: "Write down any distractin' thoughts here",
    exitFocusMode: "End focus session early",
    exitFocusModeDescription: "Can you share why you’re endin' this session?",
    reason: "Reason",
    selectReason: "Select a reason",
    congratulations: "Shiver me timbers!",
    focusDoneTitle: "YE DID IT!",
    focusDoneDescription: "Ye remained focused for",
    focusDoneDescription1: "What be yer intention?",
    focusDoneDescription4: "What be yer distractin' thoughts?",
    focusDoneDescription2: "What did ye achieve durin' this time?",
    focusDonePlaceholderDescription2: "Enter what ye achieved with our help",
    focusDoneDescription3: "Did ye have any distractions?",
    focusDonePlaceholderDescription3: "Enter any distractions ye had",
    endEarlyReasonDescription1: "I have an emergency",
    endEarlyReasonDescription2: "Focus mode be not workin' properly",
    endEarlyReasonDescription3: "I have achieved what I wanted to",
    endEarlyReasonDescription4: "I need a break",
    runningFocusModeDesc: "A focus session be runnin'",
    extendFocusDuration: "Extend Focus Duration",
    selectExtendFocusDuration: "How much longer do ye want to focus for?",
    extendFocus: "Extend",
    shortenFocusDuration: "Shorten Focus Duration",
    selectShortenFocusDuration: "How much time do ye want to shorten, matey?",
    shortenFocus: "Shorten",
    adjustFocusDuration: "Adjust Focus Duration",
    chooseAdjustmentOption: "Would ye like to extend or shorten yer focus session, ye scurvy dog?",
    editFocusDuration: "When do ye want to finish focusin', matey?",
  },
  networkError: {
    noNetworkAlertTitle: "Internet disconnected",
    retrying: "Tryin' that again",

    connectionError: "Blimey! Unstable internet connection!",
    apiError: "Blimey! Somethin' went wrong!",
    internalError: "Shiver me timbers! Internal error!",
  },
  manageAllowedApps: {
    searchPlaceholder: "Search installed apps",
  },
  addNoteModule: {
    addNote: "Add Note",
    placeholder: "Add Note Here...",
    saveNote: "Save Note",
    automaticallySave: "Yer note will be saved automatically",
  },
  permissionWarning: {
    usageAccessTitle: "We need Usage Access permission to help block distractions",
    deviceUsagedescription:
      "To allow us to block distractin' apps when ye're focusin'/doin' yer habits, we need \"usage access\" permissions so we can see which app ye be usin'",
    overlayTitle: "We need Overlay permission to help block distractions",
    overlayDescription:
      "To allow us to block distractin' apps when ye're focusin'/doin' yer habits, we need \"Overlay\" permissions so we can see which app ye be usin' and show distraction alert for not allowed apps",
    privacyNoteTitle: "Privacy note",
    privacyNoteDesc: "We don't log which apps or websites ye use. we just use it for blockin' in real time.",
    grantAccess: "Grant Pass",
  },
  onboarding: {
    nextStep: {
      upNext: "Next on the voyage: {step} ☠️",
      focusSession: "Time to buckle down, ye salty dog!",
      microBreak: "Grab a sip o’ rum, quick break it be!",
      allDone: "Ye made it! All done, me hearty!",
    },
    onboarding: "Onboardin'",
    letsDoIt: "Let's do it",
    replay: "Replay",
    instructionVideo: "Instruction Video",
    welcomeAboard: "Welcome aboard!",
    lookingForwardToHelp: "Lookin' forward to helpin' ye form healthy habits and get more deep work done.",
    getStarted: "Get Started",
    allDone: "All Done!",
    installDesktopApp: "Install the desktop app",
    installDesktopAppDesc:
      "Focus Bear works on Mac and Windows too. If ye've got a computer, download the app from <bold>focusbear.io</bold> to sync yer focus sessions and habits.",
    cutoffTimeWarning: "Get off tech time should be after the finish work time ({time}).",
  },
  goals: {
    boostProductivity: "🚀 Boost me productivity (work, study, tasks)",
    improveMentalHealth: "🧠 Calm me stormy mind (stress, sleep)",
    improvePhysicalHealth: "🏋️ Strengthen me sailor body (exercise, nutrition)",
    manageTask: "🧹 Keep me ship tidy (cleaning, chores)",
    otherSpecify: "✏️ Other (speak it plain):__",
    strengthenRelationShip: "❤️ Tend to me crew (family, crew)",
    achievement_placeholder: "Tell us yer goal",
    enableFeatures: "Enable features",
    doOurBest: "We're here to help ye reach yer goals. Which Focus Bear features would ye like to turn on?",
    achievementWithFocusBearDesc: "What d-ye aim to conquer?",
    achievementWithFocusBearDescTooltip: "I'll be usin’ me spellcraft to forge yer habits",
    help_me_develop: "Build healthy habits",
    help_me_stay: "Stay focused at work",
    help_me_develop_tooltip:
      "Focus Bear can guide ye through healthy habits (meditation, exercise, journalin' etc.) in yer mornin' and evenin' routine.",
    help_me_stay_focused_tooltip:
      "Focus Bear will block distractions while ye're workin' so ye can get deep work done.",
    organize_tasks_using_ai: "Organize your tasks using AI",
    organize_tasks_using_ai_tooltip: "Focus Bear can organize your tasks using AI",
    what_are_you_hoping_focus_bear_can_do: "What are you hoping Focus Bear can do?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Tell us what you're hoping Focus Bear can do",
    explore_the_app_first: "Explore the app first",
    setup_habits: "Set up habits",
    setup_habits_question: "Do you want to set up your habits now (takes ~3 minutes) or explore the app first?",
    habitImport: {
      cancelRecording: "Abandon the squawk",
    },
    addHabitList: {
      title: "Add yer habit list",
      description: "Upload yer habit list or tell us yer goals and our magic will add 'em into Focus Bear.",
      uploadScreenshot: "Upload a parchment",
      recordVoiceNote: "Record a squawk (voice note)",
      typeThemIn: "Type 'em in",
      or: "OR",
      haveHabitListQuestion: "Got yer own list o’ habits to bring aboard?",
      importHabits: "Load me habits",
      confirmScreenshotUpload: "Confirm Yer Image",
      confirmScreenshotUploadDesc: "Is this the image ye want to upload, matey?",
    },
  },
  habit: {
    habitPack: "Choose yer habits",
  },
  setupTime: {
    bedtimeForScreens: "Ready to turn on the tech curfew, matey?",
    bedtimeForScreensSubtitle: "That's tellin' yer phone to stand down and rest below deck til mornin'.",
    setStartupTime: "Choose Yer Start Time",
    chooseTheAbsoluteEarliest: "What time do ye wake up?",
    setShutdownTime: "When do ye finish workin'/studyin'?",
    setSleepTime: "What time do ye want to go to sleep?",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}: Ease the sails",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}: Stow Yer Gear and Hit the Hammock",
    techCurfewQuestion: "Ready to turn on the tech curfew, matey?",
    techCurfewTooltip: "That's tellin' yer phone to stand down and rest below deck til mornin'.",
    noThanks: "Nay, no curfew",
    yesPhoneWrecksSleep: "Aye - send it below deck",
    whatTimeGetOffTech: "When shall we send them screens below deck?",
    distractionBlockDesc: "No distractions, ye scallywag—tend to yer nighty duties!",
  },
  blockList: {
    title: "Make yer phone safe durin' habits/focus sessions",
    subTitleAndroidBlockList: "Choose distractin' apps to block while ye're doin' habits or focusin'",
    buttonAndroidBlockList: "Choose distractions",
    subTitleIos: "Choose distractin' apps to block while ye're doin' habits or focusin'",
    buttonIos: "Choose distractions",
  },
  editFriction: {
    frictionTooltipDescription:
      "Ye're a very disciplined person of course but occasionally ye might be tempted to skip yer habits or stop blockin' distractions on a whim. Ye can set up extra \"friction\" to help slow down those impulsive thoughts. If ye enable high friction mode, it will ask ye to wait a few seconds before ye stop blockin' distractions.",
    frictionForSkippingHabits: "Friction for skippin' habits",
    reallyEasy: "Really easy - I want to be able to skip habits/breaks in a hurry",
    makeItHardToSkip: "Make it hard to skip - otherwise I'll end up skippin' habits + breaks most o' the time",
    appBlocking: "Block distractions",
    blockDuringDaytime: "Block distractin' apps durin' the work day",
    reallyEasyDescription: "Ye be able to immediately stop blockin' distractions",
    makeItHardToSkipDescription:
      "To avoid impulsively turnin' off blocks, Focus Bear can show a short countdown timer to encourage ye to reconsider whether ye should be accessin' distractin' apps.",
  },
  strictness: {
    setPassword: "Set yerself a password",
    setPasswordDescription:
      "If yer're strugglin' to stick to yer habits, get a housemate/partner to set a password. Ye won't be able to skip habits without the password.",
    enterConfirmPasswordHint: "Confirm Password",
    askForPassword: "Ask for password",
    whenRequirePasswordDescription: "When do ye want to require a password",
    changingSettings: "Changin' settings",
    postponingMorningRoutine: "Postponin'/Skippin' mornin' routine",
    postponingEveningRoutine: "Postponin'/Skippin' evenin' routine",
    postponingAfterCuttOffTime: "Postponin'/Skippin' evenin' routine after cutoff time",
    usingPhoneLateNight: "Usin' yer phone late at night",
    relaxFocusMode: "Allow usin' relax focus mode",
    suggestion: "Notion!",
  },
  subscription: {
    upgrade: "Upgrade, ye landlubber!",
    personalizedHabit: "Personalized Ship's Orders (habits)",
    productivityBoosting: "Productivity-boostin' breaks",
    customizedFocus: "Customizable Voyages (focus modes)",
    automaticGoals: "Automatic goals trackin'",
    cancel: "Cancel auto-renewal",
    subscription: "Subscription",
    trialActive:
      "Yer trial lasts for {day} more day(s). Don't worry, ye will not be charged when the trial ends and no credit card required upfront",
    getSubscriptionPlan: "Get our subscription plan to use the app and unlock all features",
    subscriptionPlanPrice: "Continue for only <bold>{amount}</bold>/month",
    benefit: "Benefits includes",
    doesSubscriptionAutoRenew: "Does me subscription auto renew?",
    subscriptionAutoRenew:
      "Subscription will automatically renew and ye will be charge at the end of each period. Ye can disable it at anytime with just one click in the store",
    thankYouForSubscribing:
      "Thank ye for subscribin', ye can now use all features of Focus Bear\n\nYer subscription will expire in <bold>{day}</bold> days",
  },
  editHabit: {
    okay: "Okay",
    error: "Error",
    unableToSaveSettings:
      "Somethin' went wrong. Very sorry. Our engineerin' team has been notified and we'll fix it ASAP. If ye don't hear from us within 24hrs, please email support@focusbear.io and we'll get things fixed for ye.",
    goingBack:
      "Ye be about to go back to the Settings menu. If ye have made any changes, please tap the 'Save Habits' button.",
    continue: "Continue",
    cancel: "Cancel",
    warning: "Warning",
    restartingIn: "Restartin' Focus Bear in {seconds}...",
  },
  shareLogs: {
    pleaseWriteFeedback: "Please write feedback message",
    enterFeedBack: "Record yer observations",
    logsShared: "Thank ye fer sharin'! Yer logs be sent to the headquarters.",
  },
  impact_reporting: {
    title: "Analyse Yer Sleep and Mood",
    description:
      "Would ye like to track yer sleep and mood to see if Focus Bear be makin' a positive difference to yer life? This would help us too by givin' us (anonymous) data about the impact of our app.",
    subtitle: "Data we'll collect",
    bulletPoints: "● Hours o' sleep\n● Yer mood and energy level\n● How productive ye felt at the end o' the day",
    okSure: "Ok sure",
    noThanks: "No thanks",
  },
  privacyModal: {
    heading: "Privacy and Security",
    notShareData:
      "We guard yer data like a chest o' gold, and we'll fight off any buccaneers foolish enough to try nickin' it.",
    doNotLog: "• We don't keep logs of the websites or apps ye visit.",
    chooseToBlock: "• Yer data's locked tight and encrypted, and no other scallywag gets a look.",
    dataEncrypted:
      "• To swat away distractin' apps, we do need to store their names in our hold, so yer settings sail true across all yer devices.",
    moreDetails:
      "For the finer print, spy our <bold>privacy policy</bold>, or send a message in a bottle to <email>support@focusbear.io</email>",
    accept: "Seal the pact",
  },
  pushNotiPermission: {
    title: "Allow yer notifications",
    description: "We can help remind ye to stay on track with yer habits and be on time for those important meetin's.",
  },
  distractionBlockingReason: {
    notLoggedIn: "Blockin' disabled: Ye're not logged in",
    postponeActivated: "Blockin' disabled: Postpone activated",
    focusModeActivated: "Blockin' enabled: Focus mode activated",
    firstDay: "Blockin' disabled: First day - routine not activated yet",
    otherReason: "Blockin' enabled: It's time to do yer routine",
    daytimeBlockingEnabled: "Blockin' enabled: mornin' routine be complete but daytime blockin' enabled",
    defaultCase: "Blockin' disabled: Distraction blockin' be disabled",
    withinCutoffTimeAndShutdownTime: "Blockin' disabled: ye've got free time until {cutoff_time}",
    permissionNotGranted: "Blockin' disabled: Permissions not granted (enable it in settings)",
    afterCutoffTime: "Blockin' enabled: It's time to wind down before ye sleep",
    afterCutoffTimeAndEveningRoutineFinished: "Blockin' enabled: It's time to sleep",
    detailedCutOffSleepTimeBlockingReason:
      "Distractions be blocked from {cutoff_time} so ye can sleep. Yer mornin' routine be set to start at {startup_time}. After ye finish yer mornin' routine, blockin' stops.",
  },
  blocking: {
    blockingType: "Blockin' Type",
    allowList: "Allow List",
    blockList: "Block List",
    allowListDescription:
      "Choose apps that be allowed while ye're doin' yer habits or focusin'. Everythin' else will be blocked.",
    blockListDescription:
      "Choose the distractin' apps that should be blocked while ye're doin' yer habits or focusin'. Everythin' else will be allowed.",
    appBlockList: "Apps Blocklist",
    blockAtLeastOne: "Please select at least one app to stop yerself bein' distracted",
    socialFilterTitle: "Social",
    newsFilterTitle: "News",
    gamesFilterTitle: "Games",
    miscFilterTitle: "Misc",
    recommendedSectionListTitle: "Recommended apps to block",
    otherSectionListTitle: "Other Apps",
    freeAppLimitTitle: "Arrr, matey! Ye can only block five apps with the free edition, savvy?",
    freeAppLimitDesc:
      "In the free version, ye can only choose five apps to send to Davy Jones’ locker. Upgrade to Focus Bear Pro and help us chart new waters, bringin’ more treasures to boost yer productivity! 🙂",
  },
  permissionExplanation: {
    title: "Set up permissions for distraction blockin'",
    description: "Focus Bear can block distractions while:",
    workTask: "• ye're workin'/studyin' so ye get s#*% done ⚒️",
    routineTask: "• ye're doin' yer mornin' and evenin' routine so ye do yer habits 🧘",
    sleepTask: "• ye're sleepin' so ye actually sleep 😴",
    toggleOption: "By default, ye can turn off distraction blockin' at any time.",
    friendOption: "(But ye can also choose to have a friend set a password to make it harder)",
    necessaryPermission:
      "Usage permission: To detect if ye open a distractin' app\n\nOverlay permission: This be what does the distraction blockin'",
  },
  grantPermission: {
    title: "We'll need permission to block apps",
    description: "Don't worry ye can pause distraction blockin' at any time",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Keep blockin' enabled",
    description: "Allow Focus Bear to keep blockin' apps in the background by removin' battery optimization.",
    warning: "This will use slightly more battery (but not very much).",
    keepFocusBearPoweredUp: "Keep Focus Bear powered up",
  },
  launcher: {
    title: "Apps",
    morning: "🔆 Mornin'",
    evening: "🌙 Evenin'",
    play: "🥳 Play",
    work: "🔨 Work",
    setAppLabel: "Choose a category for {appName}",
    search: "Search apps",
    noAppsFound: "No apps found",
    setAsDefaultLauncher: "Default Launcher",
    restricted: "Restricted",
    restrictedMessage: "{appName} be restricted, please focus on yer routine",
    stopBlocking: "Stop blockin'",
    openAppMenuToolTip: "Tap here to open the app menu",
  },
  DND: {
    duringFocusSessions: "Durin' Focus Sessions",
    duringHabits: "Durin' Habits & Sleep",
  },
  bearsona: {
    choose: "Choose ye a Bearsona",
    useCustomLanguage: "Use {customLanguage}, aye!",
    confirmUseCustomLanguage: "Arr talk Pirate to me!",
  },
  breathingExercise: {
    title: "Arrr, Take a Breather!",
    description: "Avast ye! Take a mindful moment ‘fore ye set sail on this sea o’ distractions!",
    dontWantToOpen: "Nay, {appName} can wait!",
    wantToOpen: "Aye, sail me to {appName}!",
    motivational: "Ye sure ye be ready to brave {appName}, matey?",
  },
  simpleHome: {
    setupBlockingApp: "Hoist the sails 'n block them app scoundrels (ye best be doin’ it!)",
    setupBlockingUrl: "Block them cursed websites too (if ye dare)",
    title: "Give Focus Bear a whirl, ye scallywag!",
    focusSessionCheckboxTitle: "First focus voyage complete!",
    microBreakCheckboxTitle: "Did yer wee break ritual!",
    focusScreenTitle: "Set sail on a Focus Session!",
    focusSessionCheckboxDesc: "Hoist the sails fer deep work!",
    microBreakCheckboxDesc: "Blow off steam with a hearty breath!",
  },
  loading: {
    loading: "Hoist the sails... loading ahead!",
    breathingExercise:
      "Whilst ye wait, try a box breathing exercise, matey! Breathe in for 3 seconds, hold for 3, breathe out for 3, hold for 3 - a sailor's rhythm!",
    loadingHabit: "Loading yer habit library, arrr!",
    pleaseWaitLoadHabit:
      "We'll recommend habits based on what matters to ye! Based on yer goals, we'll suggest helpful habits from our curated library to get ye started - a pirate's promise!",
  },
  appUsage: {
    timeUsedAfterCutoff:
      "Ye used yer talkin’ box fer <bold>{duration}</bold> durin’ the sleepin’ hours, matey! 🦜📵\n\nWant t’ raise the anchor on distraction and keep yer mind in dreamland?",
    timeUsedAfterCutoffTitle: "Ye Be Burnin’ Midnight Oil!",
  },
  streakCelebration: {
    title: "{streakTypeName} streak, ye scallywag!",
    morning: "Mornin’ ritual",
    evening: "Evenin’ ritual",
    focus: "Focus voyage",
    message: "Ye be on fire, matey! Keep sailin’!",
    day: "day",
    days: "days",
  },
};
