export default {
  languageName: "Sassy English",
  baseLanguage: "en",
  error: {
    invalidVideoUrl: "Hmmm.. That YouTube video URL is a no-go.",
    videoNotFound: "Can't find that video, sorry!",
  },
  habitSetting: {
    routineSelection: "Routine",
    requirement: "What’s the move? Tell us what you’ve gotta do.",
    youtubeVideo: "YouTube or Viemo video",
    youtubeVideoDescription: "Add a YouTube video to watch when doing this habit",
    enableTimer: "Turn on the timer!",
  },
  common: {
    learnMore: "Ugh, obviously. Learn more 💅",
    doItLater: "Whatever, I’ll do it later 🙄",
    skip: "Skip!",
    goToSleep: "Time to hit the hay! 😴",
    areYouSure: "You sure about that?",
    loading: "Hang tight, loading...",
    connectionError: "Whoops! Connection error. Try again?",
    morning: "morning vibes",
    evening: "evening chill",
    welcome: "Welcome aboard!",
    somethingWrong: "Uh-oh, something went wrong.",
    logout: "Log me out!",
    ok: "Alright!",
    ok_ellipsis: "Alright...",
    confirm: "You got it!",
    next: "Onward!",
    cancel: "Nope, cancel that!",
    proceed: "Let’s do this!",
    resume: "Pick up where you left off!",
    retry: "Let’s try that again!",
    submit: "Send it in!",
    verify: "Verify, please!",
    finished: "All done!",
    sec: "sec",
    focusBear: "focus bear",
    tomorrow: "tomorrow",
    today: "today",
    save: "Save it!",
    startRoutine: "Kick off the routine!",
    continue: "Keep going!",
    end: "Wrap it up!",
    startActivity: "Let’s start {activityName}!",
    startTimerActivity: "Start {time} {unit} for {activityName}",
    Success: "Success! 🎉",
    save_changes: "Save those changes!",
    saving: "Saving your progress...",
    next_time_format: "[{day} at] h:mm A",
    sure: "Absolutely!",
    uploadScreenShots: "Upload screenshots (Optional, if you want)",
    session_expired: "Session expired, time to log back in!",
    login_again: "Please log in again, buddy.",
    continue_activity_name: "Keep going with {activityName}",
    no_thanks: "No thanks, I'm good!",
    saveHabitSuccessfully: "Your changes are saved successfully, nice job!",
    granted: "Finally",
    notGranted: "Still waiting...",
  },
  lateNoMore: {
    title: "Meeting Reminders",
    calendarIntegration: "Calendar Integration",
    calendarTooltip: "To enable meeting detection you can connect your phone's calendar or your Google calendar",
    googleCalendar: "Google Calendar",
    connected: "Connected",
    notConnected: "Not connected",
    enableReminders: "Enable Reminders",
    calendarPermission: "Device Calendar",
    calendarPermissionAlreadyGranted:
      "Device Calendar is connected. You can revoke access at any time via your phone's settings",
    calendarPermissionDenied: "Please grant calendar access permission in your phone's settings",
    openSettings: "Open settings",

    addReminder: "Add reminder",
    durationBefore: "{duration} before",
    whenMeetingStarts: "When meeting starts",
    requireMeetingUrl: "Events with Meetings Only",
    requireMeetingUrlDescription: "Only include events that have a meeting URL attached",
    // Notification messages
    notification1: "Don't be late, darling! 🐻",
    notification2: "Get ready to head to your meeting! ⏰",
    notification3: "Your meeting is waiting! 📅",
    notificationBody: "'{title}' starts {time}",
    now: "now",
    // Meeting Preparation UI
    yourMeetingStartsIn: "Meeting in <highlight>{countdown}</highlight>. Let's get ready!",
    yourMeetingIsOngoing: "There's an ongoing meeting. Join <highlight>now</highlight>!",
    upcomingMeeting: "Upcoming event",
    mentallyPrepare: "1. Mentally prepare for the meeting",
    howDoYouWantToShowUp: "How do you want to show up?",
    placeholderHowToShowUp: "Calm, listening, open-minded, collaborative...",
    joinOnTime: "2. Join on time",
    ignoreMeeting: "Ignore meeting",
    startMeeting: "Join meeting",
    noUpcomingMeetings: "No upcoming meetings",
    noMeetingsDescription: "We didn't find any meetings scheduled in the next few hours.",
    // Calendar source indicators
    googleCalendarSource: "Source: Google calendar",
    deviceCalendarSource: "Source: On-device calendar",
  },
  settings: {
    debugLog: "Turn on detailed logging",
    debugLogDescription: "Only do this if support tells you to; it might slow things down.",
    title: "Settings",
    addApps: "Add apps to the blocklist",
    clearBlocklist: "Wipe the blocklist clean",
    confirmClearBlocklist: "Are you sure you want to clear the blocklist?",
    strictness: "How strict do you want to be?",
    shareLogsWithSupport: "Share your logs to us!",
    reason_required: "Please tell us why.",
    enter_a_reason: "Mind sharing why you want to delete your account?",
    contact_desc: "Can we reach out to help fix your issues?",
    editFriction: "Friction settings",
    password: "Password, please!",
    account: "Your account",
    permissions: "Permissions, let’s check!",
    language: "Language, what’s your pick?",
    useSystemLanguage: "Use the system language, cool?",
    supportedLanguages: "Languages we support",
    overlay_permission: "Overlay Permission, please!",
    usage_permission: "Usage Permission, let’s go!",
    notification_permission: "Notification Permission, yes please!",
    screen_time_permission: "Screen Time Permission, don’t forget!",
    DND_permission: "Do Not Disturb Permission, shhh!",
    DND: "Do Not Disturb, please!",
    warning: "Warning, warning!",
    DND_permissionWarning: "You gotta turn off DND mode manually if it’s on. We can’t do it for you.",
    help: "Need help?",
    report_problem: "Report a problem, let’s fix it!",
    discord_server: "Join our Discord server!",
    videoTutorials: "Check out our video tutorials!",
    experimental: "Experimental features, ooh!",
    customization: "Customization, make it yours!",
    general: "General settings",
    allowed: "Allowed",
    notAllowed: "Not granted",
    userid: "UserId",
    copy: "Copy that!",
    copied: "Copied, nice!",
    verifyEmail: "Verify that email!",
    editNickname: "Edit your nickname, make it fabulous!",
  },
  focus: {
    title: "Focus time!",
    focusLimitReachedTitle: "Focus limit reached, buddy!",
    focusLimitReachedMessage:
      "In the free version, you can only focus for 25 minutes. Wanna upgrade for longer sessions?",
  },
  home: {
    setupHabitsDescription: "Setup your habits to start your day, darling.",
    getMotivated: "Get up and slay, darling!",
    habitName: "What’s the habit called?",
    newHabit: "New habit, what’s it gonna be?",
    duration: "Duration",
    editHabit: "Edit this habit",
    addHabit: "Add a new habit",
    deleteThisHabit: "Delete this habit, are you sure?",
    deleteHabit: "Delete habit {name}, really?",
    afterCutoffTimeDescription: "No habits available, it’s past the cutoff time",
    cutOffToolTip:
      "You set cutoff times for your habits, so they’re not available after {cutOffTime}. Change this in Change timing.",
    unlockToProceed: "Unlock to keep going!",
    title: "Habits",
    morningRitual: "Your morning ritual",
    eveningRitual: "Your evening ritual",
    time_to_earn_screen_time: "Do your morning habits to kickstart an awesome day!",
    evening_routine_text: "Here are your evening habits. Finish them up for a great night’s sleep!",
    upcoming_below_new_activities: "Here are the habits you need to crush in your next routine to use your phone.",
    start: "Let’s start!",
    mins: "mins",
    secs: "secs",
    re_activate: "Re-activate this habit",
    force_deactivate_postpone_and_start_routine: "Routine postponed. Resume routine?",
    userCompletedMorningRoutineHeading:
      "Awesome job finishing your morning routine! Can’t wait to help with your evening routine {routineTime}",
    postOnboardingRoutineHeading: "Welcome aboard! Excited to help with your {routineName} routine {routineTime}",
    userCompletedEveningRoutineHeading:
      "Great job on your evening routine! Ready to tackle the morning one {routineTime}?",
    wantLogout: "Wanna log out?",
    noDataFound: "No habits set up yet. Tap <fix>here</fix> to add some.",
    routineFetchingError: "We hit a snag while fetching your routine data. Try again later or reach out for help.",
    hi: "Hey there, {nickname}!",
    goodMorningFocusTime: "Good Morning! Let’s get focused!", // unused
    goodEveningFocusTime: "Good Evening! Time to wind down!", // unused
    allActivitiesCompleted: "You’ve completed all your habits, nice work!",
    startRoutineNow: "Let’s do my {routineName} routine!",
    passwordForSettingsTitles: "Enter your password to proceed",
    manageAlwaysAllowedAppsDesc:
      "During your morning/evening routine and when focusing on your computer, only the Always Allowed Apps will be accessible. We suggest allowing only essential apps like SMS and work-related ones to avoid distractions.",
    manageAlwaysBlockedAppsDesc:
      "During your morning/evening routine and when focusing on your computer, all apps in your blocklist will be blocked. We recommend blocking social media, games, emails, and news apps to keep distractions at bay.",
    overlayPermission: "Overlay Permission, please!",
    usagePermission: "Usage Permission, let’s go!",
    editHabits: "Edit your habits",
    editYourHabits: "Let’s tweak your habits!",
    stats: "Stats, let’s see how you’re doing!",
    motivationMsg: "Get motivated, you can do this!",
    play: "Playtime!",
    pause: "Pause for a moment!",
    customizeHabits: "Change the timing of your habits",
    deleteAccount: "Wanna delete your account?",
    accountDataHasBeen: "Your account data has been successfully deleted. Thanks for using Focus Bear!",
    blockSuperDistractingApps: "Block those super distracting apps!",
    skipHabitDesc: "Skip this habit today, no biggie!",
    screenTimePermissionNotAllowedWarningText:
      "Screentime permission is needed to block apps. Start a habit again to allow permissions.",
    OverlayPermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Overlay permission not granted. Fix it!",
    ScreenTimePermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Screen Time permission not granted. Fix it!",
    UsagePermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Usage permission not granted. Fix it!",
    noAllowedAppSelectedWarning:
      "Warning: you haven’t set up your blocklist yet, so distractions won’t be blocked. Edit your blocklist.",
    habitLimitMessage: "Free users can only access up to 3 habits per routine. Upgrade to unlock more habits!",
    routineOptionsTooltip: "This menu is where you edit your routine or change timing. Obviously.",
  },
  postpone: {
    doYouReallyWantTo: "You're not *really* pausing, are you?",
    blockingPausedForDuration: "Fine, blocking paused for {duration}",
    blockingPausedIndefinitely: "Blocking paused until you say so",
    pauseBlocking: "Pause blocking!",
    pauseDisabledStrictMode: "Nice try, but Super Strict Mode isn’t letting anyone pause right now",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Get back to business!",
    choosePostponeTime: "How long are you planning to procrastinate, darling?",
    indefinite: "Just pause forever, why don't you? *hair flip*",
    youHavePausedTimesToday_zero: "This is your first time pausing today.",
    youHavePausedTimesToday_one: "Already took one break today sweetie.",
    youHavePausedTimesToday_other: "{count} breaks already? Someone's feeling extra today!",
    countdown: "you'll have to wait {countdown} before I let you pause again!",
    areYouSureIndefinite:
      "Pause indefinitely? Girl, please! That 'urgent' thing can probably wait 15 tiny minutes while you finish your habits. Just saying!",
    doHabits: "Actually, I'll stick to my habits!",
    longTermGoalsDesc: "Hey! Remember these goals you set with Focus Bear?",
    lowQualityUsageDesc: "You've wasted {duration} on distracting apps today.",
    write: "Write it down...",
  },
  passwordForSettings: {
    invalid_password: "That password is invalid, try again!",
    resetAfter24Hours: "Reset requested. Your password will be disabled after 24 hours.",
  },
  signIn: {
    logIn: "Log me in!",
    enterEmailHint: "Your Email Address, please!",
    enterPasswordHint: "Your Password, let’s go!",
    invalidCredentials: "Invalid username or password, try again!",
    enterEmailError: "Please enter your email!",
    enterValidEmailError: "Please enter a valid email!",
    enterPasswordError: "Please enter your password!",
    dontHaveAccount: "No account yet?",
    forgotPassword: "Forgot your password?",
    signup: "Sign me up!",
    googleSignIn: "Continue with Google, easy peasy!",
    alreadyHaveAccount: "I already have a Focus Bear account!",
  },
  forgotPassword: {
    forgotPasswordTitle: "Forgot your password?",
    backToSignIn: "Back to sign in, please!",
  },
  signUp: {
    signUp: "Sign me up!",
    tosAndPP: "I agree to the <bold>Terms of Service</bold> and <bold1>Privacy Policy</bold1>",
    alreadyHaveAccount: "Already have an account?",
    passwordMatchError: "Oops! Passwords don’t match.",
    acceptTerms: "Please agree to the Terms of Service and Privacy Policy to continue.",
    passwordHintError:
      "Password must contain:\n• At least 8 characters\n• Numbers (0-9)\n• Lowercase letters (a-z)\n• Uppercase letters (A-Z)\n• Special characters (!@#$%^&*)",
    invalidSignup: "Invalid sign-up, try again!",
    userExists: "This user already exists.",
    terms: "Terms, check them out!",
    privacy: "Privacy, read up!",
    or: "OR",
  },
  profile: {
    logout: "Log me out!",
  },
  routineDetail: {
    activity: "Activity, what’s on the agenda?",
    not_playable_video: "Can’t play that video, sorry!",
    done: "I’m done, yay!",
    video: "Video time!",
    images: "Images, let’s see!",
    checklist: "Checklist, don’t forget!",
    note: "Note it down!",
  },
  quickBreak: {
    quickBreak: "Quick Breaks, let’s recharge!",
    quickStretch: "Stretch it out",
    stretch: "Loosen up!",
    drinkWater: "Drink Water, stay hydrated!",
    water: "Water, please!",
    deepBreathing: "Deep Breathing, relax!",
    breathe: "Breathe!",
    saveQuickBreakSuccessfully: "Your changes are saved successfully, nice job!",
    editQuickBreaks: "Edit Your 'Quick' Breaks",
    quickBreakName: "Quick break name, don't overthink it.",
    currentSelection: "Your current 'masterpiece' selection.",
  },
  complete: {
    backToHome: "Back to Home, let’s go!",
    logQuantity: "Log the quantity of activity",
    finishedCheck: "finished!",
    habitNotCompleted: "didn’t complete, try again tomorrow!",
    finishedAndEarnedMorning: "All done! ✅ You’ve earned your screen time!",
    finishedAndEarnedEvening: "All done! ✅ You’ve earned a good night’s sleep. See you tomorrow morning!",
    why_skip: "Why do you want to skip?",
    already_did: "I already did it!",
    cannot_today: "Can’t do it today, sorry!",
    quantity_input_error: "Number needs to be between {min} and {max}.",
    freemiumLimitReached: "Sorry, you can only complete 3 habits with a free plan.",
  },
  reason: {
    canShare: "Can you share why you're pausing indefinitely?",
    shareFeedback: "Share feedback",
    everythingIsOk: "Uh oh - hope everything’s okay. Giving you access now.",
    appBrokenDesc: "Really sorry about that. Mind telling us what happened?",
    somethingElseDesc: "Okay. Any feedback you want to share with us?",
    gotEmergency: "I’ve got an emergency!",
    appBroken: "The app is broken, help!",
    somethingElse: "Something else, what’s up?",
  },
  nativeModule: {
    backgroundService: "Focus Bear background service to help you focus, let’s go!",
  },
  notification: {
    scheduleNotificationTitleForResumeRoutine: "Resume your routine, time to focus!",
    scheduleNotificationDescriptionForResumeRoutine: "It’s time to focus on your routine!",
    floatingModuleActivityCompleteNotificationtitle: "Activity Completed, nice job!",
    floatingModuleRoutineCompleteNotificationtitle: "Routine Completed, you did it!",
    morningRoutineCompletedNotificationDescription: "Morning routine completed. Look at you being all productive!",
    eveningRoutineCompletedNotificationDescription: "Evening routine completed. Sleep well, superstar!",
    customRoutineCompletedNotificationDescription: "{{routineName}} completed. Took your time, but you got there!",
  },
  focusMode: {
    blockingPermissionNeeded: "No perms, no blocks. Period.",
    noBlockingAppsSelected: "Pick some apps, sweetie.",
    confirmSuperStrictMode: "Super strict? Once you’re in, you’re *in*. No exits, no excuses!",
    focusTitle: "Start a focus session, let’s do this!",
    superStrictToolTip:
      "Committed to this focus session? Enable super strict mode and you won’t be able to turn focusing off or pause app blocking until the timer is up.",
    superStrictMode: "Super strict mode, are you ready?",
    brainDump: "Brain dump",
    brainDumpToolTip: "Write down any distracting thoughts here. It’ll help you focus better!",
    postFocusCongrats_0: "Nice work! You crushed it!",
    postFocusCongrats_1: "Hey, great job finishing that! What’s up next?",
    postFocusCongrats_2: "You did it! Feel free to take a breather now.",
    postFocusCongrats_3: "Well done! You're really getting things done!",
    postFocusCongrats_4: "Awesome job! What’s the next thing on your radar?",
    postFocusCongrats_5: "You made it through! Time to tackle the next one?",
    postFocusCongrats_6: "Great focus! Go grab a drink or a snack!",
    postFocusCongrats_7: "Nice! You’re making serious progress!",
    postFocusCongrats_8: "Well done! Time to stretch your legs a bit?",
    postFocusCongrats_9: "You did great! Let’s keep that momentum going!",
    startFocusSession: "Start a focus session, let’s go!",
    noIntentionWasFound: "No intention entered, what’s your goal?",
    distractionAlertTitle: "Focus Mode, stay on track!",
    userIntention: "Focus Goal",
    noDistractingThoughtsWasFound: "No distracting thoughts entered, focus up!",
    userIntentionTextInputPlaceholder: "What do you want to work on?",
    startFocusing: "Start Focusing, let’s do this!",
    hours: "h",
    minutes: "m",
    duration: {
      hours: "{hours} hours",
      minutes: "{minutes} minutes",
      seconds: "{seconds} seconds",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "You got this!\nDeep work time, let’s go!",
    endSession: "End Session, wrap it up!",
    completeFocus: "Complete Focus, you did it!",
    userDumpThoughTextInputDescription: "Write down any distracting thoughts here, let it out!",
    exitFocusMode: "End focus session early, are you sure?",
    exitFocusModeDescription: "Can you share why you’re ending this session?",
    reason: "Reason, what’s up?",
    selectReason: "Select a reason, please!",
    congratulations: "Congratulations, superstar!",
    focusDoneTitle: "YOU DID IT!",
    focusDoneDescription: "You remained focused for",
    focusDoneDescription1: "What was your intention?",
    focusDoneDescription4: "What were your distracting thoughts?",
    focusDoneDescription2: "What did you achieve during this time?",
    focusDonePlaceholderDescription2: "Enter what you achieved with our help",
    focusDoneDescription3: "Did you have any distractions?",
    focusDonePlaceholderDescription3: "Enter any distractions you had",
    endEarlyReasonDescription1: "I have an emergency!",
    endEarlyReasonDescription2: "Focus mode is not working properly, help!",
    endEarlyReasonDescription3: "I’ve achieved what I wanted!",
    endEarlyReasonDescription4: "I need a break, please!",
    runningFocusModeDesc: "A focus session is running, stay focused!",
    extendFocusDuration: "Extend Focus Duration, keep it going!",
    selectExtendFocusDuration: "How much longer do you want to focus for?",
    extendFocus: "Extend, let's do it!",
    shortenFocusDuration: "Shorten Focus Duration, need a break?",
    selectShortenFocusDuration: "How much time do you want to shorten, darling?",
    shortenFocus: "Shorten, let's chill! 🍹",
    adjustFocusDuration: "Adjust Focus Duration",
    chooseAdjustmentOption: "Want to extend or shorten your focus session, sweetie?",
    editFocusDuration: "When do you want to stop slacking off and finish focusing?",
  },
  networkError: {
    noNetworkAlertTitle: "Internet disconnected, uh-oh!",
    retrying: "Trying again I guess",

    connectionError: "Aaaah! Unstable internet connection!",
    apiError: "Uh-oh! Something ain't right!",
    internalError: "Yikes! Internal error!",
  },
  manageAllowedApps: {
    searchPlaceholder: "Search installed apps, what do you need?",
  },
  addNoteModule: {
    addNote: "Add a Note, let’s jot it down!",
    placeholder: "Add Note Here...",
    saveNote: "Save Note, don’t forget!",
    automaticallySave: "Your note will be saved automatically, easy peasy!",
  },
  permissionWarning: {
    usageAccessTitle: "We need Usage Access permission to help block distractions!",
    deviceUsagedescription:
      'To block distracting apps while you’re focusing/doing your habits, we need "usage access" permissions to see which app you’re using.',
    overlayTitle: "We need Overlay permission to help block distractions!",
    overlayDescription:
      'To block distracting apps while you’re focusing/doing your habits, we need "Overlay" permissions to see which app you’re using and show distraction alerts for not allowed apps.',
    privacyNoteTitle: "Privacy note, we care!",
    privacyNoteDesc: "We don’t log which apps or websites you use. We just use it for blocking in real time.",
    grantAccess: "Allow, let’s do this!",
  },
  onboarding: {
    nextStep: {
      upNext: "Coming in hot: {step} 💁‍♀️",
      focusSession: "Time to slay in a focus sesh",
      microBreak: "Tiny break, big energy",
      allDone: "Boom. All done, gorgeous ✨",
    },
    onboarding: "Onboarding",
    letsDoIt: "Let’s do it!",
    replay: "Replay!",
    instructionVideo: "Instruction Video, check it out!",
    welcomeAboard: "Welcome aboard, let’s make some magic!",
    lookingForwardToHelp: "Looking forward to helping you form healthy habits and get more deep work done!",
    getStarted: "Get Started, let’s roll!",
    allDone: "All Done, high five!",
    installDesktopApp: "Install the desktop app, let’s go!",
    installDesktopAppDesc:
      "Focus Bear works on Mac and Windows too. If you’ve got a computer, download the app from <bold>focusbear.io</bold> to sync your focus sessions and habits.",
    cutoffTimeWarning: "Get off tech time should be after your work finish time ({time}).",
  },
  goals: {
    boostProductivity: "🚀 Boost productivity (work, study, tasks), let’s get it!",
    improveMentalHealth: "🧘 Improve mental well-being (stress, sleep), take care of yourself!",
    improvePhysicalHealth: "🏋️‍♂️ Focus on health & fitness (exercise, nutrition), stay fit!",
    manageTask: "🏡 Manage home tasks (cleaning, chores), keep it tidy!",
    otherSpecify: "✏️ Other (please specify: __)",
    strengthenRelationShip: "❤️ Strengthen relationships (family, friends), keep those bonds strong!",
    achievement_placeholder: "Tell us your goal, we’re listening!",
    enableFeatures: "Enable features, let’s unlock some magic!",
    doOurBest: "We’re here to help you reach your goals. Which Focus Bear features would you like to turn on?",
    achievementWithFocusBearDesc: "What are your main goals?",
    help_me_develop: "Build healthy habits, let’s do it!",
    help_me_stay: "Stay focused at work, keep it up!",
    help_me_develop_tooltip:
      "Focus Bear can guide you through healthy habits (meditation, exercise, journaling, etc.) in your morning and evening routine.",
    help_me_stay_focused_tooltip:
      "Focus Bear will block distractions while you’re working so you can get deep work done.",
    organize_tasks_using_ai: "Organize your tasks using AI",
    organize_tasks_using_ai_tooltip: "Focus Bear can organize your tasks using AI",
    what_are_you_hoping_focus_bear_can_do: "What are you hoping Focus Bear can do?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Tell us what you're hoping Focus Bear can do",
    explore_the_app_first: "Explore the app first",
    setup_habits: "Set up habits",
    setup_habits_question: "Do you want to set up your habits now (takes ~3 minutes) or explore the app first?",
  },
  habit: {
    habitPack: "Choose your habits, let’s see what you got!",
  },
  setupTime: {
    setStartupTime: "Choose Your Start Time, when do you wake up?",
    chooseTheAbsoluteEarliest: "What time do you wake up?",
    setShutdownTime: "When do you finish working/studying?",
    setSleepTime: "What time do you want to go to sleep?",
    sleepTimeDesc:
      "Between {shutdown_time} and {sleep_time}, you can chill on your phone. After {sleep_time}, Focus Bear will help you wind down for the evening. Distracting apps will be blocked so you can sleep well.",
  },
  blockList: {
    title: "Make your phone safe during habits/focus sessions, let’s do this!",
    subTitleAndroidBlockList: "Choose distracting apps to block while you’re doing habits or focusing.",
    buttonAndroidBlockList: "Choose distractions, let’s go!",
    subTitleIos: "Choose distracting apps to block while you’re doing habits or focusing.",
    buttonIos: "Choose distractions, let’s go!",
  },
  editFriction: {
    frictionTooltipDescription:
      'You’re a disciplined person, but sometimes you might be tempted to skip your habits or stop blocking distractions on a whim. Set up extra "friction" to slow down those impulsive thoughts. If you enable high friction mode, it’ll ask you to wait a few seconds before you stop blocking distractions.',
    frictionForSkippingHabits: "Friction for skipping habits, let’s make it tough!",
    reallyEasy: "Really easy - I want to skip habits/breaks in a hurry!",
    makeItHardToSkip: "Make it hard to skip - otherwise, I’ll end up skipping habits + breaks most of the time.",
    appBlocking: "Block distractions, let’s do it!",
    blockDuringDaytime: "Block distracting apps during the workday, keep it focused!",
    reallyEasyDescription: "Instant freedom! You’ll be able to immediately stop blocking distractions",
    makeItHardToSkipDescription:
      "Not so fast! To avoid impulsively turning off blocks, Focus Bear can show a short countdown timer to encourage you to reconsider whether you should be accessing distracting apps.",
  },
  strictness: {
    setPassword: "Set a password!",
    setPasswordDescription:
      "If you’re struggling to stick to your habits, get a housemate/partner to set a password. You won’t be able to skip habits without it.",
    enterConfirmPasswordHint: "Confirm your Password, please!",
    askForPassword: "Ask for password, let’s keep it safe!",
    whenRequirePasswordDescription: "When do you want to require a password?",
    changingSettings: "Changing settings",
    postponingMorningRoutine: "Postponing/Skipping morning routine",
    postponingEveningRoutine: "Postponing/Skipping evening routine",
    postponingAfterCuttOffTime: "Postponing/Skipping evening routine after cutoff time",
    usingPhoneLateNight: "Using your phone late at night",
    relaxFocusMode: "Allow using relax focus mode",
    suggestion: "Hint!",
  },
  subscription: {
    upgrade: "Time to upgrade!",
    personalizedHabit: "Personalized habit routines",
    productivityBoosting: "Productivity-boosting breaks",
    customizedFocus: "Customizable focus modes",
    automaticGoals: "Automatic goals tracking",
    cancel: "Cancel auto-renewal",
    subscription: "Subscription",
    trialActive:
      "Your trial lasts for {day} more day(s). Do not worry, you will not be charged when the trial ends and no credit card required upfront",
    getSubscriptionPlan: "Get our subscription plan to use the app and unlock all features",
    subscriptionPlanPrice: "Continue for only <bold>{amount}</bold>/month",
    benefit: "Benefits includes",
    doesSubscriptionAutoRenew: "Does my subscription auto renew?",
    subscriptionAutoRenew:
      "Subscription will automatically renew and you will be charge at the end of each period. You can disable it at anytime with just one click in the store",
    thankYouForSubscribing:
      "Thank you for subscribing, you can now use all features of Focus Bear\n\nYour subscription will expire in <bold>{day}</bold> days",
  },
  editHabit: {
    okay: "Okay, let’s do this!",
    error: "Error, whoops!",
    unableToSaveSettings:
      "Something went wrong. So sorry! Our engineering team has been notified, and we’ll fix it ASAP. If you don’t hear from us within 24 hours, please email support@focusbear.io, and we’ll get it sorted for you.",
    goingBack:
      "You’re about to go back to the Settings menu. If you’ve made any changes, please tap the 'Save Habits' button.",
    continue: "Continue, let’s keep going!",
    cancel: "Cancel, no problem!",
    warning: "Warning, be careful!",
    restartingIn: "Restarting Focus Bear in {seconds}...",
  },
  shareLogs: {
    pleaseWriteFeedback: "Please write a feedback message, we want to hear from you!",
    enterFeedBack: "Enter your feedback, let’s hear it!",
    logsShared: "Logs have been shared with support, thank you!",
  },
  impact_reporting: {
    title: "Analyze Your Sleep and Mood, let’s see!",
    description:
      "Would you like to track your sleep and mood to see if Focus Bear is making a positive difference in your life? This would help us too by giving us (anonymous) data about the impact of our app.",
    subtitle: "Data we’ll collect, check it out!",
    bulletPoints: "● Hours of sleep\n● Your mood and energy level\n● How productive you felt at the end of the day",
    okSure: "Ok, sure!",
    noThanks: "No thanks, I’m good!",
  },
  privacyModal: {
    heading: "Privacy and Security, we care!",
    notShareData: "We take your privacy and security very seriously and will never share your data, ever.",
    doNotLog: "• We do not log how much time you spend on websites or apps.",
    chooseToBlock:
      "• If you want to block distracting apps, we need to store the names of those installed apps in our database so your settings will sync across all your devices.",
    dataEncrypted: "• Your data is encrypted, and we don’t let anyone else see it.",
    moreDetails:
      "For more details, refer to our <bold>privacy policy</bold> or feel free to email support@focusbear.io.",
    accept: "Accept, let’s go!",
  },
  pushNotiPermission: {
    title: "Allow Notifications!",
    description: "We can remind you to stay on track with your habits and show up on time for meetings.",
  },
  distractionBlockingReason: {
    notLoggedIn: "Blocking disabled: You’re not logged in.",
    postponeActivated: "Blocking disabled: Postpone activated.",
    focusModeActivated: "Blocking enabled: Focus mode activated.",
    firstDay: "Blocking disabled: First day - routine not activated yet.",
    otherReason: "Blocking enabled: It’s time to do your routine.",
    daytimeBlockingEnabled: "Blocking enabled: Morning routine is complete, but daytime blocking is enabled.",
    defaultCase: "Blocking disabled: Distraction blocking is disabled.",
    withinCutoffTimeAndShutdownTime: "Blocking disabled: You’ve got free time until {cutoff_time}.",
    permissionNotGranted: "Blocking disabled: Permissions not granted (enable it in settings).",
    afterCutoffTime: "Blocking enabled: It’s time to wind down before you sleep.",
    afterCutoffTimeAndEveningRoutineFinished: "Blocking enabled: It’s time to sleep, goodnight!",
    detailedCutOffSleepTimeBlockingReason:
      "Distractions are blocked from {cutoff_time} so you can sleep. Your morning routine is set to start at {startup_time}. After you finish your morning routine, blocking stops.",
  },
  blocking: {
    blockingType: "Blocking Type, what’s your choice?",
    allowList: "Allow List, for the special ones!",
    blockList: "Block List, keep distractions away!",
    allowListDescription:
      "Choose apps that are allowed while you’re doing your habits or focusing. Everything else will be blocked, no distractions!",
    blockListDescription:
      "Choose the distracting apps that should be blocked while you’re doing your habits or focusing. Everything else will be allowed, focus up!",
    appBlockList: "Apps Blocklist, let’s get serious!",
    blockAtLeastOne: "Please select at least one app to stop yourself from being distracted!",
    socialFilterTitle: "Social",
    newsFilterTitle: "News",
    gamesFilterTitle: "Games",
    miscFilterTitle: "Misc",
    recommendedSectionListTitle: "Recommended apps to block, trust us!",
    otherSectionListTitle: "Other Apps, what else you got?",
    freeAppLimitTitle: "Only 5 blocks in the freebie zone! Want more? Go Pro and party harder. 🥳",
    freeAppLimitDesc:
      "Free version = 5 app blocks. Pro version = unlimited power! 💪 Your support keeps us coding, caffeinated, and building cool stuff to help you focus like a champ. 🎩✨",
  },
  permissionExplanation: {
    title: "Set up permissions for distraction blocking, let’s do this!",
    description: "Focus Bear can block distractions while:",
    workTask: "• you're working/studying so you get stuff done ⚒️",
    routineTask: "• you're doing your morning and evening routine so you stick to your habits 🧘",
    sleepTask: "• you're sleeping so you actually get some Z's 😴",
    toggleOption: "By default, you can turn off distraction blocking at any time.",
    friendOption: "(But you can also choose to have a friend set a password to make it harder to deactivate.)",
    necessaryPermission:
      "Usage permission: To detect if you open a distracting app.\n\nOverlay permission: This is what does the distraction blocking.",
  },
  grantPermission: {
    title: "We’ll need permission to block apps, please!",
    description: "Don’t worry, you can pause distraction blocking at any time.",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Keep blocking enabled, don’t let distractions win!",
    description: "Allow Focus Bear to keep blocking apps in the background by removing battery optimization.",
    warning: "This will use slightly more battery (but not very much).",
    keepFocusBearPoweredUp: "Keep Focus Bear powered up, let’s go!",
  },
  launcher: {
    title: "Apps",
    morning: "🔆 Morning",
    evening: "🌙 Evening",
    play: "🥳 Play",
    work: "🔨 Work",
    setAppLabel: "Choose a category for {appName}, what fits?",
    search: "Search apps, what do you need?",
    noAppsFound: "No apps found, try again!",
    setAsDefaultLauncher: "Default Launcher, make it happen!",
    restricted: "Restricted, focus on your routine!",
    restrictedMessage: "{appName} is being restricted, please focus!",
    stopBlocking: "Stop blocking, let’s take a break!",
    openAppMenuToolTip: "Tap here to open the app menu, let’s go!",
  },
  DND: {
    duringFocusSessions: "During Focus Sessions, keep it quiet!",
    duringHabits: "During Habits & Sleep, shhh!",
  },
  bearsona: {
    choose: "Choose one, pick your buddy",
    useCustomLanguage: "Use {customLanguage}, if you want!",
    confirmUseCustomLanguage: "Let’s get Sassy!",
  },
  breathingExercise: {
    title: "Okay, Diva—Breathe!",
    description: "Take a deep breath before diving into this hot mess of distraction.",
    dontWantToOpen: "Ugh, {appName}? Not feeling it.",
    wantToOpen: "Fine, let’s just go to {appName}. Whatever.",
    motivational: "Seriously? You’re opening {appName} *again*?",
  },
  simpleHome: {
    setupBlockingApp: "Block those messy apps (yes queen, recommended)",
    setupBlockingUrl: "Block some messy websites too (if you feel like it)",
    title: "Have a laugh with Focus Bear!",
    focusSessionCheckboxTitle: "First focus feat—achieved!",
    microBreakCheckboxTitle: "Wiggled through a mini break!",
    focusScreenTitle: "Time for some tomfoolery—Focus!",
    focusSessionCheckboxDesc: "Time to tango with tasks!",
    microBreakCheckboxDesc: "Take a breather, clown-style!",
  },
  loading: {
    loading: "Loading... don't rush me!",
    breathingExercise:
      "While you wait, try a box breathing exercise. Breathe in for 3 seconds, hold for 3, breathe out for 3, hold for 3 - and no, I won't count for you!",
    loadingHabit: "Loading your habit library, darling!",
    pleaseWaitLoadHabit:
      "We'll recommend habits based on what matters to you. Based on your goals, we'll suggest helpful habits from our curated library to get you started - because we're just that good!",
  },
  appUsage: {
    timeUsedAfterCutoff:
      "You were scrolling for <bold>{duration}</bold> during your beauty sleep 😏📲\n\nWanna crank up the sass and shut that screen down sooner?",
    timeUsedAfterCutoffTitle: "Caught Red-Handed!",
  },
  streakCelebration: {
    title: "{streakTypeName} streak, honey!",
    morning: "Morning routine",
    evening: "Evening routine",
    focus: "Focus session",
    message: "Look at you being all productive! Keep it up, superstar 💅",
    day: "day",
    days: "days",
  },
};
