export default {
  languageName: "English",
  baseLanguage: "en",
  blockingSchedule: {
    title: "Blocking Schedule",
    namePlaceholder: "Block name",
    startTime: "From",
    endTime: "To",
    adjustStart: "Adjust start time",
    adjustEnd: "Adjust end time",
    daysHeading: "On these days",
    chooseApps: "Choose apps",
    chooseUrls: "Choose websites",
    saveFailedTitle: "Unable to save schedule",
    saveFailedMessage: "Please try again after selecting apps to block.",
    duplicateNameMessage: "Please choose a unique name for this blocking schedule.",
    focusModeSuffix: "(from mobile blocking schedule)",
    defaultName: "💻 Work Time",
    appBlocking: "App blocking",
    websiteBlocking: "Website blocking (optional)",
    accessibilityRequiredForUrls: "Accessibility required to block websites.",
    selectionMissing: "Pick apps to block",
    urlsSelectionMissing: "No websites selected",
    urlsSelectionCount_one: "{count} website selected",
    urlsSelectionCount_other: "{count} websites selected",
    urlsDescription: "Add websites to block during this schedule",
    selectedUrls: "Selected websites",
    suggestedUrls: "Suggested websites",
    noAppsSelected: "No apps selected",
    iOSSelectionCounts: "{applicationsCount} apps, {categoriesCount} categories, {webDomainsCount} websites",
    androidSelectionCount: "{applicationsCount} apps selected",
    mode: {
      strict: {
        title: "Strict block",
        subtitle: "No escaping - enter a password to unlock",
      },
      cooldown: {
        title: "Cool-down block",
        subtitle: "Unlock after a short wait (gives you time to rethink)",
      },
      gentle: {
        title: "Gentle block",
        subtitle: "Pause blocking immediately with risk of doomscrolling 😅",
      },
    },
    removeTitle: "Delete this schedule?",
    removeMessage: "This will permanently delete the schedule.",
    removeFailedMessage: "Please try again.",
    blockedBySchedule: "Blocked by schedule: {scheduleName}",
    appBlockedBySchedule: "{appName} is blocked because your {scheduleName} blocking schedule is active",
    blockAllDuringHabits: "Block some apps during all habits",
    customizeBlocking: "Customize Blocking",
    habitBlocksTitle: "Habit blocks",
    scheduledBlocksTitle: "Scheduled blocks",
    scheduledBlocksInfoText: "Create time windows that repeat on selected days. You can add multiple blocks.",
    addNewBlock: "Add a block",
    habitMorningName: "Morning Routine",
    allDays: "Every day",
    permissionsRequired: "Permissions Required",
    androidPermissionDescription: "Usage access and overlay permissions are required to block apps",
    iOSPermissionDescription: "Screen Time permission is required to create and manage blocking schedules.",
  },
  tabTitle: {
    overview: "Overview",
    habits: "Habits",
    tasks: "Tasks",
  },
  error: {
    invalidVideoUrl: "That video URL doesn't look right 😕",
    videoNotFound: "Sorry, we couldn't find that video!",
    authenticationErrorName: "Authentication Error",
    authenticationErrorMessage: "Oops! Something went wrong with authentication on our side. Please try again.",
  },
  habitSetting: {
    routine: "Routine",
    selectRoutine: "Select routine",
    requirement: "What needs to be done to complete this habit",
    youtubeVideo: "YouTube or Vimeo video",
    youtubeVideoDescription: "Add a video to guide you through this habit",
    enableTimer: "Enable timer?",
    timer: "Timer",
    timerDescription: "Set a time duration for the habit",
    goal: "Goal",
    goalDescription: "Complete the habit whenever you've achieved your goal",
    goalPlaceholder: "Specify a completion goal?...",
    extras: "Extras",
    noGoalSpecified: "No goal specified",
    defaultName: "Unnamed Habit",
    allowedApps: "Allowed Apps",
    allowedAppsDescription: "Select apps you can access during this habit",
    selectApps: "Select apps",
    appsSelected: "{count} app(s) selected",
    noAppsSelected: "None selected",
    openAllowedApps: "Open Allowed Apps",
    launchApp: "Open",
  },
  common: {
    accept: "Accept",
    learnMore: "Learn more",
    doItLater: "Do it later",
    later: "Later",
    termsOfUse: "Terms and Conditions",
    privacyPolicy: "Privacy Policy",
    email: "Email",
    nickname: "Nickname",
    skip: "Skip",
    goToSleep: "Time for sleep 😴",
    areYouSure: "Are you sure?",
    loading: "Loading...",
    loadingWithoutDot: "Loading",
    pleaseWaitPatiently:
      "Please wait while we load your data. This can take a few minutes, but we're working behind the scenes to make sure everything is set up perfectly for you.",
    connectionError: "Connection error",
    morning: "morning",
    evening: "evening",
    welcome: "Welcome",
    somethingWrong: "Something went wrong",
    logout: "Logout",
    ok: "OK",
    ok_ellipsis: "OK...",
    okay: "Okay",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    next: "Next",
    cancel: "Cancel",
    delete: "Delete",
    proceed: "Proceed",
    resume: "Resume",
    retry: "Retry",
    submit: "Submit",
    resend: "Resend",
    verify: "Verify",
    edit: "Edit",
    finished: "Finished",
    done: "Done",
    sec: "sec",
    focusBear: "focus bear",
    tomorrow: "Tomorrow",
    today: "Today",
    yesterday: "Yesterday",
    add: "Add",
    start: "Start",
    startRoutine: "Start Routine",
    continue: "Continue",
    end: "End",
    startActivity: "Start {activityName}",
    startTimerActivity: "Start {time} {unit} {activityName}",
    Success: "Success!",
    SuccessfullyAddedHabit: "Successfully added habit",
    save_changes: "Save changes",
    save: "Save",
    saving: "Saving",
    saved: "Saved",
    created: "Created",
    next_time_format: "[{day} at] h:mm A",
    sure: "Sure",
    uploadScreenShots: "Upload screenshots \n(Optional)",
    session_expired: "Session Expired",
    login_again: "Please login again",
    continue_activity_name: "Continue {activityName}",
    no_thanks: "No Thanks",
    saveHabitSuccessfully: "{habitName}, to your {routineName} routine",
    couldNotProcessTheRequest: "Could not process the request, please try again",
    error: "Error",
    selected: "Selected",
    granted: "Granted",
    notGranted: "Not granted",
    all: "All",
    viewAll: "View all",
    more: "More",
    somethingElse: "Something else",
    habit: "Habit",
    empty: "Empty",
    clearAll: "Clear",
  },
  lateNoMore: {
    title: "Meeting Reminders",
    calendarIntegration: "Calendar Integration",
    calendarTooltip: "To enable meeting detection you can connect your phone's calendar or your Google calendar",
    googleCalendar: "Google Calendar",
    connected: "Connected",
    notConnected: "Not connected",
    enableReminders: "Reminder Notifications",
    calendarPermission: "Device Calendar",
    calendarPermissionAlreadyGranted:
      "Device Calendar is connected. You can revoke access at any time via your phone's settings",
    calendarPermissionDenied: "Please grant calendar access permission in your phone's settings",
    openSettings: "Open settings",
    addReminder: "Add reminder",
    durationBefore: "{duration} before",
    whenMeetingStarts: "When meeting starts",
    requireMeetingUrl: "Events with Meetings Only",
    requireMeetingUrlDescription: "Only include events that have a meeting URL attached",
    // Notification messages
    notification1: "Meeting starting soon! 🐻",
    notification2: "Get ready to head to your meeting! ⏰",
    notification3: "Your meeting is approaching! 🚀",
    notificationBody: "'{title}' starts {time}",
    now: "now",
    // Meeting Preparation UI
    yourMeetingStartsIn: "Meeting in <highlight>{countdown}</highlight>. Let's get ready!",
    yourMeetingIsOngoing: "There's an ongoing meeting. Join <highlight>now</highlight>!",
    upcomingMeeting: "Upcoming event",
    mentallyPrepare: "1. Mentally prepare for the meeting",
    howDoYouWantToShowUp: "How do you want to show up?",
    placeholderHowToShowUp: "Calm, listening, open-minded, collaborative...",
    joinOnTime: "2. Join on time",
    ignoreMeeting: "Ignore meeting",
    startMeeting: "Join meeting",
    noUpcomingMeetings: "No upcoming meetings",
    noMeetingsDescription: "We didn't find any meetings scheduled in the next few hours.",
    // Calendar source indicators
    googleCalendarSource: "Source: Google calendar",
    deviceCalendarSource: "Source: On-device calendar",
  },
  customizeBlocking: {
    customBlockedMessage: {
      title: "Custom Blocked Message",
      tooltip: "Replaces the default motivational quote shown on your block screen.",
      placeholder: "Enter your custom message...",
      hint: "Leave empty to use the default motivational quotes.",
    },
    customSoftBlocking: {
      title: "Unlock Period",
      description: "How long the app stays unlocked after taking a break in Gentle Block mode.",
      hint: "Between {min} and {max} minutes",
    },
    customPauseDelay: {
      title: "Pause Wait Time",
      description: "A small speed bump before unlocking a blocked app. Each attempt makes the next one harder.",
      hint: "Choose between {min}s and {max}s",
      sequenceLabel: "Your wait times",
    },
    saveSuccess: "Custom Blocking settings saved successfully",
    saveError: "Failed to save custom blocking settings. Please try again.",
  },
  settings: {
    healthPermission: "Health permission",
    physicalActivityPermission: "Physical Activity Permission",
    healthAndSleepPermission: "Health and Sleep Permission",
    changedBackendEndpoint: "AWS Backend Endpoint {status}",
    saveBlockedUrls: "Save Blocked URLs successfully",
    saveBlockedUrlsError: "Failed to save Blocked URLs",
    debugLog: "Enable detailed logging",
    debugLogDescription: "Only turn this on if the support team asks you to as it will slow down the app",
    title: "Settings",
    lateNoMore: "Meeting Reminders",
    addApps: "Add Apps To Blocklist",
    clearBlocklist: "Clear Blocklist",
    confirmClearBlocklist: "Confirm clear blocklist?",
    urlBlockingWarningTitle: "Important: URL Blocking Only Works in Safari",
    urlBlockingWarningMessage:
      "Website blocking only works in Safari. To prevent bypassing URL blocks, we recommend blocking Chrome, Firefox, and other third-party browsers completely in your blocklist.",
    urlBlockingHowToTitle: "How to Block Websites",
    urlBlockingHowToMessage:
      "Tap 'Add URLs to blocklist' below, then select the 'Websites' tab at the top of the picker. You can search for specific websites or browse by category. Selected websites will be blocked in Safari during your focus sessions.",
    addUrls: "Add URLs to blocklist",
    clearBlockedUrls: "Clear blocked URLs",
    confirmClearBlockedUrls: "Confirm clear blocked URLs?",
    strictness: "Strictness",
    shareLogsWithSupport: "Report problem",
    reason_required: "Please enter a reason",
    enter_a_reason: "Could you share why you want to delete your account?",
    contact_desc: "Could we contact you to provide help to fix the issues you experienced?",
    editFriction: "Friction",
    password: "Password",
    account: "Account",
    permissions: "Permissions",
    language: "Language",
    useSystemLanguage: "Use system language",
    supportedLanguages: "Supported languages",
    overlay_permission: "Overlay Permission",
    usage_permission: "Usage Permission",
    notification_permission: "Notification Permission",
    screen_time_permission: "Screen Time Permission",
    DND_permission: "Do Not Disturb Permission",
    DND: "Block Notifications",
    warning: "Warning!",
    DND_permissionWarning:
      "DND mode must be manually disabled if it's already enabled. It cannot be turned off automatically if DND permissions are not granted.",
    help: "Help",
    askForHelp: "Ask For Help",
    report_problem: "Report Problem",
    discord_server: "Discord Server",
    videoTutorials: "Video Tutorials",
    experimental: "Experimental",
    customization: "Customization",
    general: "General",
    focusGames: "Focus Games",
    allowed: "Allowed",
    notAllowed: "Not allowed",
    notGrantedYet: "Not granted",
    userid: "UserId",
    copy: "Copy",
    copied: "Copied",
    settings: "Settings",
    verifyEmail: "Verify email",
    emailVerificationResent: "Email verification resent",
    pendingVerification: "Pending verification",
    editNickname: "Edit nickname",
    nicknameError: "Invalid nickname (only letters and numbers)",
    nicknameAlreadyExists: "Nickname already exists",
    customizeBlocking: "Customize Blocking",
  },
  focus: {
    title: "Focus",
    focusLimitReachedTitle: "Focus Limit Reached",
    focusLimitReachedMessage:
      "In the free version, you can only focus for up to 25 minutes. Upgrade to premium if you want longer focus sessions.",
  },
  blockingStatusBanner: {
    additionalSchedules: " +{count} more",
    activeSchedule: "{name} ({start} – {end}) {extra}",
  },
  home: {
    setupHabitsDescription: "Setup your habits to start your day.",
    upEarlyStartMorningRoutine: "Up early? Start morning routine",
    getMotivated: "Get motivated",
    completed: "Completed",
    habitName: "Habit name",
    newHabit: "New habit...",
    duration: "Duration",
    editHabit: "Edit habit",
    addHabit: "Add habit",
    deleteThisHabit: "Delete this habit",
    deleteHabit: "Delete habit {name}",
    deleteHabitTitle: "Delete Habit",
    deleteHabitMessage: "Are you sure you want to delete '{habitName}'? This action cannot be undone.",
    afterCutoffTimeDescription: "None of your habits are available because it's past the cutoff time",
    routineNotScheduledNow: "This routine is scheduled for {routineSchedule}",
    cutOffToolTip:
      "You've configured cutoff times for your habits so that they're not accessible after {cutOffTime}.\nYou can modify this in Change timing",
    unlockToProceed: "Unlock to proceed",
    title: "Home",
    morningRitual: "Your morning ritual",
    eveningRitual: "Your evening ritual",
    time_to_earn_screen_time: `Do your morning routine habits to set yourself up for an awesome day`,
    evening_routine_text: "You'll be ready for a great night's sleep when you're done!",
    upcoming_below_new_activities:
      "Below are the habits you need to accomplish in next upcoming routine to use your mobile.",
    start: "Start",
    mins: "mins",
    secs: "secs",
    re_activate: "Resume blocking",
    force_deactivate_postpone_and_start_routine: "Routine has been postponed\n Resume routine?",
    userCompletedRoutineHeading:
      "Well done for finishing your routine. Look forward to helping you with your next routine {routineTime}",
    postOnboardingRoutineHeading:
      "Welcome onboard! Look forward to helping you with your {routineName} routine {routineTime}",
    wantLogout: "Do you want to logout?",
    noDataFound: "You haven't set up any habits yet. Tap <fix>here</fix> to add habits.",
    routineFetchingError:
      "We encountered an issue while retrieving routine data. Please try again later or reach out to us for assistance",
    hi: "Hi {nickname}!",
    welcomeDefault: "Hello!",
    goodMorningFocusTime: "Good Morning!", // unused
    goodEveningFocusTime: "Good Evening!", // unused
    allActivitiesCompleted: "No habits left to complete",
    startRoutineNow: "Do My {routineName} Routine",
    customRoutineReady: "You can start your custom routine now",
    passwordForSettingsTitles: "Enter password to proceed",
    manageAlwaysAllowedAppsDesc:
      "During your morning/evening routine and when you are focusing on your computer, all apps on your phone apart from the Always Allowed Apps will be blocked. We suggest only allowing apps like SMS, phone and apps you need for work so you don't get distracted during your habits/work.",
    manageAlwaysBlockedAppsDesc:
      "During your morning/evening routine and when you are focusing on your computer, all the apps in your block list will be blocked. We suggest blocking social media, gaming, email and news apps so you don't get distracted during your habits/work.",
    overlayPermission: "overlayPermission",
    usagePermission: "usagePermission",
    editHabits: "Edit Habits",
    editYourHabits: "Edit your habits",
    stats: "Stats",
    motivationMsg: "Get Motivated",
    play: "Play",
    pause: "Pause",
    customizeHabits: "Edit routines",
    deleteAccount: "Delete Account?",
    accountDataHasBeen: "Account data has been deleted successfully. Thanks for using Focus Bear.",
    blockSuperDistractingApps: "Block super distracting sites/apps",
    skipHabitDesc: "Skip this habit today",
    screenTimePermissionNotAllowedWarningText:
      "Screentime permission is needed to block apps, start a habit again to allow permissions",
    OverlayPermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Overlay permission not granted. Fix.",
    ScreenTimePermissionNotGrantedWarning:
      "Warning: distraction blocking not activated. Screen Time permission not granted. Fix.",
    UsagePermissionNotGrantedWarning: "Warning: distraction blocking not activated. Usage permission not granted. Fix.",
    noAllowedAppSelectedWarning:
      "Warning: you haven't configured your block list yet so distractions won't be blocked. Edit Blocklist",
    habitLimitMessage: "Free users can only access up to 3 habits per routine. Please upgrade to unlock more habits.",
    youHaveNotSetupAnyHabitsYet: "You haven't set up any habits yet.",
    guestMode: "Guest Mode",
    guestSignUpDescription: "Sign up to access your content across all your devices and unlock personalized features.",
    deleteRoutineTitle: "Delete Routine",
    deleteRoutineMessage:
      "Are you sure you want to delete this routine, and all of the habits associated with it? This is irreversible.",
    createHeading: "Create",
    completedHabits: "Completed habits",
    hiddenHabits: "Hidden habits",
    editRoutine: "Edit routine",
    changeTiming: "Change timing",
    deleteRoutine: "Delete routine",
    cutoffTimeNote:
      "Note: Your cutoff time is {time}. Habits that are not set to 'high priority' will be unavailable after this time. ",
    editCutoff: "Edit cutoff",
    unavailable: "Unavailable",
    inProgress: "In progress",
    startsAt: "Starts at {time}",
    passed: "Passed",
    completedWithCount: "{count} completed",
    unavailableWithCount: "{count} currently unavailable",
    noHabitsYetAddPrompt: "There's nothing here yet.\nAdd a habit?",
    routineIsEmpty: "Routine is empty",
    allHabitsHidden: "All habits hidden",
    habitsCount_zero: "$t(common.empty)",
    habitsCount_one: "{count} habit",
    habitsCount_other: "{count} habits",
    routineOptionsTooltip: "This menu lets you edit your routine or change its timing.",
  },
  editRoutine: {
    editTiming: "Edit timing",
    morningTime: "Morning time",
    wakeUp: "Wake up!",
    morningRoutineStartTime: "Morning routine start time",
    eveningTime: "Evening time",
    finishWork: "Finish work",
    eveningRoutineStartTime: "Evening routine start time",
    techCurfew: "Tech curfew",
    timeToSleep: "Time to sleep",
    timing: "Timing",
    anytime: "Anytime",
    scheduled: "Scheduled",
    doHabitsWhenever: "Do these habits whenever",
    doHabitsAtSpecificTime: "Do these habits at a specific time or on specific days",
    newRoutinePlaceholder: "New routine...",
    routineNamePlaceholder: "Routine name",
    customRoutineDefaultName: "Custom Routine",
    createNewRoutine: "Create new routine",
    time: "Time",
    wakeUpFinishWorkSameError: "Wake up and finish work times cannot be the same",
    cutoffOutOfRangeError: "Sleep time must be after your finish work time and before your wake up time",
    startBeforeEndError: "Start time must be before end time",
  },
  simpleHome: {
    setupBlocking: "Set up blocking",
    setupBlockingApp: "Set up distraction blocking for apps (recommended)",
    setupBlockingUrl: "Set up distraction blocking for websites (optional)",
    title: "Try out Focus Bear",
    focusSessionCheckboxTitle: "Complete your first focus session",
    microBreakCheckboxTitle: "Do a micro break habit",
    focusScreenTitle: "Try out Focus Session",
    focusSessionCheckboxDesc: "Do some deep work",
    microBreakCheckboxDesc: "De-stress with deep breathing",
    postGamePromptTitle: "Nice work!",
    postGamePromptText: "Want to start a focus session now to get that task done?",
    focusNowCta: "Yeah! Focus Time",
    focusGameTitle: "Warm up with a focus game",
    focusGameDesc: "Play a quick game to get in the zone",
  },
  postpone: {
    doYouReallyWantTo: "Do you really want to pause?",
    blockingPausedForDuration: "Blocking paused for {duration}",
    blockingPausedIndefinitely: "Blocking paused until you resume",
    pauseBlocking: "Pause Blocking",
    pauseDisabledStrictMode: "Pause blocking cannot be used when super strict mode is enabled",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Resume Blocking",
    choosePostponeTime: "How long do you want to pause?",
    indefinite: "Pause until I resume blocking",
    youHavePausedTimesToday_zero: "This is your first time pausing today.",
    youHavePausedTimesToday_one: "You have already paused once today.",
    youHavePausedTimesToday_other: "You have already paused {count} times today.",
    countdown: "We'll let you pause after {countdown}",
    areYouSureIndefinite:
      "Are you sure you want to pause indefinitely? You can if you really want to but often a seemingly urgent task can still wait 15 minutes until you finish your habits.",
    doHabits: "I'll do my habits instead",
    longTermGoalsDesc: "Just a reminder that this is what you are trying to achieve with Focus Bear:",
    lowQualityUsageDesc: "Time already spent in low quality apps today",
    write: "Leave feedback...",
  },
  passwordForSettings: {
    invalid_password: "Password is invalid",
    resetAfter24Hours: "Reset requested. Your password will be disabled after 24 hours.",
  },
  signIn: {
    logIn: "Log in",
    enterEmailHint: "Email Address",
    enterPasswordHint: "Password",
    invalidCredentials: "Invalid Username/Password",
    enterEmailError: "Please enter email",
    enterValidEmailError: "Please enter valid email",
    enterPasswordError: "Please enter password",
    dontHaveAccount: "Don't have an account?",
    forgotPassword: "Forgot Password?",
    signup: "Sign up",
    googleSignIn: "Continue with Google",
    continueWithGoogle: "Continue With Google",
    startWithApple: "Start with Apple",
    startWithEmail: "Start with email",
    backToSignInMethod: "Back to select sign in method",
    alreadyHaveAccount: "I already have a Focus Bear account",
  },
  forgotPassword: {
    forgotPasswordNotVerifiedBody:
      "You need to verify your email before you can reset your password. We can send you a new verification link now.",
    forgotPasswordNotVerifiedTitle: "Verify your email to reset your password",
    resetLinkSent: "If an account exists with this email, a password reset link has been sent.",
    verificationEmailSent: "A verification email has been sent. Please check your inbox.",
    verificationEmailFailed: "Failed to send the verification email. Please try again later.",
    forgotPasswordSuccess: "Password reset email has been sent to your email address",
    forgotPasswordErrorThirdParty:
      "If this email was used to sign up with Google or Apple, please continue by signing in with that provider.",
    cannotResetPasswordOAuthAccountTitle: "Sign in to continue",
    forgotPasswordNotVerified:
      "Your account email is not verified. Please check your inbox for a verification link or request a new one.",
    forgotPasswordEmailNotFound: "Email not found",
    forgotPasswordTitle: "Forgot Password",
    backToSignIn: "Back To Sign In",
    resetPassword: "Reset Password",
    resetFailed: "Password Reset attempt has failed. Try again later.",
    waitBeforeRetry: "Please wait before requesting another email.",
    weveEmailedYouALinkToResetYourPassword: "We've emailed you a link to reset your password.",
  },
  signUp: {
    backToSignUpMethod: "Back to select sign up method",
    verifyEmail: "Please check your inbox",
    verifyEmailMessage: "We just sent you a verification email. Please click the link to verify your account.",
    signUp: "Sign up",
    emailSignup: "Sign up with email",
    continueWithNoAccount: "Continue without an account",
    tosAndPP: "I agree to the <bold>Terms of Service</bold> and <bold1>Privacy Policy</bold1>",
    alreadyHaveAccount: "Already have an account?",
    passwordMatchError: "Password and confirm password does not match",
    acceptTerms: "Please agree to the Terms of Service and Privacy Policy to continue",
    passwordHintError: `Password Must Contain:
    • At least 8 characters
    • Numbers (0-9)
    • Lowercase letters (a-z)
    • Uppercase letters (A-Z)
    • Special characters (!@#$%^&*)`,
    invalidSignup: "Invalid sign up",
    userExists: "The user already exists.",
    terms: "Terms",
    privacy: "Privacy",
    or: "OR",
  },
  profile: {
    logout: "Logout",
  },
  routineDetail: {
    activity: "Activity",
    not_playable_video: "Not able to play video.",
    done: "I'm done",
    video: "Video",
    images: "Images",
    checklist: "Checklist",
    note: "Note",
  },
  quickBreak: {
    quickBreak: "Quick Breaks",
    quickStretch: "Stretch Exercise",
    stretch: "Stretch",
    drinkWater: "Drink Water",
    water: "Water",
    deepBreathing: "Deep Breathing",
    breathe: "Breathe",
    saveQuickBreakSuccessfully: "Your changes are saved successfully",
    editQuickBreaks: "Edit Quick Breaks",
    quickBreakName: "Quick break name",
    currentSelection: "Current selection",
  },
  complete: {
    backToHome: "Back to Home",
    logQuantity: "Log Quantity of activity",
    finishedCheck: "finished! ✅",
    habitNotCompleted: "habit skipped! ❌ You can do it tomorrow!",
    finishedAndEarnedMorning: "finished! ✅ You've earned your screen time",
    finishedAndEarnedEvening: "finished! ✅ You've earned a good night's sleep. See you tomorrow morning!",
    why_skip: "Why do you want to skip?",
    already_did: "I already did it",
    cannot_today: "Can't do it today",
    quantity_input_error: "Number needs to be between {min} and {max}.",
    freemiumLimitReached: "Sorry, you can only complete 3 habits with a free plan.",
  },
  reason: {
    canShare: "Can you share why you're pausing indefinitely?",
    shareFeedback: "Share feedback",
    everythingIsOk: "Uh oh - hope everything is ok",
    appBrokenDesc: "Really sorry about that. Would you mind telling us what happened?",
    somethingElseDesc: "Ok. Is there any feedback you want to share with us?",
    gotEmergency: "I've got an emergency",
    appBroken: "The app is broken",
    somethingElse: "Something else",
  },
  notification: {
    backgroundService: "Focus bear background service to help you focus",
    scheduleNotificationTitleForResumeRoutine: "Resume your routine",
    scheduleNotificationDescriptionForResumeRoutine: "It is time to focus on your routine",
    floatingModuleActivityCompleteNotificationtitle: "Activity Completed",
    floatingModuleRoutineCompleteNotificationtitle: "Routine Completed",
    morningRoutineCompletedNotificationDescription: "Morning routine completed. Great start to the day!",
    eveningRoutineCompletedNotificationDescription: "Evening routine completed. Sleep well!",
    customRoutineCompletedNotificationDescription: "{{routineName}} completed. Well done!",
  },
  focusMode: {
    blockingPaused: "Blocking Paused",
    blockingPermissionNeeded: "Blocking inactive: you need to grant permissions",
    noBlockingAppsSelected: "Blocking inactive: you need to choose apps to block",
    distractionBlockingNotActiveTitle: "Distraction blocking not active",
    distractionBlockingNotActiveText: "You haven't chosen apps to block yet",
    continueWithoutBlocking: "Continue without blocking",
    fixBlocking: "Fix blocking",
    confirmSuperStrictMode:
      "Are you sure you want to enable Super Strict Mode? You won't be able to exit until the session ends.",
    focusIntentionTooltip:
      "Set a goal for what you'll achieve in this focus session. Being clear on what you'll achieve helps you avoid getting distracted.",
    focusTitle: "Start a focus session",
    superStrictToolTip:
      "Committed to this focus session? Enable super strict mode and you won't be able to turn focusing off or pause app blocking until the timer is up.",
    superStrictMode: "Super strict mode",
    brainDump: "Brain dump",
    brainDumpToolTip: "Jot down your thoughts here",
    postFocusCongrats_0: "Nice work! You crushed it!",
    postFocusCongrats_1: "Hey, great job finishing that! What's up next?",
    postFocusCongrats_2: "You did it! Feel free to take a breather now.",
    postFocusCongrats_3: "Well done! You're really getting things done!",
    postFocusCongrats_4: "Awesome job! What's the next thing on your radar?",
    postFocusCongrats_5: "You made it through! Time to tackle the next one?",
    postFocusCongrats_6: "Great focus! Go grab a drink or a snack!",
    postFocusCongrats_7: "Nice! You're making serious progress!",
    postFocusCongrats_8: "Well done! Time to stretch your legs a bit?",
    postFocusCongrats_9: "You did great! Let's keep that momentum going!",
    startFocusSession: "Start a focus session",
    noIntentionWasFound: "No intention entered",
    distractionAlertTitle: "Focus Mode",
    userIntention: "Focus Goal",
    noDistractingThoughtsWasFound: "No distracting thoughts entered",
    userIntentionTextInputPlaceholder: "What do you want to work on?",
    startFocusing: "Start Focusing",
    hoursWithValue: "{value}h",
    minutesWithValue: "{value}m",
    secondsWithValue: "{value}s",
    duration: {
      hours: "{hours} hours",
      minutes: "{minutes} minutes",
      seconds: "{seconds} seconds",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "You got this!\nDeep work time",
    endSession: "End Session",
    completeFocus: "Complete Focus",
    userDumpThoughTextInputDescription: "Write down any distracting thoughts here",
    exitFocusMode: "End focus session early",
    exitFocusModeDescription: "Can you share why you're ending this session?",
    reason: "Reason",
    selectReason: "Select a reason",
    congratulations: "Congratulations!",
    focusDoneTitle: "YOU DID IT!",
    focusDoneDescription: "You remained focused for",
    focusDoneDescription1: "What was your intention?",
    focusDoneDescription4: "What was your distracting thoughts?",
    focusDoneDescription2: "What did you achieve during this time?",
    focusDonePlaceholderDescription2: "Enter what you achieved with our help",
    focusDoneDescription3: "Did you have any distractions?",
    focusDonePlaceholderDescription3: "Enter any distractions you had",
    endEarlyReasonDescription1: "I have an emergency",
    endEarlyReasonDescription2: "Focus mode is not working properly",
    endEarlyReasonDescription3: "I have achieved what I wanted to",
    endEarlyReasonDescription4: "I need a break",
    runningFocusModeDesc: "A focus session is running",
    extendFocusDuration: "Extend Focus Duration",
    shortenFocusDuration: "Shorten Focus Duration",
    selectExtendFocusDuration: "How much longer do you want to focus for?",
    selectShortenFocusDuration: "How much time do you want to shorten?",
    extendFocus: "Extend",
    shortenFocus: "Shorten",
    adjustFocusDuration: "Adjust Focus Duration",
    chooseAdjustmentOption: "Would you like to extend or shorten your focus session?",
    editFocusDuration: "When do you want to finish focusing?",
    focusMusic: "Focus music",
    focusMusicError: "Sorry, couldn't play focus music",
    focusNotes: "Focus notes",
  },
  toDos: {
    toDos: "Todos",
    todoList: "Todo List",
    notes: "Notes",
    drafts: "AI Generated",
    notStarted: "To do",
    inProgress: "Doing",
    completed: "Done",
    current: "Current",
    noMoreTasks: "No more tasks",
    noTasksToShow: "No tasks to show\nAdd some below to get started!",
    searchTasks: "Search tasks",
    noTasksFound: "No tasks found",
    addATask: "Add a task",
    taskAdded: "Task added",
    failedToAddTask: "Failed to add task",
    scanPaperWithOCR: "Scan paper with OCR",
    quickActions: {
      audio: "Audio",
      uploadAudio: "Upload audio",
      recordAudio: "Record audio",
      upgradeRequired: "Upgrade Required",
      upgradeMessage:
        "Audio and OCR features are available with Focus Bear Pro. Upgrade to unlock these powerful productivity tools.",
      ocrUpgradeMessage:
        "OCR scanning is available with Focus Bear Pro. Upgrade to extract tasks from photos and documents.",
    },
    ocr: {
      modalTitle: "Scan Paper with OCR",
      reviewModalTitle: "Review Extracted Todos",
      title: "Scan Your Todo List",
      description:
        "This feature can extract tasks from photos of handwritten or printed todo lists. You can select an image from your photo library or take a new photo.",
      reviewTitle: "Review Extracted Todos",
      reviewDescription: "Select the todos you want to add to your list. You can edit them later.",
      selectSource: "Select Photo Source",
      selectSourceDesc: "Select an option to choose an image",
      takePhoto: "Camera",
      chooseFromGallery: "Photo Library",
      capturePhoto: "Continue",
      processing: "Processing image...",
      uploading: "Uploading Image",
      error: "OCR Error",
      processingError: "Failed to process the image. Please try again.",
      noTodosSelected: "No Todos Selected",
      selectAtLeastOne: "Please select at least one todo to add.",
      createTodos: "Create Selected Todos",
      completed: "OCR Processing Complete",
      completedDesc: "Your todos have been extracted successfully!",
    },
    audio: {
      processing: "Processing audio...",
      completed: "Audio Processing Complete",
      completedDesc: "Your todos have been extracted successfully!",
      addByAudio: "Add by audio",
      record: "Record",
      upload: "Upload",
      recorded: "Recording complete",
      sendOrDiscard: "Tap to send or dismiss to discard",
    },
    due: "Due",
    dueDate: "Due Date",
    exactDate: "Choose date",
    TOP: "TOP - Task Priority Score",
    TOPPrioritization: "TOP Prioritization",
    timeline: "Timeline (due date)",
    project: "Project",
    projects: "Projects",
    scoreCalculation: "Score",
    addProjects: "Add projects",
    noExistingProjects: "No existing projects",
    createNewProject: "Create new project",
    searchOrCreateProject: "Search or create project",
    noMatchingProjects: 'No matching projects. Press enter to create "{search}"',
    addATitle: "Add a title",
    addDescription: "Add a description...",
    addASubtask: "Add a subtask",
    reschedule: "Reschedule",
    rescheduleTitle: "Reschedule task ",
    taskMovedToast: 'Task moved to "{status}"',
    sortBy: "Sort by",
    filterBy: "Filter",
    filterTasksBy: "Filter your tasks by",
    listOptions: "List options",
    lowToHigh: "Low to high TOP score",
    highToLow: "High to low TOP score",
    groupBy: "Group by",
    groupedTogether: 'Show tasks that are "to do" and "doing" in the same group',
    filterByPerspiration: "Filter by perspiration",
    spoonsDesc: "Choose tasks based on your energy level (spoon theory). More spoons = more energy.",
    learnAboutSpoonTheory: "Learn about spoon theory",
    lowSpoons: "Low spoons",
    fullSpoons: "Full spoons",
    perspirationLevel: "Perspiration level",
    filterByProject: "Filter by project",
    noFilter: "No filter",
    filterByDueDate: "Filter by due date",
    toDosDueDate: "Due Date",
    overdue: "Overdue",
    thisWeek: "This week",
    nextWeek: "Next week",
    deleteTask: "Delete Task",
    deleteTaskDesc: "Are you sure you want to delete this task?",
    deleteSubtask: "Delete Subtask",
    deleteSubtaskDesc: "Are you sure you want to delete this subtask?",
    dueIn: {
      aFewDays: "In Two Days",
      nextWeek: "In a Week",
      twoWeeks: "In Two Weeks",
      aMonth: "In a Month",
      aYear: "In a Year",
      aYearDescription: "(hah, I'll never actually do this)",
    },
    outcome: {
      outcome: "Outcome",
      whoCares: "Who cares",
      kindOfImportant: "Kind of important",
      bigDeal: "Big deal",
      huge: "Huge",
      mindBlowing: "Mind blowing",
    },
    perspiration: {
      perspiration: "Perspiration",
      fiveMinuteJob: "5 minute job",
      fifteenMinutesWork: "15 minutes work",
      halfAnHour: "Half an hour",
      anHour: "An hour",
      halfADay: "Half a day",
      aDay: "A day",
      aWeek: "A week",
    },
  },
  overview: {
    morningRoutine: "Morning Routine",
    eveningRoutine: "Evening Routine",
    noTasksCta: "No tasks yet. <bold>Add a task</bold> to get started.",
    noHabitsCta: "No habits yet. <bold>Add a habit</bold> to get started.",
    topTasksToday: "Top Tasks",
    focusModeTitle: "Focus Mode",
    newFocusSession: "New Session",
    focusActive: "Active Session",
    focusInactive: "No Active Session",
    routineCompletedShort: "✓ Completed",
    routineCompletedMessage: "All habits completed! Great job! 🎉",
    routineProgress: "{completed} of {total}",
    deadlinePrefix: "Deadline: {date}",
  },
  networkError: {
    ifTheProblemPersists: "If the problem persists, please contact support directly at\nsupport@focusbear.io",
    noNetworkAlertTitle: "Internet disconnected",
    retrying: "Trying that again",

    connectionError: "Unstable internet connection",
    connectionErrorMessage: "Please check your connection",
    connectionErrorLongMessage:
      "We're having trouple connecting to the server. $t(networkError.connectionErrorMessage). $t(networkError.ifTheProblemPersists)",

    apiError: "Something went wrong",
    apiErrorMessage: "Please try again later",
    apiErrorLongMessage:
      "There was an issue processing your request. $t(networkError.apiErrorMessage). $t(networkError.ifTheProblemPersists)",

    internalError: "Internal error",
    internalErrorMessage: "Something went wrong :(",
    internalErrorLongMessage: "Sorry, something went very wrong. $t(networkError.ifTheProblemPersists)",
  },
  manageAllowedApps: {
    searchPlaceholder: "Search installed apps",
  },
  addNoteModule: {
    addNote: "Add Note",
    placeholder: "Add Note Here...",
    saveNote: "Save Note",
    automaticallySave: "Your note will be saved automatically",
  },
  permissionWarning: {
    usageAccessTitle: "We need Usage Access permission to help block distractions",
    deviceUsagedescription:
      'To allow us to block distracting apps when you\'re focusing/doing your habits, we need "usage access" permissions so we can see which app you are using',
    overlayTitle: "We need Overlay permission to help block distractions",
    overlayDescription:
      'To allow us to block distracting apps when you\'re focusing/doing your habits, we need "Overlay" permissions so we can see which app you are using and show distraction alert for not allowed apps',
    privacyNoteTitle: "Privacy note",
    privacyNoteDesc: "We don't log which apps or websites you use. we just use it for blocking in real time.",
    grantAccess: "Allow",
  },
  onboarding: {
    nextStep: {
      upNext: "Up next: {step}",
      usagePermission: "Usage permission",
      overlayPermission: "Overlay permission",
      focusSession: "Focus session",
      microBreak: "Micro break",
      allDone: "All done",
      screenTimePermission: "Screen time permission",
    },
    wantToPersonalise: "Want to personalize?",
    wantToPersonaliseDescription: "Set up your own habits instead of using the defaults.",
    personalise: "Personalize (5 minutes)",
    onboarding: "Onboarding",
    letsDoIt: "Let's do it",
    replay: "Replay",
    instructionVideo: "Instruction Video",
    welcomeAboard: "Welcome aboard!",
    lookingForwardToHelp: "Time to activate healthy habits and deep work.",
    getStarted: "Get Started",
    allDone: "All Done!",
    habitPackSelectionNotice:
      "Next let's choose some habits for your morning and evening routine.\n\n\n<bold>Don't stress</bold> You can always tweak them later.",
    installDesktopApp: "Install the desktop app",
    installDesktopAppDesc:
      "Focus Bear works on Mac and Windows too. If you've got a computer, download the app from <bold>focusbear.io</bold> to sync your focus sessions and habits.",
    cutoffTimeWarning: "Get off tech time should be after the finish work time ({time}).",
    howFocusBearWork: "How Focus Bear works",
    habitAndRoutine: "Habits and Routines",
    habitAndRoutineDescription: "<bold>Achieve your goals</bold> with habits that rev up your brain and body",
    distractionBlocking: "Block Distractions",
    distractionBlockingDescription:
      "Focus Bear can block <bold>apps</bold> and <bold>websites</bold> to help you get things done",
    todoList: "Todo List",
    todoListDescription:
      "<bold>Plan</bold>, <bold>prioritize</bold> and <bold>stay on track</bold> with the Focus Bear Todo list",
    andMuchMore: "And that's not all",
    andMuchMorePoints: [
      "Works on your computer too",
      "Pomodoro technique",
      "Advanced habits with checklists and videos",
      "Morning and evening routines",
      "Break reminders",
      "Fun bear emojis",
    ],
    andMuchMoreDescription: "<bold>and much more...</bold>",
    end: "END",
    habitAI: "Organize your\ntasks using AI",
    habitAIDescription: "Focus Bear can help you <bold> organize your tasks</bold> using Artificial Intelligence",
    learnAboutFeatures: "Learn about features",
    setupHabitsTitle: "Setup habits to focus better",
    setupHabitsCta: "Setup habits",
    habitsPirateCopy: "Good habits keep your focus sharp all day.",
    habitImportPirateCopy: "I'll use me sea magic to bring your habits aboard.",
    habits: {
      sleep: "Sleep",
      meditate: "Meditate",
      exercise: "Exercise",
    },
    habitList: {
      nayLabel: "Nay - Give me some ideas Cap’n",
      ayeLabel: "Aye - I already have some habits",
    },
  },
  goals: {
    habitImport: {
      title: "Import Habits",
      description: "Import your habits from an image or by recording your voice",
      importFromImage: "Import from Image",
      recordVoice: "Record Voice",
      stopRecording: "Stop Recording",
      selectSource: "Select Source",
      selectImageSource: "Choose how to import your habits",
      takePhoto: "Take Photo",
      chooseFromGallery: "Choose from Gallery",
      completed: "Habits imported!",
      completedDesc: "Your habits have been successfully imported",
      error: "Import Error",
      processingError: "Failed to process your import. Please try again.",
      recordingError: "Failed to record audio. Please try again.",
      processing: "Processing your import...",
      cancelRecording: "Cancel Recording",
    },
    addHabitList: {
      title: "Add your habit list",
      description: "Upload the habit list or tell us your goals and our AI will add them in Focus Bear app.",
      uploadScreenshot: "Upload a photo",
      recordVoiceNote: "Record a voice note",
      typeThemIn: "Type them in",
      or: "OR",
      haveHabitListQuestion: "Do you have your own habit list to import?",
      importHabits: "Import habits",
      confirmScreenshotUpload: "Confirm Image",
      confirmScreenshotUploadDesc: "Is this the image you want to upload?",
    },
    boostProductivity: "🚀 Boost productivity",
    boostProductivityDescription: "(work, study, tasks)",
    improveMentalHealth: "🧘 Improve mental well-being",
    improveMentalHealthDescription: "(stress, sleep)",
    improvePhysicalHealth: "🏋️‍♂️ Focus on health & fitness",
    improvePhysicalHealthDescription: "(exercise, nutrition)",
    manageTask: "🏡 Manage home tasks",
    manageTaskDescription: "(cleaning, chores)",
    otherSpecify: "✏️ Other",
    otherSpecifyDescription: "(please specify: __)",
    strengthenRelationShip: "❤️ Strengthen relationships",
    strengthenRelationShipDescription: "(family, friends)",
    achievement_placeholder: "Tell us your goal",
    enableFeatures: "Which features would you like to enable?",
    doOurBest: "We're here to help you reach your goals. Which Focus Bear features would you like to turn on?",
    achievementWithFocusBearDesc: "What are your main goals?",
    achievementWithFocusBearDescTooltip: "We'll suggest habits that will help you achieve your goals",
    help_me_develop: "Build healthy habits",
    help_me_stay: "Stay focused at work",
    help_me_develop_tooltip:
      "Focus Bear can guide you through healthy habits (meditation, exercise, journaling etc) in your morning and evening routine.",
    help_me_stay_focused_tooltip:
      "Focus Bear will block distractions while you're working so you can get deep work done.",
    blockComputerTitle: "Block distractions on your computer?",
    blockComputerQuestion: "Do you want to block distractions on your computer too?",
    organize_tasks_using_ai: "Organize your tasks using AI",
    organize_tasks_using_ai_tooltip: "Focus Bear can organize your tasks using AI",
    what_are_you_hoping_focus_bear_can_do: "What are you hoping Focus Bear can do?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Tell us what you're hoping Focus Bear can do",
    explore_the_app_first: "Explore the app first",
    setup_habits: "Set up habits",
    setup_habits_question: "Do you want to set up your habits now (takes ~3 minutes) or explore the app first?",
    featureRequestReceived: "Thanks for the feedback! Your ideas help us make Focus Bear better.",
  },
  goalsSteps: {
    goals: "Goals",
    routine: "Routine",
    timing: "Timing",
  },
  habit: {
    habitPack: "Choose your habits",
    autostart: "Autostart",
    habitAutoStart: "Starting in {countdown}",
    habitSkipForToday: "Habit skipped for today",
  },
  setupTime: {
    fineIfLaterOrSooner: "It's fine if you wake up a bit later or earlier than this - just put in a rough time",
    morningRitualStart: "Your morning ritual will start then",
    setStartupTime: "Choose Your Start Time",
    chooseTheAbsoluteEarliest: "What time do you wake up?",
    setShutdownTime: "When do you finish working/studying?",
    setSleepTime: "What time do you want to go to sleep?",
    focusBearWillTakeOver: "Focus Bear will pause blocking\nso you can unwind!",
    subDescriptionFocusBearWillTakeOver: "Evening routine starts at {sleep_time}\n(includes a 30 minutes buffer)",
    focusBearWillTakeOverToolTip:
      "On the next screen, you'll choose when you want to go to sleep. Focus Bear will cut off distractions again before you go to bed so you can sleep well.",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}: Free time",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}: Evening ritual and then sleep",
    subDescriptionTooltipText: "{sleep_time} - {startup_time}: Phone curfew (sleep time)",
    distractionBlockDesc: "Distractions blocked - wind down for bed",
    // Simplified schedule
    techCurfewQuestion: "Do you want to have a tech curfew at night so you can sleep better?",
    techCurfewTooltip: "Focus Bear can block distracting apps on your phone in the evening so you sleep better",
    bedtimeForScreens: "Bedtime for screens?",
    bedtimeForScreensSubtitle: "Shall we put your phone to bed early so you can rest?",
    noThanks: "No thanks",
    yesPhoneWrecksSleep: "Yes - my phone wrecks my sleep!",
    whatTimeGetOffTech: "What time do you want to get off tech in the evening?",
  },
  blockList: {
    title: "Make your phone safe during habits/focus sessions",
    subTitleAndroidBlockList: "Choose distracting apps to block while you're doing habits or focusing",
    buttonAndroidBlockList: "Choose distractions",
    subTitleIos: "Choose distracting apps to block while you're doing habits or focusing",
    buttonIos: "Choose distractions",
  },
  editFriction: {
    frictionTooltipDescription:
      'You\'re a very disciplined person of course but occasionally you might be tempted to skip your habits or stop blocking distractions on a whim. You can set up extra "friction" to help slow down those impulsive thoughts. If you enable high friction mode, it will ask you to wait a few seconds before you stop blocking distractions.',
    frictionForSkippingHabits: "Friction for skipping habits",
    reallyEasy: "Really easy - I want to be able to skip habits/breaks in a hurry",
    makeItHardToSkip: "Make it hard to skip - otherwise I'll end up skipping habits + breaks most of the time",
    appBlocking: "Block distractions",
    blockDuringDaytime: "Block distracting apps during the work day",
    reallyEasyDescription: "You'll be able to immediately stop blocking distractions",
    makeItHardToSkipDescription:
      "To avoid impulsively turning off blocks, Focus Bear can show a short countdown timer to encourage you to reconsider whether you should be accessing distracting apps.",
  },
  strictness: {
    setPassword: "Set a password",
    setPasswordDescription:
      "If you're struggling to stick to your habits, get a housemate/partner to set a password. You won't be able to skip habits without the password.",
    enterConfirmPasswordHint: "Confirm Password",
    askForPassword: "Ask for password",
    whenRequirePasswordDescription: "When do you want to require a password",
    changingSettings: "Changing settings",
    postponingMorningRoutine: "Postponing/Skipping morning routine",
    postponingEveningRoutine: "Postponing/Skipping evening routine",
    postponingAfterCuttOffTime: "Postponing/Skipping evening routine after cutoff time",
    usingPhoneLateNight: "Using your phone late at night",
    relaxFocusMode: "Allow using relax focus mode",
    suggestion: "Suggestion",
  },
  subscription: {
    upgrade: "Upgrade",
    restorePurchases: "Restore Purchases",
    restorePurchasesError: "The receipt is missing",
    restorePurchasesError2: "Something went wrong. Please try again later.",
    personalizedHabit: "Personalized habit routines",
    productivityBoosting: "Productivity-boosting breaks",
    customizedFocus: "Customizable focus modes",
    automaticGoals: "Automatic goals tracking",
    cancel: "Cancel auto-renewal",
    subscription: "Subscription",
    trialActive:
      "Your trial lasts for {day} more day(s). Do not worry, you will not be charged when the trial ends and no credit card required upfront",
    trialActiveShort: "Trial: {day} days remaining",
    getSubscriptionPlan: "Get our subscription plan to use the app and unlock all features",
    subscriptionPlanPrice: "Continue for only <bold>{amount}</bold>/month",
    benefit: "Monthly plan includes",
    doesSubscriptionAutoRenew: "Does my subscription auto renew?",
    subscriptionAutoRenew:
      "This monthly plan automatically renews unless auto-renew is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period at the subscription price ({amount}). You can manage or cancel your subscription at any time through your account settings in the Store.",
    thankYouForSubscribing:
      "Thank you for subscribing, you can now use all features of Focus Bear\n\nYour subscription will expire in <bold>{day}</bold> days",
    thankYouForSubscribingGuestMode:
      "Thank you for subscribing! To continue using all the features of Focus Bear subscription sign in and restore your subscription on this screen.",
    thanksForSubscribingShort: "Thanks for your support 🎉",
  },
  editHabit: {
    okay: "Okay",
    error: "Error",
    unableToSaveSettings:
      "Something went wrong. Very sorry. Our engineering team has been notified and we'll fix it ASAP. If you don't hear from us within 24hrs, please email support@focusbear.io and we'll get things fixed for you.",
    goingBack:
      "You are about to go back to the Settings menu. If you have made any changes, please tap the 'Save Habits' button.",
    continue: "Continue",
    cancel: "Cancel",
    warning: "Warning",
    restartingIn: "Restarting Focus Bear in {seconds}...",
    settingsSavedSuccessfully: "Habits saved",
  },
  shareLogs: {
    pleaseWriteFeedback: "Please write feedback message",
    enterFeedBack: "Enter your feedback",
    logsShared: "Thank you! Your feedback report has been shared with the support team.",
    submitAnother: "Submit another",
    errorUploading:
      "There was an error uploading the logs. Ensure you have a stable internet connection and try again. $t(networkError.ifTheProblemPersists)",
    errorZipCreation:
      "There was a problem processing the files. Please try again. $t(networkError.ifTheProblemPersists)",
  },
  impact_reporting: {
    title: "Analyse Your Sleep and Mood",
    description:
      "Would you like to track your sleep and mood to see if Focus Bear is making a positive difference to your life? This would help us too by giving us (anonymous) data about the impact of our app.",
    subtitle: "Data we'll collect",
    bulletPoints: "● Hours of sleep\n● Your mood and energy level\n● How productive you felt at the end of the day",
    okSure: "Ok sure",
    noThanks: "No thanks",
  },
  privacyModal: {
    heading: "Privacy and Security",
    notShareData: "We take your privacy and security very seriously. We will never share your data ever.",
    doNotLog: "• We don't log which websites or apps you visit.",
    chooseToBlock:
      "• However, If you want to block distracting apps, we need to store the names of those apps in our database so that your settings will sync across all your devices.",
    dataEncrypted: "• Your data is encrypted and we don't let anyone else see it.",
    moreDetails:
      "For more details, refer to our <bold>privacy policy</bold> or feel free to email <email>support@focusbear.io</email>",
    accept: "Accept",
  },
  pushNotiPermission: {
    title: "Allow notifications",
    description: "We can remind you to stay on track with your habits and show up on time for meetings.",
  },
  distractionBlockingReason: {
    notLoggedIn: "Blocking disabled: You're not logged in",
    postponeActivated: "Blocking disabled: Postpone activated",
    focusModeActivated: "Blocking enabled: Focus mode activated",
    firstDay: "Blocking disabled: First day - routine not activated yet",
    otherReason: "Blocking enabled: It's time to do your routine",
    daytimeBlockingEnabled: "Blocking enabled: morning routine is complete but daytime blocking enabled",
    blockedBySchedule: "Blocking enabled: Blocking Schedules are active",
    defaultCase: "Blocking disabled: Distraction blocking is disabled",
    withinCutoffTimeAndShutdownTime: "Blocking disabled: you've got free time until {cutoff_time}",
    permissionNotGranted: "Blocking disabled: Permissions not granted (tap here to fix)",
    afterCutoffTime: "Blocking enabled: It's time to wind down before you sleep",
    afterCutoffTimeAndEveningRoutineFinished: "Blocking enabled: It's time to sleep",
    detailedCutOffSleepTimeBlockingReason:
      "Distractions are blocked from {cutoff_time} so you can sleep. Your morning routine is set to start at {startup_time}. After you finish your morning routine, blocking stops.",
  },
  blocking: {
    blockingType: "Blocking Type",
    allowList: "Allow List",
    blockList: "Block List",
    allowListDescription:
      "Choose apps that are allowed while you're doing your habits or focusing. Everything else will be blocked.",
    blockListDescription:
      "Choose the distracting apps that should be blocked while you're doing your habits or focusing. Everything else will be allowed.",
    appBlockList: "Apps Blocklist",
    appAllowList: "Apps Allowlist",
    blockAtLeastOne: "Please select at least one app to stop yourself being distracted",
    socialFilterTitle: "Social",
    newsFilterTitle: "News",
    gamesFilterTitle: "Games",
    miscFilterTitle: "Misc",
    recommendedSectionListTitle: "Recommended apps to block",
    otherSectionListTitle: "Other Apps",
    freeAppLimitTitle: "Sorry max 5 blocked apps in free edition",
    freeAppLimitDesc:
      "In the free version, you can only choose 5 apps to block. Paying for Focus Bear pro helps to support our development so we can build new features that improve your productivity 🙂",
    Success: "Settings Saved",
    saveSuccess: "App preferences saved successfully",
  },
  permissionExplanation: {
    distractionGetBlockedWhen: "Distractions get blocked when:",
    title: "Set up permissions for distraction blocking",
    description: "Focus Bear can block distractions while you work, sleep and do your habits",
    workTask: "• you're working/studying so you get s#*% done ⚒️",
    routineTask: "• you're doing your morning and evening routine so you do your habits 🧘",
    sleepTask: "• you're sleeping so you actually sleep 😴",
    toggleOption: "By default, you can turn off distraction blocking at any time.",
    friendOption: "(But you can also choose to have a friend set a password to make it harder)",
    necessaryPermission:
      "Usage permission: To detect if you open a distracting app\n\nOverlay permission: This is what does the distraction blocking",
  },
  blockingPermissionIntro: {
    holdOnTitle: "Hold on a minute!",
    captainBearMessage: "Arr... if you want to focus better, you've got to get your habits shipshape first.",
    introTitle: "Let’s setup distraction blocking so that I can be your accountability buddy 🐻",
    introPrimary: "Let’s set it up",
    introBubble: "Here is what it\nwill look like!",
    howItWorksTitle: "During scheduled focus time, I’ll gently block the apps that pull you off track.",
    howItWorksBody: "You stay in control—pause or adjust any time.",
    howItWorksPrimary: "Sounds good",
    howItWorksBubble: "You will need to tap 'Continue'.",
    screenTimeCongratsTitle: "Well done, sorting that with your bear hands!",
    whatYouNeedTitle: "Awesome. Set up an automatic blocking schedule so I can nudge you at certain times ⏰.",
    whatYouNeedPrimary: "Continue",
    whatYouNeedBubble: "For example, block distracting apps while you’re sleeping.",
    scheduleCreatedTitle: "Perfect. You are now a creature of routine",
    scheduleCreatedPrimary: "Proceed",
    scheduleCreatedBubble: "You can edit this later in the app!",
    finishTitle: "Fantastic, you’re all set over here so we can stay on track together ✨",
    finishPrimary: "Finish",
    androidIntroTitle: "Let’s setup distraction blocking so that I can be your accountability buddy 🐻",
    androidUsageTitle: "First I need to see which apps you are using. You’ll need to enable ‘Usage Access’",
    androidUsagePrimary: "Open Settings",
    androidUsageBubble: "Try finding this toggle here",
    androidOverlayTitle: "I use ‘Overlay’ permissions so I can show up with a pop-up like this one 💭",
    androidOverlayPrimary: "Let’s set it up",
    androidOverlayBubble: "Requesting permission to nudge!",
    androidPermissionVisualTitle: "The permission looks like this.",
    androidPermissionVisualPrimary: "Enable Access",
    androidPermissionVisualBubble: "Let’s go find\nit?",
    androidProceedPrimary: "Proceed",
    androidScheduleSetupTitle: "Awesome. Set up an automatic blocking schedule so I can nudge you at certain times ⏰",
    androidScheduleSetupPrimary: "Let’s set it up",
    androidScheduleSetupBubble: "For example, block distracting apps while you’re sleeping.",
  },
  grantPermission: {
    title: "We'll need permission to block apps",
    description: "Don't worry you can pause distraction blocking at any time",
    needHelp: "Need help?",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Keep blocking enabled",
    description: "Allow Focus Bear to keep blocking apps in the background by removing battery optimization.",
    warning: "This will use slightly more battery (but not very much).",
    keepFocusBearPoweredUp: "Keep Focus Bear powered up",
  },
  launcher: {
    title: "Apps",
    morning: "🔆 Morning",
    evening: "🌙 Evening",
    play: "🥳 Play",
    work: "🔨 Work",
    setAppLabel: "Choose a category for {appName}",
    search: "Search apps",
    noAppsFound: "No apps found",
    setAsDefaultLauncher: "Default Launcher",
    restricted: "Restricted",
    restrictedMessage: "{appName} is being restricted, please focus on your routine",
    stopBlocking: "Pause blocking",
    openAppMenuToolTip: "Tap here to open the app menu",
  },
  DND: {
    duringFocusSessions: "During Focus Sessions",
    duringHabits: "During Habits & Sleep",
  },
  bearsona: {
    explanation: "What type of bear do you want to have motivating you? Focus Bear will change its tone accordingly",
    title: "Bearsona",
    choose: "Choose a Bearsona",
    useCustomLanguage: "Use {customLanguage}",
    useCustomLanguageConfirmation: "Use {customLanguage} as your language?",
    useCustomLanguageConfirmationDesc: "Warning: this is fun but can be slightly confusing",
    confirmUseCustomLanguage: "Speak english to me",
    cancelUseCustomLanguage: "I changed my mind",
    name: {
      default: "OG Bear",
      pirate: "Captain Bear",
      focus: "Focus Bear",
      jester: "Jester Bear",
      sassy: "Sassy Bear",
      cheerleader: "Cheerleader Bear",
    },
    description: {
      default: "Your friendly bear assistant",
      pirate: "Yarrr! Captain Bear at your service",
      focus: "Focusing is my superpower",
      jester: "Jester Bear is ready to play",
      sassy: "Sassy Bear is here to slay",
      cheerleader: "Cheerleader Bear is rooting for you!",
    },
  },
  blockUrl: {
    addSomeSuggestedUrls:
      "We've added some suggested websites here that most people find distracting. Delete them if you need to",
    unblockableUrlTitle: "Cannot Block URL",
    unblockableUrlMessage: "This URL is not blockable. Please enter a different URL to block.",
    freemiumLimit: "You can only block 3 URLs in the free version.",
    freemiumLimitDescription: "Upgrade to the Pro version to block unlimited URLs.",
    title: "Block Websites",
    description: "Which sites do you waste time on?",
    inputPlaceholder: "Enter URL to block...",
    urlExistsTitle: "URL already exists",
    urlExistsMessage: "Please enter a different URL to block.",
    invalidUrlTitle: "Invalid URL",
    invalidUrlMessage: "Please enter a valid URL to block.",
    saveSuccess: "Blocked URLs saved successfully.",
    saveError: "Failed to save blocked URLs. Please try again.",
  },
  accessibility: {
    title: "Accessibility Permission",
    howToEnableAccessibility: "How to enable accessibility permission",
    enableAccessibility: "Enable accessibility",
    permissionRequired: "Accessibility Permission Required",
    permissionDescription:
      "Websites can be just as distracting as apps. Focus Bear can block websites too if you enable accessibility permission. Your phone will show a warning - that's normal!",
    whatWeDo: "Here's what we do:",
    checkSites: "Check your block list",
    checkSitesDescription: "We check whether the website is on the block list you set.",
    zeroDataTracked: "That's it. Zero tracking, zero data stored.",
  },
  passwordRules: {
    passwordRequirements: "Password must contain at least one number, one uppercase letter, and one special character",
    minLength: "Min. 8 characters",
    includeNumbers: "Include numbers",
    includeLowerCase: "Include lowercase",
    includeUpperCase: "Include uppercase",
    includeSpecialChars: "Include special chars",
  },
  permissions: {
    privacyFirst: "We take your privacy very seriously",
    notTracked: "Focus Bear does <bold>NOT</bold> track:",
    anythingType: "Anything you type",
    anythingTypeDescription: "Passwords, messages, emails",
    browserHistory: "Your browsing history",
    browserHistoryDescription: "We never see or store the websites you visit",
    helpStayFocused: "We are here to help you stay focused!",
    revokeHealthPermission: "Revoke Health Permission",
    revokeHealthPermissionDescription:
      "Sorry due to Apple limitations, we can't revoke health permission. If you want to revoke it, please go to the `Health` app and revoke it from there.",
    healthGroup: "Health & Sleep",
    healthGroupDescription:
      "Focus Bear can track your health and sleep data to help you improve your health and sleep. This data is used to help you improve your health and sleep.",
    areYouSure: "Are you sure you want to revoke this permission?",
    revokePermissionDescription: "This will revoke the permission to the app.",
    experimentalGroup: "Experimental",
    experimentalDescription:
      "Set up Focus Bear to be your default home/launcher app so you see your habits straight away when you open your phone. It also makes distracting apps less obvious.",
    blockingAppsGroup: "For blocking apps",
    routineUpdatesGroup: "For routine updates",
    routineUpdatesGroupDescription:
      "Focus Bear will send you notifications when it's time for your morning or evening routine",
    urlBlockingGroup: "For blocking URLs",
    urlBlockingGroupDescription:
      "If you want to block websites, Focus Bear needs accessibility permissions to detect when you visit a distracting site and redirect you away from it.",
  },
  breathingExercise: {
    title: "Breathing Exercise",
    description: "Quick mindfulness exercise before you open this distracting app.",
    dontWantToOpen: "Don't want to open {appName}",
    wantToOpen: "Continue to {appName}",
    motivational: "Oops! Are you sure you want to open {appName}?",
  },
  byPassTimePicker: {
    title: "Pause blocking to open {app}",
    duration: "{count} minutes",
    intention: "What do you want to achieve in {app}?",
    intentionInfo: "Easy to lose track when opening a distracting app. I'll remind you of your goal.",
    intentionRequiredError: "Please enter your intention before continuing.",
  },
  loading: {
    loading: "Loading",
    breathingExercise:
      "While you wait, try a box breathing exercise. Breathe in for 3 seconds, hold for 3, breathe out for 3, hold for 3.",
    loadingHabit: "Loading habit library",
    pleaseWaitLoadHabit:
      "We'll recommend habits based on what matters to you. Based on your goals, we'll suggest helpful habits from our curated library to get you started.",
  },
  stats: {
    title: "Stats",
    tabs: {
      screentime: "Screentime",
      otherStats: "Other stats",
    },
  },
  appUsage: {
    noAppsDetected: "No apps detected",
    seeMore: "See more",
    close: "Close",
    usage: "Stats",
    title: "Stats",
    longTitle: "App & Health Stats",
    lowQualityAppDetected: "Low quality app detected. Do you want to add this app to your block list?",
    yes: "Yes",
    no: "No",
    ignore: "Ignore",
    dailyAppUsage: "Apps Screen Time",
    totalTimeUsed: "Total Time Used",
    doingGreat: "You are doing great! Keep it up!",
    todayBlockCount: "Today Block Count",
    focusBearUsage: "Focus Bear Usage",
    topBlockedApps: "Top Blocked Apps",
    blockedAppsUsage: "Blocked Apps Usage",
    timeBlocked: "Times Blocked",
    timeSpent: "Time Spent",
    lastUsed: "Last Used",
    noAppsBlocked: "No apps blocked",
    noData: "Good work! You haven't used any apps yet",
    noPermission: "We can show some cool screentime stats if you give us App Usage permissions",
    grantPermission: "Grant Usage Permission",
    overLimit: "Oh no! You're over your limit",
    lowQualityScreenTime: "Low quality screentime",
    highQualityScreenTime: "High quality screentime",
    timeUsedAfterCutoff:
      "You used your phone for <bold>{duration}</bold> during your sleep window last night.\n\nWant to increase your friction level to help you stay off tech while you're sleeping?",
    timeUsedAfterCutoffTitle: "Time Used After Sleep Window",
    dontShowAgain: "Don't show this again",
    howDistractingIsThisApp: "How distracting is this app?",
    dragToEdit: "Drag to edit",
    save: "Save",
    learnMore: "Learn More",
    qualityLabel: {
      extremelyDistracting: "Extremely Distracting",
      veryDistracting: "Very Distracting",
      slightlyDistracting: "Slightly Distracting",
      neutral: "Neutral",
      slightlyProductive: "Slightly Productive",
      productive: "Productive",
      veryProductive: "Very Productive",
    },
    qualityDescription: {
      veryDistracting:
        "Apps incessantly clamoring for attention, often sidetracking you from tasks are considered Very Distracting.",
      distracting:
        "Apps that can easily pull you away from important work and consume significant time are considered Distracting.",
      slightlyDistracting:
        "Apps that may occasionally interrupt your focus but can be managed with some discipline are considered Slightly Distracting.",
      neutral:
        "Apps that serve practical purposes without significantly impacting your productivity are considered Neutral.",
      slightlyProductive:
        "Apps that contribute to your well-being, learning, or personal growth are considered Slightly Productive.",
      productive:
        "Apps that help you accomplish tasks, stay organized, and work efficiently are considered Productive.",
      veryProductive:
        "Apps that are essential tools for your work, health, or critical daily functions are considered Very Productive.",
    },
    loadingMessage: {
      harvesting: "Harvesting usage data",
      removingGremlins: "Removing statistical gremlins",
      crunchingFormulas: "Crunching focus formulas",
      assemblingMetrics: "Assembling progress metrics",
    },
  },
  healthMetrics: {
    title: "Health Stats",
    tapToView: "Tap to view your health metrics",
    tapToCollapse: "Tap to collapse",
    healthPermissionsRequired: "Health Permissions Required",
    tapToGrantPermissions: "Tap to grant health permissions to view your metrics",
    sleep: "Sleep",
    activeMinutes: "Active Minutes",
    steps: "Steps",
    loadingHealthData: "Loading health data...",
    error: "Error: {error}",
    physicalActivityPermissionsRequired: "Physical Activity Permissions Required",
    tapToGrantPhysicalActivityPermissions: "Tap to grant physical activity permissions to view your metrics",
  },
  participantCode: {
    exitUnicaesStudy: "Exit UNICAES Study",
    enrolUnicaesStudy: "Enrol in UNICAES Study",
    consentFormTitle: "Consent Form",
    consentFormDesc: "Please read the consent form and consent to the study",
    whatsappConsent: "I consent to receive once per week Whatsapp messages with updates about the study",
    invalidPhoneNumber: "Please enter a valid phone number",
    phoneNumber: "Phone Number",
    enterYourPhoneNumber: "Enter your phone number",
    unicasStudy: "UNICAES Study",
    syncManually: "Sync Manually",
    facultyOfBusiness: "Faculty of Business Sciences",
    facultyOfEngineering: "Faculty of Engineering and Architecture",
    facultyOfHumanities: "Faculty of Sciences and Humanities",
    facultyOfHealth: "Faculty of Health Sciences",
    yearLevel1: "1st Year",
    yearLevel2: "2nd Year",
    yearLevel3: "3rd Year",
    yearLevel4: "4th Year",
    yearLevel5: "5th Year",
    wrongEmail: "The participant code doesn't match your email address. Please contact support@focusbear.io",
    invalidName: "Please enter your name",
    invalidEmail: "Please enter a valid UNICAES email address",
    invalidFaculty: "Please select your faculty",
    invalidYearLevel: "Please select your year level",
    emailAlreadyExists: "This email is already registered for the study",
    pleaseCheckEmail: "Please check your email for your participant code",
    register: "Register",
    invalidCode: "Invalid code",
    email: "Email",
    name: "Name",
    faculty: "Faculty",
    yearLevel: "Year Level",
    enterYourName: "Enter your full name",
    enterYourEmail: "Enter your UNICAES email",
    selectFaculty: "Select your faculty",
    selectYearLevel: "Select your year level",
    applicationForm: "Application Form",
    title: "Focus Bear",
    description:
      "We are currently accepting participants for our trial study at UNICAES. If you want to help us and join the study please apply below. If you want more information about the study <hereLink>click here</hereLink> or contact us at {email}.",
    moreInfoLink: "click here",
    contactEmail: "support@focusbear.io",
    applyButton: "Apply for Participation",
    hasParticipantCode: "I have a participant code",
    enterYourCode: "Enter your code",
    continue: "Continue",
    back: "Back",
    permissionNeededTitle: "Permission Needed",
    permissionNeededDescription:
      "For your participation in this study, we require you to turn on permission for data tracking. You may withdraw from the study at any time by uninstalling Focus Bear.",
    uploadScreenshot: "Upload Screenshot",
    thankYouForJoining:
      "Thanks for joining our study, currently we're just collecting data so we know how you use your phone before we give you full access to Focus Bear's features. If you would like to withdraw from the study please uninstall Focus Bear. If you need to contact support please email us at: <email>support@focusbear.io</email>",
    screenshotUploadReminder:
      "Screen Time, it's time to upload your screenshot. Please follow the instructions below. If you need any support, please contact us at: support@focusbear.io\n\nInstructions:\n\n1. Screenshot app usage for past week\n2. Click on the upload screenshot button\n3. Select the image and upload",
    usageDataLastSynced: "Usage data last synced: {date}",
    whatTimeDoYouGoToSleep: "What time do you go to sleep?",
    whatTimeDoYouSleepDescription: "We'll use this and track the usage of your phone after your sleep window.",
    setupPermissions: "Setup Required",
    setupPermissionsTitle: "Grant App Permissions",
    setupPermissionsDesc: "Allow Focus Bear to help you stay focused",
    studyTasks: "Study Tasks",
    flankerTaskTitle: "Complete Flanker Task",
    flankerTaskDesc: "Test your attention and focus",
    questionnaireTitle: "Complete Questionnaire",
    questionnaireDesc: "Help us understand your experience",
    screenTime: "It's time to upload your Screen Time",
    screenshotUploadSuccess: "Successfully uploaded",
    imageProcessing: "Checking usage data...",
    imageProcessed: "Screenshot processed successfully",
    imageProcessingFailed: "Failed to process screenshot",
    checkingStatus: "Checking status",
  },
  flankerGame: {
    title: "Flanker Bear Game",
    welcome: "Welcome to the Flanker Bear Game! This game tests your attention and focus.",
    instruction1: "1. You'll see a row of arrows",
    instruction2: "2. Focus on the center arrow",
    instruction3: "3. Press the button matching the center arrow's direction",
    instruction4: "4. Try to be as quick and accurate as possible (3 seconds each trial)",
    play: "Play",
    practiceStart: "Let's do a quick warm-up so you know how it works!",
    mainStart: "Great! Now the real test begins.",
    testProgress: "Test {current} of {total}",
    ok: "OK",
    timeout: "😢",
    complete: "All done!",
    completeMessage: "Thanks! That helps us understand how your attention works.",
    practiceComplete: "Practice Complete!",
    mainInstructions: "Now let's do the real test. You'll have 2 seconds to respond to each trial.",
    startMain: "Start Main Test",
    continue: "Continue",
  },
  questionnaire: {
    title: "Questionnaire",
    loadingQuestionnaire: "Loading questionnaire",
  },
  routineSuggestion: {
    title: "Routine Suggestion",
    generatingRoutine: "Generating routine",
    loading: "Loading",
    breathingExercise: "While you wait, check out this video to see how Focus Bear can help you build habits.",
    error: "An unexpected error occurred",
    successTitle: "Routine Generated!",
    successMessage: "We've created some sample habits based on your goals.",
    errorTitle: "Oops! Something went wrong",
    errorMessage:
      "We couldn't generate your routine right now. You can try again or continue to set up your times manually.",
    errorMessageGoals: "We ran into some problem and couldn't generate your habits, please tell us whats your goals",
    updateGoals: "Tell us your goals",
    noHabitsTitle: "No habits yet",
    noHabitsMessage: "We couldn't find any habits from your import. Let's generate some personalized habits for you!",
    morningRoutine: "Morning Routine",
    eveningRoutine: "Evening Routine",
    totalDuration: "Total: {duration}",
    noActivities: "No habits in this routine",
    addActivity: "Add Habit",
    editActivity: "Edit Habit",
    adjustWithAI: "Adjust with AI",
    createWithAI: "Create with AI",
    adjust: "Adjust",
    create: "Create",
    aiPrompt: "🐻 How do these habits look? Tell me what changes you'd like.",
    aiCreatePrompt:
      "Describe the routine you want to create from scratch. For example: 'Create a morning start routine'",
    aiPlaceholder: "e.g., 'Make the meditation more specific' or 'Add a quick workout'",
    aiError: "Failed to adjust habits. Please try again.",
    adjusting: "Adjusting your habits...",
    creating: "Creating with AI...",
    aiSuccessMessage: "Habits adjusted successfully.",
    deleteActivityTitle: "Delete Habit",
    deleteActivityMessage: "Are you sure you want to delete '{activityName}'?",
    activityName: "Habit Name",
    enterActivityName: "Enter habit name",
    duration: "Duration",
    minutes: "Minutes",
    seconds: "Seconds",
    errors: {
      nameRequired: "Habit name is required",
      nameTooShort: "Habit name must be at least 2 characters",
      invalidTime: "Please enter a valid time",
      timeTooShort: "Duration must be at least 5 seconds",
    },
    tapToEdit: "Tap to edit",
  },
  streak: {
    title: "Streak is here!",
    howItWorks:
      "Start a <bold>focus session</bold>, <bold>complete one morning or evening habit</bold> each day to keep your streak going.",
    activeStreak: "Active Streak",
    activeStreakDesc: "You used Focus Bear today.",
    dueStreak: "Streak at Risk",
    dueStreakDesc: "You used Focus Bear yesterday. Use it today to keep your streak.",
    inactiveStreak: "Inactive Streak",
    inactiveStreakDesc: "You didn’t use Focus Bear yesterday.",
    motivationTip: "Consistency matters more than long sessions.",
    morningStreak: "Morning Streak",
    eveningStreak: "Evening Streak",
    focusModeStreak: "Focus Modes Streak",
    streakIconTitle: "Icon Meanings",
    day_zero: "0",
    day_one: "{count} day",
    day_other: "{count} days",
    morning: "Morning",
    evening: "Evening",
    focus: "Focus",
    days: "days",
  },
  juniorBearConversation: {
    messageNormalStep1: "Howdy! I’m Focus Bear Junior",
    messageNormalStep2: "I'm actually not that good at focusing 😢 I've got ADHD and I get distracted all the time.",
    messageNormalStep2_5: "Oho! Okay, focus master. Is there anything you do need help with?",
    messageNormalStep3:
      "It’s hard to focus with all the fun..I mean distracting! apps on my phone. Want to team up? We can focus together!",
    messageNormalStep4: "Awesome! What do you want to work on together?",
    messageNormalStep5: "Sweet. Want to set up an account so we can work together on your computer and your phone?",
    messagePirateStep1: "Summoned to help ye focus, was I? Captain Bear at yer command.",
    messagePirateStep1_5:
      "Ye made me nephew blubber like a deckhand. So now it's me — Captain Bear. Stand tall, ye scallywag.",
    messagePirateStep2:
      "Now, truth be told… I've got ADHD, same as many a fine pirate. Me mind wanders like a ship without an anchor.",
    messagePirateStep2_5: "Well strike me mast-ye’re formidable! What help be ye seekin’ then?",
    messagePirateStep3:
      "Arr, my biggest problem be those shiny apps. They're like whirlpools pullin' me off course! We could keep each other from gettin' sucked in. Care to join me crew?",
    messagePirateStep4: "Arrr, two hands on deck! What troubles do ye seek to tame?",
    messagePirateStep5: "Grand! Shall we set up an account so we can sail together on yer computer and yer phone?",
    buttonNormalStep1Primary: "Howdy",
    buttonNormalStep1Secondary: "Arr, I wish ye were a pirate…",
    buttonNormalStep2Primary: "Me too!",
    buttonNormalStep2Secondary: "I never had that issue",
    buttonNormalStep2_5Option1: "Stick to healthy habits",
    buttonNormalStep2_5Option2: "Organise tasks",
    buttonNormalStep2_5Option3: "Go away! I don't like kids!",
    buttonNormalStep3Primary: "Let's do it!",
    buttonNormalStep3Secondary: "Go away! I don't like kids!",
    buttonNormalStep4Primary: "Next",
    buttonNormalStep5Primary: "Sign me up, Scotty!",
    buttonNormalStep5Secondary: "No thanks, I'll stay anonymous",
    buttonPirateStep1Primary: "Greetings Captain",
    buttonPirateStep1Secondary: "Greetings, Captain",
    buttonPirateStep1_5Primary: "Beg pardon, Captain. I'll keep me sea legs",
    buttonPirateStep2Primary: "Aye… I misplace me anchor often",
    buttonPirateStep2Secondary: "Not I, they call me Brain Beard",
    buttonPirateStep2_5Option1: "Build sturdier sailor habits",
    buttonPirateStep2_5Option2: "Get me tasks shipshape",
    buttonPirateStep3Primary: "Aye, let's do it!",
    buttonPirateStep3Secondary: "Arr, let the ocean decide my fate",
    buttonPirateStep4Primary: "Next",
    buttonPirateStep5Primary: "Hoist the sails — sign me up!",
    buttonPirateStep5Secondary: "I'll remain a ghost on the seas",
    focusAreaBlockDistractionsNormal: "Block distractions",
    focusAreaBlockDistractionsPirate: "Sharpen me focus at the helm",
    focusAreaHealthyHabitsNormal: "Stick to healthy habits",
    focusAreaHealthyHabitsPirate: "Build sturdier sailor habits",
    focusAreaOrganiseTasksNormal: "Organise your tasks",
    focusAreaOrganiseTasksPirate: "Get me tasks shipshape",
  },
  streakCelebration: {
    title: "{streakTypeName} streak!",
    morning: "Morning routine",
    evening: "Evening routine",
    focus: "Focus session",
    message: "You're on fire! Keep up the great work.",
    day: "day",
    days: "days",
  },
  widget: {
    defaultRoutine: "No routine",
    noReasonProvided: "All set!",
    noNextHabit: "Nothing scheduled",
    whatsNext: "What's next:",
    streakTitle: "Streaks",
    motivationalQuotes: [
      '"Success is the sum of small efforts, repeated day in and day out." – Robert Collier',
      '"The secret of getting ahead is getting started." – Mark Twain',
      '"Discipline is choosing between what you want now and what you want most." – Abraham Lincoln',
      '"Your future is created by what you do today, not tomorrow." – Robert Kiyosaki',
      '"It always seems impossible until it\'s done." – Nelson Mandela',
    ],
  },
};
