export default {
  languageName: "Español",
  baseLanguage: "es",
  blockingSchedule: {
    title: "Horarios de Bloqueo",
    namePlaceholder: "Nombre del bloqueo",
    startTime: "Hora de inicio",
    endTime: "Hora de fin",
    adjustStart: "Ajustar hora de inicio",
    adjustEnd: "Ajustar hora de fin",
    daysHeading: "Días de la semana",
    chooseApps: "Elegir apps",
    chooseUrls: "Elegir sitios web",
    saveFailedTitle: "No se pudo guardar el horario",
    saveFailedMessage: "Inténtalo de nuevo después de seleccionar apps para bloquear.",
    duplicateNameMessage: "Elige un nombre único para este horario de bloqueo.",
    focusModeSuffix: "(desde horario de bloqueo móvil)",
    defaultName: "💻 Tiempo de trabajo",
    appBlocking: "Bloqueo de apps",
    websiteBlocking: "Bloqueo de sitios web (opcional)",
    accessibilityRequiredForUrls: "Se requiere accesibilidad para bloquear sitios web.",
    selectionMissing: "Elige apps para bloquear.",
    urlsSelectionMissing: "No hay sitios web seleccionados",
    urlsSelectionCount_one: "{count} sitio web seleccionado",
    urlsSelectionCount_other: "{count} sitios web seleccionados",
    urlsDescription: "Añade sitios web para bloquear durante este horario",
    selectedUrls: "Sitios web seleccionados",
    suggestedUrls: "Sitios web sugeridos",
    noAppsSelected: "No hay apps seleccionadas",
    iOSSelectionCounts: "{applicationsCount} apps, {categoriesCount} categorías, {webDomainsCount} sitios web",
    androidSelectionCount: "{applicationsCount} aplicaciónes seleccionadas",
    mode: {
      strict: {
        title: "Bloqueo estricto",
        subtitle: "Sin escape: introduce una contraseña para desbloquear",
      },
      cooldown: {
        title: "Bloqueo con enfriamiento",
        subtitle: "Desbloquea tras una breve espera (te da tiempo para reconsiderar)",
      },
      gentle: {
        title: "Bloqueo suave",
        subtitle: "Pausa el bloqueo inmediatamente con riesgo de doomscrolling 😅",
      },
    },
    removeTitle: "¿Eliminar este horario?",
    removeMessage: "Esto eliminará el horario de forma permanente.",
    removeFailedMessage: "Por favor, inténtalo de nuevo.",
    blockedBySchedule: "Bloqueado por horario: {scheduleName}",
    appBlockedBySchedule: "{appName} está bloqueado porque tu horario de bloqueo {scheduleName} está activo",
    blockAllDuringHabits: "Bloqueando algunas aplicaciones durante todos los hábitos",
    customizeBlocking: "Personalizar bloqueo",
    habitBlocksTitle: "Bloqueos por hábitos",
    scheduledBlocksTitle: "Bloqueos programados",
    scheduledBlocksInfoText:
      "Crea ventanas de tiempo que se repiten en los días seleccionados. Puedes añadir varios bloqueos.",
    addNewBlock: "Agregar un bloque",
    habitMorningName: "Rutina matutina",
    allDays: "Todos los días",
    permissionsRequired: "Permisos Requeridos",
    androidPermissionDescription: "Se requieren permisos de acceso de uso y superposición para bloquear aplicaciones",
    iOSPermissionDescription: "Se requiere el permiso de Tiempo de uso para crear y administrar horarios de bloqueo.",
  },
  tabTitle: {
    overview: "Resumen",
    habits: "Hábitos",
    tasks: "Tareas",
  },
  error: {
    invalidVideoUrl: "URL de video youtube inválida",
    videoNotFound: "Lo siento, no se encontró el video.",
    authenticationErrorName: "Error de autenticación",
    authenticationErrorMessage:
      "¡Vaya! Hubo un problema con la autenticación de nuestro lado. Por favor, inténtalo de nuevo.",
  },
  habitSetting: {
    routine: "Rutina",
    selectRoutine: "Seleccionar rutina",
    requirement: "¿Qué se necesita hacer para completar este hábito?",
    youtubeVideo: "Video de YouTube o Vimeo",
    youtubeVideoDescription: "Añade un video para que te guíe en este hábito",
    enableTimer: "¿Activar temporizador?",
    timer: "Temporizador",
    timerDescription: "Establecer una duración para el hábito",
    goal: "Meta",
    goalDescription: "Completar el hábito cuando hayas alcanzado tu meta",
    goalPlaceholder: "¿Especificar una meta para completarlo?",
    extras: "Extras",
    noGoalSpecified: "Ningún objetivo especificado",
    defaultName: "Hábito sin nombre",
    allowedApps: "Aplicaciones permitidas",
    allowedAppsDescription: "Selecciona las aplicaciones a las que puedes acceder durante este hábito",
    selectApps: "Seleccionar aplicaciones",
    appsSelected: "{count} aplicación(es) seleccionada(s)",
    noAppsSelected: "Ninguna seleccionada",
    openAllowedApps: "Abrir aplicaciones permitidas",
    launchApp: "Abrir",
  },
  common: {
    accept: "Aceptar",
    learnMore: "Aprender más",
    doItLater: "Hacerlo más tarde",
    loadingWithoutDot: "Cargando",
    pleaseWaitPatiently:
      "Por favor, espera pacientemente mientras cargamos los datos. Esto puede tomar unos minutos, pero estamos trabajando duro detrás de escena para garantizar que todo esté configurado perfectamente para ti.",
    later: "Más tarde",
    termsOfUse: "Términos y Condiciones",
    privacyPolicy: "Política de Privacidad",
    email: "Correo electrónico",
    nickname: "Nickname",
    skip: "Saltar",
    goToSleep: "Hora de dormir 😴",
    areYouSure: "¿Estás seguro/a?",
    loading: "Cargando...",
    connectionError: "Error de conexión",
    morning: "mañana",
    evening: "noche",
    welcome: "Bienvenido/a",
    somethingWrong: "Algo salió mal",
    logout: "Cerrar sesión",
    ok: "OK",
    ok_ellipsis: "OK...",
    okay: "Okay",
    yes: "Sí",
    no: "No",
    confirm: "Confirmar",
    delete: "Borrar",
    next: "Siguiente",
    cancel: "Cancelar",
    proceed: "Proceder",
    resume: "Reanudar",
    retry: "Reintentar",
    submit: "Enviar",
    resend: "Reenviar",
    verify: "Verificar",
    edit: "Editar",
    finished: "Completado",
    done: "Hecho",
    sec: "seg",
    focusBear: "focus bear",
    tomorrow: "Mañana",
    today: "Hoy",
    yesterday: "Ayer",
    add: "Agregar",
    start: "Iniciar",
    startRoutine: "Iniciar Rutina",
    continue: "Continuar",
    end: "Terminar",
    startActivity: "Iniciar {activityName}",
    startTimerActivity: "Iniciar {time} {unit} {activityName}",
    Success: "Éxito",
    SuccessfullyAddedHabit: "Hábito agregado con éxito",
    save_changes: "Guardar cambios",
    save: "Guardar",
    saving: "Guardando",
    saved: "Guardado",
    created: "Creado",
    next_time_format: "[{day} a] h:mm A",
    sure: "Sí",
    uploadScreenShots: "Subir capturas de pantalla \n(Optional)",
    session_expired: "Sesión Expirada",
    login_again: "Por favor, vuelve a iniciar sesión",
    continue_activity_name: "Continuar {activityName}",
    no_thanks: "No, gracias",
    saveHabitSuccessfully: "{habitName}, a tu rutina {routineName}",
    couldNotProcessTheRequest: "No se pudo procesar la solicitud, inténtalo de nuevo",
    error: "Error",
    selected: "Seleccionado",
    granted: "Concedido",
    notGranted: "No concedido",
    all: "Todos",
    viewAll: "Ver todo",
    more: "Más",
    somethingElse: "Algo más",
    habit: "Hábito",
    empty: "Vacío",
    clearAll: "Limpiar",
  },
  lateNoMore: {
    title: "Recordatorios de Reuniones",
    calendarIntegration: "Integración de Calendario",
    calendarTooltip:
      "Conecta el calendario de tu teléfono, o conecta tu calendario de Google a través del panel web para habilitar la detección de reuniones",
    googleCalendar: "Calendario de Google",
    connected: "Conectado",
    notConnected: "No conectado",
    enableReminders: "Habilitar Recordatorios",
    calendarPermission: "Calendario del Dispositivo",
    calendarPermissionAlreadyGranted:
      "El Calendario del Dispositivo está conectado. Puedes revocar el acceso en cualquier momento a través de la configuración de tu teléfono",
    calendarPermissionDenied:
      "Por favor, concede el permiso de acceso al calendario en la configuración de tu teléfono",
    openSettings: "Abrir configuración",
    addReminder: "Agregar Recordatorio",
    durationBefore: "{duration} antes",
    whenMeetingStarts: "Cuando comienza la reunión",
    requireMeetingUrl: "Solo Eventos con Reuniones",
    requireMeetingUrlDescription: "Incluir solo eventos que tengan una URL de reunión adjunta",
    // Notification messages
    notification1: "¡Reunión empezando pronto! 🐻",
    notification2: "¡Prepárate para ir a tu reunión! ⏰",
    notification3: "¡Tu reunión se acerca! 🚀",
    notificationBody: "'{title}' comienza {time}",
    now: "ahora",
    // Meeting Preparation UI
    yourMeetingStartsIn: "Reunión en <highlight>{countdown}</highlight>. ¡Preparémonos!",
    yourMeetingIsOngoing: "Hay una reunión en curso. Únete <highlight>ahora</highlight>!",
    upcomingMeeting: "Evento próximo",
    mentallyPrepare: "1. Prepararse mentalmente para la reunión",
    howDoYouWantToShowUp: "¿Cómo quieres presentarte?",
    placeholderHowToShowUp: "Tranquilo, escuchando, de mente abierta, colaborativo...",
    joinOnTime: "2. Unirse a tiempo",
    ignoreMeeting: "Ignorar reunión",
    startMeeting: "Unirse a la reunión",
    noUpcomingMeetings: "No hay reuniones próximas",
    noMeetingsDescription: "No encontramos reuniones programadas en las próximas horas.",
    // Calendar source indicators
    googleCalendarSource: "Fuente: Calendario de Google",
    deviceCalendarSource: "Fuente: Calendario del dispositivo",
  },
  customizeBlocking: {
    customBlockedMessage: {
      title: "Mensaje de bloqueo personalizado",
      tooltip: "Reemplaza la cita motivacional predeterminada en tu pantalla de bloqueo.",
      placeholder: "Introduce tu mensaje personalizado...",
      hint: "Déjalo vacío para usar las citas motivacionales predeterminadas.",
    },
    customSoftBlocking: {
      title: "Período de desbloqueo",
      description: "Cuánto tiempo la app permanece desbloqueada tras elegir un descanso en modo de bloqueo suave.",
      hint: "Entre {min} y {max} minutos",
    },
    customPauseDelay: {
      title: "Tiempo de espera de pausa",
      description: "Un pequeño obstáculo antes de desbloquear una app bloqueada. Cada intento hace el siguiente más difícil.",
      hint: "Elige entre {min}s y {max}s",
      sequenceLabel: "Tus tiempos de espera",
    },
    saveSuccess: "Configuración de bloqueo personalizada guardada correctamente",
    saveError: "No se pudo guardar la configuración de bloqueo personalizada. Por favor, inténtalo de nuevo.",
  },
  settings: {
    healthPermission: "Permiso de Salud",
    physicalActivityPermission: "Permiso de Actividad Física",
    healthAndSleepPermission: "Permiso de Salud y Sueño",
    changedBackendEndpoint: "Se ha cambiado el punto final del backend",
    lateNoMore: "Recordatorios de Reunión",
    saveBlockedUrls: "Las URLs bloqueadas se han guardado correctamente",
    saveBlockedUrlsError: "Error al guardar las URLs bloqueadas",
    debugLog: "Habilitar registro detallado.",
    debugLogDescription: "Solo actívalo si el equipo de soporte te lo solicita, ya que ralentizará la aplicación.",
    title: "Configuración",
    addApps: "Agregar aplicaciones a la lista de bloqueo",
    clearBlocklist: "Borrar lista de bloqueo",
    confirmClearBlocklist: "¿Confirmar limpieza de la lista de bloqueados?",
    urlBlockingWarningTitle: "Importante: El bloqueo de URLs solo funciona en Safari",
    urlBlockingWarningMessage:
      "El bloqueo de sitios web solo funciona en Safari. Para evitar eludir los bloqueos de URL, recomendamos bloquear Chrome, Firefox y otros navegadores de terceros completamente en tu lista de bloqueo.",
    urlBlockingHowToTitle: "Cómo bloquear sitios web",
    urlBlockingHowToMessage:
      "Toca 'Agregar URLs a la lista de bloqueo' abajo, luego selecciona la pestaña 'Sitios web' en la parte superior del selector. Puedes buscar sitios web específicos o navegar por categoría. Los sitios web seleccionados se bloquearán en Safari durante tus sesiones de enfoque.",
    addUrls: "Agregar URLs a la lista de bloqueo",
    clearBlockedUrls: "Borrar URLs bloqueadas",
    confirmClearBlockedUrls: "¿Confirmar borrar URLs bloqueadas?",
    shareLogsWithSupport: "Reportar problema",
    strictness: "Rigidez",
    reason_required: "Por favor, introduce una razón",
    enter_a_reason: "¿Podrías explicarnos por qué quieres eliminar tu cuenta?",
    contact_desc: "¿Podemos contactarte para ayudarte a solucionar los problemas que has experimentado?",
    editFriction: "Fricción",
    password: "Contraseña",
    account: "Cuenta",
    permissions: "Permisos",
    language: "Idioma",
    useSystemLanguage: "Usar lenguaje del sistema",
    supportedLanguages: "Idiomas disponibles",
    overlay_permission: "Permiso de Superposición",
    usage_permission: "Permiso de Uso",
    notification_permission: "Permiso de Notificación",
    screen_time_permission: "Permiso de Tiempo en Pantalla",
    DND_permission: "Permiso de No Molestar",
    DND: "No Molestar",
    warning: "¡Advertencia!",
    DND_permissionWarning:
      "El modo DND debe desactivarse manualmente si ya está activado. No se puede desactivar automáticamente si no se conceden permisos DND.",
    help: "Ayuda",
    askForHelp: "Pide ayuda",
    report_problem: "Reportar Problema",
    discord_server: "Servidor Discord",
    videoTutorials: "Video Tutoriales",
    experimental: "Experimental",
    customization: "Personalización",
    general: "General",
    focusGames: "Juegos de Enfoque",
    allowed: "Permitido",
    notAllowed: "No Permitido",
    notGrantedYet: "Pendiente",
    userid: "ID de usuario",
    copy: "Copiar",
    copied: "Copiado",
    settings: "Configuración",
    verifyEmail: "Verificar correo electrónico",
    emailVerificationResent: "Verificación de correo electrónico reenviada",
    pendingVerification: "Verificación pendiente",
    editNickname: "Editar nickname",
    nicknameError: "Nickname inválido (solo letras y números)",
    nicknameAlreadyExists: "El nickname ya existe",
    customizeBlocking: "Personalizar bloqueo",
  },
  focus: {
    title: "Enfoque",
    focusLimitReachedTitle: "Límite de Enfoque Alcanzado",
    focusLimitReachedMessage:
      "En la versión gratuita, sólo puedes concentrarte hasta 25 minutos. Actualiza a la versión Premium si quieres sesiones de enfoque más largas.",
  },
  home: {
    setupHabitsDescription: "Configura tus hábitos para empezar tu día.",
    upEarlyStartMorningRoutine: "¿Quieres empezar tu rutina matutina antes?",
    getMotivated: "Motívate",
    completed: "Completado",
    habitName: "Nombre del Hábito",
    newHabit: "Nuevo Hábito...",
    duration: "Duración",
    editHabit: "Editar hábito",
    deleteHabitTitle: "Eliminar Hábito",
    deleteHabitMessage: "¿Estás seguro de querer eliminar '{habitName}'? Esta acción no se puede deshacer.",
    addHabit: "Añadir hábito",
    deleteThisHabit: "Borrar este hábito",
    deleteHabit: "Borrar hábito {name}",
    afterCutoffTimeDescription: "Ninguno de tus hábitos está disponible porque ya pasó la hora límite.",
    routineNotScheduledNow: "Esta rutina está programada para {routineSchedule}",
    cutOffToolTip:
      "Has configurado las horas de corte de tus hábitos para que no sean accesibles después de {cutOffTime}.\nPuedes modificarlo en Cambiar Hora",
    unlockToProceed: "Desbloquear para proceder",
    title: "Inicio",
    morningRitual: "Tu ritual matutino",
    eveningRitual: "Tu ritual nocturno",
    time_to_earn_screen_time: `Haz tus hábitos matutinos para prepararte para un día increíble`,
    evening_routine_text: "¡Estarás listo para una gran noche de sueño cuando hayas terminado!",
    upcoming_below_new_activities:
      "A continuación se muestran los hábitos que debes cumplir en la próxima rutina para usar tu celular.",
    start: "Iniciar",
    mins: "mins",
    secs: "segs",
    re_activate: "Reactivar",
    force_deactivate_postpone_and_start_routine: "La rutina ha sido pospuesta\n ¿Reanudar la rutina?",
    userCompletedRoutineHeading:
      "Felicidades por terminar tu rutina. Espero poder ayudarte con tu próxima rutina {routineTime}",
    postOnboardingRoutineHeading:
      "¡Bienvenido a bordo! Esperamos poder ayudarte con tu rutina {routineName} {routineTime}",
    wantLogout: "¿Deseas cerrar sesión?",
    noDataFound: "Todavía no has configurado ningún hábito. Toca <fix>aquí</fix> para añadir hábitos.",
    routineFetchingError:
      "Se produjo un problema al recuperar datos de rutina. Por favor, intenta más tarde o contáctanos para asistencia",
    hi: "¡Hola {nickname}!",
    welcomeDefault: "¡Hola!",
    goodMorningFocusTime: "¡Buenos días!",
    goodEveningFocusTime: "¡Buenas noches!",
    allActivitiesCompleted: "No quedan hábitos por completar",
    startRoutineNow: "Hacer Mi Rutina {routineName} ",
    customRoutineReady: "Puedes iniciar tu rutina personalizada ahora",
    passwordForSettingsTitles: "Ingresar contraseña para proceder",
    manageAlwaysAllowedAppsDesc:
      "Durante tu rutina matutina/vespertina y cuando estés concentrado en tu computadora, se bloquearán todas las aplicaciones en tu teléfono, excepto las aplicaciones siempre permitidas. Te sugerimos que solo permitas aplicaciones como SMS, Teléfono y aplicaciones que necesitas para trabajar para que no te distraigas en tus hábitos/trabajo.",
    manageAlwaysBlockedAppsDesc:
      "Durante tu rutina matutina/ nocturna y cuando estés concentrado en tu computador, todas las apps en tu lista de bloqueo serán bloqueadas. Te sugerimos bloquear redes sociales, juegos, correo y apps de noticias para que no te distraigas durante tus hábitos/trabajo.",
    editHabits: "Editar Hábitos",
    editYourHabits: "Editar tus hábitos",
    stats: "Estadísticas",
    motivationMsg: "Motivarme",
    play: "Reproducir",
    pause: "Pausa",
    customizeHabits: "Cambiar Hora",
    deleteAccount: "¿Eliminar Cuenta?",
    accountDataHasBeen: "Los datos de la cuenta se han eliminado correctamente. Gracias por usar Focus Bear.",
    overlayPermission: "Permiso de Superposición",
    usagePermission: "Permiso de Uso",
    blockSuperDistractingApps: "Bloquear sitios/apps super distractores",
    skipHabitDesc: "Saltar este hábito hoy",
    screenTimePermissionNotAllowedWarningText:
      "El permiso de tiempo en pantalla es necesario para bloquear aplicaciones, inicia un hábito otra vez para conceder permisos.",
    OverlayPermissionNotGrantedWarning:
      "Advertencia: Bloqueo de distracciones no activado. Permiso de superposición no concedido. Corregir.",
    ScreenTimePermissionNotGrantedWarning:
      "Advertencia: bloqueo de distracciones no activado. Permiso de tiempo de pantalla no concedido. Corregir.",
    UsagePermissionNotGrantedWarning:
      "Advertencia: Bloqueo de distracciones no activado. Permiso de uso no concedido. Corregir.",
    noAllowedAppSelectedWarning:
      "Aviso: aún no has configurado tu lista de bloqueo, así que las distracciones no se bloquearán. Editar Lista de Bloqueo",
    habitLimitMessage:
      "Usuarios gratuitos sólo pueden acceder a un máximo de 3 hábitos por rutina. Por favor, actualiza para desbloquear más hábitos.",
    routineOptionsTooltip: "Este menú te permite editar tu rutina o cambiar su horario.",
    youHaveNotSetupAnyHabitsYet: "Aún no has configurado ningún hábito.",
    guestSignUpDescription:
      "Regístrate para acceder a tus funciones en todos tus dispositivos y desbloquear funciones personalizadas.",
    guestMode: "Modo Invitado",
    deleteRoutineTitle: "Eliminar Rutina",
    deleteRoutineMessage:
      "¿Estás seguro de que quieres eliminar esta rutina y todos los hábitos asociados? Esta acción es irreversible.",
    createHeading: "Crear",
    completedHabits: "Hábitos completados",
    hiddenHabits: "Hábitos ocultos",
    editRoutine: "Editar rutina",
    changeTiming: "Cambiar horario",
    deleteRoutine: "Eliminar rutina",
    cutoffTimeNote:
      "Nota: Tu hora de corte es {time}. Los hábitos que no están configurados como 'alta prioridad' no estarán disponibles después de esta hora. ",
    editCutoff: "Editar hora de corte",
    unavailable: "No disponible",
    inProgress: "En progreso",
    startsAt: "Comienza a las {time}",
    passed: "Pasado",
    completedWithCount: "{count} completados",
    unavailableWithCount: "{count} actualmente no disponibles",
    noHabitsYetAddPrompt: "Todavía no hay nada aquí.\n¿Añadir un hábito?",
    routineIsEmpty: "La rutina está vacía",
    allHabitsHidden: "Todos los hábitos ocultos",
    habitsCount_zero: "$t(common.empty)",
    habitsCount_one: "{count} hábito",
    habitsCount_other: "{count} hábitos",
  },
  editRoutine: {
    editTiming: "Editar horario",
    morningTime: "Hora matutina",
    wakeUp: "¡Despertarse!",
    morningRoutineStartTime: "Hora de inicio de la rutina matutina",
    eveningTime: "Hora vespertina",
    finishWork: "Terminar el trabajo",
    eveningRoutineStartTime: "Hora de inicio de la rutina vespertina",
    techCurfew: "Toque de queda tecnológico",
    timeToSleep: "Hora de dormir",
    timing: "Horario",
    anytime: "En cualquier momento",
    scheduled: "Programado",
    doHabitsWhenever: "Haz estos hábitos cuando quieras",
    doHabitsAtSpecificTime: "Haz estos hábitos a una hora específica o en días específicos",
    newRoutinePlaceholder: "Nueva rutina...",
    routineNamePlaceholder: "Nombre de la rutina",
    customRoutineDefaultName: "Rutina personalizada",
    createNewRoutine: "Crear nueva rutina",
    time: "Hora",
    wakeUpFinishWorkSameError: "La hora de despertar y la hora de finalizar el trabajo no pueden ser iguales",
    cutoffOutOfRangeError:
      "La hora de dormir debe ser después de tu hora de finalizar el trabajo y antes de tu hora de despertar",
    startBeforeEndError: "La hora de inicio debe ser anterior a la hora de fin",
  },
  blockingStatusBanner: {
    additionalSchedules: " +{count} más",
    activeSchedule: "{name} ({start} – {end}) {extra}",
  },
  simpleHome: {
    setupBlocking: "Configurar bloqueo de distracciones",
    setupBlockingApp: "Configurar bloqueo de distracciones para apps (recomendado)",
    setupBlockingUrl: "Configurar bloqueo de distracciones para sitios web (opcional)",
    title: "Prueba Focus Bear",
    focusSessionCheckboxTitle: "Completa tu primera sesión de enfoque",
    microBreakCheckboxTitle: "Haz un hábito de microdescanso",
    focusScreenTitle: "Prueba una sesión de enfoque",
    focusSessionCheckboxDesc: "Haz trabajo profundo",
    microBreakCheckboxDesc: "Desestrésate con respiración profunda",
    postGamePromptTitle: "¡Buen trabajo!",
    postGamePromptText: "¿Quieres comenzar una sesión de enfoque ahora para terminar esa tarea?",
    focusNowCta: "¡Sí! Hora de enfocarse",
    focusGameTitle: "Calienta con un juego de enfoque",
    focusGameDesc: "Juega un juego rápido para entrar en zona",
  },
  postpone: {
    doYouReallyWantTo: "¿Realmente quieres desbloquear?",
    blockingPausedForDuration: "Bloqueado pausado por {duration}",
    blockingPausedIndefinitely: "Bloqueado pausado hasta que vuelvas a desbloquear",
    pauseBlocking: "Pausar bloqueo",
    pauseDisabledStrictMode: "El bloqueo de pausas no se puede utilizar cuando el modo superestricto está habilitado",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Reanudar bloqueo",
    choosePostponeTime: "¿Cuánto tiempo quieres posponer?",
    indefinite: "Pausa hasta que reanude el bloqueo",
    youHavePausedTimesToday_zero: "Es la primera vez que pausas hoy.",
    youHavePausedTimesToday_one: "Has pausado una vez hoy.",
    youHavePausedTimesToday_other: "Ya has pausado {count} veces hoy.",
    countdown: "Podrás pausar después de {countdown}",
    areYouSureIndefinite:
      "¿Estás seguro/a de que quieres pausar el bloqueo hasta que vuelvas a desbloquear? Aunque a veces una tarea aparentemente urgente puede esperar 15 minutos hasta que termines tus hábitos.",
    doHabits: "Hago mis hábitos",
    longTermGoalsDesc: "Sólo un recordatorio de que esto es lo que intentas conseguir con Focus Bear:",
    lowQualityUsageDesc: "Has pasado {duration} minutos en apps distractoras hoy.",
    write: "Dejar retroalimentación...",
  },
  passwordForSettings: {
    invalid_password: "Contraseña inválida",
    resetAfter24Hours: "Restablecimiento solicitado. Tu contraseña se desactivará después de 24 horas.",
  },
  signIn: {
    logIn: "Iniciar sesión",
    enterEmailHint: "Dirección de correo electrónico",
    enterPasswordHint: "Contraseña",
    invalidCredentials: "Usuario/Contraseña inválido",
    enterEmailError: "Por favor, ingresa tu correo electrónico",
    enterValidEmailError: "Por favor, ingresa un correo electrónico válido",
    enterPasswordError: "Por favor, ingresa tu contraseña",
    dontHaveAccount: "¿No tienes una cuenta?",
    forgotPassword: "¿Olvidaste la contraseña?",
    signup: "Registrarse",
    googleSignIn: "Continuar con Google",
    continueWithGoogle: "Continuar con Google",
    startWithApple: "Empezar con Apple",
    startWithEmail: "Usar correo electrónico",
    backToSignInMethod: "Volver a seleccionar método de inicio de sesión",
    alreadyHaveAccount: "Ya tengo una cuenta de Focus Bear",
  },
  forgotPassword: {
    forgotPasswordNotVerifiedBody:
      "Debes verificar tu correo electrónico para poder restablecer tu contraseña. Te enviaremos un nuevo enlace de verificación ahora.",
    forgotPasswordNotVerifiedTitle: "Verifica tu correo electrónico para restablecer tu contraseña",
    resetLinkSent:
      "Si existe una cuenta con este correo electrónico, se ha enviado un enlace para restablecer la contraseña.",
    verificationEmailSent:
      "Se ha enviado el correo electrónico de verificación. Revisa tu bandeja de entrada y sigue las instrucciones.",
    verificationEmailFailed: "No se pudo enviar el correo electrónico de verificación. Inténtelo de nuevo más tarde.",
    forgotPasswordSuccess:
      "El correo electrónico de restablecimiento de contraseña ha sido enviado a tu dirección de correo electrónico",
    forgotPasswordErrorThirdParty:
      "Si utilizó este correo electrónico para registrarse en Google o Apple, continúe iniciando sesión con ese proveedor.",
    cannotResetPasswordOAuthAccountTitle: "Inicia sesión para continuar",
    forgotPasswordNotVerified:
      "El correo electrónico de tu cuenta no está verificado. Revisa tu bandeja de entrada para ver si hay un enlace de verificación o solicita uno nuevo.",
    forgotPasswordEmailNotFound: "Correo electrónico no encontrado",
    forgotPasswordTitle: "Restablecer contraseña",
    backToSignIn: "Volver a Inicio de Sesión",
    resetPassword: "Restablecer contraseña",
    resetFailed: "El intento de restablecer la contraseña ha fallado. Inténtalo de nuevo más tarde.",
    waitBeforeRetry: "Espere antes de solicitar otro correo electrónico.",
    weveEmailedYouALinkToResetYourPassword: "Te hemos enviado un enlace por correo para restablecer tu contraseña.",
  },
  signUp: {
    backToSignUpMethod: "Volver a seleccionar método de registro",
    verifyEmail: "Revisa tu bandeja de entrada",
    verifyEmailMessage:
      "Hemos enviado un correo de verificación. Por favor, haz clic en el enlace para verificar tu cuenta.",
    signUp: "Registrarse",
    emailSignup: "Registrarse con correo",
    continueWithNoAccount: "Continuar sin una cuenta",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    tosAndPP: "Acepto las <bold>Condiciones de Uso</bold> y <bold1>Política de Privacidad</bold1>",
    passwordMatchError: "Contraseña y confirmar contraseña no coinciden",
    acceptTerms: "Por favor, acepta las Condiciones de Uso y la Política de Privacidad para continuar",
    passwordHintError: `La contraseña debe contener:
    • Al menos 8 caracteres
    • Números (0-9)
    • Letras minúsculas (a-z)
    • Letras mayúsculas (A-Z)
    • Caracteres especiales (!@#$%^&*)`,
    invalidSignup: "Registro inválido",
    userExists: "El usuario ya existe.",
    terms: "Términos",
    privacy: "Privacidad",
    or: "o",
  },
  profile: {
    logout: "Cerrar Sesión",
  },
  routineDetail: {
    activity: "Actividad",
    not_playable_video: "No se puede reproducir el video.",
    done: "He terminado",
    video: "Video",
    images: "Imágenes",
    checklist: "Lista",
    note: "Nota",
  },
  quickBreak: {
    quickBreak: "Descansos Rápidos",
    quickStretch: "Ejercicio de estiramiento",
    stretch: "Extensión",
    drinkWater: "Beber Agua",
    water: "Agua",
    deepBreathing: "Respirar Profundo",
    breathe: "Respirar",
    saveQuickBreakSuccessfully: "Tus cambios se han guardado correctamente",
    editQuickBreaks: "Editar Descansos Rápidos",
    quickBreakName: "Nombre del descanso rápido",
    currentSelection: "Selección actual",
  },
  complete: {
    backToHome: "Volver al Inicio",
    logQuantity: 'Registra la Cantidad de la actividad"',
    finishedCheck: "¡completado!",
    habitNotCompleted: "no completado! ❌",
    finishedAndEarnedMorning: "¡completado! ✅ Te ganaste tu tiempo en pantalla",
    finishedAndEarnedEvening: "¡completado! ✅ Te ganaste una buena noche de sueño. ¡Hasta mañana!",
    why_skip: "¿Por qué quieres omitirlo?",
    already_did: "Ya lo hice",
    cannot_today: "No puedo hacerlo hoy",
    quantity_input_error: "El número debe estar entre {min} y {max}.",
    freemiumLimitReached:
      "Lo sentimos, solo puedes completar 3 hábitos con un plan gratuito. ¡Actualiza para continuar!",
  },
  reason: {
    canShare: "¿Puedes compartir por qué estás pausando?",
    shareFeedback: "Compartir retroalimentación",
    everythingIsOk: "¡Oh oh! Espero que todo esté bien.",
    appBrokenDesc: "Realmente lo siento ¿Puedes por favor decirnos qué pasó?",
    somethingElseDesc: "De acuerdo. ¿Hay algún comentario que quieras compartir con nosotros?",
    gotEmergency: "Tengo una emergencia",
    appBroken: "El app está dañado",
    somethingElse: "Algo más",
  },
  notification: {
    backgroundService: "Servicio en segundo plano de Focus Bear para ayudarte a concentrarte",
    scheduleNotificationTitleForResumeRoutine: "Retoma tu rutina",
    scheduleNotificationDescriptionForResumeRoutine: "Es hora de enfocarse en tu rutina.",
    floatingModuleActivityCompleteNotificationtitle: "Actividad Completada",
    floatingModuleRoutineCompleteNotificationtitle: "Rutina Completada",
    morningRoutineCompletedNotificationDescription: "Rutina matutina completada. ¡Buen comienzo del día!",
    eveningRoutineCompletedNotificationDescription: "Rutina nocturna completada. ¡Que duermas bien!",
    customRoutineCompletedNotificationDescription: "{{routineName}} completada. ¡Bien hecho!",
  },
  focusMode: {
    blockingPaused: "Bloqueo Pausado",
    blockingPermissionNeeded: "Bloqueo inactivo: necesitas conceder permisos",
    noBlockingAppsSelected: "Bloqueo inactivo: necesitas elegir aplicaciones para bloquear",
    distractionBlockingNotActiveTitle: "El bloqueo de distracciones está inactivo",
    distractionBlockingNotActiveText: "Aún no has elegido aplicaciones para bloquear",
    continueWithoutBlocking: "Continuar sin bloquear",
    fixBlocking: "Configurar bloqueo",
    confirmSuperStrictMode:
      "¿Estás seguro/a de que quieres activar el Modo Superestricto? No podrás salir hasta que termine la sesión.",
    focusIntentionTooltip:
      "Establece un objetivo para lo que lograrás en esta sesión de enfoque. Estar claro en lo que quieres lograr ayuda a evitar distracciones.",
    focusTitle: "Iniciar sesión de enfoque",
    superStrictToolTip:
      "¿Comprometido con esta sesión de enfoque? Activa el modo superestricto y no podrás desactivar el enfoque ni pausar el bloqueo de aplicaciones hasta que termine el temporizador.",
    superStrictMode: "Modo Super Estricto",
    brainDump: "Lluvia de Ideas",
    brainDumpToolTip:
      "Escribe cualquier pensamiento que te distraiga. Esto te ayudará a concentrarte en lo que estás haciendo y evitar distracciones.",
    postFocusCongrats_0: "¡Buen trabajo! ¡Lo lograste!",
    postFocusCongrats_1: "¡Hey, gran trabajo terminando eso! ¿Qué sigue?",
    postFocusCongrats_2: "¡Lo lograste! Ahora puedes tomarte un respiro.",
    postFocusCongrats_3: "¡Bien hecho! ¡Realmente estás logrando hacer las cosas!",
    postFocusCongrats_4: "¡Magnífico trabajo! ¿Qué es lo próximo en tu radar?",
    postFocusCongrats_5: "¡Lo conseguiste! ¿Es hora de pasar al siguiente?",
    postFocusCongrats_6: "¡Gran concentración! ¡Ve a tomar una bebida o snack!",
    postFocusCongrats_7: "¡Muy bien! ¡Estás progresando mucho!",
    postFocusCongrats_8: "¡Bien hecho! ¿Es hora de estirar un poco las piernas?",
    postFocusCongrats_9: "¡Lo hiciste muy bien! Mantengamos el impulso.",
    startFocusSession: "Iniciar sesión de enfoque",
    noIntentionWasFound: "Ninguna intención ingresada",
    noDistractingThoughtsWasFound: "Ningún pensamiento distractor ingresado",
    distractionAlertTitle: "Modo de Enfoque",
    userIntention: "Objetivo de Enfoque",
    userIntentionTextInputPlaceholder: "¿Qué quieres lograr?",
    startFocusing: "Empezar a concentrarse",
    hoursWithValue: "{value}h",
    minutesWithValue: "{value}min",
    secondsWithValue: "{value}s",
    duration: {
      hours: "{hours} horas",
      minutes: "{minutes} minutos",
      seconds: "{seconds} segundos",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "¡Tú puedes!\nTiempo de trabajo profundo",
    endSession: "Terminar Sesión",
    completeFocus: "Enfoque Completo",
    userDumpThoughTextInputDescription: "Escribe aquí cualquier pensamiento que te distraiga",
    exitFocusMode: "Terminar antes la sesión de enfoque",
    focusDoneDescription4: "¿Cuáles eran tus pensamientos distractores?",
    exitFocusModeDescription: "¿Puedes compartir por qué terminas esta sesión?",
    reason: "Razón",
    selectReason: "Elegir una razón",
    congratulations: "¡Felicidades!",
    focusDoneTitle: "¡LO HICISTE!",
    focusDoneDescription: "Te mantuviste concentrado durante",
    focusDoneDescription1: "¿Cuál era tu intención?",
    focusDoneDescription2: "¿Qué conseguiste durante este tiempo?",
    focusDonePlaceholderDescription2: "Introduce lo que conseguiste con nuestra ayuda",
    focusDoneDescription3: "¿Tuviste alguna distracción?",
    focusDonePlaceholderDescription3: "Introduce las distracciones que tuviste",
    endEarlyReasonDescription1: "Tengo una emergencia",
    endEarlyReasonDescription2: "El modo de enfoque no funciona correctamente",
    endEarlyReasonDescription3: "Ya conseguí lo que quería",
    endEarlyReasonDescription4: "Necesito un descanso",
    runningFocusModeDesc: "Una sesión de enfoque se está ejecutando",
    extendFocusDuration: "Extender duración del enfoque",
    shortenFocusDuration: "Acortar duración del enfoque",
    selectExtendFocusDuration: "¿Cuánto tiempo quieres concentrarte?",
    selectShortenFocusDuration: "¿Cuánto tiempo quieres acortar?",
    extendFocus: "Extender",
    shortenFocus: "Acortar",
    adjustFocusDuration: "Ajustar duración del enfoque",
    chooseAdjustmentOption: "¿Te gustaría extender o acortar tu sesión de enfoque?",
    editFocusDuration: "¿Cuándo quieres terminar de concentrarte?",
    focusMusic: "Música de enfoque",
    focusMusicError: "Lo siento, no se pudo reproducir la música para concentrarte",
    focusNotes: "Notas de enfoque",
  },
  toDos: {
    toDos: "Tareas",
    todoList: "Lista de Tareas",
    notes: "Notas",
    drafts: "Generado por IA",
    scanPaperWithOCR: "Escanear papel con OCR",
    quickActions: {
      audio: "Audio",
      uploadAudio: "Subir audio",
      recordAudio: "Grabar audio",
      upgradeRequired: "Actualización Requerida",
      upgradeMessage:
        "Las funciones de audio y OCR están disponibles con Focus Bear Pro. Actualiza para desbloquear estas poderosas herramientas de productividad.",
      ocrUpgradeMessage:
        "El escaneo OCR está disponible con Focus Bear Pro. Actualiza para extraer tareas de fotos y documentos.",
    },
    ocr: {
      modalTitle: "Escanear Papel con OCR",
      reviewModalTitle: "Revisar Tareas Extraídas",
      title: "Escanear Tu Lista de Tareas",
      description:
        "Esta función puede extraer tareas de fotos de listas de tareas escritas a mano o impresas. Puedes seleccionar una imagen de tu biblioteca de fotos o tomar una nueva foto.",
      reviewTitle: "Revisar Tareas Extraídas",
      reviewDescription: "Selecciona las tareas que quieres agregar a tu lista. Puedes editarlas más tarde.",
      selectSource: "Seleccionar Fuente de Foto",
      selectSourceDesc: "Selecciona una opción para elegir una imagen",
      takePhoto: "Cámara",
      chooseFromGallery: "Biblioteca de Fotos",
      capturePhoto: "Continuar",
      processing: "Procesando imagen...",
      uploading: "Subiendo Imagen",
      error: "Error de OCR",
      processingError: "No se pudo procesar la imagen. Por favor, inténtalo de nuevo.",
      noTodosSelected: "No Hay Tareas Seleccionadas",
      selectAtLeastOne: "Por favor selecciona al menos una tarea para agregar.",
      createTodos: "Crear Tareas Seleccionadas",
      completed: "Procesamiento de OCR Completado",
      completedDesc: "¡Tus tareas han sido extraídas con éxito!",
    },
    notStarted: "Por Hacer",
    inProgress: "Haciendo",
    completed: "Hecho",
    current: "Actual",
    noMoreTasks: "No hay más tareas",
    noTasksToShow: "No hay tareas para mostrar\n¡Agrega algunas abajo para empezar!",
    searchTasks: "Buscar tareas",
    noTasksFound: "No se encontraron tareas",
    addATask: "Agregar una tarea",
    taskAdded: "Tarea agregada",
    failedToAddTask: "No se pudo agregar la tarea",
    audio: {
      processing: "Procesando audio...",
      completed: "Procesamiento de audio completo",
      completedDesc: "¡Tus tareas han sido extraídas con éxito!",
      addByAudio: "Agregar por audio",
      record: "Grabar",
      upload: "Subir",
      recorded: "Grabación completada",
      sendOrDiscard: "Toca para enviar o cierra para descartar",
    },
    due: "Vencimiento",
    dueDate: "Fecha de vencimiento",
    exactDate: "Elegir fecha",
    TOP: "TOP - Puntuación de prioridad de tarea",
    TOPPrioritization: "Priorización TOP",
    timeline: "Cronograma (fecha de vencimiento)",
    project: "Proyecto",
    projects: "Proyectos",
    scoreCalculation: "Puntuación",
    addProjects: "Agregar proyectos",
    noExistingProjects: "No hay proyectos existentes",
    createNewProject: "Crear nuevo proyecto",
    searchOrCreateProject: "Buscar o crear proyecto",
    noMatchingProjects: 'No hay proyectos coincidentes. Presiona enter para crear "{search}"',
    addATitle: "Agregar un título",
    addDescription: "Agregar una descripción...",
    addASubtask: "Agregar una subtarea",
    reschedule: "Reprogramar",
    rescheduleTitle: "Reprogramar tarea",
    taskMovedToast: 'Tarea movida a "{status}"',
    sortBy: "Ordenar por",
    filterBy: "Filtrar",
    filterTasksBy: "Filtra tus tareas por",
    listOptions: "Opciones de listado",
    lowToHigh: "Puntuación TOP de baja a alta",
    highToLow: "Puntuación TOP de alta a baja",
    groupBy: "Agrupar por",
    groupedTogether: 'Mostrar las tareas "por hacer" y "haciendo" en el mismo grupo.',
    filterByPerspiration: "Filtrar por esfuerzo",
    spoonsDesc: "Elige tareas basado en tu nivel de energía (teoría de las cucharas). Más cucharas = más energía.",
    learnAboutSpoonTheory: "Aprende sobre la teoría de las cucharas (en inglés)",
    lowSpoons: "Bajo esfuerzo",
    fullSpoons: "Alto esfuerzo",
    perspirationLevel: "Nivel de esfuerzo",
    filterByProject: "Filtrar por proyecto",
    noFilter: "Sin filtro",
    filterByDueDate: "Filtrar por fecha de vencimiento",
    toDosDueDate: "Fecha de Vencimiento",
    overdue: "Vencida",
    thisWeek: "Esta semana",
    nextWeek: "Próxima semana",
    deleteTask: "Eliminar Tarea",
    deleteTaskDesc: "¿Estás seguro de que quieres eliminar esta tarea?",
    deleteSubtask: "Eliminar Subtarea",
    deleteSubtaskDesc: "¿Estás seguro de que quieres eliminar esta subtarea?",
    dueIn: {
      aFewDays: "En dos días",
      nextWeek: "En un semana",
      twoWeeks: "En dos semanas",
      aMonth: "En un mes",
      aYear: "En un año",
      aYearDescription: "(ja, nunca lo haré realmente)",
    },
    outcome: {
      outcome: "Resultado",
      whoCares: "A quién le importa",
      kindOfImportant: "Algo importante",
      bigDeal: "Gran cosa",
      huge: "Enorme",
      mindBlowing: "Alucinante",
    },
    perspiration: {
      perspiration: "Esfuerzo",
      fiveMinuteJob: "Trabajo de 5 minutos",
      fifteenMinutesWork: "Trabajo de 15 minutos",
      halfAnHour: "Media hora",
      anHour: "Una hora",
      halfADay: "Medio día",
      aDay: "Un día",
      aWeek: "Una semana",
    },
  },
  overview: {
    noTasksCta: "No hay tareas todavía. <bold>Agrega una tarea</bold> para empezar.",
    noHabitsCta: "No hay hábitos todavía. <bold>Agrega un hábito</bold> para empezar.",
    morningRoutine: "Rutina Matutina",
    eveningRoutine: "Rutina Nocturna",
    topTasksToday: "Tareas principales",
    focusModeTitle: "Modo de enfoque",
    newFocusSession: "Nueva sesión",
    focusActive: "Sesión activa",
    focusInactive: "Sin sesión activa",
    routineCompletedShort: "✓ Completado",
    routineCompletedMessage: "¡Todos los hábitos completados! ¡Gran trabajo! 🎉",
    routineProgress: "{completed} de {total}",
    deadlinePrefix: "Fecha límite: {date}",
  },
  networkError: {
    ifTheProblemPersists:
      "Si el problema persiste, por favor contacta directamente con soporte en\nsupport@focusbear.io",
    noNetworkAlertTitle: "Internet desconectado",
    retrying: "Intentando de nuevo",

    connectionError: "Conexión de internet inestable",
    connectionErrorMessage: "Por favor, verifica tu conexión",
    connectionErrorLongMessage:
      "Estamos teniendo problemas para conectar con el servidor. $t(networkError.connectionErrorMessage). $t(networkError.ifTheProblemPersists)",

    apiError: "Algo salió mal",
    apiErrorMessage: "Por favor, inténtalo de nuevo más tarde",
    apiErrorLongMessage:
      "Hubo un problema al procesar tu solicitud. $t(networkError.apiErrorMessage). $t(networkError.ifTheProblemPersists)",

    internalError: "Error interno",
    internalErrorMessage: "Algo salió mal :(",
    internalErrorLongMessage: "Lo sentimos, algo salió muy mal. $t(networkError.ifTheProblemPersists)",
  },
  manageAllowedApps: {
    searchPlaceholder: "Buscar aplicaciones instaladas",
  },
  permissionWarning: {
    usageAccessTitle: "Necesitamos permiso de Acceso de Uso para ayudar a bloquear las distracciones",
    deviceUsagedescription:
      'Para permitirnos bloquear las aplicaciones que te distraen cuando estás concentrado/realizando tus hábitos, necesitamos permisos de "acceso de uso" para poder ver qué aplicación estás utilizando',
    overlayTitle: "Necesitamos permiso de superposición para ayudar a bloquear distracciones",
    overlayDescription:
      'Para permitirnos bloquear las aplicaciones que te distraen cuando estás concentrado/realizando tus hábitos, necesitamos permisos de "superposición" para que podamos ver qué aplicación está utilizando y mostrar alerta de distracción para aplicaciones no permitidas',
    privacyNoteTitle: "Nota de Privacidad",
    privacyNoteDesc:
      "No registramos qué aplicaciones o sitios web utilizas. Sólo lo utilizamos para bloquear en tiempo real.",
    grantAccess: "Permitir",
  },
  addNoteModule: {
    addNote: "Agregar Nota",
    placeholder: "Agregar nota aquí...",
    saveNote: "Guardar Nota",
    automaticallySave: "Tu nota se guardará automáticamente",
  },
  onboarding: {
    nextStep: {
      upNext: "Próximo: {step}",
      usagePermission: "Permiso de uso",
      overlayPermission: "Permiso de superposición",
      focusSession: "Sesión de enfoque",
      microBreak: "Micro descanso",
      allDone: "Listo",
      screenTimePermission: "Permiso de tiempo de pantalla",
    },
    wantToPersonalise: "¿Quieres personalizar?",
    wantToPersonaliseDescription: "Configura tus propios hábitos en lugar de usar los predeterminados.",
    personalise: "Personalizar (5 minutos)",
    onboarding: "Incorporación",
    letsDoIt: "¡Vamos!",
    replay: "Repetir",
    instructionVideo: "Vídeo Instructivo",
    welcomeAboard: "¡Bienvenido/a a bordo!",
    lookingForwardToHelp: "Es hora de activar hábitos saludables y trabajo profundo.",
    getStarted: "Ponte en marcha",
    allDone: "¡Listo!",
    habitPackSelectionNotice:
      "Ahora vamos a elegir algunos hábitos para tu rutina de la mañana y de la noche.\n\n\n<bold>¡No te estreses!</bold> Siempre podrás ajustarlos más adelante.",
    installDesktopApp: "Instalar la app de escritorio",
    installDesktopAppDesc:
      "Focus Bear también funciona en Mac y Windows. Si tienes computadora, descarga la app desde <bold>focusbear.io</bold> para sincronizar tus sesiones de enfoque y hábitos.",
    cutoffTimeWarning:
      "La hora de abandonar la tecnología debe ser después de la hora de terminar el trabajo ({time}).",
    howFocusBearWork: "Cómo funciona Focus Bear",
    habitAndRoutine: "Hábitos y Rutinas",
    habitAndRoutineDescription: "<bold>Alcanza tus objetivos</bold> con hábitos que activan tu mente y cuerpo",
    distractionBlocking: "Bloqueo de distracciones",
    distractionBlockingDescription:
      "Focus Bear puede bloquear <bold>aplicaciones</bold> y <bold>sitios web</bold> para ayudarte a hacer tus tareas",
    todoList: "Lista de tareas",
    todoListDescription:
      "<bold>Planifica</bold>, <bold>prioriza</bold> y <bold>mantente en camino</bold> con la lista de tareas de Focus Bear",
    andMuchMore: "Y eso no es todo",
    andMuchMorePoints: [
      "También funciona en tu computadora",
      "Técnica Pomodoro",
      "Hábitos avanzados con listas de verificación y videos",
      "Rutinas de mañana y noche",
      "Recordatorios de descanso",
      "Divertidos emojis de osos",
    ],
    andMuchMoreDescription: "<bold>y mucho más...</bold>",
    end: "FIN",
    habitAI: "Organiza tus tareas usando IA",
    habitAIDescription: "Focus Bear puede ayudarte a <bold>organizar tus tareas</bold> usando Inteligencia Artifical",
    learnAboutFeatures: "Acerca de las características",
    setupHabitsTitle: "Configura hábitos para ayudarte a concentrarte mejor",
    setupHabitsCta: "Configurar hábitos",
    habitsPirateCopy: "Los buenos hábitos mantienen tu concentración afilada durante todo el día.",
    habitImportPirateCopy: "Usaré mi magia marina para subir tus hábitos a bordo.",
    habits: {
      sleep: "Sueño",
      meditate: "Meditar",
      exercise: "Ejercicio",
    },
    habitList: {
      nayLabel: "No – Dame algunas ideas, capitán",
      ayeLabel: "Sí – Ya tengo algunos hábitos",
    },
  },
  goals: {
    habitImport: {
      title: "Importar Hábitos",
      description: "Importa tus hábitos desde una imagen o grabando tu voz",
      importFromImage: "Importar desde Imagen",
      recordVoice: "Grabar Voz",
      stopRecording: "Detener Grabación",
      selectSource: "Seleccionar Fuente",
      selectImageSource: "Elige cómo importar tus hábitos",
      takePhoto: "Tomar Foto",
      chooseFromGallery: "Elegir de la Galería",
      completed: "¡Hábitos importados!",
      completedDesc: "Tus hábitos se han importado exitosamente",
      error: "Error de Importación",
      processingError: "No se pudo procesar tu importación. Por favor, inténtalo de nuevo.",
      recordingError: "No se pudo grabar el audio. Por favor, inténtalo de nuevo.",
      processing: "Procesando tu importación...",
      cancelRecording: "Cancelar Grabación",
    },
    addHabitList: {
      title: "Añade tu lista de hábitos",
      description:
        "Sube la lista de hábitos o cuéntanos tus objetivos y nuestra IA los añadirá en la app de Focus Bear.",
      uploadScreenshot: "Subir una captura de pantalla o foto",
      recordVoiceNote: "Grabar una nota de voz",
      typeThemIn: "Escribirlos",
      or: "O",
      haveHabitListQuestion: "¿Tienes tu propia lista de hábitos para importar?",
      importHabits: "Importar hábitos",
      confirmScreenshotUpload: "Confirmar imagen",
      confirmScreenshotUploadDesc: "¿Es esta la imagen que deseas subir?",
    },
    boostProductivity: "🚀 Aumentar la productividad",
    boostProductivityDescription: "(trabajo, estudio, tareas)",
    improveMentalHealth: "🧘 Mejorar el bienestar mental",
    improveMentalHealthDescription: "(estrés, sueño)",
    improvePhysicalHealth: "🏋️‍♂️ Enfoque en salud y físico",
    improvePhysicalHealthDescription: "(ejercicio, nutrición)",
    manageTask: "🏡 Gestionar tareas del hogar",
    manageTaskDescription: "(limpieza, tareas domésticas)",
    otherSpecify: "✏️ Otros",
    otherSpecifyDescription: "(especificar: __)",
    strengthenRelationShip: "❤️ Fortalecer las relaciones",
    strengthenRelationShipDescription: "(familia, amigos)",
    achievement_placeholder: "Dinos tu objetivo",
    enableFeatures: "¿Qué característica te gustaría activar?",
    doOurBest: "Estamos aquí para ayudarte a alcanzar tus objetivos. ¿Qué funciones de Focus Bear te gustaría activar?",
    achievementWithFocusBearDesc: "¿Cuáles son tus objetivos principales?",
    achievementWithFocusBearDescTooltip: "Te sugeriremos hábitos que te ayudarán a alcanzar tus objetivos",
    help_me_develop: "Construir hábitos saludables",
    help_me_stay: "Permanecer concentrado/a en el trabajo",
    help_me_develop_tooltip:
      "Focus Bear puede guiarte a través de hábitos saludables (meditación, ejercicio, journaling, etc) en tu rutina matutina y nocturna.",
    help_me_stay_focused_tooltip:
      "Focus Bear bloqueará las distracciones mientras trabajas para que puedas trabajar al máximo.",
    blockComputerTitle: "¿Bloquear distracciones en tu computadora?",
    blockComputerQuestion: "¿Quieres bloquear distracciones en tu computadora también?",
    organize_tasks_using_ai: "Organizar tus tareas usando AI",
    organize_tasks_using_ai_tooltip: "Focus Bear puede organizar tus tareas usando AI",
    what_are_you_hoping_focus_bear_can_do: "¿Qué esperas que pueda hacer Focus Bear?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Dinos qué esperas que pueda hacer Focus Bear",
    explore_the_app_first: "Explorar la app primero",
    setup_habits: "Configurar hábitos",
    setup_habits_question: "¿Quieres configurar tus hábitos ahora (toma ~3 minutos) o explorar la app primero?",
    featureRequestReceived: "¡Gracias por tus comentarios! Tus ideas nos ayudan a mejorar Focus Bear.",
  },
  goalsSteps: {
    goals: "Objetivos",
    routine: "Rutina",
    timing: "Horario",
  },
  habit: {
    habitPack: "Elige tus hábitos",
    autostart: "Inicio automático",
    habitAutoStart: "Comienza en {countdown}",
    habitSkipForToday: "Hábito omitido por hoy",
  },
  setupTime: {
    fineIfLaterOrSooner:
      "Está bien si te despiertas un poco más tarde o más temprano que esto, solo pon una hora aproximada",
    morningRitualStart: "Tu ritual matutino comenzará entonces",
    setStartupTime: "Elige tu Hora de Inicio",
    chooseTheAbsoluteEarliest: "¿A qué hora te despiertas?",
    setShutdownTime: "¿Cuándo terminas de trabajar/estudiar?",
    focusBearWillTakeOver: "Focus Bear pausará el bloqueo para que puedas relajarte.",
    subDescriptionFocusBearWillTakeOver:
      "¡La rutina nocturna comienza a las {sleep_time}\n(incluye un margen de 30 minutos)!",
    focusBearWillTakeOverToolTip:
      "En la siguiente pantalla, elegirás a qué hora quieres irte a dormir. Focus Bear volverá a cortar las distracciones antes de que te acuestes para que duermas bien.",
    setSleepTime: "¿A qué hora quieres ir a dormir?",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}: Tiempo libre",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}: Ritual nocturno y luego dormir",
    subDescriptionTooltipText: "{sleep_time} - {startup_time}: Toque de queda del teléfono (hora de dormir)",
    distractionBlockDesc: "Distracciones bloqueadas - relajarse para dormir",
    // Simplified schedule
    techCurfewQuestion: "¿Quieres tener un toque de queda tecnológico por la noche para dormir mejor?",
    techCurfewTooltip:
      "Focus Bear puede bloquear aplicaciones distractoras en tu teléfono por la noche para que duermas mejor",
    bedtimeForScreens: "¿Hora de dormir para las pantallas?",
    bedtimeForScreensSubtitle: "¿Ponemos tu teléfono a dormir temprano para que puedas descansar?",
    noThanks: "No, gracias",
    yesPhoneWrecksSleep: "¡Sí - mi teléfono arruina mi sueño!",
    whatTimeGetOffTech: "¿A qué hora quieres dejar la tecnología por la noche?",
  },
  blockList: {
    title: "Haz un uso seguro de tu teléfono durante las sesiones de hábitos/concentración",
    subTitleAndroidBlockList:
      "Elige aplicaciones que te distraigan para bloquearlas mientras haces hábitos o te concentras",
    buttonAndroidBlockList: "Elegir distracciones",
    subTitleIos: "Elige aplicaciones que te distraigan para bloquearlas mientras haces hábitos o te concentras",
    buttonIos: "Elegir distracciones",
  },
  editFriction: {
    frictionTooltipDescription:
      'Eres una persona muy disciplinada, por supuesto, pero ocasionalmente puedes sentirte tentado a saltarte tus hábitos o dejar de bloquear distracciones por capricho. Puedes configurar una "fricción" adicional para ayudar a frenar esos pensamientos impulsivos. Si habilita el modo de alta fricción, le pedirá que espere unos segundos antes de dejar de bloquear las distracciones.',
    frictionForSkippingHabits: "Fricción por saltar hábitos",
    reallyEasy: "Muy fácil: quiero poder saltar hábitos/descansos en un instante.",
    makeItHardToSkip:
      "Difícil de saltar - de lo contrario acabaré saltando hábitos + descansos la mayoría de las veces.",
    appBlocking: "Bloquear Distracciones",
    blockDuringDaytime: "Bloquear las aplicaciones distractoras durante la jornada laboral",
    reallyEasyDescription: "Podrás detener inmediatamente las distracciones bloqueadoras.",
    makeItHardToSkipDescription:
      "Para evitar apagar bloques impulsivamente, Focus Bear puede mostrar un temporizador de cuenta regresiva breve para alentarlo a reconsiderar si debe acceder a aplicaciones que lo distraen.",
  },
  strictness: {
    setPassword: "Establecer una contraseña",
    setPasswordDescription:
      "Si te cuesta mantener tus hábitos, pide a tu pareja o compañero de piso que establezca una contraseña. No podrás saltarte los hábitos sin la contraseña.",
    enterConfirmPasswordHint: "Confirmar contraseña",
    askForPassword: "Pedir contraseña",
    whenRequirePasswordDescription: "¿Cuándo exigir una contraseña?",
    changingSettings: "Cambiando la configuración",
    postponingMorningRoutine: "Posponer/saltar rutina matutina",
    postponingEveningRoutine: "Posponer/saltar rutina nocturna",
    postponingAfterCuttOffTime: "Posponer/saltar la rutina nocturna después de la hora límite",
    usingPhoneLateNight: "Usar el teléfono a altas horas de la noche",
    relaxFocusMode: "Permitir usar modo de enfoque relajado",
    suggestion: "Sugerencia",
  },
  subscription: {
    upgrade: "Actualizar",
    restorePurchases: "Restaurar compras",
    restorePurchasesError: "No se puede restaurar la compra debido a que el recibo está ausente",
    restorePurchasesError2: "Algo salió mal. Por favor, inténtalo de nuevo más tarde.",
    personalizedHabit: "Personalizar rutinas de hábitos",
    productivityBoosting: "Descansos para aumentar la productividad",
    customizedFocus: "Modos de enfoque personalizables",
    automaticGoals: "Seguimiento automático de objetivos",
    cancel: "Cancelar renovación automática",
    subscription: "Suscripción",
    trialActive:
      "Tu prueba dura {day} día(s) más. No te preocupes, no pagarás cuando termine la prueba y no requiere tarjeta de crédito por adelantado",
    trialActiveShort: "Prueba: {day} días restantes",
    getSubscriptionPlan: "Adquiere nuestro plan de suscripción para usar la app y desbloquear todas las funciones",
    subscriptionPlanPrice: "Continuar por sólo <bold>{amount}</bold>/mes",
    benefit: "Plan mensual incluye",
    doesSubscriptionAutoRenew: "¿Mi suscripción se renueva automáticamente?",
    subscriptionAutoRenew:
      "Esta suscripción mensual se renueva automáticamente a menos que se desactive al menos 24 horas antes de que finalice el periodo actual. Tu cuenta se cobrará por renovación dentro de las 24 horas anteriores al final del periodo actual al precio de la suscripción ({amount}). Puedes administrar o cancelar tu suscripción en cualquier momento a través de la configuración de tu cuenta en la tienda.",
    thankYouForSubscribing:
      "Gracias por suscribirte, ya puedes usar todas las funciones de Focus Bear\n\nTu suscripción expirará en <bold>{day}</bold> días",
    thankYouForSubscribingGuestMode:
      "¡Gracias por suscribirte! Por favor, regístrate para continuar usando todas las funciones de Focus Bear. Una vez que te registres, restaura tu suscripción en esta pantalla.",
    thanksForSubscribingShort: "¡Gracias por tu apoyo 🎉!",
  },
  editHabit: {
    okay: "Okay",
    error: "Error",
    unableToSaveSettings:
      "Algo salió mal. Lo sentimos mucho. Nuestro equipo de ingeniería ha sido notificado y lo arreglaremos lo antes posible. Si no recibes noticias nuestras en 24 horas, envía un correo electrónico a support@focusbear.io y nos pondremos en contacto contigo.",
    goingBack:
      "Estás a punto de volver al menú Configuración. Si has hecho algún cambio, toca el botón 'Guardar hábitos'.",
    continue: "Continuar",
    cancel: "Cancelar",
    warning: "Advertencia",
    restartingIn: "Reiniciando Focus Bear en {seconds}...",
    settingsSavedSuccessfully: "Hábito guardado con éxito",
  },
  shareLogs: {
    pleaseWriteFeedback: "Por favor, escribe tu sugerencia",
    enterFeedBack: "Ingresa tu sugerencia",
    logsShared: "¡Gracias! Tu informe de comentarios se ha compartido con el equipo de soporte.",
    submitAnother: "Enviar otro",
    errorUploading:
      "Hubo un error al subir los registros. Asegúrate de tener una conexión a internet estable e inténtalo de nuevo. $t(networkError.ifTheProblemPersists)",
    errorZipCreation:
      "Hubo un problema al procesar los archivos. Por favor, inténtalo de nuevo. $t(networkError.ifTheProblemPersists)",
  },
  impact_reporting: {
    title: "Analiza tu Sueño y Estado de Ánimo",
    description:
      "¿Te gustaría hacer un seguimiento de tu sueño y estado de ánimo para ver si Focus Bear está haciendo una diferencia positiva en tu vida? Esto también nos ayudaría a nosotros, ya que nos proporcionaría datos (anónimos) sobre el impacto de nuestra aplicación.",
    subtitle: "Datos que recopilaremos",
    bulletPoints:
      "● Horas de sueño\n● Tu estado de ánimo y nivel de energía\n● Qué tan productivo/a te sientes al final del día",
    okSure: "Ok, está bien",
    noThanks: "No, gracias",
  },
  privacyModal: {
    heading: "Privacidad y Seguridad",
    notShareData: "Nos tomamos muy en serio tu privacidad y seguridad. Nunca compartiremos tus datos.",
    doNotLog: "• No registramos los sitios web o aplicaciones que visitas.",
    chooseToBlock:
      "• Sin embargo, si deseas bloquear aplicaciones que te distraen, necesitamos almacenar los nombres de esas aplicaciones en nuestra base de datos para que tu configuración se sincronice en todos tus dispositivos.",
    dataEncrypted: "• Tus datos están encriptados y no permitimos que nadie más los vea.",
    moreDetails:
      "Para más información, consulta nuestra <bold>política de privacidad</bold> o envía un correo electrónico a support@focusbear.io",
    accept: "Aceptar",
  },
  pushNotiPermission: {
    title: "Permitir notificaciones",
    description:
      "Te enviaremos notificaciones cuando llegue el momento de hacer tus hábitos. Puedes desactivarlas en cualquier momento.",
  },
  distractionBlockingReason: {
    notLoggedIn: "Bloqueo desactivado: No has iniciado sesión",
    postponeActivated: "Bloqueo desactivado: Posponer activado",
    focusModeActivated: "Bloqueo activado: Modo de enfoque activado",
    firstDay: "Bloqueo desactivado: Primer día - rutina aún no activada",
    otherReason: "Bloqueo activado: Es hora de hacer tu rutina",
    daytimeBlockingEnabled: "Bloqueo activado: rutina matutina completa pero bloqueo durante el día activado",
    blockedBySchedule: "Bloqueo activado: Los horarios de bloqueo están activos",
    defaultCase: "Bloqueo desactivado: Bloqueo de distracciones desactivado",
    withinCutoffTimeAndShutdownTime: "Bloqueo desactivado: tienes tiempo libre hasta las {cutoff_time}",
    permissionNotGranted: "Bloqueo desactivado: Permisos no concedidos (toca aquí para corregir)",
    afterCutoffTime: "Bloqueo activado: Es hora de relajarte antes de dormir",
    afterCutoffTimeAndEveningRoutineFinished: "Bloqueo activado: Es hora de dormir",
    detailedCutOffSleepTimeBlockingReason:
      "Las distracciones están bloqueadas a partir de {cutoff_time} para que puedas dormir. Tu rutina matutina está configurada para comenzar a las {startup_time}. Cuando terminas tu rutina matutina, el bloqueo se detiene.",
  },
  blocking: {
    blockingType: "Tipo de Bloqueo",
    allowList: "Lista de Permitidos",
    blockList: "Lista de Bloqueo",
    allowListDescription:
      "Elige aplicaciones que estén permitidas mientras haces tus hábitos o te concentras. Todo lo demás estará bloqueado.",
    blockListDescription:
      "Elige las aplicaciones que te distraen y que deben bloquearse mientras haces tus hábitos o te concentras. Todo lo demás estará permitido.",
    appBlockList: "Lista de Apps Bloqueadas",
    appAllowList: "Lista de Apps Permitidas",
    blockAtLeastOne: "Por favor, elige al menos una app para evitar distraerte",
    socialFilterTitle: "Social",
    newsFilterTitle: "Noticias",
    gamesFilterTitle: "Juegos",
    miscFilterTitle: "Varios",
    recommendedSectionListTitle: "Apps recomendadas",
    otherSectionListTitle: "Todas las apps",
    freeAppLimitTitle: "Lo siento, máximo 5 apps bloqueadas en la versión gratuita",
    freeAppLimitDesc:
      "En la versión gratuita, solo puedes bloquear 5 apps. Al pagar por Focus Bear Pro, apoyas nuestro desarrollo y nos ayudas a crear nuevas funciones que mejoran tu productividad 🙂",
    Success: "Guardado",
    saveSuccess: "Cambios guardados correctamente",
  },
  permissionExplanation: {
    distractionGetBlockedWhen: "Las distracciones se bloquean cuando:",
    title: "Establecer permisos para el bloqueo de distracciones",
    description: "Focus Bear puede bloquear distracciones mientras trabajas, duermes y haces tus hábitos",
    workTask: "• estás trabajando/estudiando para conseguir hacerlo todo ⚒️",
    routineTask: "• haces tu rutina matutina y nocturna para que hagas tus hábitos 🧘",
    sleepTask: "• estás durmiendo para que realmente duermas😴",
    toggleOption: "Por defecto, puedes desactivar el bloqueo de distracciones en cualquier momento.",
    friendOption: "(Pero también puedes elegir que un amigo te ponga una contraseña para hacerlo más difícil)",
    necessaryPermission:
      "Permiso de uso: Para detectar si abres una app que te distrae\n\nPermiso de superposición: Es lo que hace el bloqueo de distracción",
  },
  blockingPermissionIntro: {
    holdOnTitle: "¡Espera un momento!",
    captainBearMessage: "Arr... si quieres concentrarte mejor, primero tenemos que poner tus hábitos en orden.",
    introTitle: "Vamos a configurar el bloqueo de distracciones para que pueda ayudarte a mantenerte enfocado.",
    introPrimary: "Configurar bloqueo",
    introBubble: "Así es más o menos\ncomo se verá.",
    howItWorksTitle:
      "Durante los periodos de enfoque que programes, bloquearé suavemente las apps que te sacan de rumbo.",
    howItWorksBody: "Tú sigues al mando: puedes pausar o ajustar el bloqueo en cualquier momento.",
    howItWorksPrimary: "Me parece bien",
    howItWorksBubble: 'A continuación solo tendrás que tocar "Continuar".',
    screenTimeCongratsTitle: "Muy bien, ya has completado este paso de configuración.",
    whatYouNeedTitle: "Para hacerlo, necesito algunos permisos en tu teléfono.",
    whatYouNeedPrimary: "Continuar",
    whatYouNeedBubble: "Por ejemplo, bloquear apps que distraen mientras duermes.",
    scheduleCreatedTitle: "Perfecto. Ahora tienes una rutina bien definida.",
    scheduleCreatedPrimary: "Seguir",
    scheduleCreatedBubble: "Podrás editar estos ajustes más adelante desde la app.",
    finishTitle: "Listo, todo está configurado para que podamos mantenernos en el buen camino juntos.",
    finishPrimary: "Finalizar",
    androidIntroTitle: "Vamos a configurar el bloqueo de distracciones para que pueda ayudarte a mantenerte enfocado.",
    androidUsageTitle:
      'Primero necesito ver qué apps utilizas. Para eso hay que activar el permiso de "Acceso de uso".',
    androidUsagePrimary: "Abrir Ajustes",
    androidUsageBubble: "Intenta localizar este interruptor en la pantalla de ajustes.",
    androidOverlayTitle:
      'Uso el permiso de "Mostrar sobre otras apps" para poder aparecer con una ventana emergente como esta.',
    androidOverlayPrimary: "Configurar ahora",
    androidOverlayBubble: "Voy a solicitar el permiso necesario para poder avisarte a tiempo.",
    androidPermissionVisualTitle: "Esta es la pinta que tiene esa pantalla de permisos.",
    androidPermissionVisualPrimary: "Activar acceso",
    androidPermissionVisualBubble: "Vamos a\nbuscarla juntos.",
    androidProceedPrimary: "Continuar",
    androidScheduleSetupTitle:
      "Genial. Ahora configura un horario de bloqueo automático para que pueda avisarte en momentos concretos.",
    androidScheduleSetupPrimary: "Configurar horario",
    androidScheduleSetupBubble: "Por ejemplo, bloquear apps que distraen mientras duermes.",
  },
  grantPermission: {
    title: "Necesitaremos permiso para bloquear aplicaciones",
    description: "No te preocupes, puedes pausar el bloqueo de distracciones en cualquier momento",
    needHelp: "¿Necesitas ayuda?",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Mantener el bloqueo activado",
    description:
      "Permitir que Focus Bear siga bloqueando aplicaciones en segundo plano eliminando la optimización de la batería.",
    warning: "Esto consumirá un poco más de batería (pero no mucha).",
    keepFocusBearPoweredUp: "Mantener Focus Bear conectado.",
  },
  launcher: {
    title: "Apps",
    morning: "🔆 Mañana",
    evening: "🌙 Noche",
    play: "🥳 Jugar",
    work: "🔨 Trabajar",
    setAppLabel: "Buscar una categoría para {appName}",
    search: "Buscar apps",
    noAppsFound: "No se encontraron apps",
    setAsDefaultLauncher: "Iniciador por defecto",
    restricted: "Restringido",
    restrictedMessage: "{appName} está siendo restringido/a, por favor concéntrate en tu rutina",
    stopBlocking: "Dejar de bloquear",
    openAppMenuToolTip: "Toca aquí para abrir el menú de la aplicación",
  },
  DND: {
    duringFocusSessions: "Durante las Sesiones de Enfoque",
    duringHabits: "Durante Hábitos & Sueño",
  },
  bearsona: {
    explanation: "¿Qué tipo de oso quieres que te motive? Focus Bear cambiará su tono según lo que elijas.",
    title: "Bearsona",
    choose: "Elige una Bearsona",
    useCustomLanguage: "Usar {customLanguage}",
    useCustomLanguageConfirmation: "¿Usar {customLanguage} como tu idioma?",
    useCustomLanguageConfirmationDesc: "Advertencia: esto es divertido pero puede ser un poco confuso",
    confirmUseCustomLanguage: "Hablar en español",
    cancelUseCustomLanguage: "Cambiar de opinión",
    name: {
      default: "OG Bear",
      pirate: "Captain Bear",
      focus: "Focus Bear",
      jester: "Jester Bear",
      sassy: "Sassy Bear",
      cheerleader: "Cheerleader Bear",
    },
    description: {
      default: "Tu amigable oso asistente",
      pirate: "¡Yarrr! Capitán Bear a tu servicio",
      focus: "Concentrarme es mi superpoder",
      jester: "Jester Bear está listo para jugar",
      sassy: "El Oso Sassy está aquí para arrasar.",
      cheerleader: "¡El Oso Animador está apoyándote!",
    },
  },
  blockUrl: {
    addSomeSuggestedUrls:
      "Hemos añadido algunas URLs sugeridas aquí que la mayoría de la gente encuentra distractoras. Elimínalas si es necesario",
    unblockableUrlTitle: "No se puede bloquear la URL",
    unblockableUrlMessage: "Esta URL no se puede bloquear. Por favor, ingresa una URL diferente para bloquear.",
    freemiumLimit: "Solo puedes bloquear 3 URLs en la versión gratuita.",
    freemiumLimitDescription: "Actualiza a la versión Pro para bloquear URLs ilimitadas.",
    title: "Bloquear sitios web",
    description: "¿En qué sitios pierdes tiempo?",
    inputPlaceholder: "Ingresa la URL para bloquear...",
    urlExistsTitle: "La URL ya existe",
    urlExistsMessage: "Por favor, ingresa una URL diferente para bloquear.",
    invalidUrlTitle: "URL no válida",
    invalidUrlMessage: "Por favor, ingresa una URL válida para bloquear.",
    saveSuccess: "Las URLs bloqueadas se guardaron correctamente.",
    saveError: "Error al guardar las URLs bloqueadas. Por favor, inténtalo de nuevo.",
  },
  accessibility: {
    title: "Permiso de accesibilidad",
    howToEnableAccessibility: "Cómo habilitar el permiso de accesibilidad",
    enableAccessibility: "Activar accesibilidad",
    permissionRequired: "Permiso de accesibilidad requerido",
    permissionDescription:
      "Los sitios web pueden distraer tanto como las aplicaciones. Focus Bear también bloquea sitios web si activas el permiso de accesibilidad. Tu teléfono mostrará un mensaje de advertencia; ¡es normal!",
    whatWeDo: "Esto es lo que hacemos:",
    checkSites: "Revisar tu lista de bloqueo",
    checkSitesDescription: "Verificamos si el sitio está en tu lista.",
    zeroDataTracked: "Eso es todo. Cero rastreo, cero datos almacenados.",
  },
  passwordRules: {
    passwordRequirements: "La contraseña debe contener al menos un número, una letra mayúscula y un carácter especial",
    minLength: "Min. 8 caracteres",
    includeNumbers: "Incluir números",
    includeLowerCase: "Incluir minúsculas",
    includeUpperCase: "Incluir mayúsculas",
    includeSpecialChars: "Incluir caracteres especiales",
  },
  permissions: {
    privacyFirst: "Tomamos tu privacidad muy enserio",
    notTracked: "Focus Bear <bold>NO</bold> rastrea:",
    anythingType: "Cualquier cosa que escribas",
    anythingTypeDescription: "Contraseñas, mensajes, emails",
    browserHistory: "Historial de navegación",
    browserHistoryDescription: "Nosotros nunca vemos o guardamos los sitios web que visitas",
    helpStayFocused: "¡Estamos aqui para ayudarte a permanecer concentrado!",
    revokeHealthPermission: "Revocar Permiso de Salud",
    revokeHealthPermissionDescription:
      "Lo sentimos, debido a las limitaciones de Apple, no podemos revocar el permiso de salud. Si deseas revocarlo, por favor ve a la app `Salud` y revócalo desde allí.",
    healthGroup: "Salud y Sueño",
    healthGroupDescription:
      "Focus Bear puede rastrear tu salud y datos de sueño para ayudarte a mejorar tu salud y sueño.",
    areYouSure: "¿Estás seguro de querer revocar este permiso?",
    revokePermissionDescription: "Esto revocará el permiso a la app.",
    experimentalGroup: "Experimental",
    experimentalDescription:
      "Configura Focus Bear como tu app de inicio/iniciador por defecto para que veas tus hábitos directamente cuando abras tu teléfono. También hace que las apps distractoras sean menos obvias.",
    blockingAppsGroup: "Para bloquear apps",
    routineUpdatesGroup: "Para actualizaciones de rutinas",
    routineUpdatesGroupDescription:
      "Focus Bear te enviará notificaciones cuando sea hora de tu rutina matutina o nocturna",
    urlBlockingGroup: "Para bloquear URLs",
    urlBlockingGroupDescription:
      "Si quieres bloquear sitios web, Focus Bear necesita permisos de accesibilidad para detectar cuando visitas un sitio web distractor y redirigirte lejos de él.",
  },
  breathingExercise: {
    title: "Breathing Exercise",
    description: "Un momento de atención plena antes de lanzarte a esta app llena de distracciones.",
    dontWantToOpen: "No quiero abrir {appName}",
    wantToOpen: "Continuar a {appName}",
    motivational: "¡Ups! ¿Estás seguro de querer abrir {appName}?",
  },
  byPassTimePicker: {
    title: "Pausar bloqueo suave para abrir {app}",
    duration: "{count} minutos",
    intention: "¿Qué quieres lograr en {app}?",
    intentionInfo: "Es fácil perder el hilo al abrir una aplicación distractora. Te recordaré tu objetivo.",
    intentionRequiredError: "Por favor, introduce tu intención antes de continuar.",
  },
  loading: {
    loading: "Cargando",
    breathingExercise:
      "Mientras esperas, intenta un ejercicio de box breathing. Respira 3 segundos, retén 3, respira 3 segundos, retén 3.",
    loadingHabit: "Cargando biblioteca de hábitos",
    pleaseWaitLoadHabit:
      "Recomendaremos hábitos basados en lo que te importa. Basado en tus objetivos, sugeriremos hábitos útiles de nuestra biblioteca curada para que comiences.",
  },
  stats: {
    title: "Estadísticas",
    tabs: {
      screentime: "Tiempo de uso",
      otherStats: "Otras estadísticas",
    },
  },
  appUsage: {
    noAppsDetected: "No se encontraron apps",
    seeMore: "Ver más",
    close: "Cerrar",
    usage: "Estadísticas",
    title: "Estadísticas",
    longTitle: "Estadísticas de Apps y Salud",
    lowQualityAppDetected: "App de baja calidad detectada. ¿Quieres agregar esta app a tu lista de bloqueo?",
    yes: "Sí",
    no: "No",
    ignore: "Ignorar",
    dailyAppUsage: "Tiempo de uso de apps",
    totalTimeUsed: "Tiempo total usado",
    doingGreat: "¡Estás haciendo un gran trabajo! ¡Sigue así!",
    todayBlockCount: "Contador de bloqueos de hoy",
    focusBearUsage: "Uso de Focus Bear",
    topBlockedApps: "Apps más bloqueadas",
    blockedAppsUsage: "Uso de apps bloqueadas",
    timeBlocked: "Veces bloqueadas",
    timeSpent: "Tiempo invertido",
    lastUsed: "Último uso",
    noAppsBlocked: "No hay apps bloqueadas",
    noData: "¡Buen trabajo! Aún no has usado ninguna app",
    noPermission:
      "Podemos mostrar estadísticas geniales de tiempo de pantalla si nos das permisos de Uso de Aplicaciones",
    grantPermission: "Conceder Permiso de Uso",
    overLimit: "¡Ups! Estás sobre tu límite",
    lowQualityScreenTime: "Tiempo no útil",
    highQualityScreenTime: "Tiempo útil",
    timeUsedAfterCutoff:
      "Usaste tu teléfono por <bold>{duration}</bold> durante tu ventana de sueño la noche pasada.\n\n¿Quieres aumentar tu nivel de fricción para ayudarte a no usar el teléfono mientras duermes?",
    timeUsedAfterCutoffTitle: "Tiempo usado después de la ventana de sueño",
    dontShowAgain: "No volver a mostrar este mensaje",
    howDistractingIsThisApp: "¿Qué tan distractor es esta app?",
    dragToEdit: "Arrastra para editar",
    save: "Guardar",
    learnMore: "Aprender más",
    qualityLabel: {
      extremelyDistracting: "Extremadamente Distractora",
      veryDistracting: "Muy Distractora",
      slightlyDistracting: "Ligeramente Distractora",
      neutral: "Neutral",
      slightlyProductive: "Ligeramente Productiva",
      productive: "Productiva",
      veryProductive: "Muy Productiva",
    },
    qualityDescription: {
      veryDistracting:
        "Las apps que constantemente exigen atención, a menudo desviándote de tus tareas, se consideran Muy Distractoras.",
      distracting:
        "Las apps que pueden alejarte fácilmente del trabajo importante y consumir mucho tiempo se consideran Distractoras.",
      slightlyDistracting:
        "Las apps que ocasionalmente pueden interrumpir tu concentración pero pueden manejarse con algo de disciplina se consideran Ligeramente Distractoras.",
      neutral:
        "Las apps que sirven propósitos prácticos sin afectar significativamente tu productividad se consideran Neutrales.",
      slightlyProductive:
        "Las apps que contribuyen a tu bienestar, aprendizaje o crecimiento personal se consideran Ligeramente Productivas.",
      productive:
        "Las apps que te ayudan a completar tareas, mantenerte organizado y trabajar eficientemente se consideran Productivas.",
      veryProductive:
        "Las apps que son herramientas esenciales para tu trabajo, salud o funciones diarias críticas se consideran Muy Productivas.",
    },
    loadingMessage: {
      harvesting: "Recopilando datos de uso",
      removingGremlins: "Eliminando gremlins estadísticos",
      crunchingFormulas: "Procesando fórmulas de enfoque",
      assemblingMetrics: "Ensamblando métricas de progreso",
    },
  },
  healthMetrics: {
    title: "Estadísticas de Salud",
    tapToView: "Toca para ver tus métricas de salud",
    tapToCollapse: "Toca para colapsar",
    healthPermissionsRequired: "Permisos de Salud Requeridos",
    tapToGrantPermissions: "Toca para conceder permisos de salud para ver tus métricas",
    sleep: "Sueño",
    activeMinutes: "Minutos Activos",
    steps: "Pasos",
    loadingHealthData: "Cargando datos de salud...",
    error: "Error: {error}",
    physicalActivityPermissionsRequired: "Permisos de Actividad Física Requeridos",
    tapToGrantPhysicalActivityPermissions: "Toca para conceder permisos de actividad física para ver tus métricas",
  },
  participantCode: {
    enrolUnicaesStudy: "Unirse al Estudio UNICAES",
    exitUnicaesStudy: "Salir del Estudio UNICAES",
    consentFormTitle: "Formulario de Consentimiento",
    consentFormDesc: "Por favor lee el formulario de consentimiento y conséntate al estudio",
    whatsappConsent: "Acepto recibir una vez por semana mensajes de Whatsapp con novedades sobre el estudio.",
    invalidPhoneNumber: "Por favor ingresa un número de teléfono válido",
    phoneNumber: "Número de Teléfono",
    enterYourPhoneNumber: "Ingresa tu número de teléfono",
    unicasStudy: "Estudio UNICAES",
    syncManually: "Sincronizar Manualmente",
    facultyOfBusiness: "Facultad de Ciencias Empresariales",
    facultyOfEngineering: "Facultad de Ingeniería y Arquitectura",
    facultyOfHumanities: "Facultad de Ciencias y Humanidades",
    facultyOfHealth: "Facultad de Ciencias de la Salud",
    yearLevel1: "1er Año",
    yearLevel2: "2do Año",
    yearLevel3: "3er Año",
    yearLevel4: "4to Año",
    yearLevel5: "5to Año",
    wrongEmail:
      "El código de participante no coincide con tu dirección de correo. Por favor contacta a support@focusbear.io",
    invalidName: "Por favor ingresa tu nombre",
    invalidEmail: "Por favor ingresa una dirección de correo UNICAES válida",
    invalidFaculty: "Por favor selecciona tu facultad",
    invalidYearLevel: "Por favor selecciona tu año académico",
    emailAlreadyExists: "Este correo ya está registrado en el estudio",
    pleaseCheckEmail: "Por favor revisa tu correo para encontrar tu código de participante",
    register: "Registrarse",
    invalidCode: "Código inválido",
    email: "Correo electrónico",
    name: "Nombre",
    faculty: "Facultad",
    yearLevel: "Año académico",
    enterYourName: "Ingresa tu nombre completo",
    enterYourEmail: "Ingresa tu correo UNICAES",
    selectFaculty: "Selecciona tu facultad",
    selectYearLevel: "Selecciona tu año académico",
    applicationForm: "Formulario de Solicitud",
    title: "Focus Bear",
    description:
      "Actualmente estamos aceptando participantes para nuestro estudio en UNICAES. Si quieres ayudarnos y unirte al estudio, por favor aplica abajo. Si quieres más información sobre el estudio <hereLink>haz clic aquí</hereLink> o contáctanos en {email}.",
    moreInfoLink: "haz clic aquí",
    contactEmail: "support@focusbear.io",
    applyButton: "Aplicar para Participar",
    hasParticipantCode: "Tengo un código de participante",
    enterYourCode: "Ingresa tu código",
    continue: "Continuar",
    back: "Atrás",
    permissionNeededTitle: "Permiso Necesario",
    permissionNeededDescription:
      "Para participar en este estudio, necesitamos que actives el permiso para el seguimiento de datos. Puedes darte de baja del estudio en cualquier momento desinstalando Focus Bear.",
    uploadScreenshot: "Subir Captura de Pantalla",
    thankYouForJoining:
      "Gracias por unirte a nuestro estudio, actualmente solo estamos recolectando datos para saber cómo usas tu teléfono antes de darte acceso completo a las funciones de Focus Bear. Si deseas darte de baja del estudio, por favor desinstala Focus Bear. Si necesitas contactar soporte, por favor escríbenos a: <email>support@focusbear.io</email>",
    screenshotUploadReminder:
      "Tiempo de Pantalla, es hora de subir tu captura de pantalla. Por favor sigue las instrucciones a continuación. Si necesitas ayuda, contáctanos en: support@focusbear.io\n\nInstrucciones:\n\n1. Captura de pantalla del uso de apps de la semana pasada\n2. Haz clic en el botón de subir captura de pantalla\n3. Selecciona la imagen y súbela",
    usageDataLastSynced: "Datos de uso sincronizados: {date}",
    whatTimeDoYouGoToSleep: "¿A qué hora te acostas?",
    whatTimeDoYouSleepDescription: "Usaremos esto y seguiremos el uso de tu teléfono después de tu ventana de sueño.",
    setupPermissions: "Configuración Requerida",
    setupPermissionsTitle: "Conceder Permisos de la App",
    setupPermissionsDesc: "Permite a Focus Bear ayudarte a mantenerte enfocado",
    studyTasks: "Tareas de Estudio",
    flankerTaskTitle: "Completar Tarea Flanker",
    flankerTaskDesc: "Prueba tu atención y concentración",
    questionnaireTitle: "Completar Cuestionario",
    questionnaireDesc: "Ayúdanos a entender tu experiencia",
    screenTime: "Tiempo de Pantalla, es hora de subir tu captura de pantalla",
    screenshotUploadSuccess: "Captura de pantalla subida",
    imageProcessing: "Verificando uso de apps...",
    imageProcessed: "Captura de pantalla procesada correctamente",
    imageProcessingFailed: "Error al procesar la captura de pantalla",
    checkingStatus: "Verificando estado",
  },
  flankerGame: {
    title: "Juego Flanker Bear",
    welcome: "¡Bienvenido al Juego Flanker Bear! Este juego prueba tu atención y concentración.",
    instruction1: "1. Verás una fila de flechas",
    instruction2: "2. Concéntrate en la flecha del centro",
    instruction3: "3. Presiona el botón que coincida con la dirección de la flecha central",
    instruction4: "4. Intenta ser lo más rápido y preciso posible",
    play: "Jugar",
    practiceStart: "¡Hagamos un calentamiento rápido para que sepas cómo funciona!",
    mainStart: "¡Excelente! Ahora comienza la prueba real.",
    testProgress: "Prueba {current} de {total}",
    ok: "OK",
    timeout: "😢",
    complete: "¡Todo listo!",
    completeMessage: "¡Gracias! Esto nos ayuda a entender cómo funciona tu atención.",
    practiceComplete: "¡Práctica Completada!",
    mainInstructions: "Ahora hagamos la prueba real. Tendrás 2 segundos para responder a cada prueba.",
    startMain: "Comenzar Prueba Principal",
    continue: "Continuar",
  },
  questionnaire: {
    title: "Cuestionario",
    loadingQuestionnaire: "Cargando cuestionario",
  },
  routineSuggestion: {
    title: "Sugerencia de Rutina",
    generatingRoutine: "Generando rutina",
    loading: "Cargando",
    breathingExercise:
      "Mientras esperas, mira este video para ver cómo Focus Bear puede ayudarte a crear buenos hábitos.",
    error: "Ocurrió un error inesperado",
    successTitle: "¡Rutina Generada!",
    successMessage: "Hemos creado algunas muestras de hábitos basados en tus objetivos.",
    errorTitle: "¡Ups! Algo salió mal",
    errorMessage:
      "No pudimos generar tu rutina en este momento. Puedes intentarlo de nuevo o continuar configurando tus tiempos manualmente.",
    errorMessageGoals:
      "Tuvimos un problema y no pudimos generar tus hábitos, por favor cuéntanos cuáles son tus objetivos",
    updateGoals: "Actualizar Mis Objetivos",
    noHabitsTitle: "Aún no hay hábitos",
    noHabitsMessage:
      "No pudimos encontrar hábitos en tu importación. ¡Generemos algunos hábitos personalizados para ti!",
    morningRoutine: "Rutina Matutina",
    eveningRoutine: "Rutina Nocturna",
    totalDuration: "Total: {duration}",
    noActivities: "No hay actividades en esta rutina",
    addActivity: "Agregar Actividad",
    editActivity: "Editar Actividad",
    deleteActivityTitle: "Eliminar Actividad",
    deleteActivityMessage: "¿Estás seguro de que quieres eliminar '{activityName}'?",
    activityName: "Nombre de la Actividad",
    enterActivityName: "Ingresa el nombre de la actividad",
    duration: "Duración",
    minutes: "Minutos",
    seconds: "Segundos",
    errors: {
      nameRequired: "El nombre de la actividad es requerido",
      nameTooShort: "El nombre de la actividad debe tener al menos 2 caracteres",
      invalidTime: "Por favor ingresa un tiempo válido",
      timeTooShort: "La duración debe ser de al menos 5 segundos",
    },
    adjustWithAI: "Ajustar con IA",
    createWithAI: "Crear con IA",
    adjust: "Ajustar",
    create: "Crear",
    aiPrompt:
      "Dile a tu oso qué cambios te gustaría hacer en tu rutina. Por ejemplo: 'Haz mi rutina más corta' o 'Agrega más ejercicios'",
    aiCreatePrompt: "Describe la rutina que quieres crear desde cero. Por ejemplo: 'Crea una rutina de inicio de día'",
    aiPlaceholder: "Describe los cambios que quieres...",
    aiError: "No pudimos ajustar tu rutina. Inténtalo de nuevo.",
    adjusting: "Ajustando con IA...",
    creating: "Creando con IA...",
    aiSuccessMessage: "Hábitos ajustados con éxito, revísalos para ver si te gustan",
    tapToEdit: "Toca para editar",
  },
  streak: {
    title: "¡La racha ha llegado!",
    howItWorks:
      "Haz una <bold>sesión de enfoque</bold> o completa <bold>un hábito matutino o nocturno</bold> cada día para incrementar tu racha.",
    activeStreak: "Racha Activa",
    activeStreakDesc: "Usaste Focus Bear ahora.",
    dueStreak: "Racha en peligro",
    dueStreakDesc: "Usaste Focus Bear ayer. Úsalo ahora para conservarla.",
    inactiveStreak: "Racha Inactiva",
    inactiveStreakDesc: "No usaste Focus Bear ayer.",
    motivationTip: "La constancia vence a la intensidad.",
    morningStreak: "Racha de Hábito Matutino",
    eveningStreak: "Racha de Hábito Nocturno",
    focusModeStreak: "Racha de Sesión de Enfoque",
    streakIconTitle: "Significado de Íconos",
    day_zero: "0",
    day_one: "{count} día",
    day_other: "{count} días",
    morning: "Mañana",
    evening: "Tarde",
    focus: "Enfoque",
    days: "días",
  },
  juniorBearConversation: {
    messageNormalStep1: "¡Hola, soy Focus Bear Junior",
    messageNormalStep2: "En realidad no soy tan bueno concentrándome 😢 Tengo TDAH y me distraigo todo el tiempo.",
    messageNormalStep2_5: "¡Oho! Está bien, maestro de la concentración. ¿Hay algo en lo que necesites ayuda?",
    messageNormalStep3:
      "Es difícil concentrarse con todas las aplicaciones divertidas… ¡quiero decir, distractoras! en mi teléfono. ¿Quieres hacer equipo? ¡Podemos concentrarnos juntos!",
    messageNormalStep4: "¡Genial! ¿En qué quieres trabajar juntos?",
    messageNormalStep5:
      "Genial. ¿Quieres configurar una cuenta para que podamos trabajar juntos en tu computadora y tu teléfono?",
    messagePirateStep1: "¿Me llamaron para ayudarte a concentrarte? El Capitán Bear a tu servicio.",
    messagePirateStep1_5:
      "Hiciste que mi sobrino llorara como un marinero. Así que ahora soy yo — el Capitán Bear. Mantente firme, bribón.",
    messagePirateStep2:
      "Ahora, la verdad sea dicha… Tengo TDAH, igual que muchos buenos piratas. Mi mente vaga como un barco sin ancla.",
    messagePirateStep2_5: "¡Har! Una mente aguda, veo. ¿Qué ayuda necesitas aún?",
    messagePirateStep3:
      "¡Arr, esas aplicaciones brillantes son más ruidosas que un loro borracho! ¿Quieres hacer equipo? ¡Podemos evitar que el otro caiga por la borda!",
    messagePirateStep4: "¡Arrr, dos manos en cubierta! ¿Qué problemas buscas domar?",
    messagePirateStep5: "¡Grandioso! ¿Configuramos una cuenta para navegar juntos en tu computadora y tu teléfono?",
    buttonNormalStep1Primary: "Hola",
    buttonNormalStep1Secondary: "Arr, desearía que fueras un pirata…",
    buttonNormalStep2Primary: "¡Yo también!",
    buttonNormalStep2Secondary: "Nunca tuve ese problema",
    buttonNormalStep2_5Option1: "Mantener hábitos saludables",
    buttonNormalStep2_5Option2: "Organizar tareas",
    buttonNormalStep2_5Option3: "¡Vete! ¡No me gustan los niños!",
    buttonNormalStep3Primary: "¡Hagámoslo!",
    buttonNormalStep3Secondary: "¡Vete! ¡No me gustan los niños!",
    buttonNormalStep4Primary: "Siguiente",
    buttonNormalStep5Primary: "¡Inscríbeme, Scotty!",
    buttonNormalStep5Secondary: "No gracias, me quedaré anónimo",
    buttonPirateStep1Primary: "Ahoy",
    buttonPirateStep1Secondary: "Saludos, Capitán",
    buttonPirateStep1_5Primary: "Perdón, Capitán. Mantendré mis piernas de mar",
    buttonPirateStep2Primary: "Aye… A menudo extravío mi ancla",
    buttonPirateStep2Secondary: "No yo, me llaman Barba Cerebro",
    buttonPirateStep2_5Option1: "Construir hábitos de marinero más sólidos",
    buttonPirateStep2_5Option2: "Poner mis tareas en orden",
    buttonPirateStep3Primary: "¡Aye, hagámoslo!",
    buttonPirateStep3Secondary: "Arr, que el océano decida mi destino",
    buttonPirateStep4Primary: "Siguiente",
    buttonPirateStep5Primary: "¡Izad las velas — inscríbeme!",
    buttonPirateStep5Secondary: "Permaneceré como un fantasma en los mares",
    focusAreaBlockDistractionsNormal: "Bloquear distracciones",
    focusAreaBlockDistractionsPirate: "Afilen mi concentración en el timón",
    focusAreaHealthyHabitsNormal: "Mantener hábitos saludables",
    focusAreaHealthyHabitsPirate: "Construir hábitos de marinero más sólidos",
    focusAreaOrganiseTasksNormal: "Organizar tus tareas",
    focusAreaOrganiseTasksPirate: "Poner mis tareas en orden",
  },
  streakCelebration: {
    title: "¡Racha de {streakTypeName}!",
    morning: "rutina matutina",
    evening: "rutina nocturna",
    focus: "sesión de enfoque",
    message: "¡Estás en llamas! Sigue así.",
    day: "día",
    days: "días",
  },
  widget: {
    defaultRoutine: "Sin rutina",
    noReasonProvided: "¡Todo listo!",
    noNextHabit: "Nada programado",
    whatsNext: "Siguiente:",
    streakTitle: "Rachas",
    motivationalQuotes: [
      "«El éxito es la suma de pequeños esfuerzos repetidos día tras día.» – Robert Collier",
      "«El secreto para salir adelante es empezar.» – Mark Twain",
      "«La disciplina es elegir entre lo que quieres ahora y lo que más quieres.» – Abraham Lincoln",
      "«Tu futuro se crea con lo que haces hoy, no mañana.» – Robert Kiyosaki",
      "«Siempre parece imposible hasta que se hace.» – Nelson Mandela",
    ],
  },
};
