export default {
  languageName: "日本語",
  baseLanguage: "ja",
  blockingSchedule: {
    title: "ブロッキングスケジュール",
    namePlaceholder: "ブロック名",
    startTime: "開始",
    endTime: "終了",
    adjustStart: "開始時刻を調整",
    adjustEnd: "終了時刻を調整",
    daysHeading: "これらの曜日",
    chooseApps: "アプリを選択",
    chooseUrls: "ウェブサイトを選択",
    saveFailedTitle: "スケジュールを保存できません",
    saveFailedMessage: "ブロックするアプリを選択してから再試行してください。",
    duplicateNameMessage: "このブロックスケジュールには重複しない名前を付けてください。",
    focusModeSuffix: "(モバイルブロックスケジュールから)",
    defaultName: "💻 作業時間",
    appBlocking: "アプリブロック",
    websiteBlocking: "ウェブサイトブロック",
    accessibilityRequiredForUrls: "ウェブサイトをブロックするにはアクセシビリティが必要です。",
    selectionMissing: "ブロックするアプリを選択してください。",
    noAppsSelected: "アプリが選択されていません",
    urlsSelectionMissing: "ウェブサイトが選択されていません",
    urlsSelectionCount_one: "{count}件のウェブサイトを選択",
    urlsSelectionCount_other: "{count}件のウェブサイトを選択",
    urlsDescription: "このスケジュール中にブロックするウェブサイトを追加",
    selectedUrls: "選択したウェブサイト",
    suggestedUrls: "おすすめのウェブサイト",
    iOSSelectionCounts:
      "{applicationsCount} 個のアプリ、{categoriesCount}個のカテゴリ、{webDomainsCount}個のウェブサイト",
    androidSelectionCount: "{applicationsCount}個のアプリが選択されました",
    mode: {
      strict: {
        title: "厳格ブロック",
        subtitle: "逃げられません - ロック解除にはパスワードが必要",
      },
      cooldown: {
        title: "クールダウンブロック",
        subtitle: "短い待機後にロック解除（考え直す時間を与えます）",
      },
      gentle: {
        title: "ソフトブロック",
        subtitle: "すぐにブロックを一時停止（無限スクロールのリスクあり😅）",
      },
    },
    removeTitle: "このスケジュールを削除しますか？",
    removeMessage: "これによりスケジュールが完全に削除されます。",
    removeFailedMessage: "もう一度お試しください。",
    blockedBySchedule: "スケジュールによりブロック中：{scheduleName}",
    appBlockedBySchedule:
      "{appName}は、あなたの{scheduleName}ブロッキングスケジュールがアクティブなためブロックされています",
    blockAllDuringHabits: "すべての習慣中に一部のアプリをブロック",
    customizeBlocking: "ブロックをカスタマイズ",
    scheduledBlocksTitle: "スケジュールされたブロック",
    scheduledBlocksInfoText: "選択した曜日に繰り返す時間枠を作成します。複数のブロックを追加できます。",
    addNewBlock: "ブロックを追加",
    habitMorningName: "朝のルーティン",
    allDays: "毎日",
    permissionsRequired: "権限が必要です",
    androidPermissionDescription: "アプリをブロックするには使用状況アクセスとオーバーレイ権限が必要です",
    iOSPermissionDescription: "ブロッキングスケジュールを作成および管理するにはスクリーンタイム権限が必要です。",
    habitBlocksTitle: "習慣ブロック",
  },
  tabTitle: {
    overview: "概要",
    habits: "習慣",
    tasks: "タスク",
  },
  error: {
    invalidVideoUrl: "その動画URLが正しくないようです😕",
    videoNotFound: "申し訳ございません、その動画が見つかりませんでした！",
    authenticationErrorName: "認証エラー",
    authenticationErrorMessage: "おっと！認証に問題が発生しました。もう一度お試しください。",
  },
  habitSetting: {
    routine: "ルーティン",
    selectRoutine: "ルーティンを選択",
    requirement: "この習慣を完了するために必要なこと",
    youtubeVideo: "YouTubeまたはVimeo動画",
    youtubeVideoDescription: "この習慣をガイドする動画を追加",
    enableTimer: "タイマーを有効にしますか？",
    timer: "タイマー",
    timerDescription: "習慣の時間を設定",
    goal: "目標",
    goalDescription: "目標を達成したら習慣を完了",
    goalPlaceholder: "完了目標を指定しますか？...",
    extras: "追加機能",
    noGoalSpecified: "目標が指定されていません",
    defaultName: "名前のない習慣",
    allowedApps: "許可するアプリ",
    allowedAppsDescription: "この習慣のあいだに使えるアプリを選びます",
    selectApps: "アプリを選択",
    appsSelected: "{count} 件のアプリを選択中",
    noAppsSelected: "未選択",
    openAllowedApps: "許可したアプリを開く",
    launchApp: "開く",
  },
  common: {
    accept: "承認",
    learnMore: "詳細を見る",
    doItLater: "後で実行",
    later: "後で",
    termsOfUse: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    email: "メール",
    nickname: "ニックネーム",
    skip: "スキップ",
    goToSleep: "睡眠時間です😴",
    areYouSure: "よろしいですか？",
    loading: "読み込み中...",
    connectionError: "接続エラー",
    morning: "朝",
    evening: "夕方",
    welcome: "ようこそ",
    somethingWrong: "問題が発生しました",
    logout: "ログアウト",
    ok: "OK",
    ok_ellipsis: "OK...",
    okay: "OK",
    yes: "はい",
    no: "いいえ",
    confirm: "確認",
    next: "次へ",
    cancel: "キャンセル",
    delete: "削除",
    proceed: "続行",
    resume: "再開",
    retry: "再試行",
    submit: "送信",
    resend: "再送信",
    verify: "確認",
    edit: "編集",
    finished: "完了",
    done: "完了",
    sec: "秒",
    focusBear: "フォーカスベア",
    tomorrow: "明日",
    today: "今日",
    yesterday: "昨日",
    add: "追加",
    start: "開始",
    startRoutine: "ルーティンを開始",
    continue: "続行",
    end: "終了",
    startActivity: "{activityName}を開始",
    startTimerActivity: "{time}{unit}の{activityName}を開始",
    Success: "成功！",
    SuccessfullyAddedHabit: "習慣を正常に追加しました",
    save_changes: "変更を保存",
    save: "保存",
    saving: "保存中",
    saved: "保存済み",
    created: "作成済み",
    next_time_format: "[{day}] h:mm A",
    sure: "確認",
    uploadScreenShots: "スクリーンショットをアップロード\n（任意）",
    session_expired: "セッションが期限切れです",
    login_again: "再度ログインしてください",
    continue_activity_name: "{activityName}を続行",
    no_thanks: "いいえ、結構です",
    saveHabitSuccessfully: "{habitName}を{routineName}ルーティンに追加しました",
    couldNotProcessTheRequest: "リクエストを処理できませんでした。もう一度お試しください",
    error: "エラー",
    selected: "選択済み",
    all: "すべて",
    viewAll: "すべて表示",
    more: "もっと見る",
    somethingElse: "その他",
    habit: "習慣",
    empty: "空",
    clearAll: "クリア",
    loadingWithoutDot: "読み込み中",
    pleaseWaitPatiently:
      "データを読み込んでいます。数分かかることがありますが、バックグラウンドで準備を進めていますのでしばらくお待ちください。",
    granted: "許可済み",
    notGranted: "未許可",
  },
  customizeBlocking: {
    customBlockedMessage: {
      title: "カスタムブロックメッセージ",
      tooltip: "ブロック画面に表示されるデフォルトのモチベーション引用文を置き換えます。",
      placeholder: "カスタムメッセージを入力してください...",
      hint: "空欄のままにすると、デフォルトのモチベーション引用文が使用されます。",
    },
    customSoftBlocking: {
      title: "解除時間",
      description: "ソフトブロックモードで休憩後、アプリが解除されたままになる時間。",
      hint: "{min}分から{max}分まで",
    },
    customPauseDelay: {
      title: "一時停止の待機時間",
      description: "ブロックされたアプリを解除する前の小さな障壁。試みるたびに次の解除がより難しくなります。",
      hint: "{min}秒から{max}秒まで",
      sequenceLabel: "あなたの待機時間",
    },
    saveSuccess: "カスタムブロック設定が正常に保存されました",
    saveError: "カスタムブロック設定の保存に失敗しました。もう一度お試しください。",
  },
  settings: {
    healthPermission: "ヘルス権限",
    physicalActivityPermission: "身体活動権限",
    healthAndSleepPermission: "ヘルスとスリープ権限",
    changedBackendEndpoint: "AWS Backend 終了point {status}",
    saveBlockedUrls: "ブロックされたURLを正常に保存しました",
    saveBlockedUrlsError: "ブロックされたURLの保存に失敗しました",
    debugLog: "詳細ログを有効化",
    debugLogDescription: "サポートチームから依頼された場合のみオンにしてください。アプリが遅くなります",
    title: "設定",
    addApps: "ブロックリストにアプリを追加",
    clearBlocklist: "ブロックリストをクリア",
    confirmClearBlocklist: "ブロックリストをクリアしてもよろしいですか？",
    urlBlockingWarningTitle: "重要：URLブロックはSafariでのみ機能します",
    urlBlockingWarningMessage:
      "ウェブサイトのブロックはSafariでのみ機能します。URLブロックを回避されないようにするため、Chrome、Firefox、その他のサードパーティブラウザをブロックリストで完全にブロックすることをお勧めします。",
    urlBlockingHowToTitle: "ウェブサイトをブロックする方法",
    urlBlockingHowToMessage:
      "下の「URLをブロックリストに追加」をタップし、ピッカーの上部にある「ウェブサイト」タブを選択します。特定のウェブサイトを検索するか、カテゴリ別に閲覧できます。選択したウェブサイトは、フォーカスセッション中にSafariでブロックされます。",
    addUrls: "URLをブロックリストに追加",
    clearBlockedUrls: "ブロックされたURLをクリア",
    confirmClearBlockedUrls: "ブロックされたURLをクリアしてもよろしいですか？",
    strictness: "厳格度",
    shareLogsWithSupport: "問題を報告",
    reason_required: "理由を入力してください",
    enter_a_reason: "アカウントを削除したい理由を教えていただけますか？",
    contact_desc: "問題解決のためにご連絡してもよろしいでしょうか？",
    editFriction: "摩擦",
    password: "パスワード",
    account: "アカウント",
    permissions: "権限",
    language: "言語",
    useSystemLanguage: "システム言語を使用",
    supportedLanguages: "サポートされている言語",
    overlay_permission: "オーバーレイ権限",
    usage_permission: "使用状況権限",
    notification_permission: "通知権限",
    screen_time_permission: "スクリーンタイム権限",
    DND_permission: "おやすみモード権限",
    DND: "通知をブロック",
    warning: "警告！",
    DND_permissionWarning:
      "おやすみモードが既に有効になっている場合は手動で無効にする必要があります。おやすみモード権限が付与されていない場合、自動的にオフにすることはできません。",
    help: "ヘルプ",
    askForHelp: "ヘルプを求める",
    report_problem: "問題を報告",
    discord_server: "Discordサーバー",
    videoTutorials: "ビデオチュートリアル",
    experimental: "実験的",
    customization: "カスタマイズ",
    general: "一般",
    focusGames: "フォーカスゲーム",
    allowed: "許可済み",
    notAllowed: "許可されていません",
    notGrantedYet: "付与されていません",
    userid: "ユーザーID",
    copy: "コピー",
    copied: "コピー済み",
    settings: "設定",
    verifyEmail: "メールを確認",
    emailVerificationResent: "メール確認を再送信しました",
    pendingVerification: "確認待ち",
    editNickname: "ニックネームを編集",
    nicknameError: "無効なニックネーム（文字と数字のみ）",
    nicknameAlreadyExists: "ニックネームは既に存在します",
    customizeBlocking: "ブロックをカスタマイズ",
    lateNoMore: "ミーティングのリマインダー",
  },
  focus: {
    title: "フォーカス",
    focusLimitReachedTitle: "フォーカス制限に達しました",
    focusLimitReachedMessage:
      "無料版では最大25分間しかフォーカスできません。より長いフォーカスセッションが必要な場合はプレミアムにアップグレードしてください。",
  },
  blockingStatusBanner: {
    additionalSchedules: " +{count}件以上",
    activeSchedule: "{name} ({start} – {end}) {extra}",
  },
  home: {
    setupHabitsDescription: "1日を始めるために習慣を設定してください。",
    upEarlyStartMorningRoutine: "早起きしましたか？朝のルーティンを開始",
    getMotivated: "やる気を出す",
    completed: "完了",
    habitName: "習慣名",
    newHabit: "新しい習慣...",
    duration: "期間",
    editHabit: "習慣を編集",
    addHabit: "習慣を追加",
    deleteThisHabit: "この習慣を削除",
    deleteHabit: "{name}の習慣を削除",
    deleteHabitTitle: "習慣を削除",
    deleteHabitMessage: "本当に削除してもよろしいですか '{habitName}'？この操作は元に戻せません。",
    afterCutoffTimeDescription: "カットオフ時刻を過ぎているため、習慣は利用できません",
    routineNotScheduledNow: "このルーティンは{routineSchedule}に予定されています",
    cutOffToolTip: "習慣のカットオフ時刻を{cutOffTime}に設定しました。\n時間設定の変更から変更できます",
    unlockToProceed: "続行するにはロック解除",
    title: "ホーム",
    morningRitual: "あなたの朝の儀式",
    eveningRitual: "あなたの夕方の儀式",
    time_to_earn_screen_time: "素晴らしい1日のために朝のルーティン習慣を実行してください",
    evening_routine_text: "完了すると、素晴らしい睡眠の準備が整います！",
    upcoming_below_new_activities: "モバイルを使用するために次のルーティンで達成する必要がある習慣は以下の通りです。",
    start: "開始",
    mins: "分",
    secs: "秒",
    re_activate: "ブロックを再開",
    force_deactivate_postpone_and_start_routine: "ルーティンが延期されました\nルーティンを再開しますか？",
    userCompletedRoutineHeading: "ルーティンを完了しました。次のルーティンは{routineTime}にお手伝いします",
    postOnboardingRoutineHeading: "ようこそ！{routineName}ルーティンは{routineTime}にお手伝いします",
    wantLogout: "ログアウトしますか？",
    noDataFound: "まだ習慣を設定していません。<fix>ここ</fix>をタップして習慣を追加してください。",
    routineFetchingError:
      "ルーティンデータの取得中に問題が発生しました。後でもう一度お試しいただくか、サポートにお問い合わせください",
    hi: "こんにちは {nickname}！",
    welcomeDefault: "こんにちは！",
    goodMorningFocusTime: "おはようございます！",
    goodEveningFocusTime: "こんばんは！",
    allActivitiesCompleted: "完了する習慣はありません",
    startRoutineNow: "{routineName} ルーティン",
    customRoutineReady: "カスタムルーティンを今すぐ開始できます",
    passwordForSettingsTitles: "続行するにはパスワードを入力してください",
    manageAlwaysAllowedAppsDesc:
      "朝/夕方のルーティン中およびコンピューターに集中しているとき、常に許可されているアプリを除くすべてのアプリがブロックされます。習慣/作業中に気が散らないように、SMS、電話、仕事に必要なアプリのみを許可することをお勧めします。",
    manageAlwaysBlockedAppsDesc:
      "朝/夕方のルーティン中およびコンピューターに集中しているとき、ブロックリストのすべてのアプリがブロックされます。習慣/作業中に気が散らないように、ソーシャルメディア、ゲーム、メール、ニュースアプリをブロックすることをお勧めします。",
    overlayPermission: "オーバーレイ権限",
    usagePermission: "使用状況権限",
    editHabits: "習慣を編集",
    editYourHabits: "習慣を編集",
    stats: "統計",
    motivationMsg: "やる気を出す",
    play: "再生",
    pause: "一時停止",
    customizeHabits: "ルーティンを編集",
    deleteAccount: "アカウントを削除しますか？",
    accountDataHasBeen: "アカウントデータが正常に削除されました。Focus Bearをご利用いただきありがとうございました。",
    blockSuperDistractingApps: "超気が散るサイト/アプリをブロック",
    skipHabitDesc: "今日はこの習慣をスキップ",
    screenTimePermissionNotAllowedWarningText:
      "アプリをブロックするにはスクリーンタイム権限が必要です。権限を許可するために習慣を再度開始してください",
    OverlayPermissionNotGrantedWarning:
      "警告：気が散るブロックが有効になっていません。オーバーレイ権限が付与されていません。修正してください。",
    ScreenTimePermissionNotGrantedWarning:
      "警告：気が散るブロックが有効になっていません。スクリーンタイム権限が付与されていません。修正してください。",
    UsagePermissionNotGrantedWarning:
      "警告：気が散るブロックが有効になっていません。使用状況権限が付与されていません。修正してください。",
    noAllowedAppSelectedWarning:
      "警告：まだブロックリストを設定していないため、気が散るものはブロックされません。ブロックリストを編集",
    habitLimitMessage:
      "無料ユーザーはルーティンごとに最大3つの習慣にしかアクセスできません。より多くの習慣のロックを解除するにはアップグレードしてください。",
    routineOptionsTooltip: "このメニューからルーティンの編集や時間の変更ができます。",
    youHaveNotSetupAnyHabitsYet: "まだ習慣を設定していません。",
    guestMode: "ゲストモード",
    guestSignUpDescription:
      "すべてのデバイスでコンテンツにアクセスし、パーソナライズされた機能のロックを解除するにはサインアップしてください。",
    deleteRoutineTitle: "ルーティンを削除",
    deleteRoutineMessage: "このルーティンと関連するすべての習慣を削除してもよろしいですか？この操作は元に戻せません。",
    createHeading: "作成",
    completedHabits: "完了した習慣",
    hiddenHabits: "非表示の習慣",
    editRoutine: "ルーティンを編集",
    changeTiming: "時間を変更",
    deleteRoutine: "ルーティンを削除",
    cutoffTimeNote:
      "注意：カットオフタイムは {time} です。「高優先度」に設定されていない習慣はこの時間以降利用できなくなります。",
    editCutoff: "カットオフを編集",
    unavailable: "利用不可",
    inProgress: "進行中",
    startsAt: "{time}に開始",
    passed: "終了",
    completedWithCount: "{count}件完了",
    unavailableWithCount: "{count}件が現在利用不可",
    noHabitsYetAddPrompt: "まだ何もありません。\n習慣を追加しますか？",
    routineIsEmpty: "ルーティンが空です",
    allHabitsHidden: "すべての習慣が非表示",
    habitsCount_zero: "$t(common.empty)",
    habitsCount_one: "{count}件の習慣",
    habitsCount_other: "{count}件の習慣",
  },
  editRoutine: {
    editTiming: "タイミングを編集",
    morningTime: "朝の時間",
    wakeUp: "起床！",
    morningRoutineStartTime: "朝のルーティン開始時間",
    eveningTime: "夜の時間",
    finishWork: "仕事終了",
    eveningRoutineStartTime: "夜のルーティン開始時間",
    techCurfew: "テクノロジー制限時間",
    timeToSleep: "就寝時間",
    timing: "タイミング",
    anytime: "いつでも",
    scheduled: "スケジュール",
    doHabitsWhenever: "いつでもこれらの習慣を行う",
    doHabitsAtSpecificTime: "特定の時間または特定の曜日にこれらの習慣を行う",
    newRoutinePlaceholder: "新しいルーティン...",
    routineNamePlaceholder: "ルーティン名",
    customRoutineDefaultName: "カスタムルーティン",
    createNewRoutine: "新しいルーティンを作成",
    time: "時間",
    wakeUpFinishWorkSameError: "起床時間と仕事終了時間は同じにできません",
    cutoffOutOfRangeError: "就寝時間は仕事終了時間より後、起床時間より前に設定してください",
    startBeforeEndError: "開始時間は終了時間より前にする必要があります",
  },
  simpleHome: {
    setupBlocking: "ブロックを設定",
    setupBlockingApp: "アプリの気が散るブロックを設定（推奨）",
    setupBlockingUrl: "ウェブサイトの気が散るブロックを設定（任意）",
    title: "フォーカスベアを試す",
    focusSessionCheckboxTitle: "最初のフォーカスセッションを完了",
    microBreakCheckboxTitle: "マイクロブレイク習慣を実行",
    focusScreenTitle: "フォーカスセッションを試す",
    focusSessionCheckboxDesc: "集中して作業する",
    microBreakCheckboxDesc: "深呼吸でストレス解消",
    postGamePromptTitle: "よくできました！",
    postGamePromptText: "今すぐフォーカスセッションを開始してタスクを完了しますか？",
    focusNowCta: "はい！フォーカスタイム",
    focusGameTitle: "フォーカスゲームでウォームアップ",
    focusGameDesc: "ゲームで集中モードに入る",
  },
  postpone: {
    doYouReallyWantTo: "本当に一時停止しますか？",
    blockingPausedForDuration: "{duration}の間ブロックを一時停止中",
    blockingPausedIndefinitely: "再開するまでブロックを一時停止中",
    pauseBlocking: "ブロックを一時停止",
    pauseDisabledStrictMode: "スーパーストリクトモードが有効な場合、ブロックの一時停止は使用できません",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "ブロックを再開",
    choosePostponeTime: "どのくらい一時停止しますか？",
    indefinite: "再開するまで一時停止",
    youHavePausedTimesToday_zero: "今日初めての一時停止です。",
    youHavePausedTimesToday_one: "今日すでに1回一時停止しています。",
    youHavePausedTimesToday_other: "今日すでに{count}回一時停止しています。",
    countdown: "{countdown}後に一時停止できます",
    areYouSureIndefinite:
      "本当に無期限で一時停止しますか？可能ですが、緊急に見えるタスクでも習慣を終えるまでの15分は待てることが多いです。",
    doHabits: "代わりに習慣を続けます",
    longTermGoalsDesc: "フォーカスベアで達成しようとしていることを思い出してください：",
    lowQualityUsageDesc: "今日、低品質なアプリに費やした時間",
    write: "フィードバックを残す...",
  },
  passwordForSettings: {
    invalid_password: "パスワードが無効です",
    resetAfter24Hours: "リセットがリクエストされました。24時間後にパスワードは無効になります。",
  },
  signIn: {
    logIn: "ログイン",
    enterEmailHint: "メールアドレス",
    enterPasswordHint: "パスワード",
    invalidCredentials: "ユーザー名またはパスワードが無効です",
    enterEmailError: "メールアドレスを入力してください",
    enterValidEmailError: "有効なメールアドレスを入力してください",
    enterPasswordError: "パスワードを入力してください",
    dontHaveAccount: "アカウントをお持ちでないですか？",
    forgotPassword: "パスワードをお忘れですか？",
    signup: "サインアップ",
    googleSignIn: "Googleで続行",
    continueWithGoogle: "Googleで続行",
    startWithApple: "Appleで開始",
    startWithEmail: "メールで開始",
    backToSignInMethod: "サインイン方法の選択に戻る",
    alreadyHaveAccount: "すでにフォーカスベアのアカウントを持っています",
  },
  forgotPassword: {
    forgotPasswordSuccess: "パスワードリセットメールをメールアドレスに送信しました",
    forgotPasswordErrorThirdParty:
      "サードパーティサービスでサインアップしたようです。GoogleまたはAppleアカウントで続行してください。",
    forgotPasswordNotVerified: "パスワードをリセットするには、メールアドレスを確認する必要があります。",
    forgotPasswordEmailNotFound: "メールが見つかりません",
    forgotPasswordTitle: "パスワードをお忘れですか",
    backToSignIn: "サインインに戻る",
    resetPassword: "パスワードをリセット",
    weveEmailedYouALinkToResetYourPassword: "パスワードリセット用のリンクをメールで送信しました。",
    forgotPasswordNotVerifiedBody:
      "You need to verify your email before you can reset your password. We can send you a new verification link now.",
    forgotPasswordNotVerifiedTitle: "Verify your email to reset your password",
    resetLinkSent: "If an account exists with this email, a password reset link has been sent.",
    verificationEmailSent: "A verification email has been sent. Please check your inbox.",
    verificationEmailFailed: "Failed to send the verification email. Please try again later.",
    cannotResetPasswordOAuthAccountTitle: "Sign in to continue",
    resetFailed: "Password Reset attempt has failed. Try again later.",
    waitBeforeRetry: "別のメールを送信する前にお待ちください。",
  },
  signUp: {
    backToSignUpMethod: "サインアップ方法の選択に戻る",
    verifyEmail: "受信トレイを確認してください",
    verifyEmailMessage: "確認メールを送信しました。リンクをクリックしてアカウントを確認してください。",
    signUp: "サインアップ",
    emailSignup: "メールでサインアップ",
    continueWithNoAccount: "アカウントなしで続行",
    tosAndPP: "<bold>利用規約</bold>と<bold1>プライバシーポリシー</bold1>に同意します",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？",
    passwordMatchError: "パスワードと確認用パスワードが一致しません",
    acceptTerms: "続行するには利用規約とプライバシーポリシーに同意してください",
    passwordHintError:
      "パスワードには以下が必要です：\n    • 8文字以上\n    • 数字（0-9）\n    • 小文字（a-z）\n    • 大文字（A-Z）\n    • 特殊文字（!@#$%^&*）",
    invalidSignup: "無効なサインアップ",
    userExists: "このユーザーは既に存在します。",
    terms: "利用規約",
    privacy: "プライバシー",
    or: "または",
  },
  profile: {
    logout: "ログアウト",
  },
  routineDetail: {
    activity: "アクティビティ",
    not_playable_video: "動画を再生できません。",
    done: "完了しました",
    video: "動画",
    images: "画像",
    checklist: "チェックリスト",
    note: "メモ",
  },
  quickBreak: {
    quickBreak: "クイックブレイク",
    quickStretch: "ストレッチ運動",
    stretch: "ストレッチ",
    drinkWater: "水を飲む",
    water: "水",
    deepBreathing: "深呼吸",
    breathe: "呼吸",
    saveQuickBreakSuccessfully: "変更が正常に保存されました",
    editQuickBreaks: "クイックブレイクを編集",
    quickBreakName: "クイックブレイク名",
    currentSelection: "現在の選択",
  },
  complete: {
    backToHome: "ホームに戻る",
    logQuantity: "アクティビティの数量を記録",
    finishedCheck: "完了しました！✅",
    habitNotCompleted: "習慣をスキップしました！❌ 明日頑張りましょう！",
    finishedAndEarnedMorning: "完了しました！✅ スクリーンタイムを獲得しました",
    finishedAndEarnedEvening: "完了しました！✅ 良い睡眠の準備ができました。また明日の朝！",
    why_skip: "なぜスキップしますか？",
    already_did: "すでに完了しました",
    cannot_today: "今日はできません",
    quantity_input_error: "数値は{min}から{max}の間である必要があります。",
    freemiumLimitReached: "申し訳ありません、無料プランでは3つの習慣しか完了できません。",
  },
  reason: {
    canShare: "なぜ無期限で一時停止するのか教えていただけますか？",
    shareFeedback: "フィードバックを共有",
    everythingIsOk: "大丈夫ですか？何かあったのでしょうか",
    appBrokenDesc: "申し訳ありません。何が起こったか教えていただけますか？",
    somethingElseDesc: "わかりました。何かフィードバックはありますか？",
    gotEmergency: "緊急事態があります",
    appBroken: "アプリが壊れています",
    somethingElse: "その他",
  },
  notification: {
    backgroundService: "集中をサポートするフォーカスベアのバックグラウンドサービス",
    scheduleNotificationTitleForResumeRoutine: "ルーティンを再開",
    scheduleNotificationDescriptionForResumeRoutine: "ルーティンに集中する時間です",
    floatingModuleActivityCompleteNotificationtitle: "アクティビティ完了",
    floatingModuleRoutineCompleteNotificationtitle: "ルーティン完了",
    morningRoutineCompletedNotificationDescription: "朝のルーティンが完了しました。素晴らしい一日の始まりです！",
    eveningRoutineCompletedNotificationDescription: "夕方のルーティンが完了しました。おやすみなさい！",
    customRoutineCompletedNotificationDescription: "{{routineName}}が完了しました。よくできました！",
  },
  focusMode: {
    blockingPaused: "ブロック一時停止中",
    blockingPermissionNeeded: "ブロック無効：権限を付与する必要があります",
    noBlockingAppsSelected: "ブロック無効：ブロックするアプリを選択する必要があります",
    distractionBlockingNotActiveTitle: "気が散るブロックが無効です",
    distractionBlockingNotActiveText: "まだブロックするアプリを選択していません",
    continueWithoutBlocking: "ブロックなしで続行",
    fixBlocking: "ブロックを修正",
    confirmSuperStrictMode: "スーパーストリクトモードを有効にしますか？セッションが終了するまで終了できなくなります。",
    focusIntentionTooltip:
      "このフォーカスセッションで達成したい目標を設定してください。達成したいことを明確にすると、気が散るのを避けるのに役立ちます。",
    focusTitle: "フォーカスセッションを開始",
    superStrictToolTip:
      "このフォーカスセッションに集中しますか？スーパーストリクトモードを有効にすると、タイマーが終了するまでフォーカスをオフにしたり、アプリブロックを一時停止したりできなくなります。",
    superStrictMode: "スーパーストリクトモード",
    brainDump: "ブレインダンプ",
    brainDumpToolTip: "ここに考えを書き留めてください",
    postFocusCongrats_0: "よくできました！やり遂げましたね！",
    postFocusCongrats_1: "素晴らしい！次は何をしますか？",
    postFocusCongrats_2: "やりました！少し休憩してください。",
    postFocusCongrats_3: "よくできました！本当に成果を上げていますね！",
    postFocusCongrats_4: "素晴らしい仕事です！次の予定は？",
    postFocusCongrats_5: "乗り越えました！次に取り組みますか？",
    postFocusCongrats_6: "素晴らしい集中力！飲み物やおやつを取りに行きましょう！",
    postFocusCongrats_7: "いいですね！着実に進歩しています！",
    postFocusCongrats_8: "よくできました！少し足を伸ばしますか？",
    postFocusCongrats_9: "素晴らしかったです！この勢いを続けましょう！",
    startFocusSession: "フォーカスセッションを開始",
    noIntentionWasFound: "目標が入力されていません",
    distractionAlertTitle: "フォーカスモード",
    userIntention: "フォーカス目標",
    noDistractingThoughtsWasFound: "気が散る考えが入力されていません",
    userIntentionTextInputPlaceholder: "何に取り組みたいですか？",
    startFocusing: "フォーカスを開始",
    hoursWithValue: "{value}時間",
    minutesWithValue: "{value}分",
    secondsWithValue: "{value}秒",
    duration: {
      hours: "{hours}時間",
      minutes: "{minutes}分",
      seconds: "{seconds}秒",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "頑張れます！\n集中作業の時間です",
    endSession: "セッションを終了",
    completeFocus: "フォーカスを完了",
    userDumpThoughTextInputDescription: "気が散る考えをここに書き留めてください",
    exitFocusMode: "フォーカスセッションを早期終了",
    exitFocusModeDescription: "なぜこのセッションを終了するのか教えていただけますか？",
    reason: "理由",
    selectReason: "理由を選択",
    congratulations: "おめでとうございます！",
    focusDoneTitle: "やりました！",
    focusDoneDescription: "集中した時間",
    focusDoneDescription1: "あなたの目標は何でしたか？",
    focusDoneDescription4: "気が散る考えは何でしたか？",
    focusDoneDescription2: "この時間で何を達成しましたか？",
    focusDonePlaceholderDescription2: "私たちの助けで達成したことを入力してください",
    focusDoneDescription3: "気が散ることはありましたか？",
    focusDonePlaceholderDescription3: "気が散ったことを入力してください",
    endEarlyReasonDescription1: "緊急事態があります",
    endEarlyReasonDescription2: "フォーカスモードが正常に動作していません",
    endEarlyReasonDescription3: "達成したいことを達成しました",
    endEarlyReasonDescription4: "休憩が必要です",
    runningFocusModeDesc: "フォーカスセッションが実行中です",
    extendFocusDuration: "フォーカス時間を延長",
    shortenFocusDuration: "フォーカス時間を短縮",
    selectExtendFocusDuration: "あとどのくらい集中したいですか？",
    selectShortenFocusDuration: "どのくらい時間を短縮しますか？",
    extendFocus: "延長",
    shortenFocus: "短縮",
    adjustFocusDuration: "フォーカス時間を調整",
    chooseAdjustmentOption: "フォーカスセッションを延長しますか、それとも短縮しますか？",
    editFocusDuration: "いつフォーカスを終了しますか？",
    focusMusic: "フォーカスミュージック",
    focusMusicError: "申し訳ありません、フォーカスミュージックを再生できませんでした",
    focusNotes: "フォーカスノート",
  },
  toDos: {
    toDos: "タスク",
    todoList: "タスクリスト",
    notes: "メモ",
    drafts: "AI生成",
    notStarted: "未着手",
    inProgress: "進行中",
    completed: "完了",
    current: "現在",
    noMoreTasks: "これ以上タスクはありません",
    noTasksToShow: "表示するタスクがありません\n下にタスクを追加して始めましょう！",
    searchTasks: "タスクを検索",
    noTasksFound: "タスクが見つかりません",
    addATask: "タスクを追加",
    taskAdded: "タスクを追加しました",
    failedToAddTask: "タスクの追加に失敗しました",
    scanPaperWithOCR: "OCRで紙をスキャン",
    quickActions: {
      audio: "音声",
      uploadAudio: "音声をアップロード",
      recordAudio: "音声を録音",
      upgradeRequired: "アップグレードが必要です",
      upgradeMessage:
        "音声とOCR機能はフォーカスベアProで利用できます。アップグレードしてこれらの強力な生産性ツールをロック解除してください。",
      ocrUpgradeMessage:
        "OCRスキャンはフォーカスベアProで利用できます。アップグレードして写真やドキュメントからタスクを抽出してください。",
    },
    ocr: {
      modalTitle: "OCRで紙をスキャン",
      reviewModalTitle: "抽出されたタスクを確認",
      title: "タスクリストをスキャン",
      description:
        "この機能は手書きまたは印刷されたタスクリストの写真からタスクを抽出できます。フォトライブラリから画像を選択するか、新しい写真を撮影できます。",
      reviewTitle: "抽出されたタスクを確認",
      reviewDescription: "リストに追加するタスクを選択してください。後で編集できます。",
      selectSource: "写真ソースを選択",
      selectSourceDesc: "画像を選択するオプションを選んでください",
      takePhoto: "カメラ",
      chooseFromGallery: "フォトライブラリ",
      capturePhoto: "続行",
      processing: "画像を処理中...",
      uploading: "画像をアップロード中",
      error: "OCRエラー",
      processingError: "画像の処理に失敗しました。もう一度お試しください。",
      noTodosSelected: "タスクが選択されていません",
      selectAtLeastOne: "少なくとも1つのタスクを選択してください。",
      createTodos: "選択したタスクを作成",
      completed: "OCR処理完了",
      completedDesc: "タスクが正常に抽出されました！",
    },
    audio: {
      processing: "音声を処理中...",
      completed: "音声処理完了",
      completedDesc: "タスクが正常に抽出されました！",
      addByAudio: "音声で追加",
      record: "録音",
      upload: "アップロード",
      recorded: "録音完了",
      sendOrDiscard: "タップして送信、または閉じて破棄",
    },
    due: "期限",
    dueDate: "期限日",
    exactDate: "日付を選択",
    TOP: "TOP - タスク優先度スコア",
    TOPPrioritization: "TOP優先順位付け",
    timeline: "タイムライン（期限日）",
    project: "プロジェクト",
    projects: "プロジェクト",
    scoreCalculation: "スコア",
    addProjects: "プロジェクトを追加",
    noExistingProjects: "既存のプロジェクトがありません",
    createNewProject: "新しいプロジェクトを作成",
    addATitle: "タイトルを追加",
    addDescription: "説明を追加...",
    addASubtask: "サブタスクを追加",
    reschedule: "再スケジュール",
    rescheduleTitle: "タスクを再スケジュール",
    taskMovedToast: "タスクを「{status}」に移動しました",
    sortBy: "並び替え",
    filterBy: "フィルター",
    filterTasksBy: "タスクをフィルターする条件",
    listOptions: "リストオプション",
    lowToHigh: "TOPスコア低い順",
    highToLow: "TOPスコア高い順",
    groupBy: "グループ化",
    groupedTogether: "「未着手」と「進行中」のタスクを同じグループに表示",
    filterByPerspiration: "労力でフィルター",
    spoonsDesc: "エネルギーレベルに基づいてタスクを選択（スプーン理論）。スプーンが多い＝エネルギーが多い。",
    learnAboutSpoonTheory: "スプーン理論について学ぶ",
    lowSpoons: "低エネルギー",
    fullSpoons: "フルエネルギー",
    perspirationLevel: "労力レベル",
    filterByProject: "プロジェクトでフィルター",
    noFilter: "フィルターなし",
    filterByDueDate: "期日でフィルター",
    toDosDueDate: "期日",
    overdue: "期限切れ",
    thisWeek: "今週",
    nextWeek: "来週",
    deleteTask: "タスクを削除",
    deleteTaskDesc: "このタスクを削除してもよろしいですか？",
    deleteSubtask: "サブタスクを削除",
    deleteSubtaskDesc: "このサブタスクを削除してもよろしいですか？",
    dueIn: {
      aFewDays: "2日後",
      nextWeek: "1週間後",
      twoWeeks: "2週間後",
      aMonth: "1ヶ月後",
      aYear: "1年後",
      aYearDescription: "（笑、実際にはやらないでしょう）",
    },
    outcome: {
      outcome: "成果",
      whoCares: "どうでもいい",
      kindOfImportant: "まあまあ重要",
      bigDeal: "重要",
      huge: "非常に重要",
      mindBlowing: "超重要",
    },
    perspiration: {
      perspiration: "労力",
      fiveMinuteJob: "5分の作業",
      fifteenMinutesWork: "15分の作業",
      halfAnHour: "30分",
      anHour: "1時間",
      halfADay: "半日",
      aDay: "1日",
      aWeek: "1週間",
    },
    searchOrCreateProject: "プロジェクトを検索または作成",
    noMatchingProjects: '一致するプロジェクトがありません。エンターキーを押して "{search}" を作成します',
  },
  overview: {
    morningRoutine: "朝のルーティン",
    eveningRoutine: "夕方のルーティン",
    noTasksCta: "まだタスクがありません。<bold>タスクを追加</bold>して始めましょう。",
    noHabitsCta: "まだ習慣がありません。<bold>習慣を追加</bold>して始めましょう。",
    topTasksToday: "今日の重要タスク",
    focusModeTitle: "フォーカスモード",
    newFocusSession: "新しいセッション",
    focusActive: "アクティブなセッション",
    focusInactive: "アクティブなセッションなし",
    routineCompletedShort: "✓ 完了",
    routineCompletedMessage: "すべての習慣を完了しました！素晴らしい！🎉",
    routineProgress: "{completed}/{total}",
    deadlinePrefix: "期限：{date}",
  },
  networkError: {
    ifTheProblemPersists: "問題が解決しない場合は、サポートに直接お問い合わせください\nsupport@focusbear.io",
    noNetworkAlertTitle: "インターネット接続が切断されました",
    retrying: "再試行中",
    connectionError: "インターネット接続が不安定です",
    connectionErrorMessage: "接続を確認してください",
    connectionErrorLongMessage:
      "サーバーへの接続に問題があります。$t(networkError.connectionErrorMessage)。$t(networkError.ifTheProblemPersists)",
    apiError: "問題が発生しました",
    apiErrorMessage: "後でもう一度お試しください",
    apiErrorLongMessage:
      "リクエストの処理中に問題が発生しました。$t(networkError.apiErrorMessage)。$t(networkError.ifTheProblemPersists)",
    internalError: "内部エラー",
    internalErrorMessage: "問題が発生しました :(",
    internalErrorLongMessage: "申し訳ありません、重大なエラーが発生しました。$t(networkError.ifTheProblemPersists)",
  },
  manageAllowedApps: {
    searchPlaceholder: "インストール済みアプリを検索",
  },
  addNoteModule: {
    addNote: "メモを追加",
    placeholder: "ここにメモを追加...",
    saveNote: "メモを保存",
    automaticallySave: "メモは自動的に保存されます",
  },
  permissionWarning: {
    usageAccessTitle: "気が散るものをブロックするために使用状況アクセス権限が必要です",
    deviceUsagedescription:
      "集中中や習慣実行中に気が散るアプリをブロックするには、使用中のアプリを確認するための「使用状況アクセス」権限が必要です",
    overlayTitle: "気が散るものをブロックするためにオーバーレイ権限が必要です",
    overlayDescription:
      "集中中や習慣実行中に気が散るアプリをブロックするには、使用中のアプリを確認し、許可されていないアプリの警告を表示するための「オーバーレイ」権限が必要です",
    privacyNoteTitle: "プライバシーに関する注意",
    privacyNoteDesc:
      "使用しているアプリやウェブサイトを記録することはありません。リアルタイムでのブロックにのみ使用します。",
    grantAccess: "許可",
  },
  onboarding: {
    nextStep: {
      upNext: "次：{step}",
      usagePermission: "使用状況権限",
      overlayPermission: "オーバーレイ権限",
      focusSession: "フォーカスセッション",
      microBreak: "マイクロブレイク",
      allDone: "すべて完了",
      screenTimePermission: "スクリーンタイム権限",
    },
    wantToPersonalise: "カスタマイズしますか？",
    wantToPersonaliseDescription: "デフォルトの代わりに独自の習慣を設定します。",
    personalise: "カスタマイズ（5分）",
    onboarding: "オンボーディング",
    letsDoIt: "始めましょう",
    replay: "リプレイ",
    instructionVideo: "説明動画",
    welcomeAboard: "ようこそ！",
    lookingForwardToHelp: "健康的な習慣と集中作業を始める時間です。",
    getStarted: "始める",
    allDone: "すべて完了！",
    habitPackSelectionNotice:
      "次に、朝と夕方のルーティンの習慣を選びましょう。\n\n\n<bold>心配しないでください</bold>後でいつでも調整できます。",
    installDesktopApp: "デスクトップアプリをインストール",
    installDesktopAppDesc:
      "フォーカスベアはMacとWindowsでも動作します。コンピューターをお持ちの場合は、<bold>focusbear.io</bold>からアプリをダウンロードして、フォーカスセッションと習慣を同期してください。",
    cutoffTimeWarning: "テクノロジーオフ時間は仕事終了時間（{time}）より後にする必要があります。",
    howFocusBearWork: "フォーカスベアの使い方",
    habitAndRoutine: "習慣とルーティン",
    habitAndRoutineDescription: "脳と体を活性化する習慣で<bold>目標を達成</bold>しましょう",
    distractionBlocking: "気が散るものをブロック",
    distractionBlockingDescription:
      "フォーカスベアは<bold>アプリ</bold>と<bold>ウェブサイト</bold>をブロックして作業を完了するのを助けます",
    todoList: "タスクリスト",
    todoListDescription:
      "フォーカスベアのタスクリストで<bold>計画</bold>、<bold>優先順位付け</bold>、<bold>進捗管理</bold>",
    andMuchMore: "それだけではありません",
    andMuchMorePoints: [
      "コンピューターでも動作",
      "ポモドーロテクニック",
      "チェックリストと動画付きの高度な習慣",
      "朝と夕方のルーティン",
      "休憩リマインダー",
      "楽しいクマの絵文字",
    ],
    andMuchMoreDescription: "<bold>さらに多くの機能...</bold>",
    end: "終了",
    habitAI: "AIを使って\nタスクを整理",
    habitAIDescription: "フォーカスベアは人工知能を使って<bold>タスクを整理</bold>するのを助けます",
    learnAboutFeatures: "機能について学ぶ",
    setupHabitsTitle: "より集中するために習慣を整えましょう",
    setupHabitsCta: "習慣を設定する",
    habitsPirateCopy: "良い習慣は一日中あなたの集中力を鋭く保ちます。",
    habitImportPirateCopy: "海の魔法であなたの習慣を船に連れてきます。",
    habits: {
      sleep: "睡眠",
      meditate: "瞑想",
      exercise: "運動",
    },
    habitList: {
      nayLabel: "いいえ - いくつか提案してほしいです",
      ayeLabel: "はい - すでにいくつかの習慣があります",
    },
  },
  goals: {
    habitImport: {
      title: "習慣をインポート",
      description: "画像から習慣をインポートするか、音声で録音してください",
      importFromImage: "画像からインポート",
      recordVoice: "音声を録音",
      stopRecording: "録音を停止",
      selectSource: "ソースを選択",
      selectImageSource: "習慣のインポート方法を選択してください",
      takePhoto: "写真を撮る",
      chooseFromGallery: "ギャラリーから選択",
      completed: "習慣をインポートしました！",
      completedDesc: "習慣が正常にインポートされました",
      error: "インポートエラー",
      processingError: "インポートの処理に失敗しました。もう一度お試しください。",
      recordingError: "音声の録音に失敗しました。もう一度お試しください。",
      processing: "インポートを処理中...",
      cancelRecording: "録音をキャンセル",
    },
    addHabitList: {
      title: "習慣リストを追加",
      description: "習慣リストをアップロードするか、目標を教えてください。AIがフォーカスベアアプリに追加します。",
      uploadScreenshot: "写真をアップロード",
      recordVoiceNote: "音声メモを録音",
      typeThemIn: "入力する",
      or: "または",
      haveHabitListQuestion: "インポートする習慣リストをお持ちですか？",
      importHabits: "習慣をインポート",
      confirmScreenshotUpload: "画像を確認",
      confirmScreenshotUploadDesc: "これがアップロードしたい画像ですか？",
    },
    boostProductivity: "🚀 生産性を向上",
    boostProductivityDescription: "（仕事、勉強、タスク）",
    improveMentalHealth: "🧘 メンタルヘルスを改善",
    improveMentalHealthDescription: "（ストレス、睡眠）",
    improvePhysicalHealth: "🏋️‍♂️ 健康とフィットネスに集中",
    improvePhysicalHealthDescription: "（運動、栄養）",
    manageTask: "🏡 家事を管理",
    manageTaskDescription: "（掃除、雑用）",
    otherSpecify: "✏️ その他",
    otherSpecifyDescription: "（具体的に：__）",
    strengthenRelationShip: "❤️ 人間関係を強化",
    strengthenRelationShipDescription: "（家族、友人）",
    achievement_placeholder: "目標を教えてください",
    enableFeatures: "どの機能を有効にしますか？",
    doOurBest: "目標達成をお手伝いします。フォーカスベアのどの機能をオンにしますか？",
    achievementWithFocusBearDesc: "主な目標は何ですか？",
    achievementWithFocusBearDescTooltip: "目標達成に役立つ習慣を提案します",
    help_me_develop: "健康的な習慣を身につける",
    help_me_stay: "仕事に集中する",
    help_me_develop_tooltip:
      "フォーカスベアは朝と夕方のルーティンで健康的な習慣（瞑想、運動、日記など）をガイドします。",
    help_me_stay_focused_tooltip: "フォーカスベアは作業中に気が散るものをブロックして、集中作業ができるようにします。",
    blockComputerTitle: "コンピューターでも気が散るものをブロックしますか？",
    blockComputerQuestion: "コンピューターでも気が散るものをブロックしますか？",
    organize_tasks_using_ai: "AIでタスクを整理",
    organize_tasks_using_ai_tooltip: "フォーカスベアはAIを使ってタスクを整理できます",
    what_are_you_hoping_focus_bear_can_do: "フォーカスベアに何を期待していますか？",
    what_are_you_hoping_focus_bear_can_do_placeholder: "フォーカスベアに期待することを教えてください",
    explore_the_app_first: "まずアプリを探索する",
    setup_habits: "習慣を設定",
    setup_habits_question: "今すぐ習慣を設定しますか（約3分）、それともまずアプリを探索しますか？",
    featureRequestReceived:
      "フィードバックありがとうございます！あなたのアイデアがフォーカスベアをより良くするのに役立ちます。",
  },
  goalsSteps: {
    goals: "目標",
    routine: "ルーティン",
    timing: "タイミング",
  },
  habit: {
    habitPack: "習慣を選択",
    autostart: "自動開始",
    habitAutoStart: "{countdown}後に開始",
    habitSkipForToday: "今日の習慣をスキップしました",
  },
  setupTime: {
    fineIfLaterOrSooner: "少し早くても遅くても大丈夫です - おおよその時間を入力してください",
    morningRitualStart: "その時間に朝のルーティンが始まります",
    setStartupTime: "開始時間を選択",
    chooseTheAbsoluteEarliest: "何時に起きますか？",
    setShutdownTime: "仕事や勉強を終える時間は？",
    setSleepTime: "何時に寝たいですか？",
    focusBearWillTakeOver: "フォーカスベアがブロックを一時停止して\nリラックスできるようにします！",
    subDescriptionFocusBearWillTakeOver: "夕方のルーティンは{sleep_time}に開始\n（30分のバッファを含む）",
    focusBearWillTakeOverToolTip:
      "次の画面で就寝時間を選択します。フォーカスベアは就寝前に再び気が散るものをブロックして、よく眠れるようにします。",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}：自由時間",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}：夕方のルーティンと就寝",
    subDescriptionTooltipText: "{sleep_time} - {startup_time}：スマホ禁止時間（睡眠時間）",
    distractionBlockDesc: "気が散るものをブロック - 就寝準備",
    techCurfewQuestion: "よく眠れるように夜のテクノロジー禁止時間を設定しますか？",
    techCurfewTooltip: "フォーカスベアは夕方にスマホの気が散るアプリをブロックして、よく眠れるようにします",
    bedtimeForScreens: "スクリーンの就寝時間？",
    bedtimeForScreensSubtitle: "休息のためにスマホを早めに休ませますか？",
    noThanks: "いいえ、結構です",
    yesPhoneWrecksSleep: "はい - スマホが睡眠を妨げています！",
    whatTimeGetOffTech: "夕方何時にテクノロジーをオフにしますか？",
  },
  blockList: {
    title: "習慣やフォーカスセッション中にスマホを安全に",
    subTitleAndroidBlockList: "習慣実行中やフォーカス中にブロックする気が散るアプリを選択",
    buttonAndroidBlockList: "気が散るものを選択",
    subTitleIos: "習慣実行中やフォーカス中にブロックする気が散るアプリを選択",
    buttonIos: "気が散るものを選択",
  },
  editFriction: {
    frictionTooltipDescription:
      "もちろんあなたは規律正しい人ですが、時々習慣をスキップしたり、気まぐれで気が散るブロックを止めたくなることがあるかもしれません。衝動的な考えを遅らせるために追加の「摩擦」を設定できます。高摩擦モードを有効にすると、気が散るブロックを停止する前に数秒待つように求められます。",
    frictionForSkippingHabits: "習慣スキップの摩擦",
    reallyEasy: "とても簡単 - 急いでいる時に習慣や休憩をスキップできるようにしたい",
    makeItHardToSkip: "スキップを難しくする - そうしないとほとんどの場合習慣や休憩をスキップしてしまう",
    appBlocking: "気が散るものをブロック",
    blockDuringDaytime: "仕事中に気が散るアプリをブロック",
    reallyEasyDescription: "すぐに気が散るブロックを停止できます",
    makeItHardToSkipDescription:
      "衝動的にブロックをオフにするのを避けるため、フォーカスベアは短いカウントダウンタイマーを表示して、気が散るアプリにアクセスすべきかどうか再考するよう促します。",
  },
  strictness: {
    setPassword: "パスワードを設定",
    setPasswordDescription:
      "習慣を守るのが難しい場合は、同居人やパートナーにパスワードを設定してもらいましょう。パスワードなしでは習慣をスキップできなくなります。",
    enterConfirmPasswordHint: "パスワードを確認",
    askForPassword: "パスワードを要求",
    whenRequirePasswordDescription: "いつパスワードを要求しますか",
    changingSettings: "設定の変更",
    postponingMorningRoutine: "朝のルーティンの延期/スキップ",
    postponingEveningRoutine: "夕方のルーティンの延期/スキップ",
    postponingAfterCuttOffTime: "カットオフ時間後の夕方ルーティンの延期/スキップ",
    usingPhoneLateNight: "深夜のスマホ使用",
    relaxFocusMode: "リラックスフォーカスモードの使用を許可",
    suggestion: "提案",
  },
  subscription: {
    upgrade: "アップグレード",
    restorePurchases: "購入を復元",
    restorePurchasesError: "レシートがありません",
    restorePurchasesError2: "問題が発生しました。後でもう一度お試しください。",
    personalizedHabit: "パーソナライズされた習慣ルーティン",
    productivityBoosting: "生産性を高める休憩",
    customizedFocus: "カスタマイズ可能なフォーカスモード",
    automaticGoals: "自動目標追跡",
    cancel: "自動更新をキャンセル",
    subscription: "サブスクリプション",
    trialActive:
      "トライアルは{day}日間続きます。ご安心ください、トライアル終了時に課金されることはなく、事前にクレジットカードも必要ありません",
    trialActiveShort: "トライアル：残り{day}日",
    getSubscriptionPlan: "サブスクリプションプランを取得してアプリを使用し、すべての機能をロック解除",
    subscriptionPlanPrice: "月額<bold>{amount}</bold>のみで続行",
    benefit: "月額プランに含まれるもの",
    doesSubscriptionAutoRenew: "サブスクリプションは自動更新されますか？",
    subscriptionAutoRenew:
      "この月額プランは、現在の期間終了の少なくとも24時間前に自動更新をオフにしない限り、自動的に更新されます。アカウントは現在の期間終了の24時間以内にサブスクリプション価格（{amount}）で更新のために課金されます。ストアのアカウント設定からいつでもサブスクリプションを管理またはキャンセルできます。",
    thankYouForSubscribing:
      "ご登録ありがとうございます。フォーカスベアのすべての機能をご利用いただけます\n\nサブスクリプションは<bold>{day}</bold>日後に期限切れになります",
    thankYouForSubscribingGuestMode:
      "ご登録ありがとうございます！フォーカスベアのすべての機能を引き続きご利用いただくには、サインインしてこの画面でサブスクリプションを復元してください。",
    thanksForSubscribingShort: "ご支援ありがとうございます 🎉",
  },
  editHabit: {
    okay: "OK",
    error: "エラー",
    unableToSaveSettings:
      "問題が発生しました。大変申し訳ありません。エンジニアリングチームに通知され、できるだけ早く修正します。24時間以内に連絡がない場合は、support@focusbear.ioにメールしてください。",
    goingBack: "設定メニューに戻ろうとしています。変更を加えた場合は、「習慣を保存」ボタンをタップしてください。",
    continue: "続行",
    cancel: "キャンセル",
    warning: "警告",
    restartingIn: "{seconds}秒後にフォーカスベアを再起動中...",
    settingsSavedSuccessfully: "習慣を保存しました",
  },
  shareLogs: {
    pleaseWriteFeedback: "フィードバックメッセージを入力してください",
    enterFeedBack: "フィードバックを入力",
    logsShared: "ありがとうございます！フィードバックレポートがサポートチームに共有されました。",
    submitAnother: "別のものを送信",
    errorUploading:
      "ログのアップロード中にエラーが発生しました。安定したインターネット接続を確認して、もう一度お試しください。$t(networkError.ifTheProblemPersists)",
    errorZipCreation:
      "ファイルの処理中に問題が発生しました。もう一度お試しください。$t(networkError.ifTheProblemPersists)",
  },
  impact_reporting: {
    title: "睡眠と気分を分析",
    description:
      "睡眠と気分を追跡して、フォーカスベアがあなたの生活にプラスの影響を与えているか確認しますか？これにより、アプリの影響に関する（匿名の）データを提供していただけると、私たちにも役立ちます。",
    subtitle: "収集するデータ",
    bulletPoints: "● 睡眠時間\n● 気分とエネルギーレベル\n● 一日の終わりにどれだけ生産的だったか",
    okSure: "はい、お願いします",
    noThanks: "いいえ、結構です",
  },
  privacyModal: {
    heading: "プライバシーとセキュリティ",
    notShareData:
      "私たちはあなたのプライバシーとセキュリティを非常に重視しています。あなたのデータを共有することは決してありません。",
    doNotLog: "• どのウェブサイトやアプリを訪問したかを記録することはありません。",
    chooseToBlock:
      "• ただし、気が散るアプリをブロックしたい場合は、すべてのデバイス間で設定を同期するために、それらのアプリ名をデータベースに保存する必要があります。",
    dataEncrypted: "• あなたのデータは暗号化されており、他の誰にも見せることはありません。",
    moreDetails:
      "詳細については、<bold>プライバシーポリシー</bold>を参照するか、support@focusbear.ioにメールしてください",
    accept: "承認",
  },
  pushNotiPermission: {
    title: "通知を許可",
    description: "習慣を守り、会議に時間通りに出席するようリマインドできます。",
  },
  distractionBlockingReason: {
    notLoggedIn: "ブロック無効：ログインしていません",
    postponeActivated: "ブロック無効：一時停止が有効です",
    focusModeActivated: "ブロック有効：フォーカスモードが有効です",
    firstDay: "ブロック無効：初日 - ルーティンがまだ有効化されていません",
    otherReason: "ブロック有効：ルーティンの時間です",
    daytimeBlockingEnabled: "ブロック有効：朝のルーティンは完了しましたが、日中ブロックが有効です",
    blockedBySchedule: "ブロック有効：ブロックスケジュールが有効です",
    defaultCase: "ブロック無効：気が散るブロックが無効です",
    withinCutoffTimeAndShutdownTime: "ブロック無効：{cutoff_time}まで自由時間です",
    permissionNotGranted: "ブロック無効：権限が付与されていません（タップして修正）",
    afterCutoffTime: "ブロック有効：就寝前にリラックスする時間です",
    afterCutoffTimeAndEveningRoutineFinished: "ブロック有効：就寝時間です",
    detailedCutOffSleepTimeBlockingReason:
      "{cutoff_time}から気が散るものがブロックされ、よく眠れます。朝のルーティンは{startup_time}に開始するよう設定されています。朝のルーティンを終えると、ブロックが停止します。",
  },
  blocking: {
    blockingType: "ブロックタイプ",
    allowList: "許可リスト",
    blockList: "ブロックリスト",
    allowListDescription:
      "習慣実行中やフォーカス中に許可するアプリを選択してください。それ以外はすべてブロックされます。",
    blockListDescription:
      "習慣実行中やフォーカス中にブロックする気が散るアプリを選択してください。それ以外はすべて許可されます。",
    appBlockList: "アプリブロックリスト",
    appAllowList: "アプリ許可リスト",
    blockAtLeastOne: "気が散らないように、少なくとも1つのアプリを選択してください",
    socialFilterTitle: "ソーシャル",
    newsFilterTitle: "ニュース",
    gamesFilterTitle: "ゲーム",
    miscFilterTitle: "その他",
    recommendedSectionListTitle: "ブロック推奨アプリ",
    otherSectionListTitle: "その他のアプリ",
    freeAppLimitTitle: "申し訳ありません、無料版では最大5つのアプリのみブロックできます",
    freeAppLimitDesc:
      "無料版では5つのアプリのみブロックできます。フォーカスベアProを購入すると、開発をサポートし、生産性を向上させる新機能を構築できます 🙂",
    Success: "設定を保存しました",
    saveSuccess: "アプリ設定が正常に保存されました",
  },
  permissionExplanation: {
    distractionGetBlockedWhen: "気が散るものがブロックされるタイミング：",
    title: "気が散るブロックの権限を設定",
    description: "フォーカスベアは仕事中、睡眠中、習慣実行中に気が散るものをブロックできます",
    workTask: "• 仕事や勉強中に作業を完了できるように ⚒️",
    routineTask: "• 朝と夕方のルーティン中に習慣を実行できるように 🧘",
    sleepTask: "• 睡眠中に実際に眠れるように 😴",
    toggleOption: "デフォルトでは、いつでも気が散るブロックをオフにできます。",
    friendOption: "（ただし、友人にパスワードを設定してもらって難しくすることもできます）",
    necessaryPermission:
      "使用状況権限：気が散るアプリを開いたかどうかを検出するため\n\nオーバーレイ権限：気が散るブロックを実行するため",
  },
  blockingPermissionIntro: {
    introTitle: "気が散るブロックを設定して、僕があなたの相棒になれるようにしよう 🐻",
    introPrimary: "ブロックを設定する",
    introBubble: "だいたいこんな感じに\n見えるよ！",
    howItWorksTitle: "予定されたフォーカスタイムの間、集中の邪魔になるアプリをそっとブロックします。",
    howItWorksBody: "コントロールはあなたのままです。いつでも一時停止・調整できます。",
    howItWorksPrimary: "いいね",
    howItWorksBubble: "つぎに「続行」をタップしてもらうよ。",
    screenTimeCongratsTitle: "さすが！クマの手さばきがお見事です。",
    whatYouNeedTitle: "そのために、あなたのスマホでいくつか権限をもらう必要があります。",
    whatYouNeedPrimary: "続行",
    whatYouNeedBubble: "たとえば、寝ているあいだに気が散るアプリをブロックできます。",
    scheduleCreatedTitle: "ばっちり。これであなたはルーティンの達人です。",
    scheduleCreatedPrimary: "進む",
    scheduleCreatedBubble: "あとからアプリの中でいつでも編集できます！",
    finishTitle: "すばらしい！これで一緒に道からそれないようにやっていけます ✨",
    finishPrimary: "完了",
    androidIntroTitle: "気が散るブロックを設定して、僕があなたの相棒になれるようにしよう 🐻",
    androidUsageTitle:
      "まずは、どのアプリを使っているかを見る必要があります。「使用状況へのアクセス」をオンにしてください。",
    androidUsagePrimary: "設定を開く",
    androidUsageBubble: "このトグルをここで探してみてね。",
    androidOverlayTitle: "このような吹き出しを表示するために「オーバーレイ」の権限を使います 💭",
    androidOverlayPrimary: "設定を進める",
    androidOverlayBubble: "ちょっとだけ背中を押させてね！",
    androidPermissionVisualTitle: "権限画面はこんな見た目です。",
    androidPermissionVisualPrimary: "アクセスを有効にする",
    androidPermissionVisualBubble: "一緒に\n探しにいこう？",
    androidProceedPrimary: "進む",
    androidScheduleSetupTitle:
      "いいね！自動のブロックスケジュールを作って、決まった時間に僕が声をかけられるようにしよう ⏰",
    androidScheduleSetupPrimary: "スケジュールを設定する",
    androidScheduleSetupBubble: "たとえば、寝ているあいだに気が散るアプリをブロックできます。",
    holdOnTitle: "Hold on a minute!",
    captainBearMessage: "Arr... if you want to focus better, you've got to get your habits shipshape first.",
  },
  grantPermission: {
    title: "アプリをブロックするには権限が必要です",
    description: "ご安心ください、いつでも気が散るブロックを一時停止できます",
    needHelp: "ヘルプが必要ですか？",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "ブロックを有効に保つ",
    description:
      "バッテリー最適化を解除して、フォーカスベアがバックグラウンドでアプリをブロックし続けられるようにします。",
    warning: "これにより少しバッテリーを消費しますが（それほど多くはありません）。",
    keepFocusBearPoweredUp: "フォーカスベアを稼働させ続ける",
  },
  launcher: {
    title: "アプリ",
    morning: "🔆 朝",
    evening: "🌙 夕方",
    play: "🥳 遊び",
    work: "🔨 仕事",
    setAppLabel: "{appName}のカテゴリを選択",
    search: "アプリを検索",
    noAppsFound: "アプリが見つかりません",
    setAsDefaultLauncher: "デフォルトランチャー",
    restricted: "制限中",
    restrictedMessage: "{appName}は制限されています。ルーティンに集中してください",
    stopBlocking: "ブロックを一時停止",
    openAppMenuToolTip: "ここをタップしてアプリメニューを開く",
  },
  DND: {
    duringFocusSessions: "フォーカスセッション中",
    duringHabits: "習慣と睡眠中",
  },
  bearsona: {
    explanation:
      "どんなタイプのクマにモチベーションを上げてもらいたいですか？フォーカスベアはそれに応じてトーンを変えます",
    title: "ベアソナ",
    choose: "ベアソナを選択",
    useCustomLanguage: "{customLanguage}を使用",
    useCustomLanguageConfirmation: "{customLanguage}を言語として使用しますか？",
    useCustomLanguageConfirmationDesc: "警告：楽しいですが、少し混乱するかもしれません",
    confirmUseCustomLanguage: "英語で話して",
    cancelUseCustomLanguage: "やっぱりやめます",
    name: {
      default: "OGベア",
      pirate: "キャプテンベア",
      focus: "フォーカスベア",
      jester: "ジェスターベア",
      sassy: "サッシーベア",
      cheerleader: "チアリーダーベア",
    },
    description: {
      default: "あなたのフレンドリーなクマアシスタント",
      pirate: "ヤーッ！キャプテンベアがお仕えします",
      focus: "集中は私のスーパーパワー",
      jester: "ジェスターベアは遊ぶ準備ができています",
      sassy: "サッシーベアが登場",
      cheerleader: "チアリーダーベアがあなたを応援しています！",
    },
  },
  blockUrl: {
    addSomeSuggestedUrls: "ほとんどの人が気が散ると感じるウェブサイトを追加しました。必要に応じて削除してください",
    unblockableUrlTitle: "URLをブロックできません",
    unblockableUrlMessage: "このURLはブロックできません。別のURLを入力してください。",
    freemiumLimit: "無料版では3つのURLのみブロックできます。",
    freemiumLimitDescription: "Pro版にアップグレードして無制限のURLをブロック。",
    title: "ウェブサイトをブロック",
    description: "どのサイトで時間を無駄にしていますか？",
    inputPlaceholder: "ブロックするURLを入力...",
    urlExistsTitle: "URLは既に存在します",
    urlExistsMessage: "別のURLを入力してください。",
    invalidUrlTitle: "無効なURL",
    invalidUrlMessage: "有効なURLを入力してください。",
    saveSuccess: "ブロックURLが正常に保存されました。",
    saveError: "ブロックURLの保存に失敗しました。もう一度お試しください。",
  },
  accessibility: {
    title: "アクセシビリティ権限",
    howToEnableAccessibility: "アクセシビリティ権限を有効にする方法",
    enableAccessibility: "アクセシビリティを有効にする",
    permissionRequired: "アクセシビリティ権限が必要です",
    permissionDescription:
      "ウェブサイトもアプリと同じくらい気が散ることがあります。アクセシビリティ権限を有効にすると、フォーカスベアはウェブサイトもブロックできます。スマホに警告が表示されますが、それは正常です！",
    whatWeDo: "私たちが行うこと：",
    checkSites: "ブロックリストを確認",
    checkSitesDescription: "ウェブサイトがあなたが設定したブロックリストにあるかどうかを確認します。",
    zeroDataTracked: "それだけです。追跡なし、データ保存なし。",
  },
  passwordRules: {
    passwordRequirements: "パスワードには少なくとも1つの数字、1つの大文字、1つの特殊文字が必要です",
    minLength: "最低8文字",
    includeNumbers: "数字を含む",
    includeLowerCase: "小文字を含む",
    includeUpperCase: "大文字を含む",
    includeSpecialChars: "特殊文字を含む",
  },
  permissions: {
    privacyFirst: "私たちはあなたのプライバシーを非常に重視しています",
    notTracked: "フォーカスベアは以下を<bold>追跡しません</bold>：",
    anythingType: "入力内容",
    anythingTypeDescription: "パスワード、メッセージ、メール",
    browserHistory: "閲覧履歴",
    browserHistoryDescription: "訪問したウェブサイトを見たり保存したりすることはありません",
    helpStayFocused: "集中力を維持するお手伝いをします！",
    revokeHealthPermission: "ヘルス権限を取り消す",
    revokeHealthPermissionDescription:
      "申し訳ありませんが、Appleの制限により、ヘルス権限を取り消すことができません。取り消したい場合は、「ヘルス」アプリから取り消してください。",
    healthGroup: "ヘルスと睡眠",
    healthGroupDescription: "フォーカスベアはあなたの健康と睡眠データを追跡して、健康と睡眠の改善をサポートします。",
    areYouSure: "この権限を取り消してもよろしいですか？",
    revokePermissionDescription: "これによりアプリへの権限が取り消されます。",
    experimentalGroup: "実験的",
    experimentalDescription:
      "フォーカスベアをデフォルトのホーム/ランチャーアプリに設定すると、スマホを開いたときにすぐに習慣が表示されます。また、気が散るアプリが目立たなくなります。",
    blockingAppsGroup: "アプリブロック用",
    routineUpdatesGroup: "ルーティン更新用",
    routineUpdatesGroupDescription: "フォーカスベアは朝または夕方のルーティンの時間になると通知を送信します",
    urlBlockingGroup: "URLブロック用",
    urlBlockingGroupDescription:
      "ウェブサイトをブロックしたい場合、フォーカスベアは気が散るサイトを訪問したときに検出してリダイレクトするためにアクセシビリティ権限が必要です。",
  },
  breathingExercise: {
    title: "呼吸エクササイズ",
    description: "この気が散るアプリを開く前の簡単なマインドフルネスエクササイズ。",
    dontWantToOpen: "{appName}を開きたくない",
    wantToOpen: "{appName}に進む",
    motivational: "おっと！本当に{appName}を開きますか？",
  },
  byPassTimePicker: {
    title: "{app}を開くためにブロックを一時停止",
    duration: "{count}分",
    intention: "{app}で何を達成したいですか？",
    intentionInfo: "気が散るアプリを開くと、目標を見失いがちです。あなたの目標をリマインドします。",
    intentionRequiredError: "続ける前に意図を入力してください。",
  },
  loading: {
    loading: "読み込み中",
    breathingExercise:
      "待っている間、ボックス呼吸法を試してみてください。3秒吸って、3秒止めて、3秒吐いて、3秒止めます。",
    loadingHabit: "習慣ライブラリを読み込み中",
    pleaseWaitLoadHabit:
      "あなたにとって大切なことに基づいて習慣をおすすめします。目標に基づいて、厳選されたライブラリから役立つ習慣を提案します。",
  },
  appUsage: {
    noAppsDetected: "アプリが検出されませんでした",
    seeMore: "もっと見る",
    close: "閉じる",
    usage: "統計",
    title: "統計",
    longTitle: "アプリとヘルス統計",
    lowQualityAppDetected: "低品質なアプリが検出されました。このアプリをブロックリストに追加しますか？",
    yes: "はい",
    no: "いいえ",
    ignore: "無視",
    dailyAppUsage: "アプリスクリーンタイム",
    totalTimeUsed: "合計使用時間",
    doingGreat: "素晴らしい！この調子で頑張りましょう！",
    todayBlockCount: "今日のブロック回数",
    focusBearUsage: "フォーカスベア使用状況",
    topBlockedApps: "最もブロックされたアプリ",
    blockedAppsUsage: "ブロックされたアプリの使用状況",
    timeBlocked: "ブロック回数",
    timeSpent: "使用時間",
    lastUsed: "最終使用",
    noAppsBlocked: "ブロックされたアプリはありません",
    noData: "素晴らしい！まだアプリを使用していません",
    noPermission: "アプリ使用状況権限を許可すると、スクリーンタイム統計を表示できます",
    grantPermission: "使用状況権限を許可",
    overLimit: "おっと！制限を超えています",
    lowQualityScreenTime: "低品質スクリーンタイム",
    highQualityScreenTime: "高品質スクリーンタイム",
    timeUsedAfterCutoff:
      "昨夜の睡眠時間中に<bold>{duration}</bold>スマホを使用しました。\n\n睡眠中にテクノロジーから離れるために、摩擦レベルを上げますか？",
    timeUsedAfterCutoffTitle: "睡眠時間後の使用時間",
    dontShowAgain: "今後表示しない",
    howDistractingIsThisApp: "このアプリはどれくらい気が散りますか？",
    dragToEdit: "ドラッグして編集",
    save: "保存",
    learnMore: "詳細を見る",
    qualityLabel: {
      extremelyDistracting: "非常に気が散る",
      veryDistracting: "とても気が散る",
      slightlyDistracting: "少し気が散る",
      neutral: "中立",
      slightlyProductive: "少し生産的",
      productive: "生産的",
      veryProductive: "非常に生産的",
    },
    qualityDescription: {
      veryDistracting: "常に注意を引き、タスクから脱線させることが多いアプリは「とても気が散る」と見なされます。",
      distracting: "重要な仕事から簡単に引き離し、かなりの時間を消費するアプリは「気が散る」と見なされます。",
      slightlyDistracting:
        "時々集中を妨げるかもしれないが、ある程度の規律で管理できるアプリは「少し気が散る」と見なされます。",
      neutral: "生産性に大きな影響を与えずに実用的な目的を果たすアプリは「中立」と見なされます。",
      slightlyProductive: "健康、学習、または個人の成長に貢献するアプリは「少し生産的」と見なされます。",
      productive: "タスクの達成、整理整頓、効率的な作業を助けるアプリは「生産的」と見なされます。",
      veryProductive: "仕事、健康、または重要な日常機能に不可欠なツールであるアプリは「非常に生産的」と見なされます。",
    },
    loadingMessage: {
      harvesting: "使用データを収集中",
      removingGremlins: "統計のグレムリンを除去中",
      crunchingFormulas: "フォーカス計算式を処理中",
      assemblingMetrics: "進捗指標を組み立て中",
    },
  },
  healthMetrics: {
    title: "ヘルス統計",
    tapToView: "タップしてヘルス指標を表示",
    tapToCollapse: "タップして折りたたむ",
    healthPermissionsRequired: "ヘルス権限が必要です",
    tapToGrantPermissions: "タップしてヘルス権限を許可し、指標を表示",
    sleep: "睡眠",
    activeMinutes: "アクティブ時間",
    steps: "歩数",
    loadingHealthData: "ヘルスデータを読み込み中...",
    error: "エラー: {error}",
    physicalActivityPermissionsRequired: "身体活動権限が必要です",
    tapToGrantPhysicalActivityPermissions: "タップして身体活動権限を許可し、指標を表示",
  },
  participantCode: {
    exitUnicaesStudy: "UNICAES研究を終了",
    enrolUnicaesStudy: "UNICAES研究に登録",
    consentFormTitle: "同意書",
    consentFormDesc: "同意書を読み、研究に同意してください",
    whatsappConsent: "研究の最新情報を週1回WhatsAppメッセージで受け取ることに同意します",
    invalidPhoneNumber: "有効な電話番号を入力してください",
    phoneNumber: "電話番号",
    enterYourPhoneNumber: "電話番号を入力",
    unicasStudy: "UNICAES研究",
    syncManually: "手動で同期",
    facultyOfBusiness: "ビジネス科学部",
    facultyOfEngineering: "工学・建築学部",
    facultyOfHumanities: "科学・人文学部",
    facultyOfHealth: "健康科学部",
    yearLevel1: "1年生",
    yearLevel2: "2年生",
    yearLevel3: "3年生",
    yearLevel4: "4年生",
    yearLevel5: "5年生",
    wrongEmail: "参加者コードがメールアドレスと一致しません。support@focusbear.ioにお問い合わせください",
    invalidName: "名前を入力してください",
    invalidEmail: "有効なUNICAESメールアドレスを入力してください",
    invalidFaculty: "学部を選択してください",
    invalidYearLevel: "学年を選択してください",
    emailAlreadyExists: "このメールアドレスは既に研究に登録されています",
    pleaseCheckEmail: "参加者コードをメールで確認してください",
    register: "登録",
    invalidCode: "無効なコード",
    email: "メール",
    name: "名前",
    faculty: "学部",
    yearLevel: "学年",
    enterYourName: "フルネームを入力",
    enterYourEmail: "UNICAESメールを入力",
    selectFaculty: "学部を選択",
    selectYearLevel: "学年を選択",
    applicationForm: "申込書",
    title: "フォーカスベア",
    description:
      "現在UNICAESでの試験研究の参加者を募集しています。研究に参加してご協力いただける場合は、以下からお申し込みください。研究についての詳細は<hereLink>こちらをクリック</hereLink>するか、{email}までお問い合わせください。",
    moreInfoLink: "こちらをクリック",
    contactEmail: "support@focusbear.io",
    applyButton: "参加を申し込む",
    hasParticipantCode: "参加者コードを持っています",
    enterYourCode: "コードを入力",
    continue: "続行",
    back: "戻る",
    permissionNeededTitle: "権限が必要です",
    permissionNeededDescription:
      "この研究への参加には、データ追跡の権限をオンにする必要があります。フォーカスベアをアンインストールすることで、いつでも研究から撤退できます。",
    uploadScreenshot: "スクリーンショットをアップロード",
    thankYouForJoining:
      "研究にご参加いただきありがとうございます。現在、フォーカスベアの全機能へのアクセスを提供する前に、スマホの使用状況を把握するためのデータを収集しています。研究から撤退したい場合は、フォーカスベアをアンインストールしてください。サポートが必要な場合は、<email>support@focusbear.io</email>までメールでお問い合わせください",
    screenshotUploadReminder:
      "スクリーンタイムのスクリーンショットをアップロードする時間です。以下の手順に従ってください。サポートが必要な場合は、support@focusbear.ioまでお問い合わせください。\n\n手順：\n\n1. 過去1週間のアプリ使用状況のスクリーンショットを撮る\n2. スクリーンショットアップロードボタンをクリック\n3. 画像を選択してアップロード",
    usageDataLastSynced: "使用データの最終同期: {date}",
    whatTimeDoYouGoToSleep: "何時に寝ますか？",
    whatTimeDoYouSleepDescription: "これを使用して、睡眠時間後のスマホ使用状況を追跡します。",
    setupPermissions: "セットアップが必要です",
    setupPermissionsTitle: "アプリ権限を許可",
    setupPermissionsDesc: "フォーカスベアが集中をサポートできるようにする",
    studyTasks: "研究タスク",
    flankerTaskTitle: "フランカータスクを完了",
    flankerTaskDesc: "注意力と集中力をテスト",
    questionnaireTitle: "アンケートを完了",
    questionnaireDesc: "あなたの経験を理解するのに役立ちます",
    screenTime: "スクリーンタイムをアップロードする時間です",
    screenshotUploadSuccess: "正常にアップロードされました",
    imageProcessing: "使用データを確認中...",
    imageProcessed: "スクリーンショットが正常に処理されました",
    imageProcessingFailed: "スクリーンショットの処理に失敗しました",
    checkingStatus: "ステータスを確認中",
  },
  flankerGame: {
    title: "フランカーベアゲーム",
    welcome: "フランカーベアゲームへようこそ！このゲームはあなたの注意力と集中力をテストします。",
    instruction1: "1. 矢印の列が表示されます",
    instruction2: "2. 中央の矢印に集中してください",
    instruction3: "3. 中央の矢印の方向に一致するボタンを押してください",
    instruction4: "4. できるだけ素早く正確に回答してください（各試行3秒）",
    play: "プレイ",
    practiceStart: "仕組みを理解するために、簡単なウォームアップをしましょう！",
    mainStart: "素晴らしい！本番テストが始まります。",
    testProgress: "テスト {current}/{total}",
    ok: "OK",
    timeout: "😢",
    complete: "すべて完了！",
    completeMessage: "ありがとうございます！これであなたの注意力の仕組みを理解するのに役立ちます。",
    practiceComplete: "練習完了！",
    mainInstructions: "では本番テストを行いましょう。各試行に2秒で回答してください。",
    startMain: "本番テストを開始",
    continue: "続行",
  },
  questionnaire: {
    title: "アンケート",
    loadingQuestionnaire: "アンケートを読み込み中",
  },
  routineSuggestion: {
    title: "ルーティン提案",
    generatingRoutine: "ルーティンを生成中",
    loading: "読み込み中",
    breathingExercise: "待っている間、フォーカスベアが習慣づくりをどのようにサポートできるか、この動画をご覧ください。",
    error: "予期しないエラーが発生しました",
    successTitle: "ルーティンが生成されました！",
    successMessage: "目標に基づいてサンプル習慣を作成しました。",
    errorTitle: "おっと！問題が発生しました",
    errorMessage: "現在ルーティンを生成できませんでした。もう一度試すか、手動で時間を設定してください。",
    errorMessageGoals: "問題が発生し、習慣を生成できませんでした。目標を教えてください",
    updateGoals: "目標を教えてください",
    noHabitsTitle: "まだ習慣がありません",
    noHabitsMessage: "インポートから習慣が見つかりませんでした。パーソナライズされた習慣を生成しましょう！",
    morningRoutine: "朝のルーティン",
    eveningRoutine: "夕方のルーティン",
    totalDuration: "合計: {duration}",
    noActivities: "このルーティンに習慣がありません",
    addActivity: "習慣を追加",
    editActivity: "習慣を編集",
    adjustWithAI: "AIで調整",
    createWithAI: "AIで作成",
    adjust: "調整",
    create: "作成",
    aiPrompt: "🐻 これらの習慣はいかがですか？変更したい点を教えてください。",
    aiCreatePrompt: "ゼロから作りたいルーティンを説明してください。例：「朝のスタートルーティンを作って」",
    aiPlaceholder: "例：「瞑想をもっと具体的に」や「簡単なワークアウトを追加」",
    aiError: "習慣の調整に失敗しました。もう一度お試しください。",
    adjusting: "習慣を調整中...",
    creating: "AIで作成中...",
    aiSuccessMessage: "習慣が正常に調整されました。",
    deleteActivityTitle: "習慣を削除",
    deleteActivityMessage: "本当に「{activityName}」を削除してもよろしいですか？",
    activityName: "習慣名",
    enterActivityName: "習慣名を入力",
    duration: "期間",
    minutes: "分",
    seconds: "秒",
    errors: {
      nameRequired: "習慣名は必須です",
      nameTooShort: "習慣名は2文字以上必要です",
      invalidTime: "有効な時間を入力してください",
      timeTooShort: "期間は5秒以上必要です",
    },
    tapToEdit: "タップして編集",
  },
  juniorBearConversation: {
    messageNormalStep1: "やあ、フォーカスベアジュニアだよ！集中をサポートするために呼ばれたんだ。",
    messageNormalStep2: "実は僕、集中するのがあまり得意じゃないんだ 😢 ADHDがあって、いつも気が散っちゃうんだ。",
    messageNormalStep2_5: "おお！わかった、集中マスターさん。何か手伝えることはある？",
    messageNormalStep3:
      "楽しい…じゃなくて気が散るアプリがたくさんあると集中するのが難しいよね。一緒にやらない？一緒に集中しよう！",
    messageNormalStep4: "すごい！一緒に何に取り組みたい？",
    messageNormalStep5: "いいね。パソコンとスマホで一緒に作業できるようにアカウントを設定する？",
    messagePirateStep1: "集中を助けるために呼ばれたのか？キャプテンベア、お前の命令に従うぞ。",
    messagePirateStep1_5: "お前は甥っ子を泣かせたな。だから今度は俺だ — キャプテンベアだ。背筋を伸ばせ、この悪党め。",
    messagePirateStep2:
      "正直に言うと…俺もADHDがあるんだ、多くの立派な海賊と同じようにな。俺の心は錨のない船のようにさまようんだ。",
    messagePirateStep2_5: "ハッ！鋭い頭脳だな。まだ何か助けが必要か？",
    messagePirateStep3:
      "アー、あのキラキラしたアプリは酔っ払ったオウムよりうるさいぜ！一緒にやらないか？お互いに船から落ちないようにしようぜ！",
    messagePirateStep4: "アー、二人で甲板に立つぞ！どんな問題を解決したいんだ？",
    messagePirateStep5: "素晴らしい！パソコンとスマホで一緒に航海できるようにアカウントを設定するか？",
    buttonNormalStep1Primary: "やあ",
    buttonNormalStep1Secondary: "アー、海賊だったらよかったのに…",
    buttonNormalStep2Primary: "僕も！",
    buttonNormalStep2Secondary: "そんな問題はなかったよ",
    buttonNormalStep2_5Option1: "健康的な習慣を続ける",
    buttonNormalStep2_5Option2: "タスクを整理する",
    buttonNormalStep2_5Option3: "あっち行って！子供は嫌い！",
    buttonNormalStep3Primary: "やろう！",
    buttonNormalStep3Secondary: "あっち行って！子供は嫌い！",
    buttonNormalStep4Primary: "次へ",
    buttonNormalStep5Primary: "登録して！",
    buttonNormalStep5Secondary: "いいえ、匿名のままでいます",
    buttonPirateStep1Primary: "アホイ",
    buttonPirateStep1Secondary: "ご挨拶、キャプテン",
    buttonPirateStep1_5Primary: "失礼しました、キャプテン。海の足を保ちます",
    buttonPirateStep2Primary: "ああ…よく錨をなくすんだ",
    buttonPirateStep2Secondary: "俺は違う、ブレインビアードと呼ばれてるんだ",
    buttonPirateStep2_5Option1: "より頑丈な船乗りの習慣を作る",
    buttonPirateStep2_5Option2: "タスクを整理整頓する",
    buttonPirateStep3Primary: "ああ、やろうぜ！",
    buttonPirateStep3Secondary: "アー、海に運命を任せよう",
    buttonPirateStep4Primary: "次へ",
    buttonPirateStep5Primary: "帆を上げろ — 登録だ！",
    buttonPirateStep5Secondary: "海の幽霊のままでいる",
    focusAreaBlockDistractionsNormal: "気が散るものをブロック",
    focusAreaBlockDistractionsPirate: "舵を取りながら集中力を研ぎ澄ます",
    focusAreaHealthyHabitsNormal: "健康的な習慣を続ける",
    focusAreaHealthyHabitsPirate: "より頑丈な船乗りの習慣を作る",
    focusAreaOrganiseTasksNormal: "タスクを整理する",
    focusAreaOrganiseTasksPirate: "タスクを整理整頓する",
  },
  streakCelebration: {
    title: "{streakTypeName}のストリーク！",
    morning: "朝のルーティン",
    evening: "夜のルーティン",
    focus: "フォーカスセッション",
    message: "絶好調です！この調子で続けましょう。",
    day: "日",
    days: "日",
  },
  lateNoMore: {
    title: "ミーティングのリマインダー",
    calendarIntegration: "カレンダー連携",
    calendarTooltip:
      "ミーティングの検出を有効にするには、スマートフォンのカレンダーまたはGoogleカレンダーを接続してください",
    googleCalendar: "Googleカレンダー",
    connected: "接続済み",
    notConnected: "未接続",
    enableReminders: "リマインダー通知",
    calendarPermission: "デバイスのカレンダー",
    calendarPermissionAlreadyGranted:
      "デバイスのカレンダーに接続済みです。スマートフォンの設定からいつでもアクセスを取り消せます",
    calendarPermissionDenied: "スマートフォンの設定でカレンダーへのアクセスを許可してください",
    openSettings: "設定を開く",
    addReminder: "リマインダーを追加",
    durationBefore: "{duration}前",
    whenMeetingStarts: "ミーティング開始時",
    requireMeetingUrl: "ミーティングURL付きの予定のみ",
    requireMeetingUrlDescription: "ミーティングURLが添付されている予定のみを含めます",
    notification1: "まもなくミーティングのはじまりです！🐻",
    notification2: "ミーティングに向かう準備をしましょう！⏰",
    notification3: "ミーティングが近づいています！🚀",
    notificationBody: "「{title}」は{time}に開始します",
    now: "今",
    yourMeetingStartsIn: "ミーティングまであと<highlight>{countdown}</highlight>。準備をしましょう！",
    yourMeetingIsOngoing: "進行中のミーティングがあります。<highlight>今</highlight>参加しましょう！",
    upcomingMeeting: "予定",
    mentallyPrepare: "1. ミーティングの心構えをする",
    howDoYouWantToShowUp: "どのように臨みますか？",
    placeholderHowToShowUp: "落ち着いて、傾聴し、オープンに、協力的に…",
    joinOnTime: "2. 時間どおりに参加する",
    ignoreMeeting: "ミーティングを無視",
    startMeeting: "ミーティングに参加",
    noUpcomingMeetings: "予定されているミーティングはありません",
    noMeetingsDescription: "今後数時間に予定されたミーティングは見つかりませんでした。",
    googleCalendarSource: "元: Googleカレンダー",
    deviceCalendarSource: "元: 端末内カレンダー",
  },
  stats: {
    title: "統計",
    tabs: {
      screentime: "スクリーンタイム",
      otherStats: "その他の統計",
    },
  },
  streak: {
    title: "ストリークが追加されました",
    howItWorks:
      "毎日<bold>フォーカスセッション</bold>を開始し、朝または夜の<bold>習慣を1つ完了</bold>するとストリークが続きます。",
    activeStreak: "アクティブなストリーク",
    activeStreakDesc: "今日Focus Bearを使いました。",
    dueStreak: "ストリークが途切れそうです",
    dueStreakDesc: "昨日Focus Bearを使いました。今日使うとストリークが維持されます。",
    inactiveStreak: "非アクティブなストリーク",
    inactiveStreakDesc: "昨日はFocus Bearを使っていません。",
    motivationTip: "長いセッションより継続が大切です。",
    morningStreak: "朝のストリーク",
    eveningStreak: "夜のストリーク",
    focusModeStreak: "フォーカスモードのストリーク",
    streakIconTitle: "アイコンの意味",
    day_zero: "0",
    day_one: "{count}日",
    day_other: "{count}日",
    morning: "朝",
    evening: "夜",
    focus: "集中",
    days: "日",
  },
  widget: {
    defaultRoutine: "ルーチンなし",
    noReasonProvided: "準備完了！",
    noNextHabit: "予定なし",
    whatsNext: "次は:",
    streakTitle: "ストリーク",
    motivationalQuotes: [
      "「成功とは、日々積み重ねる小さな努力の総和である。」 – ロバート・コリアー",
      "「先に進む秘訣は、始めることである。」 – マーク・トウェイン",
      "「規律とは、今欲しいものと、一番欲しいものを選ぶことだ。」 – エイブラハム・リンカーン",
      "「あなたの未来は、明日ではなく、今日の行動によって作られる。」 – ロバート・キヨサキ",
      "「何事も成し遂げるまでは不可能に見える。」 – ネルソン・マンデラ",
    ],
  },
};
