export default {
  languageName: "Tiếng Việt",
  baseLanguage: "vi",
  blockingSchedule: {
    title: "Lịch Chặn",
    namePlaceholder: "Tên khối chặn",
    startTime: "Từ",
    endTime: "Đến",
    adjustStart: "Điều chỉnh thời gian bắt đầu",
    adjustEnd: "Điều chỉnh thời gian kết thúc",
    daysHeading: "Vào những ngày này",
    chooseApps: "Chọn ứng dụng",
    chooseUrls: "Chọn trang web",
    saveFailedTitle: "Không thể lưu lịch trình",
    saveFailedMessage: "Vui lòng thử lại sau khi chọn ứng dụng để chặn.",
    duplicateNameMessage: "Vui lòng chọn tên duy nhất cho lịch chặn này.",
    focusModeSuffix: "(từ lịch chặn trên di động)",
    defaultName: "💻 Giờ Làm Việc",
    appBlocking: "Chặn ứng dụng",
    websiteBlocking: "Chặn trang web (tùy chọn)",
    accessibilityRequiredForUrls: "Cần quyền trợ năng để chặn trang web.",
    selectionMissing: "Chọn ứng dụng để chặn.",
    noAppsSelected: "Chưa chọn ứng dụng nào",
    urlsSelectionMissing: "Chưa chọn trang web nào",
    urlsSelectionCount_one: "{count} trang web đã chọn",
    urlsSelectionCount_other: "{count} trang web đã chọn",
    urlsDescription: "Thêm trang web để chặn trong lịch trình này",
    selectedUrls: "Trang web đã chọn",
    suggestedUrls: "Trang web gợi ý",
    iOSSelectionCounts: "{applicationsCount} ứng dụng, {categoriesCount} danh mục, {webDomainsCount} trang web",
    androidSelectionCount: "{applicationsCount} ứng dụng đã chọn",
    mode: {
      strict: {
        title: "Chặn nghiêm ngặt",
        subtitle: "Không thể thoát - nhập mật khẩu để mở khóa",
      },
      cooldown: {
        title: "Chặn làm mát",
        subtitle: "Mở khóa sau khi chờ một chút (cho bạn thời gian suy nghĩ lại)",
      },
      gentle: {
        title: "Chặn nhẹ nhàng",
        subtitle: "Tạm dừng chặn ngay lập tức với nguy cơ lướt vô tận 😅",
      },
    },
    removeTitle: "Xóa lịch trình này?",
    removeMessage: "Điều này sẽ xóa vĩnh viễn lịch trình.",
    removeFailedMessage: "Vui lòng thử lại.",
    blockedBySchedule: "Bị chặn theo lịch: {scheduleName}",
    appBlockedBySchedule: "{appName} bị chặn vì lịch chặn {scheduleName} của bạn đang hoạt động",
    blockAllDuringHabits: "Chặn một số ứng dụng trong tất cả thói quen",
    customizeBlocking: "Tùy chỉnh chặn",
    scheduledBlocksTitle: "Khối đã lên lịch",
    scheduledBlocksInfoText: "Tạo khung thời gian lặp lại vào các ngày đã chọn. Bạn có thể thêm nhiều khối.",
    addNewBlock: "Thêm khối",
    habitMorningName: "Thói Quen Buổi Sáng",
    allDays: "Mỗi ngày",
    permissionsRequired: "Yêu Cầu Quyền",
    androidPermissionDescription: "Quyền truy cập sử dụng và quyền phủ lớp là bắt buộc để chặn ứng dụng",
    iOSPermissionDescription: "Quyền Thời Gian Màn Hình là bắt buộc để tạo và quản lý lịch chặn.",
    habitBlocksTitle: "Chặn theo thói quen",
  },
  tabTitle: {
    overview: "Tổng Quan",
    habits: "Thói Quen",
    tasks: "Nhiệm Vụ",
  },
  error: {
    invalidVideoUrl: "URL video đó có vẻ không đúng 😕",
    videoNotFound: "Xin lỗi, chúng tôi không tìm thấy video đó!",
    authenticationErrorName: "Lỗi Xác Thực",
    authenticationErrorMessage: "Ối! Đã xảy ra lỗi xác thực từ phía chúng tôi. Vui lòng thử lại.",
  },
  habitSetting: {
    routine: "Thói Quen",
    selectRoutine: "Chọn thói quen",
    requirement: "Cần làm gì để hoàn thành thói quen này",
    youtubeVideo: "Video YouTube hoặc Vimeo",
    youtubeVideoDescription: "Thêm video để hướng dẫn bạn thực hiện thói quen này",
    enableTimer: "Bật hẹn giờ?",
    timer: "Hẹn Giờ",
    timerDescription: "Đặt thời lượng cho thói quen",
    goal: "Mục Tiêu",
    goalDescription: "Hoàn thành thói quen khi bạn đã đạt được mục tiêu",
    goalPlaceholder: "Chỉ định mục tiêu hoàn thành?...",
    extras: "Bổ Sung",
    noGoalSpecified: "Chưa chỉ định mục tiêu",
    defaultName: "Thói Quen Chưa Đặt Tên",
    allowedApps: "Ứng dụng được phép",
    allowedAppsDescription: "Chọn ứng dụng bạn có thể dùng trong thói quen này",
    selectApps: "Chọn ứng dụng",
    appsSelected: "Đã chọn {count} ứng dụng",
    noAppsSelected: "Chưa chọn",
    openAllowedApps: "Mở ứng dụng được phép",
    launchApp: "Mở",
  },
  common: {
    accept: "Chấp Nhận",
    learnMore: "Tìm hiểu thêm",
    doItLater: "Làm sau",
    later: "Sau",
    termsOfUse: "Điều Khoản và Điều Kiện",
    privacyPolicy: "Chính Sách Bảo Mật",
    email: "Email",
    nickname: "Biệt Danh",
    skip: "Bỏ Qua",
    goToSleep: "Đến giờ ngủ 😴",
    areYouSure: "Bạn có chắc không?",
    loading: "Đang tải...",
    connectionError: "Lỗi kết nối",
    morning: "buổi sáng",
    evening: "buổi tối",
    welcome: "Chào Mừng",
    somethingWrong: "Đã xảy ra lỗi",
    logout: "Đăng Xuất",
    ok: "OK",
    ok_ellipsis: "OK...",
    okay: "OK",
    yes: "Có",
    no: "Không",
    confirm: "Xác Nhận",
    next: "Tiếp Theo",
    cancel: "Hủy",
    delete: "Xóa",
    proceed: "Tiếp Tục",
    resume: "Tiếp Tục",
    retry: "Thử Lại",
    submit: "Gửi",
    resend: "Gửi Lại",
    verify: "Xác Minh",
    edit: "Chỉnh Sửa",
    finished: "Hoàn Thành",
    done: "Xong",
    sec: "giây",
    focusBear: "focus bear",
    tomorrow: "Ngày Mai",
    today: "Hôm Nay",
    yesterday: "Hôm Qua",
    add: "Thêm",
    start: "Bắt Đầu",
    startRoutine: "Bắt Đầu Thói Quen",
    continue: "Tiếp Tục",
    end: "Kết Thúc",
    startActivity: "Bắt đầu {activityName}",
    startTimerActivity: "Bắt đầu {time} {unit} {activityName}",
    Success: "Thành Công!",
    SuccessfullyAddedHabit: "Đã thêm thói quen thành công",
    save_changes: "Lưu thay đổi",
    save: "Lưu",
    saving: "Đang lưu",
    saved: "Đã lưu",
    created: "Đã tạo",
    next_time_format: "[{day} at] h:mm A",
    sure: "Chắc chắn",
    uploadScreenShots: "Tải lên ảnh chụp màn hình \n(Tùy chọn)",
    session_expired: "Phiên Đã Hết Hạn",
    login_again: "Vui lòng đăng nhập lại",
    continue_activity_name: "Tiếp tục {activityName}",
    no_thanks: "Không, Cảm Ơn",
    saveHabitSuccessfully: "{habitName}, vào thói quen {routineName} của bạn",
    couldNotProcessTheRequest: "Không thể xử lý yêu cầu, vui lòng thử lại",
    error: "Lỗi",
    selected: "Đã Chọn",
    all: "Tất Cả",
    viewAll: "Xem tất cả",
    more: "Thêm",
    somethingElse: "Điều khác",
    habit: "Thói quen",
    empty: "Trống",
    clearAll: "Xóa",
    loadingWithoutDot: "Đang tải",
    pleaseWaitPatiently:
      "Vui lòng đợi trong khi chúng tôi tải dữ liệu của bạn. Quá trình này có thể mất vài phút; chúng tôi đang chuẩn bị mọi thứ ở phía sau.",
    granted: "Đã cấp",
    notGranted: "Chưa cấp",
  },
  customizeBlocking: {
    customBlockedMessage: {
      title: "Tin nhắn chặn tùy chỉnh",
      tooltip: "Thay thế câu trích dẫn tạo động lực mặc định trên màn hình chặn.",
      placeholder: "Nhập tin nhắn tùy chỉnh của bạn...",
      hint: "Để trống để sử dụng các câu trích dẫn tạo động lực mặc định.",
    },
    customSoftBlocking: {
      title: "Thời gian mở khóa",
      description: "Thời gian ứng dụng được mở khóa sau khi chọn nghỉ trong chế độ Chặn nhẹ.",
      hint: "Từ {min} đến {max} phút",
    },
    customPauseDelay: {
      title: "Thời gian chờ tạm dừng",
      description: "Một rào cản nhỏ trước khi mở khóa ứng dụng bị chặn. Mỗi lần thử làm lần tiếp theo khó hơn.",
      hint: "Chọn từ {min}s đến {max}s",
      sequenceLabel: "Thời gian chờ của bạn",
    },
    saveSuccess: "Đã lưu cài đặt chặn tùy chỉnh thành công",
    saveError: "Không thể lưu cài đặt chặn tùy chỉnh. Vui lòng thử lại.",
  },
  settings: {
    healthPermission: "Quyền sức khỏe",
    physicalActivityPermission: "Quyền Hoạt Động Thể Chất",
    healthAndSleepPermission: "Quyền Sức Khỏe và Giấc Ngủ",
    changedBackendEndpoint: "Điểm cuối AWS Backend {status}",
    saveBlockedUrls: "Đã lưu URL bị chặn thành công",
    saveBlockedUrlsError: "Không thể lưu URL bị chặn",
    debugLog: "Bật ghi nhật ký chi tiết",
    debugLogDescription: "Chỉ bật tính năng này nếu nhóm hỗ trợ yêu cầu vì nó sẽ làm chậm ứng dụng",
    title: "Cài Đặt",
    addApps: "Thêm Ứng Dụng Vào Danh Sách Chặn",
    clearBlocklist: "Xóa Danh Sách Chặn",
    confirmClearBlocklist: "Xác nhận xóa danh sách chặn?",
    urlBlockingWarningTitle: "Quan trọng: Chặn URL chỉ hoạt động trong Safari",
    urlBlockingWarningMessage:
      "Chặn trang web chỉ hoạt động trong Safari. Để ngăn việc vượt qua các chặn URL, chúng tôi khuyên bạn nên chặn hoàn toàn Chrome, Firefox và các trình duyệt bên thứ ba khác trong danh sách chặn của bạn.",
    urlBlockingHowToTitle: "Cách chặn trang web",
    urlBlockingHowToMessage:
      "Nhấn 'Thêm URL vào danh sách chặn' bên dưới, sau đó chọn tab 'Trang web' ở đầu bộ chọn. Bạn có thể tìm kiếm các trang web cụ thể hoặc duyệt theo danh mục. Các trang web đã chọn sẽ bị chặn trong Safari trong các phiên tập trung của bạn.",
    addUrls: "Thêm URL vào danh sách chặn",
    clearBlockedUrls: "Xóa URL đã chặn",
    confirmClearBlockedUrls: "Xác nhận xóa URL đã chặn?",
    strictness: "Độ Nghiêm Ngặt",
    shareLogsWithSupport: "Báo cáo sự cố",
    reason_required: "Vui lòng nhập lý do",
    enter_a_reason: "Bạn có thể chia sẻ lý do muốn xóa tài khoản không?",
    contact_desc: "Chúng tôi có thể liên hệ với bạn để giúp khắc phục các vấn đề bạn gặp phải không?",
    editFriction: "Độ nghiêm khắc",
    password: "Mật Khẩu",
    account: "Tài Khoản",
    permissions: "Quyền",
    language: "Ngôn Ngữ",
    useSystemLanguage: "Sử dụng ngôn ngữ hệ thống",
    supportedLanguages: "Ngôn ngữ được hỗ trợ",
    overlay_permission: "Quyền Phủ Lớp",
    usage_permission: "Quyền Sử Dụng",
    notification_permission: "Quyền Thông Báo",
    screen_time_permission: "Quyền Thời Gian Màn Hình",
    DND_permission: "Quyền Không Làm Phiền",
    DND: "Chặn Thông Báo",
    warning: "Cảnh Báo!",
    DND_permissionWarning:
      "Chế độ Không Làm Phiền phải được tắt thủ công nếu đã được bật. Nó không thể tự động tắt nếu quyền Không Làm Phiền chưa được cấp.",
    help: "Trợ Giúp",
    askForHelp: "Yêu Cầu Trợ Giúp",
    report_problem: "Báo Cáo Sự Cố",
    discord_server: "Máy Chủ Discord",
    videoTutorials: "Hướng Dẫn Video",
    experimental: "Thử Nghiệm",
    customization: "Tùy Chỉnh",
    general: "Chung",
    focusGames: "Trò Chơi Tập Trung",
    allowed: "Cho Phép",
    notAllowed: "Không cho phép",
    notGrantedYet: "Chưa cấp",
    userid: "ID Người Dùng",
    copy: "Sao Chép",
    copied: "Đã Sao Chép",
    settings: "Cài Đặt",
    verifyEmail: "Xác minh email",
    emailVerificationResent: "Đã gửi lại xác minh email",
    pendingVerification: "Đang chờ xác minh",
    editNickname: "Chỉnh sửa biệt danh",
    nicknameError: "Biệt danh không hợp lệ (chỉ chữ cái và số)",
    nicknameAlreadyExists: "Biệt danh đã tồn tại",
    customizeBlocking: "Tùy chỉnh chặn",
    lateNoMore: "Nhắc họp",
  },
  focus: {
    title: "Tập Trung",
    focusLimitReachedTitle: "Đã Đạt Giới Hạn Tập Trung",
    focusLimitReachedMessage:
      "Trong phiên bản miễn phí, bạn chỉ có thể tập trung tối đa 25 phút. Nâng cấp lên premium nếu bạn muốn phiên tập trung dài hơn.",
  },
  blockingStatusBanner: {
    additionalSchedules: " +{count} nữa",
    activeSchedule: "{name} ({start} – {end}) {extra}",
  },
  home: {
    setupHabitsDescription: "Thiết lập thói quen của bạn để bắt đầu ngày mới.",
    upEarlyStartMorningRoutine: "Dậy sớm? Bắt đầu thói quen buổi sáng",
    getMotivated: "Tạo động lực",
    completed: "Đã Hoàn Thành",
    habitName: "Tên thói quen",
    newHabit: "Thói quen mới...",
    duration: "Thời Lượng",
    editHabit: "Chỉnh sửa thói quen",
    addHabit: "Thêm thói quen",
    deleteThisHabit: "Xóa thói quen này",
    deleteHabit: "Xóa thói quen {name}",
    deleteHabitTitle: "Xóa Thói Quen",
    deleteHabitMessage: "Bạn có chắc muốn xóa '{habitName}'? Hành động này không thể hoàn tác.",
    afterCutoffTimeDescription: "Không có thói quen nào khả dụng vì đã qua thời gian giới hạn",
    routineNotScheduledNow: "Thói quen này được lên lịch cho {routineSchedule}",
    cutOffToolTip:
      "Bạn đã cấu hình thời gian giới hạn cho thói quen nên chúng không thể truy cập sau {cutOffTime}.\nBạn có thể thay đổi trong Thay đổi thời gian",
    unlockToProceed: "Mở khóa để tiếp tục",
    title: "Trang Chủ",
    morningRitual: "Nghi thức buổi sáng của bạn",
    eveningRitual: "Nghi thức buổi tối của bạn",
    time_to_earn_screen_time: "Thực hiện thói quen buổi sáng để chuẩn bị cho một ngày tuyệt vời",
    evening_routine_text: "Bạn sẽ sẵn sàng cho một giấc ngủ ngon khi hoàn thành!",
    upcoming_below_new_activities:
      "Dưới đây là các thói quen bạn cần hoàn thành trong thói quen sắp tới để sử dụng điện thoại.",
    start: "Bắt Đầu",
    mins: "phút",
    secs: "giây",
    re_activate: "Tiếp tục chặn",
    force_deactivate_postpone_and_start_routine: "Thói quen đã bị hoãn\n Tiếp tục thói quen?",
    userCompletedRoutineHeading:
      "Làm tốt lắm khi hoàn thành thói quen. Mong được giúp bạn với thói quen tiếp theo {routineTime}",
    postOnboardingRoutineHeading: "Chào mừng bạn! Mong được giúp bạn với thói quen {routineName} {routineTime}",
    wantLogout: "Bạn có muốn đăng xuất không?",
    noDataFound: "Bạn chưa thiết lập thói quen nào. Nhấn <fix>vào đây</fix> để thêm thói quen.",
    routineFetchingError:
      "Chúng tôi gặp sự cố khi lấy dữ liệu thói quen. Vui lòng thử lại sau hoặc liên hệ với chúng tôi để được hỗ trợ",
    hi: "Xin chào {nickname}!",
    welcomeDefault: "Xin chào!",
    goodMorningFocusTime: "Chào Buổi Sáng!",
    goodEveningFocusTime: "Chào Buổi Tối!",
    allActivitiesCompleted: "Không còn thói quen nào để hoàn thành",
    startRoutineNow: "Thực Hiện Thói Quen {routineName}",
    customRoutineReady: "Bạn có thể bắt đầu thói quen tùy chỉnh ngay bây giờ",
    passwordForSettingsTitles: "Nhập mật khẩu để tiếp tục",
    manageAlwaysAllowedAppsDesc:
      "Trong thói quen buổi sáng/tối và khi bạn đang tập trung trên máy tính, tất cả ứng dụng trên điện thoại ngoại trừ Ứng Dụng Luôn Được Phép sẽ bị chặn. Chúng tôi khuyên chỉ cho phép các ứng dụng như SMS, điện thoại và ứng dụng cần cho công việc để bạn không bị phân tâm.",
    manageAlwaysBlockedAppsDesc:
      "Trong thói quen buổi sáng/tối và khi bạn đang tập trung trên máy tính, tất cả ứng dụng trong danh sách chặn sẽ bị chặn. Chúng tôi khuyên chặn mạng xã hội, game, email và ứng dụng tin tức để bạn không bị phân tâm.",
    overlayPermission: "overlayPermission",
    usagePermission: "usagePermission",
    editHabits: "Chỉnh Sửa Thói Quen",
    editYourHabits: "Chỉnh sửa thói quen của bạn",
    stats: "Thống Kê",
    motivationMsg: "Tạo Động Lực",
    play: "Phát",
    pause: "Tạm Dừng",
    customizeHabits: "Chỉnh sửa thói quen",
    deleteAccount: "Xóa Tài Khoản?",
    accountDataHasBeen: "Dữ liệu tài khoản đã được xóa thành công. Cảm ơn bạn đã sử dụng Focus Bear.",
    blockSuperDistractingApps: "Chặn các trang web/ứng dụng gây phân tâm nghiêm trọng",
    skipHabitDesc: "Bỏ qua thói quen này hôm nay",
    screenTimePermissionNotAllowedWarningText:
      "Cần quyền Thời Gian Màn Hình để chặn ứng dụng, bắt đầu lại thói quen để cấp quyền",
    OverlayPermissionNotGrantedWarning:
      "Cảnh báo: chặn phân tâm chưa được kích hoạt. Quyền phủ lớp chưa được cấp. Sửa.",
    ScreenTimePermissionNotGrantedWarning:
      "Cảnh báo: chặn phân tâm chưa được kích hoạt. Quyền Thời Gian Màn Hình chưa được cấp. Sửa.",
    UsagePermissionNotGrantedWarning: "Cảnh báo: chặn phân tâm chưa được kích hoạt. Quyền sử dụng chưa được cấp. Sửa.",
    noAllowedAppSelectedWarning:
      "Cảnh báo: bạn chưa cấu hình danh sách chặn nên các phân tâm sẽ không bị chặn. Chỉnh sửa Danh sách chặn",
    habitLimitMessage:
      "Người dùng miễn phí chỉ có thể truy cập tối đa 3 thói quen mỗi thói quen. Vui lòng nâng cấp để mở khóa thêm thói quen.",
    routineOptionsTooltip: "Menu này cho phép bạn chỉnh sửa lịch trình hoặc thay đổi thời gian.",
    youHaveNotSetupAnyHabitsYet: "Bạn chưa thiết lập thói quen nào.",
    guestMode: "Chế Độ Khách",
    guestSignUpDescription:
      "Đăng ký để truy cập nội dung của bạn trên tất cả các thiết bị và mở khóa các tính năng được cá nhân hóa.",
    deleteRoutineTitle: "Xóa Thói Quen",
    deleteRoutineMessage:
      "Bạn có chắc muốn xóa thói quen này và tất cả các hoạt động liên quan? Thao tác này không thể hoàn tác.",
    createHeading: "Tạo mới",
    completedHabits: "Thói quen đã hoàn thành",
    hiddenHabits: "Thói quen bị ẩn",
    editRoutine: "Chỉnh sửa lịch trình",
    changeTiming: "Thay đổi thời gian",
    deleteRoutine: "Xóa thói quen",
    cutoffTimeNote:
      "Lưu ý: Giờ ngắt của bạn là {time}. Các thói quen không được đặt là 'ưu tiên cao' sẽ không khả dụng sau giờ này. ",
    editCutoff: "Chỉnh sửa giờ ngắt",
    unavailable: "Không khả dụng",
    inProgress: "Đang thực hiện",
    startsAt: "Bắt đầu lúc {time}",
    passed: "Đã qua",
    completedWithCount: "Đã hoàn thành {count}",
    unavailableWithCount: "{count} hiện không khả dụng",
    noHabitsYetAddPrompt: "Chưa có gì ở đây.\nThêm thói quen?",
    routineIsEmpty: "Thói quen trống",
    allHabitsHidden: "Tất cả thói quen bị ẩn",
    habitsCount_zero: "$t(common.empty)",
    habitsCount_one: "{count} thói quen",
    habitsCount_other: "{count} thói quen",
  },
  editRoutine: {
    editTiming: "Chỉnh sửa thời gian",
    morningTime: "Thời gian buổi sáng",
    wakeUp: "Thức dậy!",
    morningRoutineStartTime: "Thời gian bắt đầu thói quen buổi sáng",
    eveningTime: "Thời gian buổi tối",
    finishWork: "Kết thúc công việc",
    eveningRoutineStartTime: "Thời gian bắt đầu thói quen buổi tối",
    techCurfew: "Giờ cấm công nghệ",
    timeToSleep: "Giờ đi ngủ",
    timing: "Thời gian",
    anytime: "Bất kỳ lúc nào",
    scheduled: "Đã lên lịch",
    doHabitsWhenever: "Thực hiện các thói quen này bất kỳ lúc nào",
    doHabitsAtSpecificTime: "Thực hiện các thói quen này vào thời gian cụ thể hoặc ngày cụ thể",
    newRoutinePlaceholder: "Thói quen mới...",
    routineNamePlaceholder: "Tên thói quen",
    customRoutineDefaultName: "Thói quen tùy chỉnh",
    createNewRoutine: "Tạo lịch trình mới",
    time: "Thời gian",
    wakeUpFinishWorkSameError: "Thời gian thức dậy và thời gian kết thúc công việc không thể giống nhau",
    cutoffOutOfRangeError: "Thời gian ngủ phải sau thời gian kết thúc công việc và trước thời gian thức dậy",
    startBeforeEndError: "Thời gian bắt đầu phải trước thời gian kết thúc",
  },
  simpleHome: {
    setupBlocking: "Thiết lập chặn",
    setupBlockingApp: "Thiết lập chặn phân tâm cho ứng dụng (khuyến nghị)",
    setupBlockingUrl: "Thiết lập chặn phân tâm cho trang web (tùy chọn)",
    title: "Dùng thử Focus Bear",
    focusSessionCheckboxTitle: "Hoàn thành phiên tập trung đầu tiên",
    microBreakCheckboxTitle: "Thực hiện thói quen nghỉ ngắn",
    focusScreenTitle: "Dùng thử Phiên Tập Trung",
    focusSessionCheckboxDesc: "Làm việc sâu",
    microBreakCheckboxDesc: "Giảm căng thẳng với hít thở sâu",
    postGamePromptTitle: "Làm tốt lắm!",
    postGamePromptText: "Bạn có muốn bắt đầu phiên tập trung ngay để hoàn thành nhiệm vụ đó không?",
    focusNowCta: "Có! Thời Gian Tập Trung",
    focusGameTitle: "Khởi động với trò chơi tập trung",
    focusGameDesc: "Chơi trò chơi nhanh để vào trạng thái",
  },
  postpone: {
    doYouReallyWantTo: "Bạn có thực sự muốn tạm dừng không?",
    blockingPausedForDuration: "Đã tạm dừng chặn trong {duration}",
    blockingPausedIndefinitely: "Đã tạm dừng chặn cho đến khi bạn tiếp tục",
    pauseBlocking: "Tạm Dừng Chặn",
    pauseDisabledStrictMode: "Không thể tạm dừng chặn khi chế độ siêu nghiêm ngặt được bật",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "Tiếp Tục Chặn",
    choosePostponeTime: "Bạn muốn tạm dừng bao lâu?",
    indefinite: "Tạm dừng cho đến khi tôi tiếp tục chặn",
    youHavePausedTimesToday_zero: "Đây là lần đầu tiên bạn tạm dừng hôm nay.",
    youHavePausedTimesToday_one: "Bạn đã tạm dừng một lần hôm nay.",
    youHavePausedTimesToday_other: "Bạn đã tạm dừng {count} lần hôm nay.",
    countdown: "Chúng tôi sẽ cho bạn tạm dừng sau {countdown}",
    areYouSureIndefinite:
      "Bạn có chắc muốn tạm dừng vô thời hạn không? Bạn có thể nếu thực sự muốn nhưng thường một nhiệm vụ có vẻ khẩn cấp vẫn có thể chờ 15 phút cho đến khi bạn hoàn thành thói quen.",
    doHabits: "Tôi sẽ làm thói quen thay vì",
    longTermGoalsDesc: "Chỉ nhắc nhở rằng đây là những gì bạn đang cố đạt được với Focus Bear:",
    lowQualityUsageDesc: "Thời gian đã dùng trong ứng dụng chất lượng thấp hôm nay",
    write: "Để lại phản hồi...",
  },
  passwordForSettings: {
    invalid_password: "Mật khẩu không hợp lệ",
    resetAfter24Hours: "Đã yêu cầu đặt lại. Mật khẩu của bạn sẽ bị vô hiệu hóa sau 24 giờ.",
  },
  signIn: {
    logIn: "Đăng nhập",
    enterEmailHint: "Địa Chỉ Email",
    enterPasswordHint: "Mật Khẩu",
    invalidCredentials: "Tên đăng nhập/Mật khẩu không hợp lệ",
    enterEmailError: "Vui lòng nhập email",
    enterValidEmailError: "Vui lòng nhập email hợp lệ",
    enterPasswordError: "Vui lòng nhập mật khẩu",
    dontHaveAccount: "Chưa có tài khoản?",
    forgotPassword: "Quên Mật Khẩu?",
    signup: "Đăng ký",
    googleSignIn: "Tiếp tục với Google",
    continueWithGoogle: "Tiếp Tục Với Google",
    startWithApple: "Bắt đầu với Apple",
    startWithEmail: "Bắt đầu với email",
    backToSignInMethod: "Quay lại chọn phương thức đăng nhập",
    alreadyHaveAccount: "Tôi đã có tài khoản Focus Bear",
  },
  forgotPassword: {
    forgotPasswordSuccess: "Email đặt lại mật khẩu đã được gửi đến địa chỉ email của bạn",
    forgotPasswordErrorThirdParty:
      "Có vẻ như bạn đã đăng ký bằng dịch vụ bên thứ ba. Vui lòng tiếp tục với tài khoản Google hoặc Apple của bạn.",
    forgotPasswordNotVerified: "Bạn cần xác minh địa chỉ email để đặt lại mật khẩu.",
    forgotPasswordEmailNotFound: "Không tìm thấy email",
    forgotPasswordTitle: "Quên Mật Khẩu",
    backToSignIn: "Quay Lại Đăng Nhập",
    resetPassword: "Đặt Lại Mật Khẩu",
    weveEmailedYouALinkToResetYourPassword: "Chúng tôi đã gửi email cho bạn một liên kết để đặt lại mật khẩu.",
    forgotPasswordNotVerifiedBody:
      "You need to verify your email before you can reset your password. We can send you a new verification link now.",
    forgotPasswordNotVerifiedTitle: "Verify your email to reset your password",
    resetLinkSent: "If an account exists with this email, a password reset link has been sent.",
    verificationEmailSent: "A verification email has been sent. Please check your inbox.",
    verificationEmailFailed: "Failed to send the verification email. Please try again later.",
    cannotResetPasswordOAuthAccountTitle: "Sign in to continue",
    resetFailed: "Password Reset attempt has failed. Try again later.",
    waitBeforeRetry: "Please wait before requesting another email.",
  },
  signUp: {
    backToSignUpMethod: "Quay lại chọn phương thức đăng ký",
    verifyEmail: "Vui lòng kiểm tra hộp thư đến",
    verifyEmailMessage: "Chúng tôi vừa gửi cho bạn email xác minh. Vui lòng nhấp vào liên kết để xác minh tài khoản.",
    signUp: "Đăng ký",
    emailSignup: "Đăng ký bằng email",
    continueWithNoAccount: "Tiếp tục không cần tài khoản",
    tosAndPP: "Tôi đồng ý với <bold>Điều Khoản Dịch Vụ</bold> và <bold1>Chính Sách Bảo Mật</bold1>",
    alreadyHaveAccount: "Đã có tài khoản?",
    passwordMatchError: "Mật khẩu và xác nhận mật khẩu không khớp",
    acceptTerms: "Vui lòng đồng ý với Điều Khoản Dịch Vụ và Chính Sách Bảo Mật để tiếp tục",
    passwordHintError:
      "Mật Khẩu Phải Chứa:\n    • Ít nhất 8 ký tự\n    • Số (0-9)\n    • Chữ thường (a-z)\n    • Chữ hoa (A-Z)\n    • Ký tự đặc biệt (!@#$%^&*)",
    invalidSignup: "Đăng ký không hợp lệ",
    userExists: "Người dùng đã tồn tại.",
    terms: "Điều Khoản",
    privacy: "Bảo Mật",
    or: "HOẶC",
  },
  profile: {
    logout: "Đăng Xuất",
  },
  routineDetail: {
    activity: "Hoạt Động",
    not_playable_video: "Không thể phát video.",
    done: "Tôi đã xong",
    video: "Video",
    images: "Hình Ảnh",
    checklist: "Danh Sách Kiểm Tra",
    note: "Ghi Chú",
  },
  quickBreak: {
    quickBreak: "Nghỉ Ngắn",
    quickStretch: "Bài Tập Giãn Cơ",
    stretch: "Giãn Cơ",
    drinkWater: "Uống Nước",
    water: "Nước",
    deepBreathing: "Hít Thở Sâu",
    breathe: "Thở",
    saveQuickBreakSuccessfully: "Thay đổi của bạn đã được lưu thành công",
    editQuickBreaks: "Chỉnh Sửa Nghỉ Ngắn",
    quickBreakName: "Tên nghỉ ngắn",
    currentSelection: "Lựa chọn hiện tại",
  },
  complete: {
    backToHome: "Quay Về Trang Chủ",
    logQuantity: "Ghi lại số lượng hoạt động",
    finishedCheck: "hoàn thành! ✅",
    habitNotCompleted: "thói quen đã bỏ qua! ❌ Bạn có thể làm vào ngày mai!",
    finishedAndEarnedMorning: "hoàn thành! ✅ Bạn đã kiếm được thời gian màn hình",
    finishedAndEarnedEvening: "hoàn thành! ✅ Bạn đã kiếm được một giấc ngủ ngon. Hẹn gặp lại vào sáng mai!",
    why_skip: "Tại sao bạn muốn bỏ qua?",
    already_did: "Tôi đã làm rồi",
    cannot_today: "Không thể làm hôm nay",
    quantity_input_error: "Số cần nằm trong khoảng {min} và {max}.",
    freemiumLimitReached: "Xin lỗi, bạn chỉ có thể hoàn thành 3 thói quen với gói miễn phí.",
  },
  reason: {
    canShare: "Bạn có thể chia sẻ lý do tạm dừng vô thời hạn không?",
    shareFeedback: "Chia sẻ phản hồi",
    everythingIsOk: "Ôi - hy vọng mọi thứ đều ổn",
    appBrokenDesc: "Thực sự xin lỗi về điều đó. Bạn có thể cho chúng tôi biết chuyện gì đã xảy ra không?",
    somethingElseDesc: "Được rồi. Bạn có phản hồi nào muốn chia sẻ với chúng tôi không?",
    gotEmergency: "Tôi có việc khẩn cấp",
    appBroken: "Ứng dụng bị lỗi",
    somethingElse: "Điều khác",
  },
  notification: {
    backgroundService: "Dịch vụ nền Focus Bear giúp bạn tập trung",
    scheduleNotificationTitleForResumeRoutine: "Tiếp tục thói quen của bạn",
    scheduleNotificationDescriptionForResumeRoutine: "Đã đến lúc tập trung vào thói quen của bạn",
    floatingModuleActivityCompleteNotificationtitle: "Hoạt Động Đã Hoàn Thành",
    floatingModuleRoutineCompleteNotificationtitle: "Thói Quen Đã Hoàn Thành",
    morningRoutineCompletedNotificationDescription: "Thói quen buổi sáng đã hoàn thành. Bắt đầu ngày tuyệt vời!",
    eveningRoutineCompletedNotificationDescription: "Thói quen buổi tối đã hoàn thành. Ngủ ngon!",
    customRoutineCompletedNotificationDescription: "{{routineName}} đã hoàn thành. Làm tốt lắm!",
  },
  focusMode: {
    blockingPaused: "Đã Tạm Dừng Chặn",
    blockingPermissionNeeded: "Chặn không hoạt động: bạn cần cấp quyền",
    noBlockingAppsSelected: "Chặn không hoạt động: bạn cần chọn ứng dụng để chặn",
    distractionBlockingNotActiveTitle: "Chặn phân tâm không hoạt động",
    distractionBlockingNotActiveText: "Bạn chưa chọn ứng dụng để chặn",
    continueWithoutBlocking: "Tiếp tục không chặn",
    fixBlocking: "Sửa chặn",
    confirmSuperStrictMode:
      "Bạn có chắc muốn bật Chế Độ Siêu Nghiêm Ngặt? Bạn sẽ không thể thoát cho đến khi phiên kết thúc.",
    focusIntentionTooltip:
      "Đặt mục tiêu cho những gì bạn sẽ đạt được trong phiên tập trung này. Rõ ràng về những gì bạn sẽ đạt được giúp bạn tránh bị phân tâm.",
    focusTitle: "Bắt đầu phiên tập trung",
    superStrictToolTip:
      "Cam kết với phiên tập trung này? Bật chế độ siêu nghiêm ngặt và bạn sẽ không thể tắt tập trung hoặc tạm dừng chặn ứng dụng cho đến khi hết giờ.",
    superStrictMode: "Chế độ siêu nghiêm ngặt",
    brainDump: "Ghi chú nhanh",
    brainDumpToolTip: "Ghi lại suy nghĩ của bạn ở đây",
    postFocusCongrats_0: "Làm tốt lắm! Bạn đã xuất sắc!",
    postFocusCongrats_1: "Này, làm tốt lắm! Tiếp theo là gì?",
    postFocusCongrats_2: "Bạn đã làm được! Hãy nghỉ ngơi một chút.",
    postFocusCongrats_3: "Tuyệt vời! Bạn đang hoàn thành công việc!",
    postFocusCongrats_4: "Tuyệt vời! Điều tiếp theo trong danh sách là gì?",
    postFocusCongrats_5: "Bạn đã vượt qua! Sẵn sàng cho việc tiếp theo?",
    postFocusCongrats_6: "Tập trung tuyệt vời! Đi lấy đồ uống hoặc đồ ăn nhẹ!",
    postFocusCongrats_7: "Tuyệt! Bạn đang tiến bộ đáng kể!",
    postFocusCongrats_8: "Làm tốt lắm! Đến lúc duỗi chân một chút?",
    postFocusCongrats_9: "Bạn làm tuyệt vời! Hãy giữ đà này!",
    startFocusSession: "Bắt đầu phiên tập trung",
    noIntentionWasFound: "Chưa nhập mục tiêu",
    distractionAlertTitle: "Chế Độ Tập Trung",
    userIntention: "Mục Tiêu Tập Trung",
    noDistractingThoughtsWasFound: "Chưa nhập suy nghĩ phân tâm",
    userIntentionTextInputPlaceholder: "Bạn muốn làm việc gì?",
    startFocusing: "Bắt Đầu Tập Trung",
    hoursWithValue: "{value}g",
    minutesWithValue: "{value}p",
    secondsWithValue: "{value}s",
    duration: {
      hours: "{hours} giờ",
      minutes: "{minutes} phút",
      seconds: "{seconds} giây",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "Bạn làm được!\nThời gian làm việc sâu",
    endSession: "Kết Thúc Phiên",
    completeFocus: "Hoàn Thành Tập Trung",
    userDumpThoughTextInputDescription: "Ghi lại bất kỳ suy nghĩ phân tâm nào ở đây",
    exitFocusMode: "Kết thúc phiên tập trung sớm",
    exitFocusModeDescription: "Bạn có thể chia sẻ lý do kết thúc phiên này không?",
    reason: "Lý Do",
    selectReason: "Chọn lý do",
    congratulations: "Chúc Mừng!",
    focusDoneTitle: "BẠN ĐÃ LÀM ĐƯỢC!",
    focusDoneDescription: "Bạn đã tập trung trong",
    focusDoneDescription1: "Mục tiêu của bạn là gì?",
    focusDoneDescription4: "Suy nghĩ phân tâm của bạn là gì?",
    focusDoneDescription2: "Bạn đã đạt được gì trong thời gian này?",
    focusDonePlaceholderDescription2: "Nhập những gì bạn đã đạt được với sự giúp đỡ của chúng tôi",
    focusDoneDescription3: "Bạn có bị phân tâm không?",
    focusDonePlaceholderDescription3: "Nhập bất kỳ sự phân tâm nào bạn gặp phải",
    endEarlyReasonDescription1: "Tôi có việc khẩn cấp",
    endEarlyReasonDescription2: "Chế độ tập trung không hoạt động đúng",
    endEarlyReasonDescription3: "Tôi đã đạt được những gì tôi muốn",
    endEarlyReasonDescription4: "Tôi cần nghỉ ngơi",
    runningFocusModeDesc: "Một phiên tập trung đang chạy",
    extendFocusDuration: "Kéo Dài Thời Gian Tập Trung",
    shortenFocusDuration: "Rút Ngắn Thời Gian Tập Trung",
    selectExtendFocusDuration: "Bạn muốn tập trung thêm bao lâu?",
    selectShortenFocusDuration: "Bạn muốn rút ngắn bao nhiêu thời gian?",
    extendFocus: "Kéo Dài",
    shortenFocus: "Rút Ngắn",
    adjustFocusDuration: "Điều Chỉnh Thời Gian Tập Trung",
    chooseAdjustmentOption: "Bạn muốn kéo dài hay rút ngắn phiên tập trung?",
    editFocusDuration: "Bạn muốn kết thúc tập trung khi nào?",
    focusMusic: "Nhạc tập trung",
    focusMusicError: "Xin lỗi, không thể phát nhạc tập trung",
    focusNotes: "Ghi chú tập trung",
  },
  toDos: {
    toDos: "Việc Cần Làm",
    todoList: "Danh Sách Việc Cần Làm",
    notes: "Ghi chú",
    drafts: "AI Tạo",
    notStarted: "Cần làm",
    inProgress: "Đang làm",
    completed: "Xong",
    current: "Hiện tại",
    noMoreTasks: "Không còn nhiệm vụ nào",
    noTasksToShow: "Không có nhiệm vụ để hiển thị\nThêm một số bên dưới để bắt đầu!",
    searchTasks: "Tìm kiếm nhiệm vụ",
    noTasksFound: "Không tìm thấy nhiệm vụ",
    addATask: "Thêm nhiệm vụ",
    taskAdded: "Đã thêm nhiệm vụ",
    failedToAddTask: "Không thể thêm nhiệm vụ",
    scanPaperWithOCR: "Quét giấy bằng OCR",
    quickActions: {
      audio: "Âm thanh",
      uploadAudio: "Tải lên âm thanh",
      recordAudio: "Ghi âm",
      upgradeRequired: "Cần Nâng Cấp",
      upgradeMessage:
        "Tính năng âm thanh và OCR có sẵn với Focus Bear Pro. Nâng cấp để mở khóa các công cụ năng suất mạnh mẽ này.",
      ocrUpgradeMessage: "Quét OCR có sẵn với Focus Bear Pro. Nâng cấp để trích xuất nhiệm vụ từ ảnh và tài liệu.",
    },
    ocr: {
      modalTitle: "Quét Giấy Bằng OCR",
      reviewModalTitle: "Xem Lại Việc Cần Làm Đã Trích Xuất",
      title: "Quét Danh Sách Việc Cần Làm",
      description:
        "Tính năng này có thể trích xuất nhiệm vụ từ ảnh danh sách việc cần làm viết tay hoặc in. Bạn có thể chọn ảnh từ thư viện hoặc chụp ảnh mới.",
      reviewTitle: "Xem Lại Việc Cần Làm Đã Trích Xuất",
      reviewDescription: "Chọn các việc cần làm bạn muốn thêm vào danh sách. Bạn có thể chỉnh sửa sau.",
      selectSource: "Chọn Nguồn Ảnh",
      selectSourceDesc: "Chọn một tùy chọn để chọn ảnh",
      takePhoto: "Máy Ảnh",
      chooseFromGallery: "Thư Viện Ảnh",
      capturePhoto: "Tiếp Tục",
      processing: "Đang xử lý ảnh...",
      uploading: "Đang Tải Lên Ảnh",
      error: "Lỗi OCR",
      processingError: "Không thể xử lý ảnh. Vui lòng thử lại.",
      noTodosSelected: "Chưa Chọn Việc Cần Làm",
      selectAtLeastOne: "Vui lòng chọn ít nhất một việc cần làm để thêm.",
      createTodos: "Tạo Việc Cần Làm Đã Chọn",
      completed: "Xử Lý OCR Hoàn Tất",
      completedDesc: "Việc cần làm của bạn đã được trích xuất thành công!",
    },
    audio: {
      processing: "Đang xử lý âm thanh...",
      completed: "Xử Lý Âm Thanh Hoàn Tất",
      completedDesc: "Việc cần làm của bạn đã được trích xuất thành công!",
      addByAudio: "Thêm bằng âm thanh",
      record: "Ghi âm",
      upload: "Tải lên",
      recorded: "Ghi âm hoàn tất",
      sendOrDiscard: "Nhấn để gửi hoặc bỏ qua để hủy",
    },
    due: "Hạn",
    dueDate: "Ngày Hạn",
    exactDate: "Chọn ngày",
    TOP: "TOP - Điểm Ưu Tiên Nhiệm Vụ",
    TOPPrioritization: "Ưu Tiên TOP",
    timeline: "Dòng thời gian (ngày hạn)",
    project: "Dự Án",
    projects: "Dự Án",
    scoreCalculation: "Điểm",
    addProjects: "Thêm dự án",
    noExistingProjects: "Không có dự án nào",
    createNewProject: "Tạo dự án mới",
    addATitle: "Thêm tiêu đề",
    addDescription: "Thêm mô tả...",
    addASubtask: "Thêm nhiệm vụ con",
    reschedule: "Lên lịch lại",
    rescheduleTitle: "Lên lịch lại nhiệm vụ ",
    taskMovedToast: 'Nhiệm vụ đã chuyển sang "{status}"',
    sortBy: "Sắp xếp theo",
    filterBy: "Lọc",
    filterTasksBy: "Lọc nhiệm vụ của bạn theo",
    listOptions: "Tùy chọn danh sách",
    lowToHigh: "Điểm TOP từ thấp đến cao",
    highToLow: "Điểm TOP từ cao đến thấp",
    groupBy: "Nhóm theo",
    groupedTogether: 'Hiển thị nhiệm vụ "cần làm" và "đang làm" trong cùng nhóm',
    filterByPerspiration: "Lọc theo mức độ nỗ lực",
    spoonsDesc:
      "Chọn nhiệm vụ dựa trên mức năng lượng của bạn (lý thuyết thìa). Nhiều thìa hơn = nhiều năng lượng hơn.",
    learnAboutSpoonTheory: "Tìm hiểu về lý thuyết thìa",
    lowSpoons: "Ít thìa",
    fullSpoons: "Đầy thìa",
    perspirationLevel: "Mức độ nỗ lực",
    filterByProject: "Lọc theo dự án",
    noFilter: "Không lọc",
    filterByDueDate: "Lọc theo ngày đến hạn",
    toDosDueDate: "Ngày đến hạn",
    overdue: "Quá hạn",
    thisWeek: "Tuần này",
    nextWeek: "Tuần tới",
    deleteTask: "Xóa Nhiệm Vụ",
    deleteTaskDesc: "Bạn có chắc muốn xóa nhiệm vụ này?",
    deleteSubtask: "Xóa Nhiệm Vụ Con",
    deleteSubtaskDesc: "Bạn có chắc muốn xóa nhiệm vụ con này?",
    dueIn: {
      aFewDays: "Trong Hai Ngày",
      nextWeek: "Trong Một Tuần",
      twoWeeks: "Trong Hai Tuần",
      aMonth: "Trong Một Tháng",
      aYear: "Trong Một Năm",
      aYearDescription: "(haha, tôi sẽ không bao giờ thực sự làm điều này)",
    },
    outcome: {
      outcome: "Kết Quả",
      whoCares: "Ai quan tâm",
      kindOfImportant: "Khá quan trọng",
      bigDeal: "Quan trọng",
      huge: "Rất lớn",
      mindBlowing: "Cực kỳ quan trọng",
    },
    perspiration: {
      perspiration: "Mức Độ Nỗ Lực",
      fiveMinuteJob: "Việc 5 phút",
      fifteenMinutesWork: "Việc 15 phút",
      halfAnHour: "Nửa giờ",
      anHour: "Một giờ",
      halfADay: "Nửa ngày",
      aDay: "Một ngày",
      aWeek: "Một tuần",
    },
    searchOrCreateProject: "Tìm kiếm hoặc tạo dự án",
    noMatchingProjects: 'Không tìm thấy dự án nào. Nhấn enter để tạo "{search}"',
  },
  overview: {
    morningRoutine: "Thói Quen Buổi Sáng",
    eveningRoutine: "Thói Quen Buổi Tối",
    noTasksCta: "Chưa có nhiệm vụ. <bold>Thêm nhiệm vụ</bold> để bắt đầu.",
    noHabitsCta: "Chưa có thói quen. <bold>Thêm thói quen</bold> để bắt đầu.",
    topTasksToday: "Nhiệm Vụ Hàng Đầu",
    focusModeTitle: "Chế Độ Tập Trung",
    newFocusSession: "Phiên Mới",
    focusActive: "Phiên Đang Hoạt Động",
    focusInactive: "Không Có Phiên Hoạt Động",
    routineCompletedShort: "✓ Hoàn thành",
    routineCompletedMessage: "Tất cả thói quen đã hoàn thành! Làm tốt lắm! 🎉",
    routineProgress: "{completed} trên {total}",
    deadlinePrefix: "Hạn chót: {date}",
  },
  networkError: {
    ifTheProblemPersists: "Nếu vấn đề vẫn tiếp tục, vui lòng liên hệ hỗ trợ trực tiếp tại\nsupport@focusbear.io",
    noNetworkAlertTitle: "Mất kết nối Internet",
    retrying: "Đang thử lại",
    connectionError: "Kết nối Internet không ổn định",
    connectionErrorMessage: "Vui lòng kiểm tra kết nối của bạn",
    connectionErrorLongMessage:
      "Chúng tôi gặp sự cố khi kết nối với máy chủ. $t(networkError.connectionErrorMessage). $t(networkError.ifTheProblemPersists)",
    apiError: "Đã xảy ra lỗi",
    apiErrorMessage: "Vui lòng thử lại sau",
    apiErrorLongMessage:
      "Đã xảy ra sự cố khi xử lý yêu cầu của bạn. $t(networkError.apiErrorMessage). $t(networkError.ifTheProblemPersists)",
    internalError: "Lỗi nội bộ",
    internalErrorMessage: "Đã xảy ra lỗi :(",
    internalErrorLongMessage: "Xin lỗi, đã xảy ra lỗi nghiêm trọng. $t(networkError.ifTheProblemPersists)",
  },
  manageAllowedApps: {
    searchPlaceholder: "Tìm kiếm ứng dụng đã cài đặt",
  },
  addNoteModule: {
    addNote: "Thêm Ghi Chú",
    placeholder: "Thêm Ghi Chú Tại Đây...",
    saveNote: "Lưu Ghi Chú",
    automaticallySave: "Ghi chú của bạn sẽ được lưu tự động",
  },
  permissionWarning: {
    usageAccessTitle: "Chúng tôi cần quyền Truy Cập Sử Dụng để giúp chặn phân tâm",
    deviceUsagedescription:
      'Để cho phép chúng tôi chặn ứng dụng gây phân tâm khi bạn đang tập trung/thực hiện thói quen, chúng tôi cần quyền "truy cập sử dụng" để xem bạn đang dùng ứng dụng nào',
    overlayTitle: "Chúng tôi cần quyền Phủ Lớp để giúp chặn phân tâm",
    overlayDescription:
      'Để cho phép chúng tôi chặn ứng dụng gây phân tâm khi bạn đang tập trung/thực hiện thói quen, chúng tôi cần quyền "Phủ Lớp" để xem bạn đang dùng ứng dụng nào và hiển thị cảnh báo phân tâm cho ứng dụng không được phép',
    privacyNoteTitle: "Lưu ý về quyền riêng tư",
    privacyNoteDesc:
      "Chúng tôi không ghi lại ứng dụng hoặc trang web bạn sử dụng. Chúng tôi chỉ dùng để chặn theo thời gian thực.",
    grantAccess: "Cho Phép",
  },
  onboarding: {
    nextStep: {
      upNext: "Tiếp theo: {step}",
      usagePermission: "Quyền sử dụng",
      overlayPermission: "Quyền phủ lớp",
      focusSession: "Phiên tập trung",
      microBreak: "Nghỉ ngắn",
      allDone: "Hoàn tất",
      screenTimePermission: "Quyền thời gian màn hình",
    },
    wantToPersonalise: "Muốn cá nhân hóa?",
    wantToPersonaliseDescription: "Thiết lập thói quen riêng thay vì sử dụng mặc định.",
    personalise: "Cá nhân hóa (5 phút)",
    onboarding: "Giới Thiệu",
    letsDoIt: "Bắt đầu thôi",
    replay: "Phát lại",
    instructionVideo: "Video Hướng Dẫn",
    welcomeAboard: "Chào mừng bạn!",
    lookingForwardToHelp: "Đã đến lúc kích hoạt thói quen lành mạnh và làm việc sâu.",
    getStarted: "Bắt Đầu",
    allDone: "Hoàn Tất!",
    habitPackSelectionNotice:
      "Tiếp theo hãy chọn một số thói quen cho thói quen buổi sáng và buổi tối của bạn.\n\n\n<bold>Đừng lo lắng</bold> Bạn luôn có thể điều chỉnh sau.",
    installDesktopApp: "Cài đặt ứng dụng máy tính",
    installDesktopAppDesc:
      "Focus Bear cũng hoạt động trên Mac và Windows. Nếu bạn có máy tính, tải ứng dụng từ <bold>focusbear.io</bold> để đồng bộ phiên tập trung và thói quen.",
    cutoffTimeWarning: "Thời gian ngừng sử dụng công nghệ phải sau thời gian kết thúc công việc ({time}).",
    howFocusBearWork: "Cách Focus Bear hoạt động",
    habitAndRoutine: "Thói Quen và Lịch Trình",
    habitAndRoutineDescription: "<bold>Đạt được mục tiêu</bold> với các thói quen kích hoạt não và cơ thể",
    distractionBlocking: "Chặn Phân Tâm",
    distractionBlockingDescription:
      "Focus Bear có thể chặn <bold>ứng dụng</bold> và <bold>trang web</bold> để giúp bạn hoàn thành công việc",
    todoList: "Danh Sách Việc Cần Làm",
    todoListDescription:
      "<bold>Lên kế hoạch</bold>, <bold>ưu tiên</bold> và <bold>theo dõi tiến độ</bold> với danh sách việc cần làm Focus Bear",
    andMuchMore: "Và còn nhiều hơn nữa",
    andMuchMorePoints: [
      "Hoạt động trên máy tính của bạn",
      "Kỹ thuật Pomodoro",
      "Thói quen nâng cao với danh sách kiểm tra và video",
      "Thói quen buổi sáng và buổi tối",
      "Nhắc nhở nghỉ ngơi",
      "Biểu tượng gấu vui nhộn",
    ],
    andMuchMoreDescription: "<bold>và còn nhiều hơn nữa...</bold>",
    end: "KẾT THÚC",
    habitAI: "Sắp xếp nhiệm vụ\nbằng AI",
    habitAIDescription: "Focus Bear có thể giúp bạn <bold>sắp xếp nhiệm vụ</bold> bằng Trí Tuệ Nhân Tạo",
    learnAboutFeatures: "Tìm hiểu về tính năng",
    setupHabitsTitle: "Thiết lập thói quen để tập trung tốt hơn",
    setupHabitsCta: "Thiết lập thói quen",
    habitsPirateCopy: "Thói quen tốt giúp bạn giữ sự tập trung sắc bén cả ngày.",
    habitImportPirateCopy: "Tôi sẽ dùng phép thuật biển cả để đưa thói quen của bạn lên tàu.",
    habits: {
      sleep: "Ngủ",
      meditate: "Thiền",
      exercise: "Tập thể dục",
    },
    habitList: {
      nayLabel: "Không - Gợi ý cho tôi vài ý tưởng",
      ayeLabel: "Có - Tôi đã có sẵn vài thói quen",
    },
  },
  goals: {
    habitImport: {
      title: "Nhập Thói Quen",
      description: "Nhập thói quen từ hình ảnh hoặc bằng cách ghi âm giọng nói",
      importFromImage: "Nhập từ Hình Ảnh",
      recordVoice: "Ghi Âm Giọng Nói",
      stopRecording: "Dừng Ghi Âm",
      selectSource: "Chọn Nguồn",
      selectImageSource: "Chọn cách nhập thói quen của bạn",
      takePhoto: "Chụp Ảnh",
      chooseFromGallery: "Chọn từ Thư Viện",
      completed: "Đã nhập thói quen!",
      completedDesc: "Thói quen của bạn đã được nhập thành công",
      error: "Lỗi Nhập",
      processingError: "Không thể xử lý nhập. Vui lòng thử lại.",
      recordingError: "Không thể ghi âm. Vui lòng thử lại.",
      processing: "Đang xử lý nhập của bạn...",
      cancelRecording: "Hủy Ghi Âm",
    },
    addHabitList: {
      title: "Thêm danh sách thói quen",
      description:
        "Tải lên danh sách thói quen hoặc cho chúng tôi biết mục tiêu và AI sẽ thêm chúng vào ứng dụng Focus Bear.",
      uploadScreenshot: "Tải lên ảnh",
      recordVoiceNote: "Ghi âm ghi chú",
      typeThemIn: "Nhập thủ công",
      or: "HOẶC",
      haveHabitListQuestion: "Bạn có danh sách thói quen riêng để nhập không?",
      importHabits: "Nhập thói quen",
      confirmScreenshotUpload: "Xác Nhận Ảnh",
      confirmScreenshotUploadDesc: "Đây có phải là ảnh bạn muốn tải lên không?",
    },
    boostProductivity: "🚀 Tăng năng suất",
    boostProductivityDescription: "(công việc, học tập, nhiệm vụ)",
    improveMentalHealth: "🧘 Cải thiện sức khỏe tinh thần",
    improveMentalHealthDescription: "(căng thẳng, giấc ngủ)",
    improvePhysicalHealth: "🏋️‍♂️ Tập trung vào sức khỏe & thể dục",
    improvePhysicalHealthDescription: "(tập luyện, dinh dưỡng)",
    manageTask: "🏡 Quản lý công việc nhà",
    manageTaskDescription: "(dọn dẹp, việc vặt)",
    otherSpecify: "✏️ Khác",
    otherSpecifyDescription: "(vui lòng ghi rõ: __)",
    strengthenRelationShip: "❤️ Củng cố mối quan hệ",
    strengthenRelationShipDescription: "(gia đình, bạn bè)",
    achievement_placeholder: "Cho chúng tôi biết mục tiêu của bạn",
    enableFeatures: "Bạn muốn bật tính năng nào?",
    doOurBest: "Chúng tôi ở đây để giúp bạn đạt được mục tiêu. Bạn muốn bật tính năng Focus Bear nào?",
    achievementWithFocusBearDesc: "Mục tiêu chính của bạn là gì?",
    achievementWithFocusBearDescTooltip: "Chúng tôi sẽ gợi ý thói quen giúp bạn đạt được mục tiêu",
    help_me_develop: "Xây dựng thói quen lành mạnh",
    help_me_stay: "Tập trung khi làm việc",
    help_me_develop_tooltip:
      "Focus Bear có thể hướng dẫn bạn qua các thói quen lành mạnh (thiền, tập thể dục, viết nhật ký, v.v.) trong thói quen buổi sáng và buổi tối.",
    help_me_stay_focused_tooltip: "Focus Bear sẽ chặn phân tâm khi bạn đang làm việc để bạn có thể làm việc sâu.",
    blockComputerTitle: "Chặn phân tâm trên máy tính?",
    blockComputerQuestion: "Bạn có muốn chặn phân tâm trên máy tính không?",
    organize_tasks_using_ai: "Sắp xếp nhiệm vụ bằng AI",
    organize_tasks_using_ai_tooltip: "Focus Bear có thể sắp xếp nhiệm vụ của bạn bằng AI",
    what_are_you_hoping_focus_bear_can_do: "Bạn hy vọng Focus Bear có thể làm gì?",
    what_are_you_hoping_focus_bear_can_do_placeholder: "Cho chúng tôi biết bạn hy vọng Focus Bear có thể làm gì",
    explore_the_app_first: "Khám phá ứng dụng trước",
    setup_habits: "Thiết lập thói quen",
    setup_habits_question: "Bạn muốn thiết lập thói quen ngay (mất ~3 phút) hay khám phá ứng dụng trước?",
    featureRequestReceived: "Cảm ơn phản hồi! Ý tưởng của bạn giúp chúng tôi cải thiện Focus Bear.",
  },
  goalsSteps: {
    goals: "Mục Tiêu",
    routine: "Thói Quen",
    timing: "Thời Gian",
  },
  habit: {
    habitPack: "Chọn thói quen của bạn",
    autostart: "Tự động bắt đầu",
    habitAutoStart: "Bắt đầu sau {countdown}",
    habitSkipForToday: "Đã bỏ qua thói quen hôm nay",
  },
  setupTime: {
    fineIfLaterOrSooner: "Không sao nếu bạn thức dậy muộn hoặc sớm hơn một chút - chỉ cần nhập thời gian ước tính",
    morningRitualStart: "Nghi thức buổi sáng của bạn sẽ bắt đầu lúc đó",
    setStartupTime: "Chọn Thời Gian Bắt Đầu",
    chooseTheAbsoluteEarliest: "Bạn thức dậy lúc mấy giờ?",
    setShutdownTime: "Bạn kết thúc làm việc/học tập lúc mấy giờ?",
    setSleepTime: "Bạn muốn đi ngủ lúc mấy giờ?",
    focusBearWillTakeOver: "Focus Bear sẽ tạm dừng chặn\nđể bạn có thể thư giãn!",
    subDescriptionFocusBearWillTakeOver: "Thói quen buổi tối bắt đầu lúc {sleep_time}\n(bao gồm 30 phút đệm)",
    focusBearWillTakeOverToolTip:
      "Ở màn hình tiếp theo, bạn sẽ chọn khi nào muốn đi ngủ. Focus Bear sẽ chặn phân tâm lại trước khi bạn đi ngủ để bạn ngủ ngon.",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}: Thời gian tự do",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}: Nghi thức buổi tối rồi đi ngủ",
    subDescriptionTooltipText: "{sleep_time} - {startup_time}: Giờ giới nghiêm điện thoại (thời gian ngủ)",
    distractionBlockDesc: "Phân tâm bị chặn - thư giãn trước khi ngủ",
    techCurfewQuestion: "Bạn có muốn giờ giới nghiêm công nghệ vào ban đêm để ngủ ngon hơn không?",
    techCurfewTooltip: "Focus Bear có thể chặn ứng dụng gây phân tâm trên điện thoại vào buổi tối để bạn ngủ ngon hơn",
    bedtimeForScreens: "Giờ ngủ cho màn hình?",
    bedtimeForScreensSubtitle: "Chúng ta có nên cho điện thoại đi ngủ sớm để bạn nghỉ ngơi không?",
    noThanks: "Không, cảm ơn",
    yesPhoneWrecksSleep: "Có - điện thoại làm hỏng giấc ngủ của tôi!",
    whatTimeGetOffTech: "Bạn muốn ngừng sử dụng công nghệ lúc mấy giờ vào buổi tối?",
  },
  blockList: {
    title: "Làm cho điện thoại an toàn trong thói quen/phiên tập trung",
    subTitleAndroidBlockList: "Chọn ứng dụng gây phân tâm để chặn khi bạn đang thực hiện thói quen hoặc tập trung",
    buttonAndroidBlockList: "Chọn phân tâm",
    subTitleIos: "Chọn ứng dụng gây phân tâm để chặn khi bạn đang thực hiện thói quen hoặc tập trung",
    buttonIos: "Chọn phân tâm",
  },
  editFriction: {
    frictionTooltipDescription:
      'Tất nhiên bạn là người rất kỷ luật nhưng đôi khi bạn có thể bị cám dỗ bỏ qua thói quen hoặc ngừng chặn phân tâm theo ý thích. Bạn có thể thiết lập thêm "độ nghiêm khắc" để giúp làm chậm những suy nghĩ bốc đồng đó. Nếu bạn bật chế độ nghiêm khắc cao, nó sẽ yêu cầu bạn chờ vài giây trước khi ngừng chặn phân tâm.',
    frictionForSkippingHabits: "Độ nghiêm khắc cho việc bỏ qua thói quen",
    reallyEasy: "Rất dễ - Tôi muốn có thể bỏ qua thói quen/nghỉ ngơi nhanh chóng",
    makeItHardToSkip: "Làm cho khó bỏ qua - nếu không tôi sẽ bỏ qua thói quen + nghỉ ngơi hầu hết thời gian",
    appBlocking: "Chặn phân tâm",
    blockDuringDaytime: "Chặn ứng dụng gây phân tâm trong ngày làm việc",
    reallyEasyDescription: "Bạn sẽ có thể ngừng chặn phân tâm ngay lập tức",
    makeItHardToSkipDescription:
      "Để tránh tắt chặn một cách bốc đồng, Focus Bear có thể hiển thị bộ đếm ngược ngắn để khuyến khích bạn xem xét lại liệu bạn có nên truy cập ứng dụng gây phân tâm không.",
  },
  strictness: {
    setPassword: "Đặt mật khẩu",
    setPasswordDescription:
      "Nếu bạn đang gặp khó khăn trong việc duy trì thói quen, hãy nhờ bạn cùng phòng/đối tác đặt mật khẩu. Bạn sẽ không thể bỏ qua thói quen mà không có mật khẩu.",
    enterConfirmPasswordHint: "Xác Nhận Mật Khẩu",
    askForPassword: "Yêu cầu mật khẩu",
    whenRequirePasswordDescription: "Khi nào bạn muốn yêu cầu mật khẩu",
    changingSettings: "Thay đổi cài đặt",
    postponingMorningRoutine: "Hoãn/Bỏ qua thói quen buổi sáng",
    postponingEveningRoutine: "Hoãn/Bỏ qua thói quen buổi tối",
    postponingAfterCuttOffTime: "Hoãn/Bỏ qua thói quen buổi tối sau giờ giới hạn",
    usingPhoneLateNight: "Sử dụng điện thoại vào đêm khuya",
    relaxFocusMode: "Cho phép sử dụng chế độ tập trung thư giãn",
    suggestion: "Gợi Ý",
  },
  subscription: {
    upgrade: "Nâng Cấp",
    restorePurchases: "Khôi Phục Mua Hàng",
    restorePurchasesError: "Thiếu biên lai",
    restorePurchasesError2: "Đã xảy ra lỗi. Vui lòng thử lại sau.",
    personalizedHabit: "Thói quen cá nhân hóa",
    productivityBoosting: "Nghỉ ngơi tăng năng suất",
    customizedFocus: "Chế độ tập trung tùy chỉnh",
    automaticGoals: "Theo dõi mục tiêu tự động",
    cancel: "Hủy tự động gia hạn",
    subscription: "Đăng Ký",
    trialActive:
      "Bản dùng thử của bạn còn {day} ngày. Đừng lo, bạn sẽ không bị tính phí khi hết thời gian dùng thử và không cần thẻ tín dụng trước",
    trialActiveShort: "Dùng thử: còn {day} ngày",
    getSubscriptionPlan: "Đăng ký gói để sử dụng ứng dụng và mở khóa tất cả tính năng",
    subscriptionPlanPrice: "Tiếp tục chỉ với <bold>{amount}</bold>/tháng",
    benefit: "Gói hàng tháng bao gồm",
    doesSubscriptionAutoRenew: "Đăng ký của tôi có tự động gia hạn không?",
    subscriptionAutoRenew:
      "Gói hàng tháng này tự động gia hạn trừ khi tự động gia hạn được tắt ít nhất 24 giờ trước khi kết thúc kỳ hiện tại. Tài khoản của bạn sẽ bị tính phí gia hạn trong vòng 24 giờ trước khi kết thúc kỳ hiện tại với giá đăng ký ({amount}). Bạn có thể quản lý hoặc hủy đăng ký bất cứ lúc nào qua cài đặt tài khoản trong Cửa hàng.",
    thankYouForSubscribing:
      "Cảm ơn bạn đã đăng ký, bạn có thể sử dụng tất cả tính năng của Focus Bear\n\nĐăng ký của bạn sẽ hết hạn sau <bold>{day}</bold> ngày",
    thankYouForSubscribingGuestMode:
      "Cảm ơn bạn đã đăng ký! Để tiếp tục sử dụng tất cả tính năng của đăng ký Focus Bear, hãy đăng nhập và khôi phục đăng ký trên màn hình này.",
    thanksForSubscribingShort: "Cảm ơn sự hỗ trợ của bạn 🎉",
  },
  editHabit: {
    okay: "Được",
    error: "Lỗi",
    unableToSaveSettings:
      "Đã xảy ra lỗi. Rất xin lỗi. Đội kỹ thuật của chúng tôi đã được thông báo và chúng tôi sẽ sửa ngay. Nếu bạn không nhận được phản hồi trong 24 giờ, vui lòng email support@focusbear.io và chúng tôi sẽ khắc phục cho bạn.",
    goingBack: "Bạn sắp quay lại menu Cài đặt. Nếu bạn đã thực hiện thay đổi, vui lòng nhấn nút 'Lưu Thói Quen'.",
    continue: "Tiếp Tục",
    cancel: "Hủy",
    warning: "Cảnh Báo",
    restartingIn: "Đang khởi động lại Focus Bear sau {seconds}...",
    settingsSavedSuccessfully: "Đã lưu thói quen",
  },
  shareLogs: {
    pleaseWriteFeedback: "Vui lòng viết tin nhắn phản hồi",
    enterFeedBack: "Nhập phản hồi của bạn",
    logsShared: "Cảm ơn! Báo cáo phản hồi của bạn đã được chia sẻ với đội hỗ trợ.",
    submitAnother: "Gửi thêm",
    errorUploading:
      "Đã xảy ra lỗi khi tải lên nhật ký. Đảm bảo bạn có kết nối internet ổn định và thử lại. $t(networkError.ifTheProblemPersists)",
    errorZipCreation: "Đã xảy ra sự cố khi xử lý tệp. Vui lòng thử lại. $t(networkError.ifTheProblemPersists)",
  },
  impact_reporting: {
    title: "Phân Tích Giấc Ngủ và Tâm Trạng",
    description:
      "Bạn có muốn theo dõi giấc ngủ và tâm trạng để xem Focus Bear có tạo ra sự khác biệt tích cực cho cuộc sống của bạn không? Điều này cũng giúp chúng tôi bằng cách cung cấp dữ liệu (ẩn danh) về tác động của ứng dụng.",
    subtitle: "Dữ liệu chúng tôi sẽ thu thập",
    bulletPoints:
      "● Số giờ ngủ\n● Tâm trạng và mức năng lượng của bạn\n● Bạn cảm thấy năng suất như thế nào vào cuối ngày",
    okSure: "Được, chắc chắn",
    noThanks: "Không, cảm ơn",
  },
  privacyModal: {
    heading: "Quyền Riêng Tư và Bảo Mật",
    notShareData:
      "Chúng tôi rất coi trọng quyền riêng tư và bảo mật của bạn. Chúng tôi sẽ không bao giờ chia sẻ dữ liệu của bạn.",
    doNotLog: "• Chúng tôi không ghi lại trang web hoặc ứng dụng bạn truy cập.",
    chooseToBlock:
      "• Tuy nhiên, nếu bạn muốn chặn ứng dụng gây phân tâm, chúng tôi cần lưu tên các ứng dụng đó trong cơ sở dữ liệu để cài đặt của bạn đồng bộ trên tất cả thiết bị.",
    dataEncrypted: "• Dữ liệu của bạn được mã hóa và chúng tôi không cho phép ai khác xem.",
    moreDetails:
      "Để biết thêm chi tiết, tham khảo <bold>chính sách bảo mật</bold> của chúng tôi hoặc email support@focusbear.io",
    accept: "Chấp Nhận",
  },
  pushNotiPermission: {
    title: "Cho phép thông báo",
    description: "Chúng tôi có thể nhắc bạn duy trì thói quen và đến đúng giờ cho các cuộc họp.",
  },
  distractionBlockingReason: {
    notLoggedIn: "Chặn tắt: Bạn chưa đăng nhập",
    postponeActivated: "Chặn tắt: Hoãn đã kích hoạt",
    focusModeActivated: "Chặn bật: Chế độ tập trung đã kích hoạt",
    firstDay: "Chặn tắt: Ngày đầu tiên - thói quen chưa kích hoạt",
    otherReason: "Chặn bật: Đã đến lúc thực hiện thói quen",
    daytimeBlockingEnabled: "Chặn bật: thói quen buổi sáng hoàn thành nhưng chặn ban ngày đang bật",
    blockedBySchedule: "Chặn đã bật: Lịch chặn đang hoạt động",
    defaultCase: "Chặn tắt: Chặn phân tâm đã tắt",
    withinCutoffTimeAndShutdownTime: "Chặn tắt: bạn có thời gian rảnh đến {cutoff_time}",
    permissionNotGranted: "Chặn tắt: Chưa cấp quyền (nhấn đây để sửa)",
    afterCutoffTime: "Chặn bật: Đã đến lúc thư giãn trước khi ngủ",
    afterCutoffTimeAndEveningRoutineFinished: "Chặn bật: Đã đến lúc ngủ",
    detailedCutOffSleepTimeBlockingReason:
      "Phân tâm bị chặn từ {cutoff_time} để bạn có thể ngủ. Thói quen buổi sáng của bạn được đặt bắt đầu lúc {startup_time}. Sau khi hoàn thành thói quen buổi sáng, chặn sẽ dừng.",
  },
  blocking: {
    blockingType: "Loại Chặn",
    allowList: "Danh Sách Cho Phép",
    blockList: "Danh Sách Chặn",
    allowListDescription:
      "Chọn ứng dụng được phép khi bạn đang thực hiện thói quen hoặc tập trung. Mọi thứ khác sẽ bị chặn.",
    blockListDescription:
      "Chọn ứng dụng gây phân tâm cần chặn khi bạn đang thực hiện thói quen hoặc tập trung. Mọi thứ khác sẽ được phép.",
    appBlockList: "Danh Sách Chặn Ứng Dụng",
    appAllowList: "Danh Sách Cho Phép Ứng Dụng",
    blockAtLeastOne: "Vui lòng chọn ít nhất một ứng dụng để tránh bị phân tâm",
    socialFilterTitle: "Mạng Xã Hội",
    newsFilterTitle: "Tin Tức",
    gamesFilterTitle: "Trò Chơi",
    miscFilterTitle: "Khác",
    recommendedSectionListTitle: "Ứng dụng được đề xuất chặn",
    otherSectionListTitle: "Ứng Dụng Khác",
    freeAppLimitTitle: "Xin lỗi, tối đa 5 ứng dụng chặn trong phiên bản miễn phí",
    freeAppLimitDesc:
      "Trong phiên bản miễn phí, bạn chỉ có thể chọn 5 ứng dụng để chặn. Trả phí cho Focus Bear pro giúp hỗ trợ phát triển để chúng tôi có thể xây dựng tính năng mới cải thiện năng suất của bạn 🙂",
    Success: "Đã Lưu Cài Đặt",
    saveSuccess: "Đã lưu tùy chọn ứng dụng thành công",
  },
  permissionExplanation: {
    distractionGetBlockedWhen: "Phân tâm bị chặn khi:",
    title: "Thiết lập quyền để chặn phân tâm",
    description: "Focus Bear có thể chặn phân tâm khi bạn làm việc, ngủ và thực hiện thói quen",
    workTask: "• bạn đang làm việc/học tập để hoàn thành công việc ⚒️",
    routineTask: "• bạn đang thực hiện thói quen buổi sáng và buổi tối để duy trì thói quen 🧘",
    sleepTask: "• bạn đang ngủ để thực sự được ngủ 😴",
    toggleOption: "Theo mặc định, bạn có thể tắt chặn phân tâm bất cứ lúc nào.",
    friendOption: "(Nhưng bạn cũng có thể chọn để bạn bè đặt mật khẩu để khó hơn)",
    necessaryPermission:
      "Quyền sử dụng: Để phát hiện nếu bạn mở ứng dụng gây phân tâm\n\nQuyền phủ lớp: Đây là thứ thực hiện chặn phân tâm",
  },
  blockingPermissionIntro: {
    introTitle: "Hãy thiết lập chặn phân tâm để tôi có thể đồng hành nhắc nhở bạn.",
    introPrimary: "Thiết lập chặn phân tâm",
    introBubble: "Trông sẽ\nđại khái như thế này.",
    howItWorksTitle:
      "Trong các khoảng thời gian tập trung đã lên lịch, tôi sẽ chặn nhẹ nhàng những app kéo bạn lệch hướng.",
    howItWorksBody: "Bạn luôn chủ động – có thể tạm dừng hoặc điều chỉnh bất cứ lúc nào.",
    howItWorksPrimary: "Nghe ổn",
    howItWorksBubble: "Tiếp theo bạn chỉ cần bấm “Tiếp tục”.",
    screenTimeCongratsTitle: "Tốt lắm, bạn đã hoàn tất bước quan trọng này.",
    whatYouNeedTitle: "Để làm được điều này, tôi cần một vài quyền trên điện thoại của bạn.",
    whatYouNeedPrimary: "Tiếp tục",
    whatYouNeedBubble: "Ví dụ: chặn các app gây xao nhãng trong lúc bạn ngủ.",
    scheduleCreatedTitle: "Hoàn hảo. Giờ bạn đã có một lịch trình ổn định.",
    scheduleCreatedPrimary: "Tiếp tục",
    scheduleCreatedBubble: "Bạn luôn có thể chỉnh sửa lại trong app sau này.",
    finishTitle: "Tuyệt vời, mọi thứ đã sẵn sàng để chúng ta cùng giữ đúng lộ trình.",
    finishPrimary: "Hoàn tất",
    androidIntroTitle: "Hãy thiết lập chặn phân tâm để tôi có thể đồng hành nhắc nhở bạn.",
    androidUsageTitle: 'Trước hết tôi cần biết bạn đang dùng những app nào. Bạn cần bật quyền "Truy cập sử dụng".',
    androidUsagePrimary: "Mở Cài đặt",
    androidUsageBubble: "Hãy thử tìm nút gạt này trong màn hình cài đặt.",
    androidOverlayTitle:
      'Tôi dùng quyền "Hiển thị trên ứng dụng khác" để có thể hiện lên dạng cửa sổ nhắc nhỏ giống màn hình này.',
    androidOverlayPrimary: "Thiết lập ngay",
    androidOverlayBubble: "Tôi sẽ yêu cầu quyền để có thể nhắc bạn đúng lúc.",
    androidPermissionVisualTitle: "Màn hình cấp quyền sẽ trông như thế này.",
    androidPermissionVisualPrimary: "Bật quyền truy cập",
    androidPermissionVisualBubble: "Cùng nhau tìm\nmục này nhé.",
    androidProceedPrimary: "Tiếp tục",
    androidScheduleSetupTitle: "Rất tốt. Hãy tạo lịch chặn tự động để tôi nhắc bạn vào những khung giờ nhất định.",
    androidScheduleSetupPrimary: "Thiết lập lịch chặn",
    androidScheduleSetupBubble: "Ví dụ: chặn các app gây xao nhãng khi bạn đang ngủ.",
    holdOnTitle: "Hold on a minute!",
    captainBearMessage: "Arr... if you want to focus better, you've got to get your habits shipshape first.",
  },
  grantPermission: {
    title: "Chúng tôi cần quyền để chặn ứng dụng",
    description: "Đừng lo, bạn có thể tạm dừng chặn phân tâm bất cứ lúc nào",
    needHelp: "Cần trợ giúp?",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "Giữ chặn được bật",
    description: "Cho phép Focus Bear tiếp tục chặn ứng dụng ở chế độ nền bằng cách tắt tối ưu hóa pin.",
    warning: "Điều này sẽ sử dụng nhiều pin hơn một chút (nhưng không nhiều lắm).",
    keepFocusBearPoweredUp: "Giữ Focus Bear luôn hoạt động",
  },
  launcher: {
    title: "Ứng Dụng",
    morning: "🔆 Buổi Sáng",
    evening: "🌙 Buổi Tối",
    play: "🥳 Giải Trí",
    work: "🔨 Làm Việc",
    setAppLabel: "Chọn danh mục cho {appName}",
    search: "Tìm kiếm ứng dụng",
    noAppsFound: "Không tìm thấy ứng dụng",
    setAsDefaultLauncher: "Trình Khởi Chạy Mặc Định",
    restricted: "Bị Hạn Chế",
    restrictedMessage: "{appName} đang bị hạn chế, vui lòng tập trung vào thói quen của bạn",
    stopBlocking: "Tạm dừng chặn",
    openAppMenuToolTip: "Nhấn đây để mở menu ứng dụng",
  },
  DND: {
    duringFocusSessions: "Trong Phiên Tập Trung",
    duringHabits: "Trong Thói Quen & Giấc Ngủ",
  },
  bearsona: {
    explanation: "Bạn muốn loại gấu nào động viên bạn? Focus Bear sẽ thay đổi giọng điệu tương ứng",
    title: "Bearsona",
    choose: "Chọn một Bearsona",
    useCustomLanguage: "Sử dụng {customLanguage}",
    useCustomLanguageConfirmation: "Sử dụng {customLanguage} làm ngôn ngữ của bạn?",
    useCustomLanguageConfirmationDesc: "Cảnh báo: điều này vui nhưng có thể hơi khó hiểu",
    confirmUseCustomLanguage: "Nói tiếng Anh với tôi",
    cancelUseCustomLanguage: "Tôi đổi ý rồi",
    name: {
      default: "Gấu Gốc",
      pirate: "Gấu Thuyền Trưởng",
      focus: "Gấu Tập Trung",
      jester: "Gấu Hề",
      sassy: "Gấu Sành Điệu",
      cheerleader: "Gấu Cổ Vũ",
    },
    description: {
      default: "Trợ lý gấu thân thiện của bạn",
      pirate: "Yarrr! Gấu Thuyền Trưởng phục vụ bạn",
      focus: "Tập trung là siêu năng lực của tôi",
      jester: "Gấu Hề sẵn sàng chơi",
      sassy: "Gấu Sành Điệu ở đây để tỏa sáng",
      cheerleader: "Gấu Cổ Vũ đang cổ vũ cho bạn!",
    },
  },
  blockUrl: {
    addSomeSuggestedUrls:
      "Chúng tôi đã thêm một số trang web được đề xuất mà hầu hết mọi người thấy gây phân tâm. Xóa chúng nếu bạn cần",
    unblockableUrlTitle: "Không Thể Chặn URL",
    unblockableUrlMessage: "URL này không thể chặn được. Vui lòng nhập URL khác để chặn.",
    freemiumLimit: "Bạn chỉ có thể chặn 3 URL trong phiên bản miễn phí.",
    freemiumLimitDescription: "Nâng cấp lên phiên bản Pro để chặn không giới hạn URL.",
    title: "Chặn Trang Web",
    description: "Bạn lãng phí thời gian trên trang web nào?",
    inputPlaceholder: "Nhập URL để chặn...",
    urlExistsTitle: "URL đã tồn tại",
    urlExistsMessage: "Vui lòng nhập URL khác để chặn.",
    invalidUrlTitle: "URL Không Hợp Lệ",
    invalidUrlMessage: "Vui lòng nhập URL hợp lệ để chặn.",
    saveSuccess: "Đã lưu URL bị chặn thành công.",
    saveError: "Không thể lưu URL bị chặn. Vui lòng thử lại.",
  },
  accessibility: {
    title: "Quyền Trợ Năng",
    howToEnableAccessibility: "Cách bật quyền trợ năng",
    enableAccessibility: "Bật trợ năng",
    permissionRequired: "Yêu Cầu Quyền Trợ Năng",
    permissionDescription:
      "Trang web có thể gây phân tâm như ứng dụng. Focus Bear cũng có thể chặn trang web nếu bạn bật quyền trợ năng. Điện thoại của bạn sẽ hiển thị cảnh báo - đó là bình thường!",
    whatWeDo: "Đây là những gì chúng tôi làm:",
    checkSites: "Kiểm tra danh sách chặn của bạn",
    checkSitesDescription: "Chúng tôi kiểm tra xem trang web có trong danh sách chặn bạn đặt không.",
    zeroDataTracked: "Chỉ vậy thôi. Không theo dõi, không lưu dữ liệu.",
  },
  passwordRules: {
    passwordRequirements: "Mật khẩu phải chứa ít nhất một số, một chữ hoa và một ký tự đặc biệt",
    minLength: "Tối thiểu 8 ký tự",
    includeNumbers: "Bao gồm số",
    includeLowerCase: "Bao gồm chữ thường",
    includeUpperCase: "Bao gồm chữ hoa",
    includeSpecialChars: "Bao gồm ký tự đặc biệt",
  },
  permissions: {
    privacyFirst: "Chúng tôi rất coi trọng quyền riêng tư của bạn",
    notTracked: "Focus Bear <bold>KHÔNG</bold> theo dõi:",
    anythingType: "Bất cứ thứ gì bạn gõ",
    anythingTypeDescription: "Mật khẩu, tin nhắn, email",
    browserHistory: "Lịch sử duyệt web của bạn",
    browserHistoryDescription: "Chúng tôi không bao giờ xem hoặc lưu các trang web bạn truy cập",
    helpStayFocused: "Chúng tôi ở đây để giúp bạn tập trung!",
    revokeHealthPermission: "Thu Hồi Quyền Sức Khỏe",
    revokeHealthPermissionDescription:
      "Xin lỗi do hạn chế của Apple, chúng tôi không thể thu hồi quyền sức khỏe. Nếu bạn muốn thu hồi, vui lòng vào ứng dụng `Sức Khỏe` và thu hồi từ đó.",
    healthGroup: "Sức Khỏe & Giấc Ngủ",
    healthGroupDescription:
      "Focus Bear có thể theo dõi dữ liệu sức khỏe và giấc ngủ để giúp bạn cải thiện sức khỏe và giấc ngủ. Dữ liệu này được sử dụng để giúp bạn cải thiện sức khỏe và giấc ngủ.",
    areYouSure: "Bạn có chắc muốn thu hồi quyền này không?",
    revokePermissionDescription: "Điều này sẽ thu hồi quyền của ứng dụng.",
    experimentalGroup: "Thử Nghiệm",
    experimentalDescription:
      "Thiết lập Focus Bear làm ứng dụng màn hình chính/trình khởi chạy mặc định để bạn thấy thói quen ngay khi mở điện thoại. Nó cũng làm cho ứng dụng gây phân tâm ít rõ ràng hơn.",
    blockingAppsGroup: "Để chặn ứng dụng",
    routineUpdatesGroup: "Để cập nhật thói quen",
    routineUpdatesGroupDescription:
      "Focus Bear sẽ gửi thông báo khi đến lúc thực hiện thói quen buổi sáng hoặc buổi tối",
    urlBlockingGroup: "Để chặn URL",
    urlBlockingGroupDescription:
      "Nếu bạn muốn chặn trang web, Focus Bear cần quyền trợ năng để phát hiện khi bạn truy cập trang gây phân tâm và chuyển hướng bạn đi.",
  },
  breathingExercise: {
    title: "Bài Tập Thở",
    description: "Bài tập chánh niệm nhanh trước khi bạn mở ứng dụng gây phân tâm này.",
    dontWantToOpen: "Không muốn mở {appName}",
    wantToOpen: "Tiếp tục đến {appName}",
    motivational: "Ôi! Bạn có chắc muốn mở {appName} không?",
  },
  byPassTimePicker: {
    title: "Tạm dừng chặn để mở {app}",
    duration: "{count} phút",
    intention: "Bạn muốn đạt được gì trong {app}?",
    intentionInfo: "Dễ mất phương hướng khi mở ứng dụng gây mất tập trung. Tôi sẽ nhắc bạn về mục tiêu của mình.",
    intentionRequiredError: "Vui lòng nhập mục đích của bạn trước khi tiếp tục.",
  },
  loading: {
    loading: "Đang Tải",
    breathingExercise:
      "Trong khi chờ đợi, hãy thử bài tập thở hộp. Hít vào trong 3 giây, giữ 3 giây, thở ra 3 giây, giữ 3 giây.",
    loadingHabit: "Đang tải thư viện thói quen",
    pleaseWaitLoadHabit:
      "Chúng tôi sẽ đề xuất thói quen dựa trên những gì quan trọng với bạn. Dựa trên mục tiêu của bạn, chúng tôi sẽ gợi ý thói quen hữu ích từ thư viện được tuyển chọn để bạn bắt đầu.",
  },
  stats: {
    title: "Thống Kê",
    tabs: {
      screentime: "Thời Gian Màn Hình",
      otherStats: "Thống kê khác",
    },
  },
  appUsage: {
    noAppsDetected: "Không phát hiện ứng dụng",
    seeMore: "Xem thêm",
    close: "Đóng",
    usage: "Thống Kê",
    title: "Thống Kê",
    longTitle: "Thống Kê Ứng Dụng & Sức Khỏe",
    lowQualityAppDetected:
      "Phát hiện ứng dụng chất lượng thấp. Bạn có muốn thêm ứng dụng này vào danh sách chặn không?",
    yes: "Có",
    no: "Không",
    ignore: "Bỏ qua",
    dailyAppUsage: "Thời Gian Màn Hình Ứng Dụng",
    totalTimeUsed: "Tổng Thời Gian Sử Dụng",
    doingGreat: "Bạn đang làm tốt lắm! Tiếp tục phát huy!",
    todayBlockCount: "Số Lần Chặn Hôm Nay",
    focusBearUsage: "Sử Dụng Focus Bear",
    topBlockedApps: "Ứng Dụng Bị Chặn Nhiều Nhất",
    blockedAppsUsage: "Sử Dụng Ứng Dụng Bị Chặn",
    timeBlocked: "Số Lần Bị Chặn",
    timeSpent: "Thời Gian Sử Dụng",
    lastUsed: "Lần Cuối Sử Dụng",
    noAppsBlocked: "Không có ứng dụng bị chặn",
    noData: "Làm tốt lắm! Bạn chưa sử dụng ứng dụng nào",
    noPermission: "Chúng tôi có thể hiển thị thống kê thời gian màn hình thú vị nếu bạn cấp quyền Sử Dụng Ứng Dụng",
    grantPermission: "Cấp Quyền Sử Dụng",
    overLimit: "Ôi không! Bạn đã vượt quá giới hạn",
    lowQualityScreenTime: "Thời gian màn hình chất lượng thấp",
    highQualityScreenTime: "Thời gian màn hình chất lượng cao",
    timeUsedAfterCutoff:
      "Bạn đã sử dụng điện thoại <bold>{duration}</bold> trong thời gian ngủ tối qua.\n\nBạn có muốn tăng mức độ nghiêm khắc để giúp bạn tránh xa công nghệ khi ngủ không?",
    timeUsedAfterCutoffTitle: "Thời Gian Sử Dụng Sau Giờ Ngủ",
    dontShowAgain: "Không hiển thị lại",
    howDistractingIsThisApp: "Ứng dụng này gây phân tâm như thế nào?",
    dragToEdit: "Kéo để chỉnh sửa",
    save: "Lưu",
    learnMore: "Tìm Hiểu Thêm",
    qualityLabel: {
      extremelyDistracting: "Cực Kỳ Gây Phân Tâm",
      veryDistracting: "Rất Gây Phân Tâm",
      slightlyDistracting: "Hơi Gây Phân Tâm",
      neutral: "Trung Lập",
      slightlyProductive: "Hơi Năng Suất",
      productive: "Năng Suất",
      veryProductive: "Rất Năng Suất",
    },
    qualityDescription: {
      veryDistracting:
        "Ứng dụng liên tục đòi hỏi sự chú ý, thường làm bạn xao nhãng khỏi công việc được coi là Rất Gây Phân Tâm.",
      distracting:
        "Ứng dụng có thể dễ dàng kéo bạn ra khỏi công việc quan trọng và tiêu tốn nhiều thời gian được coi là Gây Phân Tâm.",
      slightlyDistracting:
        "Ứng dụng đôi khi có thể làm gián đoạn sự tập trung nhưng có thể quản lý được với một chút kỷ luật được coi là Hơi Gây Phân Tâm.",
      neutral: "Ứng dụng phục vụ mục đích thực tế mà không ảnh hưởng đáng kể đến năng suất được coi là Trung Lập.",
      slightlyProductive: "Ứng dụng đóng góp vào sức khỏe, học tập hoặc phát triển cá nhân được coi là Hơi Năng Suất.",
      productive: "Ứng dụng giúp bạn hoàn thành công việc, tổ chức và làm việc hiệu quả được coi là Năng Suất.",
      veryProductive:
        "Ứng dụng là công cụ thiết yếu cho công việc, sức khỏe hoặc chức năng hàng ngày quan trọng được coi là Rất Năng Suất.",
    },
    loadingMessage: {
      harvesting: "Đang thu thập dữ liệu sử dụng",
      removingGremlins: "Đang loại bỏ lỗi thống kê",
      crunchingFormulas: "Đang tính toán công thức tập trung",
      assemblingMetrics: "Đang tổng hợp số liệu tiến độ",
    },
  },
  healthMetrics: {
    title: "Thống Kê Sức Khỏe",
    tapToView: "Nhấn để xem số liệu sức khỏe",
    tapToCollapse: "Nhấn để thu gọn",
    healthPermissionsRequired: "Yêu Cầu Quyền Sức Khỏe",
    tapToGrantPermissions: "Nhấn để cấp quyền sức khỏe để xem số liệu",
    sleep: "Giấc Ngủ",
    activeMinutes: "Phút Hoạt Động",
    steps: "Bước Chân",
    loadingHealthData: "Đang tải dữ liệu sức khỏe...",
    error: "Lỗi: {error}",
    physicalActivityPermissionsRequired: "Yêu Cầu Quyền Hoạt Động Thể Chất",
    tapToGrantPhysicalActivityPermissions: "Nhấn để cấp quyền hoạt động thể chất để xem số liệu",
  },
  participantCode: {
    exitUnicaesStudy: "Thoát Nghiên Cứu UNICAES",
    enrolUnicaesStudy: "Đăng Ký Nghiên Cứu UNICAES",
    consentFormTitle: "Mẫu Đồng Ý",
    consentFormDesc: "Vui lòng đọc mẫu đồng ý và đồng ý tham gia nghiên cứu",
    whatsappConsent: "Tôi đồng ý nhận tin nhắn Whatsapp mỗi tuần một lần với cập nhật về nghiên cứu",
    invalidPhoneNumber: "Vui lòng nhập số điện thoại hợp lệ",
    phoneNumber: "Số Điện Thoại",
    enterYourPhoneNumber: "Nhập số điện thoại của bạn",
    unicasStudy: "Nghiên Cứu UNICAES",
    syncManually: "Đồng Bộ Thủ Công",
    facultyOfBusiness: "Khoa Kinh Doanh",
    facultyOfEngineering: "Khoa Kỹ Thuật và Kiến Trúc",
    facultyOfHumanities: "Khoa Khoa Học và Nhân Văn",
    facultyOfHealth: "Khoa Khoa Học Sức Khỏe",
    yearLevel1: "Năm 1",
    yearLevel2: "Năm 2",
    yearLevel3: "Năm 3",
    yearLevel4: "Năm 4",
    yearLevel5: "Năm 5",
    wrongEmail: "Mã tham gia không khớp với địa chỉ email của bạn. Vui lòng liên hệ support@focusbear.io",
    invalidName: "Vui lòng nhập tên của bạn",
    invalidEmail: "Vui lòng nhập địa chỉ email UNICAES hợp lệ",
    invalidFaculty: "Vui lòng chọn khoa của bạn",
    invalidYearLevel: "Vui lòng chọn năm học của bạn",
    emailAlreadyExists: "Email này đã được đăng ký cho nghiên cứu",
    pleaseCheckEmail: "Vui lòng kiểm tra email để lấy mã tham gia",
    register: "Đăng Ký",
    invalidCode: "Mã không hợp lệ",
    email: "Email",
    name: "Tên",
    faculty: "Khoa",
    yearLevel: "Năm Học",
    enterYourName: "Nhập họ tên đầy đủ của bạn",
    enterYourEmail: "Nhập email UNICAES của bạn",
    selectFaculty: "Chọn khoa của bạn",
    selectYearLevel: "Chọn năm học của bạn",
    applicationForm: "Mẫu Đăng Ký",
    title: "Focus Bear",
    description:
      "Chúng tôi đang tuyển người tham gia cho nghiên cứu thử nghiệm tại UNICAES. Nếu bạn muốn giúp chúng tôi và tham gia nghiên cứu, vui lòng đăng ký bên dưới. Nếu bạn muốn biết thêm thông tin về nghiên cứu <hereLink>nhấn vào đây</hereLink> hoặc liên hệ chúng tôi tại {email}.",
    moreInfoLink: "nhấn vào đây",
    contactEmail: "support@focusbear.io",
    applyButton: "Đăng Ký Tham Gia",
    hasParticipantCode: "Tôi có mã tham gia",
    enterYourCode: "Nhập mã của bạn",
    continue: "Tiếp Tục",
    back: "Quay Lại",
    permissionNeededTitle: "Cần Quyền Truy Cập",
    permissionNeededDescription:
      "Để tham gia nghiên cứu này, chúng tôi yêu cầu bạn bật quyền theo dõi dữ liệu. Bạn có thể rút khỏi nghiên cứu bất cứ lúc nào bằng cách gỡ cài đặt Focus Bear.",
    uploadScreenshot: "Tải Lên Ảnh Chụp Màn Hình",
    thankYouForJoining:
      "Cảm ơn bạn đã tham gia nghiên cứu, hiện tại chúng tôi chỉ đang thu thập dữ liệu để biết cách bạn sử dụng điện thoại trước khi cung cấp cho bạn quyền truy cập đầy đủ vào các tính năng của Focus Bear. Nếu bạn muốn rút khỏi nghiên cứu, vui lòng gỡ cài đặt Focus Bear. Nếu bạn cần liên hệ hỗ trợ, vui lòng email chúng tôi tại: <email>support@focusbear.io</email>",
    screenshotUploadReminder:
      "Thời Gian Màn Hình, đã đến lúc tải lên ảnh chụp màn hình. Vui lòng làm theo hướng dẫn bên dưới. Nếu bạn cần hỗ trợ, vui lòng liên hệ chúng tôi tại: support@focusbear.io\n\nHướng dẫn:\n\n1. Chụp màn hình sử dụng ứng dụng trong tuần qua\n2. Nhấn nút tải lên ảnh chụp màn hình\n3. Chọn hình ảnh và tải lên",
    usageDataLastSynced: "Dữ liệu sử dụng đồng bộ lần cuối: {date}",
    whatTimeDoYouGoToSleep: "Bạn đi ngủ lúc mấy giờ?",
    whatTimeDoYouSleepDescription:
      "Chúng tôi sẽ sử dụng thông tin này và theo dõi việc sử dụng điện thoại sau giờ ngủ của bạn.",
    setupPermissions: "Cần Thiết Lập",
    setupPermissionsTitle: "Cấp Quyền Ứng Dụng",
    setupPermissionsDesc: "Cho phép Focus Bear giúp bạn tập trung",
    studyTasks: "Nhiệm Vụ Nghiên Cứu",
    flankerTaskTitle: "Hoàn Thành Nhiệm Vụ Flanker",
    flankerTaskDesc: "Kiểm tra sự chú ý và tập trung của bạn",
    questionnaireTitle: "Hoàn Thành Bảng Câu Hỏi",
    questionnaireDesc: "Giúp chúng tôi hiểu trải nghiệm của bạn",
    screenTime: "Đã đến lúc tải lên Thời Gian Màn Hình của bạn",
    screenshotUploadSuccess: "Tải lên thành công",
    imageProcessing: "Đang kiểm tra dữ liệu sử dụng...",
    imageProcessed: "Xử lý ảnh chụp màn hình thành công",
    imageProcessingFailed: "Không thể xử lý ảnh chụp màn hình",
    checkingStatus: "Đang kiểm tra trạng thái",
  },
  flankerGame: {
    title: "Trò Chơi Gấu Flanker",
    welcome: "Chào mừng đến với Trò Chơi Gấu Flanker! Trò chơi này kiểm tra sự chú ý và tập trung của bạn.",
    instruction1: "1. Bạn sẽ thấy một hàng mũi tên",
    instruction2: "2. Tập trung vào mũi tên ở giữa",
    instruction3: "3. Nhấn nút khớp với hướng của mũi tên ở giữa",
    instruction4: "4. Cố gắng nhanh và chính xác nhất có thể (3 giây mỗi lượt)",
    play: "Chơi",
    practiceStart: "Hãy khởi động nhanh để bạn biết cách chơi!",
    mainStart: "Tuyệt vời! Bây giờ bài kiểm tra thực sự bắt đầu.",
    testProgress: "Bài kiểm tra {current} trên {total}",
    ok: "OK",
    timeout: "😢",
    complete: "Hoàn tất!",
    completeMessage: "Cảm ơn! Điều này giúp chúng tôi hiểu cách sự chú ý của bạn hoạt động.",
    practiceComplete: "Hoàn Thành Luyện Tập!",
    mainInstructions: "Bây giờ hãy làm bài kiểm tra thực sự. Bạn có 2 giây để trả lời mỗi lượt.",
    startMain: "Bắt Đầu Bài Kiểm Tra Chính",
    continue: "Tiếp Tục",
  },
  questionnaire: {
    title: "Bảng Câu Hỏi",
    loadingQuestionnaire: "Đang tải bảng câu hỏi",
  },
  routineSuggestion: {
    title: "Gợi Ý Thói Quen",
    generatingRoutine: "Đang tạo thói quen",
    loading: "Đang Tải",
    breathingExercise:
      "Trong khi chờ đợi, hãy xem video này để biết Focus Bear có thể giúp bạn xây dựng thói quen như thế nào.",
    error: "Đã xảy ra lỗi không mong muốn",
    successTitle: "Đã Tạo Thói Quen!",
    successMessage: "Chúng tôi đã tạo một số thói quen mẫu dựa trên mục tiêu của bạn.",
    errorTitle: "Ôi! Đã xảy ra lỗi",
    errorMessage:
      "Chúng tôi không thể tạo thói quen của bạn ngay bây giờ. Bạn có thể thử lại hoặc tiếp tục thiết lập thời gian thủ công.",
    errorMessageGoals:
      "Chúng tôi gặp sự cố và không thể tạo thói quen của bạn, vui lòng cho chúng tôi biết mục tiêu của bạn",
    updateGoals: "Cho chúng tôi biết mục tiêu của bạn",
    noHabitsTitle: "Chưa có thói quen",
    noHabitsMessage:
      "Chúng tôi không tìm thấy thói quen nào từ nhập của bạn. Hãy tạo một số thói quen cá nhân hóa cho bạn!",
    morningRoutine: "Thói Quen Buổi Sáng",
    eveningRoutine: "Thói Quen Buổi Tối",
    totalDuration: "Tổng: {duration}",
    noActivities: "Không có thói quen trong lịch trình này",
    addActivity: "Thêm Thói Quen",
    editActivity: "Sửa Thói Quen",
    adjustWithAI: "Điều Chỉnh với AI",
    createWithAI: "Tạo với AI",
    adjust: "Điều Chỉnh",
    create: "Tạo",
    aiPrompt: "🐻 Những thói quen này trông như thế nào? Hãy cho tôi biết bạn muốn thay đổi gì.",
    aiCreatePrompt: "Mô tả thói quen bạn muốn tạo từ đầu. Ví dụ: 'Tạo thói quen bắt đầu buổi sáng'",
    aiPlaceholder: "ví dụ: 'Làm thiền cụ thể hơn' hoặc 'Thêm bài tập nhanh'",
    aiError: "Không thể điều chỉnh thói quen. Vui lòng thử lại.",
    adjusting: "Đang điều chỉnh thói quen của bạn...",
    creating: "Đang tạo với AI...",
    aiSuccessMessage: "Đã điều chỉnh thói quen thành công.",
    deleteActivityTitle: "Xóa Thói Quen",
    deleteActivityMessage: "Bạn có chắc muốn xóa '{activityName}' không?",
    activityName: "Tên Thói Quen",
    enterActivityName: "Nhập tên thói quen",
    duration: "Thời Lượng",
    minutes: "Phút",
    seconds: "Giây",
    errors: {
      nameRequired: "Tên thói quen là bắt buộc",
      nameTooShort: "Tên thói quen phải có ít nhất 2 ký tự",
      invalidTime: "Vui lòng nhập thời gian hợp lệ",
      timeTooShort: "Thời lượng phải ít nhất 5 giây",
    },
    tapToEdit: "Nhấn để chỉnh sửa",
  },
  juniorBearConversation: {
    messageNormalStep1: "Xin chào, tôi là Focus Bear Junior",
    messageNormalStep2: "Thực ra tôi không giỏi tập trung lắm 😢 Tôi bị ADHD và luôn bị phân tâm.",
    messageNormalStep2_5: "Ồ! Được rồi, bậc thầy tập trung. Có điều gì bạn cần giúp không?",
    messageNormalStep3:
      "Thật khó tập trung với tất cả các ứng dụng vui… ý tôi là gây phân tâm! trên điện thoại. Muốn hợp tác không? Chúng ta có thể cùng tập trung!",
    messageNormalStep4: "Tuyệt vời! Bạn muốn làm việc gì cùng nhau?",
    messageNormalStep5:
      "Hay quá. Bạn có muốn tạo tài khoản để chúng ta có thể làm việc cùng nhau trên máy tính và điện thoại không?",
    messagePirateStep1: "Được triệu hồi để giúp ngươi tập trung, phải không? Gấu Thuyền Trưởng sẵn sàng phục vụ.",
    messagePirateStep1_5:
      "Ngươi làm cháu ta khóc như thủy thủ mới. Giờ đến lượt ta — Gấu Thuyền Trưởng. Đứng thẳng lên, tên cướp biển!",
    messagePirateStep2:
      "Nói thật nhé… ta cũng bị ADHD, giống như nhiều cướp biển giỏi khác. Tâm trí ta lang thang như con tàu không có neo.",
    messagePirateStep2_5: "Har! Một tâm trí sắc bén, ta thấy. Ngươi còn cần hỗ trợ gì?",
    messagePirateStep3:
      "Arr, những ứng dụng sáng bóng đó ồn hơn con vẹt say! Muốn hợp tác không? Chúng ta có thể giữ nhau khỏi rơi xuống biển!",
    messagePirateStep4: "Arrr, hai tay trên boong! Ngươi muốn thuần phục rắc rối gì?",
    messagePirateStep5:
      "Tuyệt! Chúng ta có nên tạo tài khoản để có thể cùng nhau đi biển trên máy tính và điện thoại không?",
    buttonNormalStep1Primary: "Xin chào",
    buttonNormalStep1Secondary: "Arr, ước gì bạn là cướp biển…",
    buttonNormalStep2Primary: "Tôi cũng vậy!",
    buttonNormalStep2Secondary: "Tôi chưa bao giờ gặp vấn đề đó",
    buttonNormalStep2_5Option1: "Duy trì thói quen lành mạnh",
    buttonNormalStep2_5Option2: "Tổ chức công việc",
    buttonNormalStep2_5Option3: "Đi đi! Tôi không thích trẻ con!",
    buttonNormalStep3Primary: "Làm thôi!",
    buttonNormalStep3Secondary: "Đi đi! Tôi không thích trẻ con!",
    buttonNormalStep4Primary: "Tiếp Theo",
    buttonNormalStep5Primary: "Đăng ký cho tôi đi!",
    buttonNormalStep5Secondary: "Không, cảm ơn, tôi sẽ ẩn danh",
    buttonPirateStep1Primary: "Ahoy",
    buttonPirateStep1Secondary: "Chào Thuyền Trưởng",
    buttonPirateStep1_5Primary: "Xin lỗi, Thuyền Trưởng. Tôi sẽ giữ vững chân",
    buttonPirateStep2Primary: "Aye… Tôi thường mất neo",
    buttonPirateStep2Secondary: "Không phải tôi, họ gọi tôi là Râu Não",
    buttonPirateStep2_5Option1: "Xây dựng thói quen thủy thủ vững chắc hơn",
    buttonPirateStep2_5Option2: "Sắp xếp công việc gọn gàng",
    buttonPirateStep3Primary: "Aye, làm thôi!",
    buttonPirateStep3Secondary: "Arr, để đại dương quyết định số phận của tôi",
    buttonPirateStep4Primary: "Tiếp Theo",
    buttonPirateStep5Primary: "Kéo buồm lên — đăng ký cho tôi!",
    buttonPirateStep5Secondary: "Tôi sẽ vẫn là bóng ma trên biển",
    focusAreaBlockDistractionsNormal: "Chặn phân tâm",
    focusAreaBlockDistractionsPirate: "Mài sắc sự tập trung tại bánh lái",
    focusAreaHealthyHabitsNormal: "Duy trì thói quen lành mạnh",
    focusAreaHealthyHabitsPirate: "Xây dựng thói quen thủy thủ vững chắc hơn",
    focusAreaOrganiseTasksNormal: "Tổ chức công việc của bạn",
    focusAreaOrganiseTasksPirate: "Sắp xếp công việc gọn gàng",
  },
  streakCelebration: {
    title: "Chuỗi {streakTypeName}!",
    morning: "Thói quen buổi sáng",
    evening: "Thói quen buổi tối",
    focus: "Phiên tập trung",
    message: "Bạn đang rất xuất sắc! Tiếp tục phát huy.",
    day: "ngày",
    days: "ngày",
  },
  lateNoMore: {
    title: "Nhắc họp",
    calendarIntegration: "Tích hợp lịch",
    calendarTooltip: "Để phát hiện cuộc họp, bạn có thể kết nối lịch trên điện thoại hoặc Google Calendar",
    googleCalendar: "Google Calendar",
    connected: "Đã kết nối",
    notConnected: "Chưa kết nối",
    enableReminders: "Thông báo nhắc",
    calendarPermission: "Lịch trên thiết bị",
    calendarPermissionAlreadyGranted:
      "Đã kết nối lịch trên thiết bị. Bạn có thể thu hồi quyền bất cứ lúc nào trong cài đặt điện thoại",
    calendarPermissionDenied: "Vui lòng cấp quyền truy cập lịch trong cài đặt điện thoại",
    openSettings: "Mở cài đặt",
    addReminder: "Thêm nhắc",
    durationBefore: "{duration} trước",
    whenMeetingStarts: "Khi cuộc họp bắt đầu",
    requireMeetingUrl: "Chỉ sự kiện có cuộc họp",
    requireMeetingUrlDescription: "Chỉ gồm các sự kiện có liên kết cuộc họp đính kèm",
    notification1: "Cuộc họp sắp bắt đầu! 🐻",
    notification2: "Chuẩn bị tham gia cuộc họp! ⏰",
    notification3: "Cuộc họp của bạn đang đến gần! 🚀",
    notificationBody: "“{title}” bắt đầu {time}",
    now: "bây giờ",
    yourMeetingStartsIn: "Cuộc họp sau <highlight>{countdown}</highlight>. Hãy chuẩn bị!",
    yourMeetingIsOngoing: "Đang có cuộc họp diễn ra. Tham gia <highlight>ngay</highlight>!",
    upcomingMeeting: "Sự kiện sắp tới",
    mentallyPrepare: "1. Chuẩn bị tinh thần cho cuộc họp",
    howDoYouWantToShowUp: "Bạn muốn thể hiện thế nào?",
    placeholderHowToShowUp: "Bình tĩnh, lắng nghe, cởi mở, hợp tác...",
    joinOnTime: "2. Tham gia đúng giờ",
    ignoreMeeting: "Bỏ qua cuộc họp",
    startMeeting: "Tham gia cuộc họp",
    noUpcomingMeetings: "Không có cuộc họp sắp tới",
    noMeetingsDescription: "Chúng tôi không tìm thấy cuộc họp nào trong vài giờ tới.",
    googleCalendarSource: "Nguồn: Google Calendar",
    deviceCalendarSource: "Nguồn: Lịch trên thiết bị",
  },
  streak: {
    title: "Chuỗi ngày đã có!",
    howItWorks:
      "Mỗi ngày hãy <bold>bắt đầu phiên tập trung</bold> và <bold>hoàn thành một thói quen buổi sáng hoặc tối</bold> để duy trì chuỗi ngày.",
    activeStreak: "Chuỗi đang hoạt động",
    activeStreakDesc: "Bạn đã dùng Focus Bear hôm nay.",
    dueStreak: "Chuỗi đang gặp rủi ro",
    dueStreakDesc: "Bạn đã dùng Focus Bear hôm qua. Hãy dùng hôm nay để giữ chuỗi.",
    inactiveStreak: "Chuỗi không hoạt động",
    inactiveStreakDesc: "Bạn đã không dùng Focus Bear hôm qua.",
    motivationTip: "Kiên trì quan trọng hơn các phiên dài.",
    morningStreak: "Chuỗi buổi sáng",
    eveningStreak: "Chuỗi buổi tối",
    focusModeStreak: "Chuỗi chế độ tập trung",
    streakIconTitle: "Ý nghĩa biểu tượng",
    day_zero: "0",
    day_one: "{count} ngày",
    day_other: "{count} ngày",
    morning: "Sáng",
    evening: "Tối",
    focus: "Tập trung",
    days: "ngày",
  },
  widget: {
    defaultRoutine: "Không có lịch trình",
    noReasonProvided: "Sẵn sàng!",
    noNextHabit: "Không có gì được lên lịch",
    whatsNext: "Tiếp theo:",
    streakTitle: "Chuỗi",
    motivationalQuotes: [
      '"Thành công là tổng của những nỗ lực nhỏ, lặp đi lặp lại ngày này qua ngày khác." – Robert Collier',
      '"Bí quyết để tiến lên là bắt đầu." – Mark Twain',
      '"Kỷ luật là lựa chọn giữa điều bạn muốn ngay bây giờ và điều bạn muốn nhất." – Abraham Lincoln',
      '"Tương lai của bạn được tạo ra bởi những gì bạn làm hôm nay, không phải ngày mai." – Robert Kiyosaki',
      '"Mọi thứ dường như không thể cho đến khi nó được hoàn thành." – Nelson Mandela',
    ],
  },
};
