export default {
  languageName: "简体中文",
  baseLanguage: "zh-CN",
  blockingSchedule: {
    title: "阻止计划",
    namePlaceholder: "阻止名称",
    startTime: "从",
    endTime: "到",
    adjustStart: "调整开始时间",
    adjustEnd: "调整结束时间",
    daysHeading: "在这些天",
    chooseApps: "选择应用",
    chooseUrls: "选择网站",
    saveFailedTitle: "无法保存计划",
    saveFailedMessage: "请在选择要阻止的应用后重试。",
    duplicateNameMessage: "请为此阻止计划选择一个唯一名称。",
    focusModeSuffix: "（来自移动端拦截计划）",
    defaultName: "💻 工作时间",
    appBlocking: "应用阻止",
    websiteBlocking: "网站阻止（可选）",
    selectionMissing: "请选择要阻止的应用。",
    noAppsSelected: "未选择应用",
    iOSSelectionCounts: "{applicationsCount} 个应用，{categoriesCount} 个类别，{webDomainsCount} 个网站",
    androidSelectionCount: "已选择 {applicationsCount} 个应用",
    mode: {
      strict: {
        title: "严格阻止",
        subtitle: "无法逃避 - 输入密码解锁",
      },
      cooldown: {
        title: "冷却阻止",
        subtitle: "短暂等待后解锁（给你时间重新考虑）",
      },
      gentle: {
        title: "温和阻止",
        subtitle: "立即暂停阻止，有无限滚动的风险 😅",
      },
    },
    removeTitle: "删除此计划？",
    removeMessage: "这将永久删除该计划。",
    removeFailedMessage: "请重试。",
    blockedBySchedule: "被计划阻止：{scheduleName}",
    appBlockedBySchedule: "{appName} 被阻止，因为您的 {scheduleName} 阻止计划正在生效",
    blockAllDuringHabits: "在所有习惯期间阻止某些应用",
    customizeBlocking: "自定义阻止",
    scheduledBlocksTitle: "计划阻止",
    scheduledBlocksInfoText: "创建在选定日期重复的时间窗口。您可以添加多个阻止。",
    addNewBlock: "添加阻止",
    habitMorningName: "早晨例程",
    allDays: "每天",
    permissionsRequired: "需要权限",
    androidPermissionDescription: "需要使用权限和悬浮窗权限才能阻止应用",
    iOSPermissionDescription: "需要屏幕使用时间权限来创建和管理阻止计划。",
    accessibilityRequiredForUrls: "拦截网站需要开启辅助功能。",
    urlsSelectionMissing: "未选择网站",
    urlsSelectionCount_one: "已选择 {count} 个网站",
    urlsSelectionCount_other: "已选择 {count} 个网站",
    urlsDescription: "在此计划期间添加要拦截的网站",
    selectedUrls: "已选网站",
    suggestedUrls: "推荐网站",
    habitBlocksTitle: "习惯屏蔽",
  },
  tabTitle: {
    overview: "概览",
    habits: "习惯",
    tasks: "任务",
  },
  error: {
    invalidVideoUrl: "该视频网址看起来不对 😕",
    videoNotFound: "抱歉，我们找不到该视频！",
    authenticationErrorName: "身份验证错误",
    authenticationErrorMessage: "糟糕！我们这边的身份验证出了问题。请重试。",
  },
  habitSetting: {
    routine: "例程",
    selectRoutine: "选择例程",
    requirement: "完成此习惯需要做什么",
    youtubeVideo: "YouTube 或 Vimeo 视频",
    youtubeVideoDescription: "添加视频指导您完成此习惯",
    enableTimer: "启用计时器？",
    timer: "计时器",
    timerDescription: "为习惯设置时间长度",
    goal: "目标",
    goalDescription: "每当您实现目标时完成习惯",
    goalPlaceholder: "指定完成目标？...",
    extras: "额外",
    noGoalSpecified: "未指定目标",
    defaultName: "未命名习惯",
    allowedApps: "允许的应用",
    allowedAppsDescription: "选择在践行此习惯时可以使用的应用",
    selectApps: "选择应用",
    appsSelected: "已选择 {count} 个应用",
    noAppsSelected: "未选择",
    openAllowedApps: "打开允许的应用",
    launchApp: "打开",
  },
  common: {
    accept: "接受",
    learnMore: "了解更多",
    doItLater: "稍后执行",
    later: "稍后",
    termsOfUse: "条款和条件",
    privacyPolicy: "隐私政策",
    email: "电子邮件",
    nickname: "昵称",
    skip: "跳过",
    goToSleep: "睡觉时间到了 😴",
    areYouSure: "您确定吗？",
    loading: "加载中...",
    connectionError: "连接错误",
    morning: "早晨",
    evening: "晚上",
    welcome: "欢迎",
    somethingWrong: "出了点问题",
    logout: "退出登录",
    ok: "确定",
    ok_ellipsis: "确定...",
    okay: "确定",
    yes: "是",
    no: "否",
    confirm: "确认",
    next: "下一步",
    cancel: "取消",
    delete: "删除",
    proceed: "继续",
    resume: "恢复",
    retry: "重试",
    submit: "提交",
    resend: "重新发送",
    verify: "验证",
    edit: "编辑",
    finished: "完成",
    done: "完成",
    sec: "秒",
    focusBear: "专注熊",
    tomorrow: "明天",
    today: "今天",
    yesterday: "昨天",
    add: "添加",
    start: "开始",
    startRoutine: "开始日程",
    continue: "继续",
    end: "结束",
    startActivity: "开始 {activityName}",
    startTimerActivity: "开始 {time} {unit} {activityName}",
    Success: "成功！",
    SuccessfullyAddedHabit: "成功添加习惯",
    save_changes: "保存更改",
    save: "保存",
    saving: "保存中",
    saved: "已保存",
    created: "已创建",
    next_time_format: "[{day} at] h:mm A",
    sure: "确定",
    uploadScreenShots: "上传截图\n（可选）",
    session_expired: "会话已过期",
    login_again: "请重新登录",
    continue_activity_name: "继续 {activityName}",
    no_thanks: "不用了，谢谢",
    saveHabitSuccessfully: "{habitName}，已添加到您的 {routineName} 日程",
    couldNotProcessTheRequest: "无法处理请求，请重试",
    error: "错误",
    selected: "已选择",
    all: "全部",
    viewAll: "查看全部",
    more: "更多",
    somethingElse: "其他",
    habit: "习惯",
    empty: "空",
    clearAll: "清除",
    loadingWithoutDot: "加载中",
    pleaseWaitPatiently: "正在加载数据，请稍候。这可能需要几分钟，我们会在后台为你完成设置。",
    granted: "已授权",
    notGranted: "未授权",
  },
  customizeBlocking: {
    customBlockedMessage: {
      title: "自定义阻止消息",
      tooltip: "替换封锁屏幕上的默认励志语录。",
      placeholder: "输入你的自定义消息...",
      hint: "留空将使用默认的励志语录。",
    },
    customSoftBlocking: {
      title: "解锁时长",
      description: "在温和屏蔽模式下休息后，应用保持解锁的时间。",
      hint: "{min} 到 {max} 分钟",
    },
    customPauseDelay: {
      title: "暂停等待时间",
      description: "解锁被屏蔽应用前的一道小关卡。每次尝试都会让下一次更难。",
      hint: "选择 {min}s 到 {max}s",
      sequenceLabel: "你的等待时间",
    },
    saveSuccess: "自定义阻止设置已成功保存",
    saveError: "保存自定义阻止设置失败。请重试。",
  },
  settings: {
    healthPermission: "健康权限",
    physicalActivityPermission: "身体活动权限",
    healthAndSleepPermission: "健康和睡眠权限",
    changedBackendEndpoint: "AWS Backend Endpoint {status}",
    saveBlockedUrls: "成功保存被阻止的网址",
    saveBlockedUrlsError: "保存被阻止的网址失败",
    debugLog: "启用详细日志记录",
    debugLogDescription: "仅在支持团队要求时打开此功能，因为它会减慢应用速度",
    title: "设置",
    addApps: "将应用添加到阻止列表",
    clearBlocklist: "清除阻止列表",
    confirmClearBlocklist: "确认清除阻止列表？",
    strictness: "严格程度",
    shareLogsWithSupport: "报告问题",
    reason_required: "请输入原因",
    enter_a_reason: "您能分享一下为什么要删除您的帐户吗？",
    contact_desc: "我们可以联系您以帮助解决您遇到的问题吗？",
    editFriction: "摩擦",
    password: "密码",
    account: "帐户",
    permissions: "权限",
    language: "语言",
    useSystemLanguage: "使用系统语言",
    supportedLanguages: "支持的语言",
    overlay_permission: "覆盖权限",
    usage_permission: "使用权限",
    notification_permission: "通知权限",
    screen_time_permission: "屏幕时间权限",
    DND_permission: "勿扰权限",
    DND: "阻止通知",
    warning: "警告！",
    DND_permissionWarning: "如果勿扰模式已启用，必须手动禁用。如果未授予勿扰权限，则无法自动关闭。",
    help: "帮助",
    askForHelp: "寻求帮助",
    report_problem: "报告问题",
    discord_server: "Discord 服务器",
    videoTutorials: "视频教程",
    experimental: "实验性",
    customization: "自定义",
    general: "常规",
    focusGames: "专注游戏",
    allowed: "允许",
    notAllowed: "不允许",
    notGrantedYet: "未授权",
    userid: "用户ID",
    copy: "复制",
    copied: "已复制",
    settings: "设置",
    verifyEmail: "验证电子邮件",
    emailVerificationResent: "电子邮件验证已重新发送",
    pendingVerification: "待验证",
    editNickname: "编辑昵称",
    nicknameError: "无效的昵称（仅限字母和数字）",
    nicknameAlreadyExists: "昵称已存在",
    customizeBlocking: "自定义阻止",
    lateNoMore: "会议提醒",
    urlBlockingWarningTitle: "重要：网址拦截仅在 Safari 中有效",
    urlBlockingWarningMessage:
      "网站拦截仅在 Safari 中有效。为防止绕过网址拦截，建议在阻止列表中完全拦截 Chrome、Firefox 和其他第三方浏览器。",
    urlBlockingHowToTitle: "如何拦截网站",
    urlBlockingHowToMessage:
      "在下方点击「将网址添加到阻止列表」，然后在选择器顶部选择「网站」标签。你可以搜索特定网站或按类别浏览。在专注会话期间，所选网站将在 Safari 中被拦截。",
    addUrls: "将网址添加到阻止列表",
    clearBlockedUrls: "清除已拦截的网址",
    confirmClearBlockedUrls: "确认清除已拦截的网址？",
  },
  focus: {
    title: "专注",
    focusLimitReachedTitle: "已达到专注限制",
    focusLimitReachedMessage: "在免费版本中，您只能专注最多25分钟。如果您想要更长的专注时间，请升级到高级版。",
  },
  blockingStatusBanner: {
    additionalSchedules: " +{count} 更多",
    activeSchedule: "{name} ({start} – {end}) {extra}",
  },
  home: {
    setupHabitsDescription: "设置您的习惯以开始新的一天。",
    upEarlyStartMorningRoutine: "起得早？开始早晨日程",
    getMotivated: "获得动力",
    completed: "已完成",
    habitName: "习惯名称",
    newHabit: "新习惯...",
    duration: "持续时间",
    editHabit: "编辑习惯",
    addHabit: "添加习惯",
    deleteThisHabit: "删除此习惯",
    deleteHabit: "删除习惯 {name}",
    deleteHabitTitle: "删除习惯",
    deleteHabitMessage: "您确定要删除此习惯吗？此操作无法撤消。",
    afterCutoffTimeDescription: "您的习惯都不可用，因为已过截止时间",
    routineNotScheduledNow: "此例行公事计划在{routineSchedule}",
    cutOffToolTip: "您已为习惯配置了截止时间，因此在{cutOffTime}之后无法访问。\n您可以在更改时间中修改此设置",
    unlockToProceed: "解锁以继续",
    title: "主页",
    morningRitual: "您的早晨仪式",
    eveningRitual: "您的晚上仪式",
    time_to_earn_screen_time: "完成您的早晨日程习惯，为美好的一天做好准备",
    evening_routine_text: "完成后您将准备好享受美好的睡眠！",
    upcoming_below_new_activities: "以下是您需要在下一个日程中完成的习惯才能使用手机。",
    start: "开始",
    mins: "分钟",
    secs: "秒",
    re_activate: "恢复阻止",
    force_deactivate_postpone_and_start_routine: "日程已被推迟\n恢复日程？",
    userCompletedRoutineHeading: "完成日程做得好。期待在{routineTime}帮助您完成下一个日程",
    postOnboardingRoutineHeading: "欢迎加入！期待在{routineTime}帮助您完成{routineName}日程",
    wantLogout: "您想退出登录吗？",
    noDataFound: "您还没有设置任何习惯。点击<fix>这里</fix>添加习惯。",
    routineFetchingError: "我们在检索日程数据时遇到问题。请稍后重试或联系我们寻求帮助",
    hi: "你好 {nickname}！",
    welcomeDefault: "你好！",
    goodMorningFocusTime: "早上好！",
    goodEveningFocusTime: "晚上好！",
    allActivitiesCompleted: "没有剩余的习惯要完成",
    startRoutineNow: "开始我的{routineName}日程",
    customRoutineReady: "您现在可以开始自定义例程",
    passwordForSettingsTitles: "输入密码以继续",
    manageAlwaysAllowedAppsDesc:
      "在您的早晨/晚上日程期间以及您在电脑上专注时，除了始终允许的应用外，手机上的所有应用都将被阻止。我们建议只允许短信、电话和工作所需的应用，这样您在习惯/工作期间不会分心。",
    manageAlwaysBlockedAppsDesc:
      "在您的早晨/晚上日程期间以及您在电脑上专注时，阻止列表中的所有应用都将被阻止。我们建议阻止社交媒体、游戏、电子邮件和新闻应用，这样您在习惯/工作期间不会分心。",
    overlayPermission: "悬浮窗权限",
    usagePermission: "使用权限",
    editHabits: "编辑习惯",
    editYourHabits: "编辑您的习惯",
    stats: "统计",
    motivationMsg: "获得动力",
    play: "播放",
    pause: "暂停",
    customizeHabits: "编辑例程",
    deleteAccount: "删除账户？",
    accountDataHasBeen: "账户数据已成功删除。感谢使用Focus Bear。",
    blockSuperDistractingApps: "阻止超级分散注意力的网站/应用",
    skipHabitDesc: "今天跳过此习惯",
    screenTimePermissionNotAllowedWarningText: "需要屏幕使用时间权限来阻止应用，请重新开始习惯以允许权限",
    OverlayPermissionNotGrantedWarning: "警告：分心阻止未激活。悬浮窗权限未授予。修复。",
    ScreenTimePermissionNotGrantedWarning: "警告：分心阻止未激活。屏幕使用时间权限未授予。修复。",
    UsagePermissionNotGrantedWarning: "警告：分心阻止未激活。使用权限未授予。修复。",
    noAllowedAppSelectedWarning: "警告：您还没有配置阻止列表，所以分心不会被阻止。编辑阻止列表",
    habitLimitMessage: "免费用户每个日程只能访问最多3个习惯。请升级以解锁更多习惯。",
    routineOptionsTooltip: "在此菜单可编辑日程或更改时间。",
    youHaveNotSetupAnyHabitsYet: "您还没有设置任何习惯。",
    guestMode: "访客模式",
    guestSignUpDescription: "注册以在所有设备上访问您的内容并解锁个性化功能。",
    deleteRoutineTitle: "删除日程",
    deleteRoutineMessage: "您确定要删除此日程及所有相关习惯吗？此操作无法撤销。",
    createHeading: "创建",
    completedHabits: "已完成的习惯",
    hiddenHabits: "隐藏的习惯",
    editRoutine: "编辑日程",
    changeTiming: "更改时间设置",
    deleteRoutine: "删除日程",
    cutoffTimeNote: '注意：您的截止时间为 {time}。未设为"高优先级"的习惯将在此时间后不可用。',
    editCutoff: "编辑截止时间",
    unavailable: "不可用",
    inProgress: "进行中",
    startsAt: "{time} 开始",
    passed: "已过",
    completedWithCount: "已完成 {count} 个",
    unavailableWithCount: "{count} 个当前不可用",
    noHabitsYetAddPrompt: "这里还没有任何内容。\n添加习惯？",
    routineIsEmpty: "日程为空",
    allHabitsHidden: "所有习惯已隐藏",
    habitsCount_zero: "$t(common.empty)",
    habitsCount_one: "{count} 个习惯",
    habitsCount_other: "{count} 个习惯",
  },
  editRoutine: {
    editTiming: "编辑时间设置",
    morningTime: "早晨时间",
    wakeUp: "起床！",
    morningRoutineStartTime: "晨间日程开始时间",
    eveningTime: "晚间时间",
    finishWork: "结束工作",
    eveningRoutineStartTime: "晚间日程开始时间",
    techCurfew: "科技宵禁",
    timeToSleep: "就寝时间",
    timing: "时间设置",
    anytime: "随时",
    scheduled: "已计划",
    doHabitsWhenever: "随时执行这些习惯",
    doHabitsAtSpecificTime: "在特定时间或特定日期执行这些习惯",
    newRoutinePlaceholder: "新日程...",
    routineNamePlaceholder: "日程名称",
    customRoutineDefaultName: "自定义日程",
    createNewRoutine: "创建新日程",
    time: "时间",
    wakeUpFinishWorkSameError: "起床时间和结束工作时间不能相同",
    cutoffOutOfRangeError: "睡眠时间必须在结束工作时间之后、起床时间之前",
    startBeforeEndError: "开始时间必须早于结束时间",
  },
  simpleHome: {
    setupBlocking: "设置阻止",
    setupBlockingApp: "设置应用分心阻止（推荐）",
    setupBlockingUrl: "设置网站分心阻止（可选）",
    title: "试用 Focus Bear",
    focusSessionCheckboxTitle: "完成您的第一个专注时段",
    microBreakCheckboxTitle: "做一个微休息习惯",
    focusScreenTitle: "试用专注时段",
    focusSessionCheckboxDesc: "做一些深度工作",
    microBreakCheckboxDesc: "通过深呼吸减压",
    postGamePromptTitle: "做得好！",
    postGamePromptText: "想现在开始一个专注时段来完成那个任务吗？",
    focusNowCta: "是的！专注时间",
    focusGameTitle: "通过专注游戏热身",
    focusGameDesc: "玩一个快速游戏进入状态",
  },
  postpone: {
    doYouReallyWantTo: "您真的想暂停吗？",
    blockingPausedForDuration: "阻止已暂停 {duration}",
    blockingPausedIndefinitely: "阻止已暂停，直到您恢复",
    pauseBlocking: "暂停阻止",
    pauseDisabledStrictMode: "启用超级严格模式时无法使用暂停阻止功能",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "恢复阻止",
    choosePostponeTime: "您想暂停多长时间？",
    indefinite: "暂停直到我恢复阻止",
    youHavePausedTimesToday_zero: "这是您今天第一次暂停。",
    youHavePausedTimesToday_one: "您今天已经暂停过一次。",
    youHavePausedTimesToday_other: "您今天已经暂停了 {count} 次。",
    countdown: "我们将在 {countdown} 后让您暂停",
    areYouSureIndefinite:
      "您确定要无限期暂停吗？如果您真的想要可以这样做，但通常看似紧急的任务仍然可以等待15分钟，直到您完成习惯。",
    doHabits: "我会做我的习惯",
    longTermGoalsDesc: "提醒一下，这是您使用 Focus Bear 想要实现的目标：",
    lowQualityUsageDesc: "今天已在低质量应用上花费的时间",
    write: "留下反馈...",
  },
  passwordForSettings: {
    invalid_password: "密码无效",
    resetAfter24Hours: "已请求重置。您的密码将在24小时后被禁用。",
  },
  signIn: {
    logIn: "登录",
    enterEmailHint: "电子邮件地址",
    enterPasswordHint: "密码",
    invalidCredentials: "无效的用户名/密码",
    enterEmailError: "请输入电子邮件",
    enterValidEmailError: "请输入有效的电子邮件",
    enterPasswordError: "请输入密码",
    dontHaveAccount: "没有帐户？",
    forgotPassword: "忘记密码？",
    signup: "注册",
    googleSignIn: "使用 Google 继续",
    continueWithGoogle: "使用 Google 继续",
    startWithApple: "使用 Apple 开始",
    startWithEmail: "使用电子邮件开始",
    backToSignInMethod: "返回选择登录方式",
    alreadyHaveAccount: "我已经有 Focus Bear 帐户",
  },
  forgotPassword: {
    forgotPasswordSuccess: "密码重置电子邮件已发送到您的电子邮件地址",
    forgotPasswordErrorThirdParty: "看起来您是通过第三方服务注册的。请使用您的 Google 或 Apple 帐户继续。",
    forgotPasswordNotVerified: "您需要验证您的电子邮件地址才能重置密码。",
    forgotPasswordEmailNotFound: "找不到电子邮件",
    forgotPasswordTitle: "忘记密码",
    backToSignIn: "返回登录",
    resetPassword: "重置密码",
    weveEmailedYouALinkToResetYourPassword: "我们已向您发送了重置密码的链接。",
    forgotPasswordNotVerifiedBody:
      "You need to verify your email before you can reset your password. We can send you a new verification link now.",
    forgotPasswordNotVerifiedTitle: "Verify your email to reset your password",
    resetLinkSent: "If an account exists with this email, a password reset link has been sent.",
    verificationEmailSent: "A verification email has been sent. Please check your inbox.",
    verificationEmailFailed: "Failed to send the verification email. Please try again later.",
    cannotResetPasswordOAuthAccountTitle: "Sign in to continue",
    resetFailed: "Password Reset attempt has failed. Try again later.",
    waitBeforeRetry: "Please wait before requesting another email.",
  },
  signUp: {
    backToSignUpMethod: "返回选择注册方式",
    verifyEmail: "请检查您的收件箱",
    verifyEmailMessage: "我们刚刚向您发送了一封验证邮件。请点击链接验证您的帐户。",
    signUp: "注册",
    emailSignup: "使用电子邮件注册",
    continueWithNoAccount: "不使用帐户继续",
    tosAndPP: "我同意<bold>服务条款</bold>和<bold1>隐私政策</bold1>",
    alreadyHaveAccount: "已有帐户？",
    passwordMatchError: "密码和确认密码不匹配",
    acceptTerms: "请同意服务条款和隐私政策以继续",
    passwordHintError:
      "密码必须包含：\n        • 至少8个字符\n        • 数字 (0-9)\n        • 小写字母 (a-z)\n        • 大写字母 (A-Z)\n        • 特殊字符 (!@#$%^&*)",
    invalidSignup: "无效的注册",
    userExists: "用户已存在。",
    terms: "条款",
    privacy: "隐私",
    or: "或",
  },
  profile: {
    logout: "退出登录",
  },
  routineDetail: {
    activity: "活动",
    not_playable_video: "无法播放视频。",
    done: "我完成了",
    video: "视频",
    images: "图片",
    checklist: "清单",
    note: "笔记",
  },
  quickBreak: {
    quickBreak: "快速休息",
    quickStretch: "伸展运动",
    stretch: "伸展",
    drinkWater: "喝水",
    water: "水",
    deepBreathing: "深呼吸",
    breathe: "呼吸",
    saveQuickBreakSuccessfully: "您的更改已成功保存",
    editQuickBreaks: "编辑快速休息",
    quickBreakName: "快速休息名称",
    currentSelection: "当前选择",
  },
  complete: {
    backToHome: "返回主页",
    logQuantity: "记录活动数量",
    finishedCheck: "完成！✅",
    habitNotCompleted: "习惯已跳过！❌ 明天可以做！",
    finishedAndEarnedMorning: "完成！✅ 您已获得屏幕时间",
    finishedAndEarnedEvening: "完成！✅ 您已获得美好的睡眠。明天早上见！",
    why_skip: "您为什么想跳过？",
    already_did: "我已经做了",
    cannot_today: "今天不能做",
    quantity_input_error: "数字需要在 {min} 和 {max} 之间。",
    freemiumLimitReached: "抱歉，免费计划只能完成3个习惯。",
  },
  reason: {
    canShare: "您能分享一下为什么要无限期暂停吗？",
    shareFeedback: "分享反馈",
    everythingIsOk: "哦哦 - 希望一切都好",
    appBrokenDesc: "非常抱歉。您能告诉我们发生了什么吗？",
    somethingElseDesc: "好的。您有什么反馈想与我们分享吗？",
    gotEmergency: "我有紧急情况",
    appBroken: "应用已损坏",
    somethingElse: "其他",
  },
  notification: {
    backgroundService: "Focus Bear 后台服务帮助您专注",
    scheduleNotificationTitleForResumeRoutine: "恢复您的例程",
    scheduleNotificationDescriptionForResumeRoutine: "是时候专注于您的例程了",
    floatingModuleActivityCompleteNotificationtitle: "活动已完成",
    floatingModuleRoutineCompleteNotificationtitle: "例程已完成",
    morningRoutineCompletedNotificationDescription: "早晨例程已完成。美好的一天开始了！",
    eveningRoutineCompletedNotificationDescription: "晚上例程已完成。睡个好觉！",
    customRoutineCompletedNotificationDescription: "{{routineName}}已完成。干得好！",
  },
  focusMode: {
    blockingPaused: "阻止已暂停",
    blockingPermissionNeeded: "阻止未激活：您需要授予权限",
    noBlockingAppsSelected: "阻止未激活：您需要选择要阻止的应用",
    distractionBlockingNotActiveTitle: "分心阻止未激活",
    distractionBlockingNotActiveText: "您还没有选择要阻止的应用",
    continueWithoutBlocking: "不阻止继续",
    fixBlocking: "修复阻止",
    confirmSuperStrictMode: "您确定要启用超级严格模式吗？在会话结束前您将无法退出。",
    focusIntentionTooltip: "为这个专注时段设定一个目标。明确您要实现的目标有助于避免分心。",
    focusTitle: "开始专注时段",
    superStrictToolTip: "决心完成这个专注时段？启用超级严格模式，在计时器结束前您将无法关闭专注或暂停应用阻止。",
    superStrictMode: "超级严格模式",
    brainDump: "大脑倾倒",
    brainDumpToolTip: "在这里记下您的想法",
    postFocusCongrats_0: "干得好！您太棒了！",
    postFocusCongrats_1: "嘿，完成得很好！接下来做什么？",
    postFocusCongrats_2: "您做到了！现在可以休息一下。",
    postFocusCongrats_3: "做得好！您真的在完成任务！",
    postFocusCongrats_4: "太棒了！接下来要做什么？",
    postFocusCongrats_5: "您完成了！是时候处理下一个了？",
    postFocusCongrats_6: "专注得很好！去喝点东西或吃点零食吧！",
    postFocusCongrats_7: "很好！您正在取得重大进展！",
    postFocusCongrats_8: "做得好！是时候伸展一下腿了？",
    postFocusCongrats_9: "您做得很好！让我们保持这个势头！",
    startFocusSession: "开始专注时段",
    noIntentionWasFound: "未输入意图",
    distractionAlertTitle: "专注模式",
    userIntention: "专注目标",
    noDistractingThoughtsWasFound: "未输入分心想法",
    userIntentionTextInputPlaceholder: "您想做什么？",
    startFocusing: "开始专注",
    hoursWithValue: "{value}小时",
    minutesWithValue: "{value}分钟",
    secondsWithValue: "{value}秒",
    duration: {
      hours: "{hours} 小时",
      minutes: "{minutes} 分钟",
      seconds: "{seconds} 秒",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "你可以的！\n深度工作时间",
    endSession: "结束会话",
    completeFocus: "完成专注",
    userDumpThoughTextInputDescription: "在这里写下任何分心的想法",
    exitFocusMode: "提前结束专注时段",
    exitFocusModeDescription: "您能分享一下为什么要结束这个时段吗？",
    reason: "原因",
    selectReason: "选择原因",
    congratulations: "恭喜！",
    focusDoneTitle: "您做到了！",
    focusDoneDescription: "您保持专注",
    focusDoneDescription1: "您的意图是什么？",
    focusDoneDescription4: "您有什么分心的想法？",
    focusDoneDescription2: "在这段时间里您取得了什么成就？",
    focusDonePlaceholderDescription2: "输入您在我们帮助下取得的成就",
    focusDoneDescription3: "您有任何分心吗？",
    focusDonePlaceholderDescription3: "输入您遇到的任何分心",
    endEarlyReasonDescription1: "我有紧急情况",
    endEarlyReasonDescription2: "专注模式无法正常工作",
    endEarlyReasonDescription3: "我已经实现了我想要的",
    endEarlyReasonDescription4: "我需要休息",
    runningFocusModeDesc: "专注时段正在运行",
    extendFocusDuration: "延长专注时长",
    shortenFocusDuration: "缩短专注时长",
    selectExtendFocusDuration: "您还想专注多长时间？",
    selectShortenFocusDuration: "您想缩短多少时间？",
    extendFocus: "延长",
    shortenFocus: "缩短",
    adjustFocusDuration: "调整专注时长",
    chooseAdjustmentOption: "您想延长还是缩短您的专注时段？",
    editFocusDuration: "您想什么时候结束专注？",
    focusMusic: "专注音乐",
    focusMusicError: "抱歉，无法播放专注音乐",
    focusNotes: "专注笔记",
  },
  toDos: {
    toDos: "待办事项",
    todoList: "待办事项列表",
    notes: "笔记",
    drafts: "AI 生成",
    notStarted: "待办",
    inProgress: "进行中",
    completed: "已完成",
    current: "当前",
    noMoreTasks: "没有更多任务",
    noTasksToShow: "没有任务显示\n在下方添加一些以开始！",
    searchTasks: "搜索任务",
    noTasksFound: "未找到任务",
    addATask: "添加任务",
    taskAdded: "任务已添加",
    failedToAddTask: "添加任务失败",
    scanPaperWithOCR: "使用 OCR 扫描纸张",
    quickActions: {
      audio: "音频",
      uploadAudio: "上传音频",
      recordAudio: "录制音频",
      upgradeRequired: "需要升级",
      upgradeMessage: "音频和OCR功能在Focus Bear Pro中可用。升级以解锁这些强大的生产力工具。",
      ocrUpgradeMessage: "OCR扫描在Focus Bear Pro中可用。升级以从照片和文档中提取任务。",
    },
    ocr: {
      modalTitle: "使用 OCR 扫描纸张",
      reviewModalTitle: "审核提取的待办事项",
      title: "扫描您的待办事项列表",
      description: "此功能可以从手写或打印的待办事项列表照片中提取任务。您可以从照片库中选择图片或拍摄新照片。",
      reviewTitle: "审核提取的待办事项",
      reviewDescription: "选择您想添加到列表中的待办事项。您可以稍后编辑它们。",
      selectSource: "选择照片来源",
      selectSourceDesc: "选择一个选项来选择图片",
      takePhoto: "相机",
      chooseFromGallery: "照片库",
      capturePhoto: "继续",
      processing: "处理图片...",
      uploading: "上传图片",
      error: "OCR错误",
      processingError: "处理图片失败。请重试。",
      noTodosSelected: "未选择待办事项",
      selectAtLeastOne: "请至少选择一个待办事项添加。",
      createTodos: "创建选定的待办事项",
      completed: "OCR处理完成",
      completedDesc: "您的待办事项已成功提取！",
    },
    audio: {
      processing: "处理音频中...",
      completed: "音频处理完成",
      completedDesc: "您的待办事项已成功提取！",
      addByAudio: "通过音频添加",
      record: "录制",
      upload: "上传",
      recorded: "录制完成",
      sendOrDiscard: "点击发送或关闭丢弃",
    },
    due: "截止",
    dueDate: "截止日期",
    exactDate: "选择日期",
    TOP: "TOP - 任务优先级分数",
    TOPPrioritization: "TOP 优先级",
    timeline: "时间线（截止日期）",
    project: "项目",
    projects: "项目",
    scoreCalculation: "分数",
    addProjects: "添加项目",
    noExistingProjects: "没有现有项目",
    createNewProject: "创建新项目",
    addATitle: "添加标题",
    addDescription: "添加描述...",
    addASubtask: "添加子任务",
    reschedule: "重新安排",
    rescheduleTitle: "重新安排任务",
    taskMovedToast: '任务已移至"{status}"',
    sortBy: "排序方式",
    filterBy: "筛选",
    filterTasksBy: "按以下条件筛选您的任务",
    listOptions: "列表选项",
    lowToHigh: "从低到高 TOP 分数",
    highToLow: "从高到低 TOP 分数",
    groupBy: "分组方式",
    groupedTogether: '将"待办"和"进行中"的任务显示在同一组中',
    filterByPerspiration: "按出汗程度筛选",
    spoonsDesc: "根据您的能量水平选择任务（勺子理论）。更多勺子 = 更多能量。",
    learnAboutSpoonTheory: "了解勺子理论",
    lowSpoons: "低勺子",
    fullSpoons: "满勺子",
    perspirationLevel: "出汗程度",
    filterByProject: "按项目过滤",
    noFilter: "无过滤",
    filterByDueDate: "按截止日期筛选",
    toDosDueDate: "截止日期",
    overdue: "已逾期",
    thisWeek: "本周",
    nextWeek: "下周",
    deleteTask: "删除任务",
    deleteTaskDesc: "您确定要删除此任务吗？",
    deleteSubtask: "删除子任务",
    deleteSubtaskDesc: "您确定要删除此子任务吗？",
    dueIn: {
      aFewDays: "两天后",
      nextWeek: "一周后",
      twoWeeks: "两周后",
      aMonth: "一个月后",
      aYear: "一年后",
      aYearDescription: "（哈，我永远不会真的做这个）",
    },
    outcome: {
      outcome: "结果",
      whoCares: "谁在乎",
      kindOfImportant: "有点重要",
      bigDeal: "大事",
      huge: "巨大",
      mindBlowing: "令人震惊",
    },
    perspiration: {
      perspiration: "出汗",
      fiveMinuteJob: "5分钟工作",
      fifteenMinutesWork: "15分钟工作",
      halfAnHour: "半小时",
      anHour: "一小时",
      halfADay: "半天",
      aDay: "一天",
      aWeek: "一周",
    },
    searchOrCreateProject: "搜索或创建项目",
    noMatchingProjects: '没有匹配的项目。按回车键创建 "{search}"',
  },
  overview: {
    morningRoutine: "早晨例程",
    eveningRoutine: "晚上例程",
    noTasksCta: "还没有任务。<bold>添加任务</bold>开始。",
    noHabitsCta: "还没有习惯。<bold>添加习惯</bold>开始。",
    topTasksToday: "首要任务",
    focusModeTitle: "专注模式",
    newFocusSession: "新会话",
    focusActive: "活动会话",
    focusInactive: "无活动会话",
    routineCompletedShort: "✓ 已完成",
    routineCompletedMessage: "所有习惯已完成！做得好！🎉",
    routineProgress: "{completed}/{total}",
    deadlinePrefix: "截止日期：{date}",
  },
  networkError: {
    ifTheProblemPersists: "如果问题仍然存在，请直接联系支持\nsupport@focusbear.io",
    noNetworkAlertTitle: "互联网已断开",
    retrying: "再试一次",
    connectionError: "不稳定的互联网连接",
    connectionErrorMessage: "请检查您的连接",
    connectionErrorLongMessage:
      "我们连接服务器时遇到问题。$t(networkError.connectionErrorMessage)。$t(networkError.ifTheProblemPersists)",
    apiError: "出了点问题",
    apiErrorMessage: "请稍后重试",
    apiErrorLongMessage:
      "处理您的请求时出现问题。$t(networkError.apiErrorMessage)。$t(networkError.ifTheProblemPersists)",
    internalError: "内部错误",
    internalErrorMessage: "出了点问题 :(",
    internalErrorLongMessage: "抱歉，出了很大的问题。$t(networkError.ifTheProblemPersists)",
  },
  manageAllowedApps: {
    searchPlaceholder: "搜索已安装的应用",
  },
  addNoteModule: {
    addNote: "添加笔记",
    placeholder: "在这里添加笔记...",
    saveNote: "保存笔记",
    automaticallySave: "您的笔记将自动保存",
  },
  permissionWarning: {
    usageAccessTitle: "我们需要使用访问权限来帮助阻止分心",
    deviceUsagedescription: '为了在您专注/执行习惯时阻止分心应用，我们需要"使用访问"权限，以便查看您正在使用的应用',
    overlayTitle: "我们需要覆盖权限来帮助阻止分心",
    overlayDescription:
      '为了在您专注/执行习惯时阻止分心应用，我们需要"悬浮窗"权限，以便查看您正在使用的应用并显示不允许应用的分心提醒',
    privacyNoteTitle: "隐私说明",
    privacyNoteDesc: "我们不会记录您使用的应用或网站。我们只是用它来实时阻止。",
    grantAccess: "允许",
  },
  onboarding: {
    nextStep: {
      upNext: "接下来：{step}",
      usagePermission: "使用权限",
      overlayPermission: "悬浮窗权限",
      focusSession: "专注时段",
      microBreak: "微休息",
      allDone: "全部完成",
      screenTimePermission: "屏幕使用时间权限",
    },
    wantToPersonalise: "想要个性化吗？",
    wantToPersonaliseDescription: "设置您自己的习惯，而不是使用默认值。",
    personalise: "个性化（5 分钟）",
    onboarding: "入门",
    letsDoIt: "开始吧",
    replay: "重播",
    instructionVideo: "教学视频",
    welcomeAboard: "欢迎加入！",
    lookingForwardToHelp: "是时候激活健康习惯和深度工作了。",
    getStarted: "开始",
    allDone: "全部完成！",
    habitPackSelectionNotice:
      "接下来让我们为您的早晨和晚上日程选择一些习惯。\n\n\n<bold>不要紧张</bold> 您以后随时可以调整它们。",
    installDesktopApp: "安装桌面应用",
    installDesktopAppDesc:
      "Focus Bear 也可在 Mac 和 Windows 上使用。如果您有电脑，请从 <bold>focusbear.io</bold> 下载应用以同步您的专注时段和习惯。",
    cutoffTimeWarning: "离开科技时间应该在完成工作时间之后 ({time})。",
    howFocusBearWork: "Focus Bear 的工作原理",
    habitAndRoutine: "习惯和例程",
    habitAndRoutineDescription: "<bold>实现您的目标</bold>，通过激活大脑和身体的习惯",
    distractionBlocking: "阻止分心",
    distractionBlockingDescription: "Focus Bear 可以阻止<bold>应用</bold>和<bold>网站</bold>来帮助您完成任务",
    todoList: "待办事项列表",
    todoListDescription: "使用 Focus Bear 待办事项列表<bold>计划</bold>、<bold>优先排序</bold>和<bold>保持进度</bold>",
    andMuchMore: "还有更多",
    andMuchMorePoints: [
      "也可在电脑上使用",
      "番茄工作法",
      "带有清单和视频的高级习惯",
      "早晚日程",
      "休息提醒",
      "有趣的熊表情",
    ],
    andMuchMoreDescription: "<bold>还有更多...</bold>",
    end: "结束",
    habitAI: "使用AI\n整理您的任务",
    habitAIDescription: "Focus Bear 可以使用人工智能帮助您<bold>整理任务</bold>",
    learnAboutFeatures: "了解功能",
    setupHabitsTitle: "设置习惯以更好地专注",
    setupHabitsCta: "设置习惯",
    habitsPirateCopy: "好习惯能让你一整天都保持专注。",
    habitImportPirateCopy: "我会用海洋魔法把你的习惯带上船。",
    habits: {
      sleep: "睡眠",
      meditate: "冥想",
      exercise: "锻炼",
    },
    habitList: {
      nayLabel: "不用了——给我一些习惯建议",
      ayeLabel: "好的——我已经有一些习惯了",
    },
  },
  goals: {
    habitImport: {
      title: "导入习惯",
      description: "通过图片或录音导入您的习惯",
      importFromImage: "从图片导入",
      recordVoice: "录制语音",
      stopRecording: "停止录制",
      selectSource: "选择来源",
      selectImageSource: "选择如何导入您的习惯",
      takePhoto: "拍照",
      chooseFromGallery: "从相册选择",
      completed: "习惯已导入！",
      completedDesc: "您的习惯已成功导入",
      error: "导入错误",
      processingError: "处理您的导入失败。请重试。",
      recordingError: "录制音频失败。请重试。",
      processing: "处理您的导入...",
      cancelRecording: "取消录音",
    },
    addHabitList: {
      title: "添加您的习惯列表",
      description: "上传习惯列表或告诉我们您的目标，我们的AI将在Focus Bear应用中添加它们。",
      uploadScreenshot: "上传照片",
      recordVoiceNote: "录制语音笔记",
      typeThemIn: "输入它们",
      or: "或",
      haveHabitListQuestion: "您有自己的习惯列表要导入吗？",
      importHabits: "导入习惯",
      confirmScreenshotUpload: "确认图片",
      confirmScreenshotUploadDesc: "这是您要上传的图片吗？",
    },
    boostProductivity: "🚀 提高生产力",
    boostProductivityDescription: "（工作、学习、任务）",
    improveMentalHealth: "🧘 改善心理健康",
    improveMentalHealthDescription: "（压力、睡眠）",
    improvePhysicalHealth: "🏋️‍♂️ 关注健康和健身",
    improvePhysicalHealthDescription: "（运动、营养）",
    manageTask: "🏡 管理家务",
    manageTaskDescription: "（清洁、家务）",
    otherSpecify: "✏️ 其他",
    otherSpecifyDescription: "（请说明：__）",
    strengthenRelationShip: "❤️ 加强关系",
    strengthenRelationShipDescription: "（家人、朋友）",
    achievement_placeholder: "告诉我们您的目标",
    enableFeatures: "您想启用哪些功能？",
    doOurBest: "我们在这里帮助您实现目标。您想开启哪些 Focus Bear 功能？",
    achievementWithFocusBearDesc: "您的主要目标是什么？",
    achievementWithFocusBearDescTooltip: "我们会建议帮助您实现目标的习惯",
    help_me_develop: "建立健康习惯",
    help_me_stay: "工作时保持专注",
    help_me_develop_tooltip: "Focus Bear可以在您的早晨和晚上日程中引导您养成健康习惯（冥想、锻炼、写日记等）。",
    help_me_stay_focused_tooltip: "Focus Bear会在您工作时阻止分心，让您能够完成深度工作。",
    blockComputerTitle: "在电脑上阻止分心？",
    blockComputerQuestion: "您也想在电脑上阻止分心吗？",
    organize_tasks_using_ai: "使用 AI 组织您的任务",
    organize_tasks_using_ai_tooltip: "Focus Bear 可以使用 AI 组织您的任务",
    what_are_you_hoping_focus_bear_can_do: "您希望 Focus Bear 能做什么？",
    what_are_you_hoping_focus_bear_can_do_placeholder: "告诉我们您希望 Focus Bear 能做什么",
    explore_the_app_first: "先探索应用",
    setup_habits: "设置习惯",
    setup_habits_question: "您想现在设置习惯（大约需要3分钟）还是先探索应用？",
    featureRequestReceived: "感谢您的反馈！您的想法帮助我们让Focus Bear变得更好。",
  },
  goalsSteps: {
    goals: "目标",
    routine: "例程",
    timing: "时间",
  },
  habit: {
    habitPack: "选择您的习惯",
    autostart: "自动启动",
    habitAutoStart: "将在 {countdown} 后开始",
    habitSkipForToday: "今日已跳过习惯",
  },
  setupTime: {
    fineIfLaterOrSooner: "如果您比这个时间稍晚或稍早起床也没关系 - 只需输入一个大概时间",
    morningRitualStart: "您的早晨仪式将从那时开始",
    setStartupTime: "选择您的开始时间",
    chooseTheAbsoluteEarliest: "您几点起床？",
    setShutdownTime: "您什么时候完成工作/学习？",
    setSleepTime: "您想几点睡觉？",
    focusBearWillTakeOver: "Focus Bear 将暂停阻止\n让您可以放松！",
    subDescriptionFocusBearWillTakeOver: "晚间日程从 {sleep_time} 开始\n（包括30分钟缓冲时间）",
    focusBearWillTakeOverToolTip: "在下一个屏幕上，您将选择何时睡觉。Focus Bear 将在您睡觉前再次阻止分心，让您睡得好。",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}: 自由时间",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}: 晚间仪式然后睡觉",
    subDescriptionTooltipText: "{sleep_time} - {startup_time}: 手机宵禁（睡眠时间）",
    distractionBlockDesc: "分心被阻止 - 准备睡觉",
    techCurfewQuestion: "您想在晚上设置科技宵禁以便睡得更好吗？",
    techCurfewTooltip: "Focus Bear可以在晚上阻止手机上的干扰应用，让您睡得更好",
    bedtimeForScreens: "屏幕的睡眠时间？",
    bedtimeForScreensSubtitle: "我们让您的手机早点休息，这样您可以休息吗？",
    noThanks: "不用了，谢谢",
    yesPhoneWrecksSleep: "是的 - 我的手机破坏了我的睡眠！",
    whatTimeGetOffTech: "您晚上想几点停止使用科技产品？",
  },
  blockList: {
    title: "在习惯/专注时段期间让您的手机安全",
    subTitleAndroidBlockList: "选择在做习惯或专注时要阻止的分心应用",
    buttonAndroidBlockList: "选择分心",
    subTitleIos: "选择在做习惯或专注时要阻止的分心应用",
    buttonIos: "选择分心",
  },
  editFriction: {
    frictionTooltipDescription:
      '您当然是一个非常自律的人，但偶尔您可能会一时冲动想跳过习惯或停止阻止分心。您可以设置额外的"阻力"来帮助减缓这些冲动的想法。如果您启用高阻力模式，它会在您停止阻止分心之前要求您等待几秒钟。',
    frictionForSkippingHabits: "跳过习惯的阻力",
    reallyEasy: "非常简单 - 我希望能够快速跳过习惯/休息",
    makeItHardToSkip: "让跳过变得困难 - 否则我大部分时间都会跳过习惯和休息",
    appBlocking: "阻止分心",
    blockDuringDaytime: "在工作日阻止分心应用",
    reallyEasyDescription: "您将能够立即停止阻止分心",
    makeItHardToSkipDescription:
      "为了避免冲动地关闭阻止，Focus Bear可以显示一个短暂的倒计时器，鼓励您重新考虑是否应该访问分心应用。",
  },
  strictness: {
    setPassword: "设置密码",
    setPasswordDescription: "如果您难以坚持习惯，让室友/伴侣设置密码。没有密码您将无法跳过习惯。",
    enterConfirmPasswordHint: "确认密码",
    askForPassword: "要求密码",
    whenRequirePasswordDescription: "您想什么时候需要密码",
    changingSettings: "更改设置",
    postponingMorningRoutine: "推迟/跳过早晨例程",
    postponingEveningRoutine: "推迟/跳过晚上例程",
    postponingAfterCuttOffTime: "在截止时间后推迟/跳过晚间日程",
    usingPhoneLateNight: "深夜使用手机",
    relaxFocusMode: "允许使用放松专注模式",
    suggestion: "建议",
  },
  subscription: {
    upgrade: "升级",
    restorePurchases: "恢复购买",
    restorePurchasesError: "收据丢失",
    restorePurchasesError2: "出了点问题。请稍后重试。",
    personalizedHabit: "个性化习惯例程",
    productivityBoosting: "提高生产力的休息",
    customizedFocus: "可自定义的专注模式",
    automaticGoals: "自动目标跟踪",
    cancel: "取消自动续订",
    subscription: "订阅",
    trialActive: "您的试用还剩 {day} 天。不用担心，试用结束时不会收费，也不需要预先提供信用卡",
    trialActiveShort: "试用：剩余 {day} 天",
    getSubscriptionPlan: "获取我们的订阅计划以使用应用并解锁所有功能",
    subscriptionPlanPrice: "仅需 <bold>{amount}</bold>/月 继续使用",
    benefit: "月度计划包括",
    doesSubscriptionAutoRenew: "我的订阅会自动续订吗？",
    subscriptionAutoRenew:
      "此月度计划会自动续订，除非在当前周期结束前至少24小时关闭自动续订。您的账户将在当前周期结束前24小时内按订阅价格（{amount}）收取续订费用。您可以随时通过商店中的账户设置管理或取消订阅。",
    thankYouForSubscribing:
      "感谢您的订阅，您现在可以使用 Focus Bear 的所有功能\n\n您的订阅将在 <bold>{day}</bold> 天后到期",
    thankYouForSubscribingGuestMode:
      "感谢您的订阅！要继续使用 Focus Bear 订阅的所有功能，请在此屏幕上登录并恢复您的订阅。",
    thanksForSubscribingShort: "感谢您的支持 🎉",
  },
  editHabit: {
    okay: "好的",
    error: "错误",
    unableToSaveSettings:
      "出了点问题。非常抱歉。我们的工程团队已收到通知，我们会尽快修复。如果您在24小时内没有收到我们的消息，请发送电子邮件至 support@focusbear.io，我们会为您解决问题。",
    goingBack: '您即将返回设置菜单。如果您做了任何更改，请点击"保存习惯"按钮。',
    continue: "继续",
    cancel: "取消",
    warning: "警告",
    restartingIn: "Focus Bear 将在 {seconds} 秒后重启...",
    settingsSavedSuccessfully: "习惯已保存",
  },
  shareLogs: {
    pleaseWriteFeedback: "请写反馈消息",
    enterFeedBack: "输入您的反馈",
    logsShared: "谢谢！您的反馈报告已与支持团队共享。",
    submitAnother: "提交另一个",
    errorUploading: "上传日志时出错。请确保您有稳定的网络连接并重试。$t(networkError.ifTheProblemPersists)",
    errorZipCreation: "处理文件时出现问题。请重试。$t(networkError.ifTheProblemPersists)",
  },
  impact_reporting: {
    title: "分析您的睡眠和情绪",
    description:
      "您想跟踪您的睡眠和情绪，看看Focus Bear是否对您的生活产生积极影响吗？这也会通过向我们提供（匿名）应用影响数据来帮助我们。",
    subtitle: "我们将收集的数据",
    bulletPoints: "● 睡眠时间\n● 您的情绪和能量水平\n● 一天结束时您感觉有多高效",
    okSure: "好的",
    noThanks: "不用了，谢谢",
  },
  privacyModal: {
    heading: "隐私和安全",
    notShareData: "我们非常重视您的隐私和安全。我们永远不会分享您的数据。",
    doNotLog: "• 我们不会记录您访问的网站或应用。",
    chooseToBlock:
      "• 但是，如果您想阻止分心应用，我们需要在数据库中存储这些应用的名称，以便您的设置可以在所有设备上同步。",
    dataEncrypted: "• 您的数据已加密，我们不会让任何其他人看到它。",
    moreDetails: "有关更多详情，请参阅我们的<bold>隐私政策</bold>或随时发送电子邮件至support@focusbear.io",
    accept: "接受",
  },
  pushNotiPermission: {
    title: "允许通知",
    description: "我们可以提醒您保持习惯进度并准时参加会议。",
  },
  distractionBlockingReason: {
    notLoggedIn: "阻止已禁用：您未登录",
    postponeActivated: "阻止已禁用：推迟已激活",
    focusModeActivated: "阻止已启用：专注模式已激活",
    firstDay: "阻止已禁用：第一天 - 例程尚未激活",
    otherReason: "阻止已启用：是时候做您的例程了",
    daytimeBlockingEnabled: "阻止已启用：早晨例程已完成但白天阻止已启用",
    blockedBySchedule: "已启用屏蔽：屏蔽计划正在生效",
    defaultCase: "阻止已禁用：分心阻止已禁用",
    withinCutoffTimeAndShutdownTime: "阻止已禁用：您有自由时间直到 {cutoff_time}",
    permissionNotGranted: "阻止已禁用：权限未授予（点击此处修复）",
    afterCutoffTime: "阻止已启用：是时候在睡觉前放松了",
    afterCutoffTimeAndEveningRoutineFinished: "阻止已启用：是时候睡觉了",
    detailedCutOffSleepTimeBlockingReason:
      "从 {cutoff_time} 开始阻止分心，让您可以睡觉。您的早晨日程设置为 {startup_time} 开始。完成早晨日程后，阻止停止。",
  },
  blocking: {
    blockingType: "阻止类型",
    allowList: "允许列表",
    blockList: "阻止列表",
    allowListDescription: "选择在做习惯或专注时允许使用的应用。其他所有应用将被阻止。",
    blockListDescription: "选择在做习惯或专注时应该阻止的分心应用。其他所有应用将被允许。",
    appBlockList: "应用阻止列表",
    appAllowList: "应用允许列表",
    blockAtLeastOne: "请至少选择一个应用以防止自己分心",
    socialFilterTitle: "社交",
    newsFilterTitle: "新闻",
    gamesFilterTitle: "游戏",
    miscFilterTitle: "其他",
    recommendedSectionListTitle: "推荐阻止的应用",
    otherSectionListTitle: "其他应用",
    freeAppLimitTitle: "抱歉，免费版最多阻止 5 个应用",
    freeAppLimitDesc:
      "在免费版本中，您只能选择5个应用来阻止。购买 Focus Bear Pro 有助于支持我们的开发，让我们可以构建提高您生产力的新功能 🙂",
    Success: "设置已保存",
    saveSuccess: "应用偏好设置保存成功",
  },
  permissionExplanation: {
    distractionGetBlockedWhen: "分心被阻止的时间：",
    title: "设置分心阻止权限",
    description: "Focus Bear 可以在您工作、睡觉和做习惯时阻止分心",
    workTask: "• 您在工作/学习时完成任务 ⚒️",
    routineTask: "• 您在做早晨和晚上日程时完成习惯 🧘",
    sleepTask: "• 您在睡觉时真正入睡 😴",
    toggleOption: "默认情况下，您可以随时关闭分心阻止。",
    friendOption: "（但您也可以选择让朋友设置密码使其更难）",
    necessaryPermission: "使用权限：检测您是否打开分心应用\n\n悬浮窗权限：这是执行分心阻止的权限",
  },
  blockingPermissionIntro: {
    introTitle: "来设置一下分心阻止，这样我可以更好地帮你保持专注。",
    introPrimary: "开始设置",
    introBubble: "大概就是\n这样的效果。",
    howItWorksTitle: "在你安排好的专注时间里，我会温和地拦截让你分心的应用。",
    howItWorksBody: "一切由你掌控——可以随时暂停或调整。",
    howItWorksPrimary: "听起来不错",
    howItWorksBubble: "接下来你只需要点击“继续”。",
    screenTimeCongratsTitle: "很好，你已经完成了这一步的设置。",
    whatYouNeedTitle: "为此，我需要在你的手机上获得几个权限。",
    whatYouNeedPrimary: "继续",
    whatYouNeedBubble: "例如，在你睡觉的时候屏蔽让你分心的应用。",
    scheduleCreatedTitle: "完美。现在你已经有了一套固定的日程。",
    scheduleCreatedPrimary: "继续",
    scheduleCreatedBubble: "这些设置可以随时在应用里修改。",
    finishTitle: "一切都设置好了，我们可以一起更稳定地保持在正确轨道上。",
    finishPrimary: "完成",
    androidIntroTitle: "来设置一下分心阻止，这样我可以更好地帮你保持专注。",
    androidUsageTitle: "首先，我需要知道你正在使用哪些应用。你需要启用“使用情况访问”权限。",
    androidUsagePrimary: "打开设置",
    androidUsageBubble: "试着在这里找到这个开关。",
    androidOverlayTitle: "我会使用“在其他应用上层显示”的权限，这样就能像这样弹出一个提示窗口。",
    androidOverlayPrimary: "开始设置",
    androidOverlayBubble: "我会向系统请求显示提示的权限。",
    androidPermissionVisualTitle: "权限界面大致长这样。",
    androidPermissionVisualPrimary: "启用访问",
    androidPermissionVisualBubble: "一起\n去找找看吧。",
    androidProceedPrimary: "继续",
    androidScheduleSetupTitle: "很好。现在设置一个自动的阻止日程，这样我可以在固定时间轻轻提醒你。",
    androidScheduleSetupPrimary: "设置阻止日程",
    androidScheduleSetupBubble: "例如，在你睡觉的时候屏蔽让你分心的应用。",
    holdOnTitle: "Hold on a minute!",
    captainBearMessage: "Arr... if you want to focus better, you've got to get your habits shipshape first.",
  },
  grantPermission: {
    title: "我们需要权限来阻止应用",
    description: "别担心，您可以随时暂停分心阻止",
    needHelp: "需要帮助？",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "保持阻止启用",
    description: "通过移除电池优化，允许 Focus Bear 在后台继续阻止应用。",
    warning: "这会稍微增加电池消耗（但不会很多）。",
    keepFocusBearPoweredUp: "保持 Focus Bear 运行",
  },
  launcher: {
    title: "应用",
    morning: "🔆 早晨",
    evening: "🌙 晚上",
    play: "🥳 玩耍",
    work: "🔨 工作",
    setAppLabel: "为 {appName} 选择类别",
    search: "搜索应用",
    noAppsFound: "未找到应用",
    setAsDefaultLauncher: "默认启动器",
    restricted: "受限",
    restrictedMessage: "{appName} 正在被限制，请专注于您的日程",
    stopBlocking: "暂停阻止",
    openAppMenuToolTip: "点击这里打开应用菜单",
  },
  DND: {
    duringFocusSessions: "在专注时段期间",
    duringHabits: "在习惯和睡眠期间",
  },
  bearsona: {
    explanation: "您想要什么类型的熊来激励您？Focus Bear 会相应地改变语气",
    title: "熊角色",
    choose: "选择熊角色",
    useCustomLanguage: "使用 {customLanguage}",
    useCustomLanguageConfirmation: "使用 {customLanguage} 作为您的语言？",
    useCustomLanguageConfirmationDesc: "警告：这很有趣但可能会有点令人困惑",
    confirmUseCustomLanguage: "用英语和我说话",
    cancelUseCustomLanguage: "我改变主意了",
    name: {
      default: "原版熊",
      pirate: "船长熊",
      focus: "专注熊",
      jester: "小丑熊",
      sassy: "俏皮熊",
      cheerleader: "啦啦队熊",
    },
    description: {
      default: "您友好的熊助手",
      pirate: "呀！熊船长为您服务",
      focus: "专注是我的超能力",
      jester: "小丑熊准备好玩耍了",
      sassy: "俏皮熊来大显身手了",
      cheerleader: "啦啦队熊为您加油！",
    },
  },
  blockUrl: {
    addSomeSuggestedUrls: "我们在这里添加了一些大多数人认为会分心的建议网站。如果需要，请删除它们",
    unblockableUrlTitle: "无法阻止网址",
    unblockableUrlMessage: "此网址无法阻止。请输入其他网址来阻止。",
    freemiumLimit: "免费版只能阻止 3 个网址。",
    freemiumLimitDescription: "升级到 Pro 版本以阻止无限网址。",
    title: "阻止网站",
    description: "您在哪些网站上浪费时间？",
    inputPlaceholder: "输入要阻止的网址...",
    urlExistsTitle: "网址已存在",
    urlExistsMessage: "请输入其他网址来阻止。",
    invalidUrlTitle: "无效网址",
    invalidUrlMessage: "请输入有效的网址来阻止。",
    saveSuccess: "阻止的网址保存成功。",
    saveError: "保存阻止的网址失败。请重试。",
  },
  accessibility: {
    title: "无障碍权限",
    howToEnableAccessibility: "如何启用无障碍权限",
    permissionRequired: "需要无障碍权限",
    permissionDescription:
      "网站可能和应用一样令人分心。如果您启用无障碍权限，Focus Bear 也可以阻止网站。您的手机会显示警告 - 这是正常的！",
    whatWeDo: "这是我们做的：",
    checkSites: "检查您的阻止列表",
    checkSitesDescription: "我们检查网站是否在您设置的阻止列表中。",
    zeroDataTracked: "就是这样。零跟踪，零数据存储。",
    enableAccessibility: "Enable accessibility",
  },
  passwordRules: {
    passwordRequirements: "密码必须包含至少一个数字、一个大写字母和一个特殊字符",
    minLength: "最少 8 个字符",
    includeNumbers: "包含数字",
    includeLowerCase: "包含小写字母",
    includeUpperCase: "包含大写字母",
    includeSpecialChars: "包含特殊字符",
  },
  permissions: {
    privacyFirst: "我们非常重视您的隐私",
    notTracked: "Focus Bear <bold>不会</bold>跟踪：",
    anythingType: "您输入的任何内容",
    anythingTypeDescription: "密码、消息、电子邮件",
    browserHistory: "您的浏览历史",
    browserHistoryDescription: "我们从不查看或存储您访问的网站",
    helpStayFocused: "我们在这里帮助您保持专注！",
    revokeHealthPermission: "撤销健康权限",
    revokeHealthPermissionDescription:
      '抱歉，由于 Apple 的限制，我们无法撤销健康权限。如果您想撤销它，请前往"健康"应用并从那里撤销。',
    healthGroup: "健康和睡眠",
    healthGroupDescription:
      "Focus Bear 可以跟踪您的健康和睡眠数据，帮助您改善健康和睡眠。这些数据用于帮助您改善健康和睡眠。",
    areYouSure: "您确定要撤销此权限吗？",
    revokePermissionDescription: "这将撤销应用的权限。",
    experimentalGroup: "实验性",
    experimentalDescription:
      "将 Focus Bear 设置为您的默认主屏幕/启动器应用，这样您打开手机时就能立即看到您的习惯。它还能让分心应用不那么显眼。",
    blockingAppsGroup: "用于阻止应用",
    routineUpdatesGroup: "用于例程更新",
    routineUpdatesGroupDescription: "Focus Bear 会在您的早晨或晚上日程时间到时发送通知",
    urlBlockingGroup: "用于阻止网址",
    urlBlockingGroupDescription:
      "如果您想阻止网站，Focus Bear 需要无障碍权限来检测您何时访问分心网站并将您重定向离开。",
  },
  breathingExercise: {
    title: "呼吸练习",
    description: "在打开这个分心应用之前做一个快速正念练习。",
    dontWantToOpen: "不想打开 {appName}",
    wantToOpen: "继续打开 {appName}",
    motivational: "哎呀！您确定要打开 {appName} 吗？",
  },
  byPassTimePicker: {
    title: "暂停阻止以打开 {app}",
    duration: "{count} 分钟",
    intention: "你想在 {app} 中实现什么？",
    intentionInfo: "打开令人分心的应用时容易迷失方向。我会提醒你记住目标。",
    intentionRequiredError: "请在继续之前输入您的意图。",
  },
  loading: {
    loading: "加载中",
    breathingExercise: "在等待时，尝试一下方块呼吸练习。吸气3秒，屏住3秒，呼气3秒，屏住3秒。",
    loadingHabit: "加载习惯库",
    pleaseWaitLoadHabit: "我们将根据您关心的事项推荐习惯。根据您的目标，我们会从精选库中建议有帮助的习惯来帮助您开始。",
  },
  appUsage: {
    noAppsDetected: "未检测到应用",
    seeMore: "查看更多",
    close: "关闭",
    usage: "统计",
    title: "统计",
    longTitle: "应用和健康统计",
    lowQualityAppDetected: "检测到低质量应用。您想将此应用添加到阻止列表吗？",
    yes: "是",
    no: "否",
    ignore: "忽略",
    dailyAppUsage: "应用屏幕时间",
    totalTimeUsed: "总使用时间",
    doingGreat: "您做得很好！继续保持！",
    todayBlockCount: "今日阻止次数",
    focusBearUsage: "Focus Bear 使用情况",
    topBlockedApps: "最常被阻止的应用",
    blockedAppsUsage: "被阻止应用使用情况",
    timeBlocked: "被阻止次数",
    timeSpent: "花费时间",
    lastUsed: "上次使用",
    noAppsBlocked: "没有应用被阻止",
    noData: "做得好！您还没有使用任何应用",
    noPermission: "如果您授予我们应用使用权限，我们可以显示一些很酷的屏幕使用时间统计",
    grantPermission: "授予使用权限",
    overLimit: "哦不！您超出了限制",
    lowQualityScreenTime: "低质量屏幕时间",
    highQualityScreenTime: "高质量屏幕时间",
    timeUsedAfterCutoff:
      "您昨晚在睡眠时段使用手机 <bold>{duration}</bold>。\n\n想要增加阻力级别来帮助您在睡觉时远离科技产品吗？",
    timeUsedAfterCutoffTitle: "睡眠时段后使用时间",
    dontShowAgain: "不再显示",
    howDistractingIsThisApp: "这个应用有多分心？",
    dragToEdit: "拖动编辑",
    save: "保存",
    learnMore: "了解更多",
    qualityLabel: {
      extremelyDistracting: "极度分心",
      veryDistracting: "非常分散注意力",
      slightlyDistracting: "稍微分心",
      neutral: "中性",
      slightlyProductive: "稍微有生产力",
      productive: "有生产力",
      veryProductive: "非常有生产力",
    },
    qualityDescription: {
      veryDistracting: "不断争夺注意力、经常让您偏离任务的应用被认为是非常分心的。",
      distracting: "容易让您脱离重要工作并消耗大量时间的应用被认为是分心的。",
      slightlyDistracting: "可能偶尔打断您专注但可以通过一些自律来管理的应用被认为是稍微分心的。",
      neutral: "服务于实际目的而不会显著影响您生产力的应用被认为是中性的。",
      slightlyProductive: "有助于您的健康、学习或个人成长的应用被认为是稍微有生产力的。",
      productive: "帮助您完成任务、保持组织和高效工作的应用被认为是有生产力的。",
      veryProductive: "对您的工作、健康或关键日常功能至关重要的应用被认为是非常有生产力的。",
    },
    loadingMessage: {
      harvesting: "收集使用数据",
      removingGremlins: "移除统计小精灵",
      crunchingFormulas: "计算专注公式",
      assemblingMetrics: "组装进度指标",
    },
  },
  healthMetrics: {
    title: "健康统计",
    tapToView: "点击查看您的健康指标",
    tapToCollapse: "点击折叠",
    healthPermissionsRequired: "需要健康权限",
    tapToGrantPermissions: "点击授予健康权限以查看您的指标",
    sleep: "睡眠",
    activeMinutes: "活动分钟",
    steps: "步数",
    loadingHealthData: "加载健康数据...",
    error: "错误：{error}",
    physicalActivityPermissionsRequired: "需要身体活动权限",
    tapToGrantPhysicalActivityPermissions: "点击授予身体活动权限以查看您的指标",
  },
  participantCode: {
    exitUnicaesStudy: "退出 UNICAES 研究",
    enrolUnicaesStudy: "参加 UNICAES 研究",
    consentFormTitle: "同意书",
    consentFormDesc: "请阅读同意书并同意参与研究",
    whatsappConsent: "我同意每周接收一次关于研究更新的WhatsApp消息",
    invalidPhoneNumber: "请输入有效的电话号码",
    phoneNumber: "电话号码",
    enterYourPhoneNumber: "输入您的电话号码",
    unicasStudy: "UNICAES 研究",
    syncManually: "手动同步",
    facultyOfBusiness: "商业科学学院",
    facultyOfEngineering: "工程与建筑学院",
    facultyOfHumanities: "科学与人文学院",
    facultyOfHealth: "健康科学学院",
    yearLevel1: "一年级",
    yearLevel2: "二年级",
    yearLevel3: "三年级",
    yearLevel4: "四年级",
    yearLevel5: "五年级",
    wrongEmail: "参与者代码与您的电子邮件地址不匹配。请联系support@focusbear.io",
    invalidName: "请输入您的姓名",
    invalidEmail: "请输入有效的UNICAES电子邮件地址",
    invalidFaculty: "请选择您的院系",
    invalidYearLevel: "请选择您的年级",
    emailAlreadyExists: "此电子邮件已注册参与研究",
    pleaseCheckEmail: "请检查您的电子邮件以获取参与者代码",
    register: "注册",
    invalidCode: "无效的代码",
    email: "电子邮件",
    name: "姓名",
    faculty: "学院",
    yearLevel: "年级",
    enterYourName: "输入您的全名",
    enterYourEmail: "输入您的UNICAES电子邮件",
    selectFaculty: "选择您的学院",
    selectYearLevel: "选择您的年级",
    applicationForm: "申请表",
    title: "专注熊",
    description:
      "我们目前正在接受 UNICAES 试验研究的参与者。如果您想帮助我们并加入研究，请在下方申请。如果您想了解更多关于研究的信息，<hereLink>点击这里</hereLink>或联系我们 {email}。",
    moreInfoLink: "点击这里",
    contactEmail: "support@focusbear.io",
    applyButton: "申请参与",
    hasParticipantCode: "我有参与者代码",
    enterYourCode: "输入您的代码",
    continue: "继续",
    back: "返回",
    permissionNeededTitle: "需要权限",
    permissionNeededDescription: "为了参与本研究，我们需要您开启数据跟踪权限。您可以随时通过卸载 Focus Bear 退出研究。",
    uploadScreenshot: "上传截图",
    thankYouForJoining:
      "感谢您加入我们的研究，目前我们只是在收集数据，以便在为您提供 Focus Bear 全部功能之前了解您如何使用手机。如果您想退出研究，请卸载 Focus Bear。如果您需要联系支持，请发送电子邮件至：<email>support@focusbear.io</email>",
    screenshotUploadReminder:
      "屏幕使用时间，是时候上传您的截图了。请按照以下说明操作。如果您需要任何支持，请通过support@focusbear.io联系我们\n\n说明：\n\n1. 截取过去一周的应用使用情况\n2. 点击上传截图按钮\n3. 选择图片并上传",
    usageDataLastSynced: "使用数据上次同步：{date}",
    whatTimeDoYouGoToSleep: "您几点睡觉？",
    whatTimeDoYouSleepDescription: "我们将使用此信息并跟踪您在睡眠时段后的手机使用情况。",
    setupPermissions: "需要设置",
    setupPermissionsTitle: "授予应用权限",
    setupPermissionsDesc: "允许Focus Bear帮助您保持专注",
    studyTasks: "研究任务",
    flankerTaskTitle: "完成Flanker任务",
    flankerTaskDesc: "测试您的注意力和专注力",
    questionnaireTitle: "完成问卷",
    questionnaireDesc: "帮助我们了解您的体验",
    screenTime: "是时候上传您的屏幕使用时间了",
    screenshotUploadSuccess: "上传成功",
    imageProcessing: "检查使用数据...",
    imageProcessed: "截图处理成功",
    imageProcessingFailed: "处理截图失败",
    checkingStatus: "检查状态",
  },
  flankerGame: {
    title: "Flanker熊游戏",
    welcome: "欢迎来到侧翼熊游戏！这个游戏测试您的注意力和专注力。",
    instruction1: "1. 您会看到一排箭头",
    instruction2: "2. 专注于中心箭头",
    instruction3: "3. 按下与中心箭头方向匹配的按钮",
    instruction4: "4. 尽量快速准确（每次试验3秒）",
    play: "播放",
    practiceStart: "让我们做一个快速热身，这样您就知道它是如何工作的！",
    mainStart: "太好了！现在真正的测试开始了。",
    testProgress: "测试 {current}/{total}",
    ok: "确定",
    timeout: "😢",
    complete: "全部完成！",
    completeMessage: "谢谢！这帮助我们了解您的注意力是如何工作的。",
    practiceComplete: "练习完成！",
    mainInstructions: "现在让我们做真正的测试。您有 2 秒钟来响应每个试验。",
    startMain: "开始主测试",
    continue: "继续",
  },
  questionnaire: {
    title: "问卷",
    loadingQuestionnaire: "加载问卷",
  },
  routineSuggestion: {
    title: "日程建议",
    generatingRoutine: "生成例程",
    loading: "加载中",
    breathingExercise: "在等待时，观看此视频了解 Focus Bear 如何帮助您养成习惯。",
    error: "发生意外错误",
    successTitle: "例程已生成！",
    successMessage: "我们根据您的目标创建了一些示例习惯。",
    errorTitle: "哎呀！出了点问题",
    errorMessage: "我们现在无法生成您的日程。您可以重试或继续手动设置时间。",
    errorMessageGoals: "我们遇到了一些问题，无法生成您的习惯，请告诉我们您的目标是什么",
    updateGoals: "告诉我们您的目标",
    noHabitsTitle: "还没有习惯",
    noHabitsMessage: "我们无法从您的导入中找到任何习惯。让我们为您生成一些个性化习惯！",
    morningRoutine: "早晨例程",
    eveningRoutine: "晚上例程",
    totalDuration: "总计：{duration}",
    noActivities: "此例程中没有习惯",
    addActivity: "添加习惯",
    editActivity: "编辑习惯",
    adjustWithAI: "使用 AI 调整",
    createWithAI: "使用 AI 创建",
    adjust: "调整",
    create: "创建",
    aiPrompt: "🐻 这些习惯看起来怎么样？告诉我您想要什么改变。",
    aiCreatePrompt: "描述你想从头创建的例程。例如：'创建一个早晨开始例程'",
    aiPlaceholder: "例如，'让冥想更具体'或'添加快速锻炼'",
    aiError: "调整习惯失败。请重试。",
    adjusting: "调整您的习惯...",
    creating: "正在用 AI 创建...",
    aiSuccessMessage: "习惯调整成功。",
    deleteActivityTitle: "删除习惯",
    deleteActivityMessage: "您确定要删除'{activityName}'吗？",
    activityName: "习惯名称",
    enterActivityName: "输入习惯名称",
    duration: "持续时间",
    minutes: "分钟",
    seconds: "秒",
    errors: {
      nameRequired: "需要习惯名称",
      nameTooShort: "习惯名称必须至少 2 个字符",
      invalidTime: "请输入有效时间",
      timeTooShort: "时长必须至少 5 秒",
    },
    tapToEdit: "点击以编辑",
  },
  juniorBearConversation: {
    messageNormalStep1: "你好，我是 Focus Bear Junior！被召唤来帮助你专注。",
    messageNormalStep2: "其实我不太擅长专注 😢 我有多动症，总是分心。",
    messageNormalStep2_5: "哦！好的，专注大师。有什么需要帮助的吗？",
    messageNormalStep3: "手机上有这么多有趣的……我是说分心的！应用，很难专注。想组队吗？我们可以一起专注！",
    messageNormalStep4: "太棒了！您想一起做什么？",
    messageNormalStep5: "太好了。想设置一个账户，这样我们可以在您的电脑和手机上一起工作吗？",
    messagePirateStep1: "被召唤来帮助你专注，是吗？熊船长听候差遣。",
    messagePirateStep1_5: "你让我侄子哭得像个水手。所以现在是我——熊船长。站直了，你这个无赖。",
    messagePirateStep2: "说实话……我有多动症，和许多优秀的海盗一样。我的思绪像没有锚的船一样漂泊。",
    messagePirateStep2_5: "哈！我看你头脑敏锐。你还需要什么帮助？",
    messagePirateStep3: "啊，那些闪亮的应用比醉酒的鹦鹉还吵！想组队吗？我们可以互相防止掉下船！",
    messagePirateStep4: "啊，两手上甲板！你想驯服什么麻烦？",
    messagePirateStep5: "太好了！我们设置一个账户，这样我们可以在你的电脑和手机上一起航行吗？",
    buttonNormalStep1Primary: "你好",
    buttonNormalStep1Secondary: "啊，我希望你是个海盗……",
    buttonNormalStep2Primary: "我也是！",
    buttonNormalStep2Secondary: "我从来没有这个问题",
    buttonNormalStep2_5Option1: "坚持健康习惯",
    buttonNormalStep2_5Option2: "整理任务",
    buttonNormalStep2_5Option3: "走开！我不喜欢小孩！",
    buttonNormalStep3Primary: "开始吧！",
    buttonNormalStep3Secondary: "走开！我不喜欢小孩！",
    buttonNormalStep4Primary: "下一步",
    buttonNormalStep5Primary: "给我注册！",
    buttonNormalStep5Secondary: "不用了，我保持匿名",
    buttonPirateStep1Primary: "嗨",
    buttonPirateStep1Secondary: "你好，船长",
    buttonPirateStep1_5Primary: "请原谅，船长。我会保持我的海上脚步",
    buttonPirateStep2Primary: "是的…我经常丢失我的锚",
    buttonPirateStep2Secondary: "不是我，他们叫我脑胡子",
    buttonPirateStep2_5Option1: "建立更坚固的水手习惯",
    buttonPirateStep2_5Option2: "让我的任务井井有条",
    buttonPirateStep3Primary: "好的，开始吧！",
    buttonPirateStep3Secondary: "啊，让大海决定我的命运",
    buttonPirateStep4Primary: "下一步",
    buttonPirateStep5Primary: "升起风帆——给我注册！",
    buttonPirateStep5Secondary: "我将继续做海上的幽灵",
    focusAreaBlockDistractionsNormal: "阻止分心",
    focusAreaBlockDistractionsPirate: "在舵手位置上集中注意力",
    focusAreaHealthyHabitsNormal: "坚持健康习惯",
    focusAreaHealthyHabitsPirate: "建立更坚固的水手习惯",
    focusAreaOrganiseTasksNormal: "组织您的任务",
    focusAreaOrganiseTasksPirate: "让我的任务井井有条",
  },
  streakCelebration: {
    title: "{streakTypeName}连续记录！",
    morning: "早晨例程",
    evening: "晚间例程",
    focus: "专注时段",
    message: "你太棒了！继续保持。",
    day: "天",
    days: "天",
  },
  lateNoMore: {
    title: "会议提醒",
    calendarIntegration: "日历集成",
    calendarTooltip: "要启用会议检测，可以连接手机日历或 Google 日历",
    googleCalendar: "Google 日历",
    connected: "已连接",
    notConnected: "未连接",
    enableReminders: "提醒通知",
    calendarPermission: "设备日历",
    calendarPermissionAlreadyGranted: "已连接设备日历。你可以随时在手机设置中撤销访问权限",
    calendarPermissionDenied: "请在手机设置中授予日历访问权限",
    openSettings: "打开设置",
    addReminder: "添加提醒",
    durationBefore: "提前 {duration}",
    whenMeetingStarts: "会议开始时",
    requireMeetingUrl: "仅含会议的日程",
    requireMeetingUrlDescription: "仅包含附有会议链接的日程",
    notification1: "会议即将开始！🐻",
    notification2: "准备参加你的会议！⏰",
    notification3: "会议快到了！🚀",
    notificationBody: "「{title}」将于 {time} 开始",
    now: "现在",
    yourMeetingStartsIn: "距离会议还有 <highlight>{countdown}</highlight>。准备一下吧！",
    yourMeetingIsOngoing: "会议正在进行中。<highlight>现在</highlight>加入吧！",
    upcomingMeeting: "即将开始的日程",
    mentallyPrepare: "1. 为会议做好心理准备",
    howDoYouWantToShowUp: "你想以什么样的状态参与？",
    placeholderHowToShowUp: "冷静、倾听、开放、协作……",
    joinOnTime: "2. 准时加入",
    ignoreMeeting: "忽略会议",
    startMeeting: "加入会议",
    noUpcomingMeetings: "暂无即将开始的会议",
    noMeetingsDescription: "我们在接下来几小时内没有找到已安排的会议。",
    googleCalendarSource: "来源：Google 日历",
    deviceCalendarSource: "来源：设备日历",
  },
  stats: {
    title: "统计",
    tabs: {
      screentime: "屏幕使用时间",
      otherStats: "其他统计",
    },
  },
  streak: {
    title: "连续记录来了！",
    howItWorks: "每天开始一次<bold>专注时段</bold>，或<bold>完成一个晨间或晚间习惯</bold>，即可保持你的连续记录。",
    activeStreak: "活跃连续记录",
    activeStreakDesc: "你今天使用了Focus Bear。",
    dueStreak: "连续记录岌岌可危",
    dueStreakDesc: "你昨天使用了Focus Bear。今天使用它来维持记录吧。",
    inactiveStreak: "非活跃连续记录",
    inactiveStreakDesc: "你昨天没有使用Focus Bear。",
    motivationTip: "坚持比每次时间长更重要。",
    morningStreak: "晨间连续记录",
    eveningStreak: "晚间连续记录",
    focusModeStreak: "专注模式连续记录",
    streakIconTitle: "图标含义",
    day_zero: "0",
    day_one: "{count}天",
    day_other: "{count}天",
    morning: "早晨",
    evening: "晚上",
    focus: "专注",
    days: "天",
  },
  widget: {
    defaultRoutine: "无例程",
    noReasonProvided: "准备就绪！",
    noNextHabit: "没有安排",
    whatsNext: "接下来：",
    streakTitle: "连续记录",
    motivationalQuotes: [
      "“成功是日复一日微小努力的总和。” – 罗伯特·科利尔",
      "“领先的秘诀就是开始。” – 马克·吐温",
      "“自律是在你现在想要的和你最想要的之间做出选择。” – 亚伯拉罕·林肯",
      "“你的未来是由你今天所做的事创造的，而不是明天。” – 罗伯特·清崎",
      "“在完成之前，一切看起来都是不可能的。” – 纳尔逊·曼德拉",
    ],
  },
};
