export default {
  languageName: "繁體中文",
  baseLanguage: "zh-TW",
  blockingSchedule: {
    title: "封鎖時程表",
    namePlaceholder: "封鎖名稱",
    startTime: "從",
    endTime: "到",
    adjustStart: "調整開始時間",
    adjustEnd: "調整結束時間",
    daysHeading: "在這些日子",
    chooseApps: "選擇應用程式",
    chooseUrls: "選擇網站",
    saveFailedTitle: "無法儲存時程表",
    saveFailedMessage: "請在選擇要封鎖的應用程式後重試。",
    duplicateNameMessage: "請為這個封鎖時程選擇一個不重複的名稱。",
    focusModeSuffix: "（來自行動端封鎖時程）",
    defaultName: "💻 工作時間",
    appBlocking: "應用程式封鎖",
    websiteBlocking: "網站封鎖（選用）",
    accessibilityRequiredForUrls: "封鎖網站需要啟用無障礙權限。",
    selectionMissing: "請選擇要封鎖的應用程式。",
    noAppsSelected: "未選擇應用程式",
    iOSSelectionCounts: "{applicationsCount} 個應用程式、{categoriesCount} 個類別、{webDomainsCount} 個網站",
    androidSelectionCount: "已選擇 {applicationsCount} 個應用程式",
    mode: {
      strict: {
        title: "嚴格封鎖",
        subtitle: "無法逃脫 - 輸入密碼才能解鎖",
      },
      cooldown: {
        title: "冷靜封鎖",
        subtitle: "短暫等待後解鎖（給你時間重新思考）",
      },
      gentle: {
        title: "溫和封鎖",
        subtitle: "立即暫停封鎖，但有無限滾動的風險 😅",
      },
    },
    removeTitle: "刪除此時程表？",
    removeMessage: "這將永久刪除此時程表。",
    removeFailedMessage: "請重試。",
    blockedBySchedule: "被時程表封鎖：{scheduleName}",
    appBlockedBySchedule: "{appName} 被封鎖，因為你的 {scheduleName} 封鎖時程表正在運作中",
    blockAllDuringHabits: "在所有習慣期間封鎖某些應用程式",
    customizeBlocking: "自訂封鎖",
    scheduledBlocksTitle: "排程封鎖",
    scheduledBlocksInfoText: "建立在選定日期重複的時間視窗。你可以新增多個封鎖。",
    addNewBlock: "新增封鎖",
    habitMorningName: "早晨例行公事",
    allDays: "每天",
    permissionsRequired: "需要權限",
    androidPermissionDescription: "需要使用權限和覆蓋權限才能封鎖應用程式",
    iOSPermissionDescription: "需要螢幕使用時間權限才能建立和管理封鎖時程表。",
    urlsSelectionMissing: "未選擇網站",
    urlsSelectionCount_one: "已選擇 {count} 個網站",
    urlsSelectionCount_other: "已選擇 {count} 個網站",
    urlsDescription: "在此時程期間新增要封鎖的網站",
    selectedUrls: "已選網站",
    suggestedUrls: "建議網站",
    habitBlocksTitle: "習慣封鎖",
  },
  tabTitle: {
    overview: "總覽",
    habits: "習慣",
    tasks: "任務",
  },
  error: {
    invalidVideoUrl: "這個影片網址看起來不對 😕",
    videoNotFound: "抱歉，我們找不到這個影片！",
    authenticationErrorName: "驗證錯誤",
    authenticationErrorMessage: "糟糕！我們這邊的驗證出了問題。請重試。",
  },
  habitSetting: {
    routine: "例行公事",
    selectRoutine: "選擇例行公事",
    requirement: "完成此習慣需要做什麼",
    youtubeVideo: "YouTube 或 Vimeo 影片",
    youtubeVideoDescription: "新增影片來引導你完成此習慣",
    enableTimer: "啟用計時器？",
    timer: "計時器",
    timerDescription: "設定習慣的時間長度",
    goal: "目標",
    goalDescription: "達成目標後即完成習慣",
    goalPlaceholder: "指定完成目標？...",
    extras: "額外選項",
    noGoalSpecified: "未指定目標",
    defaultName: "未命名習慣",
    allowedApps: "允許的應用程式",
    allowedAppsDescription: "選擇在進行此習慣時可以使用的應用程式",
    selectApps: "選擇應用程式",
    appsSelected: "已選擇 {count} 個應用程式",
    noAppsSelected: "未選擇",
    openAllowedApps: "開啟允許的應用程式",
    launchApp: "開啟",
  },
  common: {
    accept: "接受",
    learnMore: "了解更多",
    doItLater: "稍後再做",
    later: "稍後",
    termsOfUse: "服務條款",
    privacyPolicy: "隱私權政策",
    email: "電子郵件",
    nickname: "暱稱",
    skip: "跳過",
    goToSleep: "該睡覺了 😴",
    areYouSure: "你確定嗎？",
    loading: "載入中...",
    connectionError: "連線錯誤",
    morning: "早晨",
    evening: "晚間",
    welcome: "歡迎",
    somethingWrong: "發生錯誤",
    logout: "登出",
    ok: "確定",
    ok_ellipsis: "確定...",
    okay: "確定",
    yes: "是",
    no: "否",
    confirm: "確認",
    next: "下一步",
    cancel: "取消",
    delete: "刪除",
    proceed: "繼續",
    resume: "恢復",
    retry: "重試",
    submit: "提交",
    resend: "重新發送",
    verify: "驗證",
    edit: "編輯",
    finished: "完成",
    done: "完成",
    sec: "秒",
    focusBear: "focus bear",
    tomorrow: "明天",
    today: "今天",
    yesterday: "昨天",
    add: "新增",
    start: "開始",
    startRoutine: "開始例行公事",
    continue: "繼續",
    end: "結束",
    startActivity: "開始 {activityName}",
    startTimerActivity: "開始 {time} {unit} {activityName}",
    Success: "成功！",
    SuccessfullyAddedHabit: "成功新增習慣",
    save_changes: "儲存變更",
    save: "儲存",
    saving: "儲存中",
    saved: "已儲存",
    created: "已建立",
    next_time_format: "[{day}] h:mm A",
    sure: "確定",
    uploadScreenShots: "上傳截圖\n（選填）",
    session_expired: "工作階段已過期",
    login_again: "請重新登入",
    continue_activity_name: "繼續 {activityName}",
    no_thanks: "不用了，謝謝",
    saveHabitSuccessfully: "{habitName}，已加入你的 {routineName} 例行公事",
    couldNotProcessTheRequest: "無法處理請求，請重試",
    error: "錯誤",
    selected: "已選擇",
    all: "全部",
    viewAll: "查看全部",
    more: "更多",
    somethingElse: "其他",
    habit: "習慣",
    empty: "空",
    clearAll: "清除",
    loadingWithoutDot: "載入中",
    pleaseWaitPatiently: "正在載入資料，請稍候。這可能需要幾分鐘，我們會在背景為你完成設定。",
    granted: "已授權",
    notGranted: "未授權",
  },
  customizeBlocking: {
    customBlockedMessage: {
      title: "自訂封鎖訊息",
      tooltip: "取代封鎖畫面上的預設勵志語錄。",
      placeholder: "輸入你的自訂訊息...",
      hint: "留空將使用預設的勵志語錄。",
    },
    customSoftBlocking: {
      title: "解鎖時間",
      description: "在溫和封鎖模式下休息後，應用程式保持解鎖的時間。",
      hint: "{min} 到 {max} 分鐘",
    },
    customPauseDelay: {
      title: "暫停等待時間",
      description: "解鎖被封鎖應用程式前的一道小關卡。每次嘗試都會讓下一次更難。",
      hint: "選擇 {min}s 到 {max}s",
      sequenceLabel: "你的等待時間",
    },
    saveSuccess: "自訂封鎖設定已成功儲存",
    saveError: "無法儲存自訂封鎖設定。請再試一次。",
  },
  settings: {
    healthPermission: "健康權限",
    physicalActivityPermission: "身體活動權限",
    healthAndSleepPermission: "健康與睡眠權限",
    changedBackendEndpoint: "AWS 後端端點 {status}",
    saveBlockedUrls: "成功儲存封鎖的網址",
    saveBlockedUrlsError: "儲存封鎖的網址失敗",
    debugLog: "啟用詳細記錄",
    debugLogDescription: "只有在支援團隊要求時才開啟，因為這會讓應用程式變慢",
    title: "設定",
    addApps: "將應用程式加入封鎖清單",
    clearBlocklist: "清除封鎖清單",
    confirmClearBlocklist: "確定要清除封鎖清單嗎？",
    strictness: "嚴格程度",
    shareLogsWithSupport: "回報問題",
    reason_required: "請輸入原因",
    enter_a_reason: "可以分享你為什麼要刪除帳號嗎？",
    contact_desc: "我們可以聯繫你來幫助解決你遇到的問題嗎？",
    editFriction: "阻力",
    password: "密碼",
    account: "帳號",
    permissions: "權限",
    language: "語言",
    useSystemLanguage: "使用系統語言",
    supportedLanguages: "支援的語言",
    overlay_permission: "覆蓋權限",
    usage_permission: "使用權限",
    notification_permission: "通知權限",
    screen_time_permission: "螢幕使用時間權限",
    DND_permission: "勿擾模式權限",
    DND: "封鎖通知",
    warning: "警告！",
    DND_permissionWarning: "如果勿擾模式已啟用，必須手動停用。如果未授予勿擾模式權限，則無法自動關閉。",
    help: "幫助",
    askForHelp: "尋求幫助",
    report_problem: "回報問題",
    discord_server: "Discord 伺服器",
    videoTutorials: "影片教學",
    experimental: "實驗性功能",
    customization: "自訂",
    general: "一般",
    focusGames: "專注遊戲",
    allowed: "已允許",
    notAllowed: "不允許",
    notGrantedYet: "尚未授予",
    userid: "使用者 ID",
    copy: "複製",
    copied: "已複製",
    settings: "設定",
    verifyEmail: "驗證電子郵件",
    emailVerificationResent: "已重新發送驗證電子郵件",
    pendingVerification: "等待驗證中",
    editNickname: "編輯暱稱",
    nicknameError: "無效的暱稱（只能使用字母和數字）",
    nicknameAlreadyExists: "暱稱已存在",
    customizeBlocking: "自訂封鎖",
    lateNoMore: "會議提醒",
    urlBlockingWarningTitle: "重要：網址封鎖僅在 Safari 中有效",
    urlBlockingWarningMessage:
      "網站封鎖僅在 Safari 中有效。為避免繞過網址封鎖，建議在封鎖列表中完整封鎖 Chrome、Firefox 及其他第三方瀏覽器。",
    urlBlockingHowToTitle: "如何封鎖網站",
    urlBlockingHowToMessage:
      "在下方點選「將網址加入封鎖列表」，然後在選擇器頂端選取「網站」分頁。你可以搜尋特定網站或依類別瀏覽。在專注時段中，所選網站會在 Safari 被封鎖。",
    addUrls: "將網址加入封鎖列表",
    clearBlockedUrls: "清除已封鎖的網址",
    confirmClearBlockedUrls: "確認清除已封鎖的網址？",
  },
  focus: {
    title: "專注",
    focusLimitReachedTitle: "已達專注上限",
    focusLimitReachedMessage: "在免費版本中，你只能專注最多 25 分鐘。如果想要更長的專注時段，請升級至進階版。",
  },
  blockingStatusBanner: {
    additionalSchedules: " +{count} 個",
    activeSchedule: "{name}（{start} – {end}）{extra}",
  },
  home: {
    setupHabitsDescription: "設定你的習慣來開始新的一天。",
    upEarlyStartMorningRoutine: "早起了？開始早晨例行公事",
    getMotivated: "獲取動力",
    completed: "已完成",
    habitName: "習慣名稱",
    newHabit: "新習慣...",
    duration: "時長",
    editHabit: "編輯習慣",
    addHabit: "新增習慣",
    deleteThisHabit: "刪除此習慣",
    deleteHabit: "刪除習慣 {name}",
    deleteHabitTitle: "刪除習慣",
    deleteHabitMessage: "你確定要刪除「{habitName}」嗎？此操作無法復原。",
    afterCutoffTimeDescription: "你的習慣都無法使用，因為已經過了截止時間",
    routineNotScheduledNow: "此例行公事排定在 {routineSchedule}",
    cutOffToolTip: "你已設定習慣的截止時間，因此在 {cutOffTime} 之後無法存取。\n你可以在「變更時間」中修改此設定",
    unlockToProceed: "解鎖以繼續",
    title: "首頁",
    morningRitual: "你的早晨儀式",
    eveningRitual: "你的晚間儀式",
    time_to_earn_screen_time: "完成你的早晨例行習慣，為美好的一天做好準備",
    evening_routine_text: "完成後，你將準備好迎接一夜好眠！",
    upcoming_below_new_activities: "以下是你需要在下一個例行公事中完成的習慣，才能使用你的手機。",
    start: "開始",
    mins: "分鐘",
    secs: "秒",
    re_activate: "恢復封鎖",
    force_deactivate_postpone_and_start_routine: "例行公事已延後\n恢復例行公事？",
    userCompletedRoutineHeading: "做得好，你完成了例行公事。期待在 {routineTime} 幫助你完成下一個例行公事",
    postOnboardingRoutineHeading: "歡迎加入！期待在 {routineTime} 幫助你完成 {routineName} 例行公事",
    wantLogout: "你要登出嗎？",
    noDataFound: "你還沒有設定任何習慣。點擊<fix>這裡</fix>新增習慣。",
    routineFetchingError: "我們在取得例行公事資料時遇到問題。請稍後再試或聯繫我們尋求協助",
    hi: "嗨 {nickname}！",
    welcomeDefault: "你好！",
    goodMorningFocusTime: "早安！",
    goodEveningFocusTime: "晚安！",
    allActivitiesCompleted: "沒有剩餘的習慣需要完成",
    startRoutineNow: "開始我的 {routineName} 例行公事",
    customRoutineReady: "你現在可以開始你的自訂例行公事",
    passwordForSettingsTitles: "輸入密碼以繼續",
    manageAlwaysAllowedAppsDesc:
      "在你的早晨/晚間例行公事期間，以及當你在電腦上專注時，除了「始終允許的應用程式」外，手機上的所有應用程式都會被封鎖。我們建議只允許簡訊、電話和工作所需的應用程式，這樣你在習慣/工作期間就不會分心。",
    manageAlwaysBlockedAppsDesc:
      "在你的早晨/晚間例行公事期間，以及當你在電腦上專注時，封鎖清單中的所有應用程式都會被封鎖。我們建議封鎖社群媒體、遊戲、電子郵件和新聞應用程式，這樣你就不會分心。",
    overlayPermission: "覆蓋權限",
    usagePermission: "使用權限",
    editHabits: "編輯習慣",
    editYourHabits: "編輯你的習慣",
    stats: "統計",
    motivationMsg: "獲取動力",
    play: "播放",
    pause: "暫停",
    customizeHabits: "編輯例行公事",
    deleteAccount: "刪除帳號？",
    accountDataHasBeen: "帳號資料已成功刪除。感謝你使用 Focus Bear。",
    blockSuperDistractingApps: "封鎖超級令人分心的網站/應用程式",
    skipHabitDesc: "今天跳過此習慣",
    screenTimePermissionNotAllowedWarningText: "需要螢幕使用時間權限才能封鎖應用程式，請重新開始一個習慣以允許權限",
    OverlayPermissionNotGrantedWarning: "警告：分心封鎖未啟用。覆蓋權限未授予。修復。",
    ScreenTimePermissionNotGrantedWarning: "警告：分心封鎖未啟用。螢幕使用時間權限未授予。修復。",
    UsagePermissionNotGrantedWarning: "警告：分心封鎖未啟用。使用權限未授予。修復。",
    noAllowedAppSelectedWarning: "警告：你尚未設定封鎖清單，因此分心內容不會被封鎖。編輯封鎖清單",
    habitLimitMessage: "免費用戶每個例行公事只能使用最多 3 個習慣。請升級以解鎖更多習慣。",
    routineOptionsTooltip: "在此選單可編輯例行公事或變更時間。",
    youHaveNotSetupAnyHabitsYet: "你還沒有設定任何習慣。",
    guestMode: "訪客模式",
    guestSignUpDescription: "註冊以在所有裝置上存取你的內容並解鎖個人化功能。",
    deleteRoutineTitle: "刪除例行程序",
    deleteRoutineMessage: "您確定要刪除此例行程序及所有相關習慣嗎？此操作無法復原。",
    createHeading: "建立",
    completedHabits: "已完成的習慣",
    hiddenHabits: "隱藏的習慣",
    editRoutine: "編輯例行程序",
    changeTiming: "更改時間設定",
    deleteRoutine: "刪除例行程序",
    cutoffTimeNote: "注意：您的截止時間為 {time}。未設為「高優先級」的習慣將在此時間後不可用。",
    editCutoff: "編輯截止時間",
    unavailable: "不可用",
    inProgress: "進行中",
    startsAt: "{time} 開始",
    passed: "已過",
    completedWithCount: "已完成 {count} 個",
    unavailableWithCount: "{count} 個目前不可用",
    noHabitsYetAddPrompt: "這裡還沒有任何內容。\n新增習慣？",
    routineIsEmpty: "例行程序為空",
    allHabitsHidden: "所有習慣已隱藏",
    habitsCount_zero: "$t(common.empty)",
    habitsCount_one: "{count} 個習慣",
    habitsCount_other: "{count} 個習慣",
  },
  editRoutine: {
    editTiming: "編輯時間設定",
    morningTime: "早上時間",
    wakeUp: "起床！",
    morningRoutineStartTime: "早晨例行程序開始時間",
    eveningTime: "晚上時間",
    finishWork: "結束工作",
    eveningRoutineStartTime: "晚間例行程序開始時間",
    techCurfew: "科技宵禁",
    timeToSleep: "就寢時間",
    timing: "時間設定",
    anytime: "隨時",
    scheduled: "已排程",
    doHabitsWhenever: "隨時執行這些習慣",
    doHabitsAtSpecificTime: "在特定時間或特定日期執行這些習慣",
    newRoutinePlaceholder: "新例行程序...",
    routineNamePlaceholder: "例行程序名稱",
    customRoutineDefaultName: "自訂例行程序",
    createNewRoutine: "建立新例行程序",
    time: "時間",
    wakeUpFinishWorkSameError: "起床時間和結束工作時間不能相同",
    cutoffOutOfRangeError: "睡眠時間必須在結束工作時間之後、起床時間之前",
    startBeforeEndError: "開始時間必須早於結束時間",
  },
  simpleHome: {
    setupBlocking: "設定封鎖",
    setupBlockingApp: "設定應用程式分心封鎖（建議）",
    setupBlockingUrl: "設定網站分心封鎖（選填）",
    title: "試用 Focus Bear",
    focusSessionCheckboxTitle: "完成你的第一個專注時段",
    microBreakCheckboxTitle: "做一個微休息習慣",
    focusScreenTitle: "試用專注時段",
    focusSessionCheckboxDesc: "做一些深度工作",
    microBreakCheckboxDesc: "透過深呼吸來放鬆",
    postGamePromptTitle: "做得好！",
    postGamePromptText: "想現在開始一個專注時段來完成那個任務嗎？",
    focusNowCta: "好！專注時間",
    focusGameTitle: "用專注遊戲熱身",
    focusGameDesc: "玩個快速遊戲來進入狀態",
  },
  postpone: {
    doYouReallyWantTo: "你真的要暫停嗎？",
    blockingPausedForDuration: "封鎖已暫停 {duration}",
    blockingPausedIndefinitely: "封鎖已暫停，直到你恢復",
    pauseBlocking: "暫停封鎖",
    pauseDisabledStrictMode: "啟用超級嚴格模式時無法使用暫停封鎖",
    pauseDisabledDuringSoftUnlock: "Pause blocking is unavailable while a gentle unlock period is active",
    resumeBlocking: "恢復封鎖",
    choosePostponeTime: "你想暫停多久？",
    indefinite: "暫停直到我恢復封鎖",
    youHavePausedTimesToday_zero: "這是你今天第一次暫停。",
    youHavePausedTimesToday_one: "你今天已經暫停過一次了。",
    youHavePausedTimesToday_other: "你今天已經暫停了 {count} 次。",
    countdown: "我們會在 {countdown} 後讓你暫停",
    areYouSureIndefinite:
      "你確定要無限期暫停嗎？如果你真的想要可以這樣做，但通常看似緊急的任務仍然可以等 15 分鐘，直到你完成習慣。",
    doHabits: "我還是做我的習慣吧",
    longTermGoalsDesc: "提醒一下，這是你想透過 Focus Bear 達成的目標：",
    lowQualityUsageDesc: "今天已花在低品質應用程式的時間",
    write: "留下回饋...",
  },
  passwordForSettings: {
    invalid_password: "密碼無效",
    resetAfter24Hours: "已提出重設要求。您的密碼將在 24 小時後停用。",
  },
  signIn: {
    logIn: "登入",
    enterEmailHint: "電子郵件地址",
    enterPasswordHint: "密碼",
    invalidCredentials: "無效的使用者名稱/密碼",
    enterEmailError: "請輸入電子郵件",
    enterValidEmailError: "請輸入有效的電子郵件",
    enterPasswordError: "請輸入密碼",
    dontHaveAccount: "還沒有帳號？",
    forgotPassword: "忘記密碼？",
    signup: "註冊",
    googleSignIn: "使用 Google 繼續",
    continueWithGoogle: "使用 Google 繼續",
    startWithApple: "使用 Apple 開始",
    startWithEmail: "使用電子郵件開始",
    backToSignInMethod: "返回選擇登入方式",
    alreadyHaveAccount: "我已經有 Focus Bear 帳號",
  },
  forgotPassword: {
    forgotPasswordSuccess: "密碼重設郵件已發送到你的電子郵件地址",
    forgotPasswordErrorThirdParty: "看起來你是使用第三方服務註冊的。請使用你的 Google 或 Apple 帳號繼續。",
    forgotPasswordNotVerified: "你需要驗證電子郵件地址才能重設密碼。",
    forgotPasswordEmailNotFound: "找不到電子郵件",
    forgotPasswordTitle: "忘記密碼",
    backToSignIn: "返回登入",
    resetPassword: "重設密碼",
    weveEmailedYouALinkToResetYourPassword: "我們已發送重設密碼連結到你的電子郵件。",
    forgotPasswordNotVerifiedBody:
      "You need to verify your email before you can reset your password. We can send you a new verification link now.",
    forgotPasswordNotVerifiedTitle: "Verify your email to reset your password",
    resetLinkSent: "If an account exists with this email, a password reset link has been sent.",
    verificationEmailSent: "A verification email has been sent. Please check your inbox.",
    verificationEmailFailed: "Failed to send the verification email. Please try again later.",
    cannotResetPasswordOAuthAccountTitle: "Sign in to continue",
    resetFailed: "Password Reset attempt has failed. Try again later.",
    waitBeforeRetry: "Please wait before requesting another email.",
  },
  signUp: {
    backToSignUpMethod: "返回選擇註冊方式",
    verifyEmail: "請檢查你的收件匣",
    verifyEmailMessage: "我們剛剛發送了一封驗證郵件給你。請點擊連結來驗證你的帳號。",
    signUp: "註冊",
    emailSignup: "使用電子郵件註冊",
    continueWithNoAccount: "不使用帳號繼續",
    tosAndPP: "我同意<bold>服務條款</bold>和<bold1>隱私權政策</bold1>",
    alreadyHaveAccount: "已經有帳號了？",
    passwordMatchError: "密碼和確認密碼不相符",
    acceptTerms: "請同意服務條款和隱私權政策以繼續",
    passwordHintError:
      "密碼必須包含：\n    • 至少 8 個字元\n    • 數字 (0-9)\n    • 小寫字母 (a-z)\n    • 大寫字母 (A-Z)\n    • 特殊字元 (!@#$%^&*)",
    invalidSignup: "無效的註冊",
    userExists: "此使用者已存在。",
    terms: "條款",
    privacy: "隱私",
    or: "或",
  },
  profile: {
    logout: "登出",
  },
  routineDetail: {
    activity: "活動",
    not_playable_video: "無法播放影片。",
    done: "我完成了",
    video: "影片",
    images: "圖片",
    checklist: "檢查清單",
    note: "備註",
  },
  quickBreak: {
    quickBreak: "快速休息",
    quickStretch: "伸展運動",
    stretch: "伸展",
    drinkWater: "喝水",
    water: "水",
    deepBreathing: "深呼吸",
    breathe: "呼吸",
    saveQuickBreakSuccessfully: "你的變更已成功儲存",
    editQuickBreaks: "編輯快速休息",
    quickBreakName: "快速休息名稱",
    currentSelection: "目前選擇",
  },
  complete: {
    backToHome: "返回首頁",
    logQuantity: "記錄活動數量",
    finishedCheck: "完成！✅",
    habitNotCompleted: "習慣已跳過！❌ 你明天可以做到！",
    finishedAndEarnedMorning: "完成！✅ 你已獲得螢幕使用時間",
    finishedAndEarnedEvening: "完成！✅ 你已獲得一夜好眠。明天早上見！",
    why_skip: "你為什麼要跳過？",
    already_did: "我已經做過了",
    cannot_today: "今天無法做",
    quantity_input_error: "數字需要在 {min} 和 {max} 之間。",
    freemiumLimitReached: "抱歉，免費方案只能完成 3 個習慣。",
  },
  reason: {
    canShare: "可以分享你為什麼要無限期暫停嗎？",
    shareFeedback: "分享回饋",
    everythingIsOk: "糟糕 - 希望一切都好",
    appBrokenDesc: "真的很抱歉。你介意告訴我們發生了什麼事嗎？",
    somethingElseDesc: "好的。有任何回饋想與我們分享嗎？",
    gotEmergency: "我有緊急情況",
    appBroken: "應用程式壞了",
    somethingElse: "其他",
  },
  notification: {
    backgroundService: "Focus Bear 背景服務幫助你專注",
    scheduleNotificationTitleForResumeRoutine: "恢復你的例行公事",
    scheduleNotificationDescriptionForResumeRoutine: "是時候專注於你的例行公事了",
    floatingModuleActivityCompleteNotificationtitle: "活動已完成",
    floatingModuleRoutineCompleteNotificationtitle: "例行公事已完成",
    morningRoutineCompletedNotificationDescription: "早晨例行公事已完成。美好的一天開始了！",
    eveningRoutineCompletedNotificationDescription: "晚間例行公事已完成。睡個好覺！",
    customRoutineCompletedNotificationDescription: "{{routineName}}已完成。做得好！",
  },
  focusMode: {
    blockingPaused: "封鎖已暫停",
    blockingPermissionNeeded: "封鎖未啟用：你需要授予權限",
    noBlockingAppsSelected: "封鎖未啟用：你需要選擇要封鎖的應用程式",
    distractionBlockingNotActiveTitle: "分心封鎖未啟用",
    distractionBlockingNotActiveText: "你還沒有選擇要封鎖的應用程式",
    continueWithoutBlocking: "不封鎖繼續",
    fixBlocking: "修復封鎖",
    confirmSuperStrictMode: "你確定要啟用超級嚴格模式嗎？在時段結束前你將無法退出。",
    focusIntentionTooltip: "設定你在這個專注時段要達成的目標。明確知道要達成什麼可以幫助你避免分心。",
    focusTitle: "開始專注時段",
    superStrictToolTip: "決心要完成這個專注時段？啟用超級嚴格模式，在計時器結束前你將無法關閉專注或暫停應用程式封鎖。",
    superStrictMode: "超級嚴格模式",
    brainDump: "腦力傾瀉",
    brainDumpToolTip: "在這裡記下你的想法",
    postFocusCongrats_0: "做得好！你太棒了！",
    postFocusCongrats_1: "嘿，完成得很好！接下來要做什麼？",
    postFocusCongrats_2: "你做到了！現在可以休息一下。",
    postFocusCongrats_3: "做得好！你真的很有效率！",
    postFocusCongrats_4: "太棒了！接下來要處理什麼？",
    postFocusCongrats_5: "你撐過來了！準備好處理下一個了嗎？",
    postFocusCongrats_6: "專注得很好！去喝杯飲料或吃點零食吧！",
    postFocusCongrats_7: "很好！你正在取得重大進展！",
    postFocusCongrats_8: "做得好！該起來伸展一下了？",
    postFocusCongrats_9: "你做得很棒！讓我們保持這個動力！",
    startFocusSession: "開始專注時段",
    noIntentionWasFound: "未輸入意圖",
    distractionAlertTitle: "專注模式",
    userIntention: "專注目標",
    noDistractingThoughtsWasFound: "未輸入分心想法",
    userIntentionTextInputPlaceholder: "你想專注做什麼？",
    startFocusing: "開始專注",
    hoursWithValue: "{value}小時",
    minutesWithValue: "{value}分鐘",
    secondsWithValue: "{value}秒",
    duration: {
      hours: "{hours} 小時",
      minutes: "{minutes} 分鐘",
      seconds: "{seconds} 秒",
      format: "{hours} {minutes} {seconds}",
    },
    focusingDescription: "你可以的！\n深度工作時間",
    endSession: "結束時段",
    completeFocus: "完成專注",
    userDumpThoughTextInputDescription: "在這裡寫下任何分心的想法",
    exitFocusMode: "提前結束專注時段",
    exitFocusModeDescription: "可以分享你為什麼要結束這個時段嗎？",
    reason: "原因",
    selectReason: "選擇原因",
    congratulations: "恭喜！",
    focusDoneTitle: "你做到了！",
    focusDoneDescription: "你保持專注了",
    focusDoneDescription1: "你的意圖是什麼？",
    focusDoneDescription4: "你有什麼分心的想法？",
    focusDoneDescription2: "在這段時間你達成了什麼？",
    focusDonePlaceholderDescription2: "輸入你在我們幫助下達成的事項",
    focusDoneDescription3: "你有任何分心嗎？",
    focusDonePlaceholderDescription3: "輸入你遇到的任何分心",
    endEarlyReasonDescription1: "我有緊急情況",
    endEarlyReasonDescription2: "專注模式運作不正常",
    endEarlyReasonDescription3: "我已經達成我想要的",
    endEarlyReasonDescription4: "我需要休息",
    runningFocusModeDesc: "專注時段正在進行中",
    extendFocusDuration: "延長專注時間",
    shortenFocusDuration: "縮短專注時間",
    selectExtendFocusDuration: "你想再專注多久？",
    selectShortenFocusDuration: "你想縮短多少時間？",
    extendFocus: "延長",
    shortenFocus: "縮短",
    adjustFocusDuration: "調整專注時間",
    chooseAdjustmentOption: "你想延長還是縮短你的專注時段？",
    editFocusDuration: "你想什麼時候結束專注？",
    focusMusic: "專注音樂",
    focusMusicError: "抱歉，無法播放專注音樂",
    focusNotes: "專注筆記",
  },
  toDos: {
    toDos: "待辦事項",
    todoList: "待辦清單",
    notes: "筆記",
    drafts: "AI 生成",
    notStarted: "待辦",
    inProgress: "進行中",
    completed: "已完成",
    current: "目前",
    noMoreTasks: "沒有更多任務",
    noTasksToShow: "沒有任務可顯示\n在下方新增一些來開始！",
    searchTasks: "搜尋任務",
    noTasksFound: "找不到任務",
    addATask: "新增任務",
    taskAdded: "任務已新增",
    failedToAddTask: "新增任務失敗",
    scanPaperWithOCR: "使用 OCR 掃描紙張",
    quickActions: {
      audio: "音訊",
      uploadAudio: "上傳音訊",
      recordAudio: "錄製音訊",
      upgradeRequired: "需要升級",
      upgradeMessage: "音訊和 OCR 功能可在 Focus Bear Pro 中使用。升級以解鎖這些強大的生產力工具。",
      ocrUpgradeMessage: "OCR 掃描可在 Focus Bear Pro 中使用。升級以從照片和文件中提取任務。",
    },
    ocr: {
      modalTitle: "使用 OCR 掃描紙張",
      reviewModalTitle: "檢視提取的待辦事項",
      title: "掃描你的待辦清單",
      description: "此功能可以從手寫或印刷待辦清單的照片中提取任務。你可以從相簿中選擇圖片或拍攝新照片。",
      reviewTitle: "檢視提取的待辦事項",
      reviewDescription: "選擇你想新增到清單的待辦事項。你可以稍後編輯它們。",
      selectSource: "選擇照片來源",
      selectSourceDesc: "選擇一個選項來選擇圖片",
      takePhoto: "相機",
      chooseFromGallery: "相簿",
      capturePhoto: "繼續",
      processing: "正在處理圖片...",
      uploading: "正在上傳圖片",
      error: "OCR 錯誤",
      processingError: "處理圖片失敗。請重試。",
      noTodosSelected: "未選擇待辦事項",
      selectAtLeastOne: "請至少選擇一個待辦事項來新增。",
      createTodos: "建立選定的待辦事項",
      completed: "OCR 處理完成",
      completedDesc: "你的待辦事項已成功提取！",
    },
    audio: {
      processing: "正在處理音訊...",
      completed: "音訊處理完成",
      completedDesc: "你的待辦事項已成功提取！",
      addByAudio: "透過音訊新增",
      record: "錄製",
      upload: "上傳",
      recorded: "錄製完成",
      sendOrDiscard: "點擊發送或關閉以捨棄",
    },
    due: "到期",
    dueDate: "到期日",
    exactDate: "選擇日期",
    TOP: "TOP - 任務優先順序分數",
    TOPPrioritization: "TOP 優先順序",
    timeline: "時間軸（到期日）",
    project: "專案",
    projects: "專案",
    scoreCalculation: "分數",
    addProjects: "新增專案",
    noExistingProjects: "沒有現有專案",
    createNewProject: "建立新專案",
    addATitle: "新增標題",
    addDescription: "新增描述...",
    addASubtask: "新增子任務",
    reschedule: "重新排程",
    rescheduleTitle: "重新排程任務",
    taskMovedToast: "任務已移至「{status}」",
    sortBy: "排序依據",
    filterBy: "篩選",
    filterTasksBy: "按以下條件篩選您的任務",
    listOptions: "清單選項",
    lowToHigh: "TOP 分數由低到高",
    highToLow: "TOP 分數由高到低",
    groupBy: "分組依據",
    groupedTogether: "將「待辦」和「進行中」的任務顯示在同一組",
    filterByPerspiration: "依精力篩選",
    spoonsDesc: "根據你的精力水平選擇任務（湯匙理論）。更多湯匙 = 更多精力。",
    learnAboutSpoonTheory: "了解湯匙理論",
    lowSpoons: "低精力",
    fullSpoons: "滿精力",
    perspirationLevel: "精力等級",
    filterByProject: "依專案篩選",
    noFilter: "無篩選",
    filterByDueDate: "按截止日期篩選",
    toDosDueDate: "截止日期",
    overdue: "已逾期",
    thisWeek: "本週",
    nextWeek: "下週",
    deleteTask: "刪除任務",
    deleteTaskDesc: "你確定要刪除此任務嗎？",
    deleteSubtask: "刪除子任務",
    deleteSubtaskDesc: "你確定要刪除此子任務嗎？",
    dueIn: {
      aFewDays: "兩天後",
      nextWeek: "一週後",
      twoWeeks: "兩週後",
      aMonth: "一個月後",
      aYear: "一年後",
      aYearDescription: "（哈，我永遠不會真的做這個）",
    },
    outcome: {
      outcome: "成果",
      whoCares: "無所謂",
      kindOfImportant: "有點重要",
      bigDeal: "很重要",
      huge: "非常重要",
      mindBlowing: "極其重要",
    },
    perspiration: {
      perspiration: "精力消耗",
      fiveMinuteJob: "5 分鐘工作",
      fifteenMinutesWork: "15 分鐘工作",
      halfAnHour: "半小時",
      anHour: "一小時",
      halfADay: "半天",
      aDay: "一天",
      aWeek: "一週",
    },
    searchOrCreateProject: "搜尋或建立專案",
    noMatchingProjects: '沒有相符的專案。按 Enter 鍵建立 "{search}"',
  },
  overview: {
    morningRoutine: "早晨例行公事",
    eveningRoutine: "晚間例行公事",
    noTasksCta: "還沒有任務。<bold>新增任務</bold>來開始。",
    noHabitsCta: "還沒有習慣。<bold>新增習慣</bold>來開始。",
    topTasksToday: "重要任務",
    focusModeTitle: "專注模式",
    newFocusSession: "新時段",
    focusActive: "進行中的時段",
    focusInactive: "沒有進行中的時段",
    routineCompletedShort: "✓ 已完成",
    routineCompletedMessage: "所有習慣都完成了！做得好！🎉",
    routineProgress: "{completed} / {total}",
    deadlinePrefix: "截止日期：{date}",
  },
  networkError: {
    ifTheProblemPersists: "如果問題持續存在，請直接聯繫支援團隊\nsupport@focusbear.io",
    noNetworkAlertTitle: "網路已斷開",
    retrying: "正在重試",
    connectionError: "網路連線不穩定",
    connectionErrorMessage: "請檢查你的連線",
    connectionErrorLongMessage:
      "我們在連接伺服器時遇到問題。$t(networkError.connectionErrorMessage)。$t(networkError.ifTheProblemPersists)",
    apiError: "發生錯誤",
    apiErrorMessage: "請稍後再試",
    apiErrorLongMessage:
      "處理你的請求時發生問題。$t(networkError.apiErrorMessage)。$t(networkError.ifTheProblemPersists)",
    internalError: "內部錯誤",
    internalErrorMessage: "發生錯誤了 :(",
    internalErrorLongMessage: "抱歉，發生了嚴重錯誤。$t(networkError.ifTheProblemPersists)",
  },
  manageAllowedApps: {
    searchPlaceholder: "搜尋已安裝的應用程式",
  },
  addNoteModule: {
    addNote: "新增備註",
    placeholder: "在這裡新增備註...",
    saveNote: "儲存備註",
    automaticallySave: "你的備註將自動儲存",
  },
  permissionWarning: {
    usageAccessTitle: "我們需要使用權限來幫助封鎖分心內容",
    deviceUsagedescription:
      "為了在你專注/進行習慣時封鎖令人分心的應用程式，我們需要「使用權限」以便查看你正在使用哪個應用程式",
    overlayTitle: "我們需要覆蓋權限來幫助封鎖分心內容",
    overlayDescription:
      "為了在你專注/進行習慣時封鎖令人分心的應用程式，我們需要「覆蓋權限」以便查看你正在使用哪個應用程式，並為不允許的應用程式顯示分心警告",
    privacyNoteTitle: "隱私說明",
    privacyNoteDesc: "我們不會記錄你使用哪些應用程式或網站。我們只是用於即時封鎖。",
    grantAccess: "允許",
  },
  blockingPermissionIntro: {
    introTitle: "來設定分心封鎖，讓我可以當你的專注夥伴。",
    introPrimary: "開始設定",
    introBubble: "大概會是\n這個樣子。",
    howItWorksTitle: "在你排定的專注時間裡，我會溫和地封鎖那些讓你分心的應用程式。",
    howItWorksBody: "主導權始終在你手上，你可以隨時暫停或調整。",
    howItWorksPrimary: "聽起來不錯",
    howItWorksBubble: "接下來只要點一下「繼續」就好。",
    screenTimeCongratsTitle: "很好，你已經完成這個重要步驟。",
    whatYouNeedTitle: "為了做到這件事，我需要在手機上取得幾個權限。",
    whatYouNeedPrimary: "繼續",
    whatYouNeedBubble: "例如：在你睡覺的時候封鎖讓你分心的 App。",
    scheduleCreatedTitle: "太好了，現在你已經有一個固定的作息安排。",
    scheduleCreatedPrimary: "繼續",
    scheduleCreatedBubble: "之後隨時都可以在 App 裡重新調整。",
    finishTitle: "一切都設定完成，之後我們可以一起更穩定地保持在正軌上。",
    finishPrimary: "完成",
    androidIntroTitle: "來設定分心封鎖，讓我可以當你的專注夥伴。",
    androidUsageTitle: "首先，我需要知道你在用哪些應用程式。你需要先開啟「使用情況存取」權限。",
    androidUsagePrimary: "開啟設定",
    androidUsageBubble: "試著在這個畫面裡找到這個開關。",
    androidOverlayTitle: "我會使用「顯示在其他應用程式上層」的權限，才能跳出像這樣的提示視窗。",
    androidOverlayPrimary: "開始設定",
    androidOverlayBubble: "我會向系統請求顯示提示的權限。",
    androidPermissionVisualTitle: "權限畫面大致上會長這樣。",
    androidPermissionVisualPrimary: "啟用存取",
    androidPermissionVisualBubble: "一起來\n找找看吧。",
    androidProceedPrimary: "繼續",
    androidScheduleSetupTitle: "很好。現在來設定自動封鎖時段，這樣我可以在特定時間提醒你。",
    androidScheduleSetupPrimary: "設定封鎖時段",
    androidScheduleSetupBubble: "例如：在你睡覺的時候封鎖讓你分心的 App。",
    holdOnTitle: "Hold on a minute!",
    captainBearMessage: "Arr... if you want to focus better, you've got to get your habits shipshape first.",
  },
  onboarding: {
    nextStep: {
      upNext: "接下來：{step}",
      usagePermission: "使用權限",
      overlayPermission: "覆蓋權限",
      focusSession: "專注時段",
      microBreak: "微休息",
      allDone: "全部完成",
      screenTimePermission: "螢幕使用時間權限",
    },
    wantToPersonalise: "想要個人化嗎？",
    wantToPersonaliseDescription: "設定你自己的習慣，而不是使用預設值。",
    personalise: "個人化（5 分鐘）",
    onboarding: "新手引導",
    letsDoIt: "開始吧",
    replay: "重播",
    instructionVideo: "教學影片",
    welcomeAboard: "歡迎加入！",
    lookingForwardToHelp: "是時候啟動健康習慣和深度工作了。",
    getStarted: "開始使用",
    allDone: "全部完成！",
    habitPackSelectionNotice:
      "接下來讓我們為你的早晨和晚間例行公事選擇一些習慣。\n\n\n<bold>別擔心</bold> 你隨時可以調整它們。",
    installDesktopApp: "安裝桌面應用程式",
    installDesktopAppDesc:
      "Focus Bear 也可以在 Mac 和 Windows 上使用。如果你有電腦，請從 <bold>focusbear.io</bold> 下載應用程式來同步你的專注時段和習慣。",
    cutoffTimeWarning: "停止使用科技的時間應該在結束工作時間（{time}）之後。",
    howFocusBearWork: "Focus Bear 如何運作",
    habitAndRoutine: "習慣和例行公事",
    habitAndRoutineDescription: "<bold>達成你的目標</bold>，透過激活大腦和身體的習慣",
    distractionBlocking: "封鎖分心內容",
    distractionBlockingDescription: "Focus Bear 可以封鎖<bold>應用程式</bold>和<bold>網站</bold>來幫助你完成工作",
    todoList: "待辦清單",
    todoListDescription:
      "使用 Focus Bear 待辦清單來<bold>計劃</bold>、<bold>排序優先順序</bold>和<bold>保持進度</bold>",
    andMuchMore: "還有更多",
    andMuchMorePoints: [
      "也可以在電腦上使用",
      "番茄鐘技術",
      "帶有檢查清單和影片的進階習慣",
      "早晨和晚間例行公事",
      "休息提醒",
      "有趣的熊表情符號",
    ],
    andMuchMoreDescription: "<bold>還有更多...</bold>",
    end: "結束",
    habitAI: "使用 AI 整理\n你的任務",
    habitAIDescription: "Focus Bear 可以幫助你使用人工智慧<bold>整理你的任務</bold>",
    learnAboutFeatures: "了解功能",
    setupHabitsTitle: "設定習慣來幫助你更專注",
    setupHabitsCta: "設定習慣",
    habitsPirateCopy: "好習慣能讓你一整天保持專注與敏銳。",
    habitImportPirateCopy: "我會用海洋魔法把你的習慣帶上船。",
    habits: {
      sleep: "睡眠",
      meditate: "冥想",
      exercise: "運動",
    },
    habitList: {
      nayLabel: "不用 - 給我一些習慣建議",
      ayeLabel: "好呀 - 我已經有一些習慣了",
    },
  },
  goals: {
    habitImport: {
      title: "匯入習慣",
      description: "從圖片匯入習慣或錄製你的聲音",
      importFromImage: "從圖片匯入",
      recordVoice: "錄製聲音",
      stopRecording: "停止錄製",
      selectSource: "選擇來源",
      selectImageSource: "選擇如何匯入你的習慣",
      takePhoto: "拍照",
      chooseFromGallery: "從相簿選擇",
      completed: "習慣已匯入！",
      completedDesc: "你的習慣已成功匯入",
      error: "匯入錯誤",
      processingError: "處理匯入失敗。請重試。",
      recordingError: "錄製音訊失敗。請重試。",
      processing: "正在處理你的匯入...",
      cancelRecording: "取消錄音",
    },
    addHabitList: {
      title: "新增你的習慣清單",
      description: "上傳習慣清單或告訴我們你的目標，我們的 AI 會將它們新增到 Focus Bear 應用程式中。",
      uploadScreenshot: "上傳照片",
      recordVoiceNote: "錄製語音備忘",
      typeThemIn: "手動輸入",
      or: "或",
      haveHabitListQuestion: "你有自己的習慣清單要匯入嗎？",
      importHabits: "匯入習慣",
      confirmScreenshotUpload: "確認圖片",
      confirmScreenshotUploadDesc: "這是您要上傳的圖片嗎？",
    },
    boostProductivity: "🚀 提升生產力",
    boostProductivityDescription: "（工作、學習、任務）",
    improveMentalHealth: "🧘 改善心理健康",
    improveMentalHealthDescription: "（壓力、睡眠）",
    improvePhysicalHealth: "🏋️‍♂️ 專注健康與健身",
    improvePhysicalHealthDescription: "（運動、營養）",
    manageTask: "🏡 管理家務",
    manageTaskDescription: "（清潔、雜務）",
    otherSpecify: "✏️ 其他",
    otherSpecifyDescription: "（請說明：__）",
    strengthenRelationShip: "❤️ 加強人際關係",
    strengthenRelationShipDescription: "（家人、朋友）",
    achievement_placeholder: "告訴我們你的目標",
    enableFeatures: "你想啟用哪些功能？",
    doOurBest: "我們在這裡幫助你達成目標。你想開啟哪些 Focus Bear 功能？",
    achievementWithFocusBearDesc: "你的主要目標是什麼？",
    achievementWithFocusBearDescTooltip: "我們會建議能幫助你達成目標的習慣",
    help_me_develop: "建立健康習慣",
    help_me_stay: "在工作時保持專注",
    help_me_develop_tooltip: "Focus Bear 可以在你的早晨和晚間例行公事中引導你進行健康習慣（冥想、運動、寫日記等）。",
    help_me_stay_focused_tooltip: "Focus Bear 會在你工作時封鎖分心內容，讓你可以進行深度工作。",
    blockComputerTitle: "在電腦上封鎖分心內容？",
    blockComputerQuestion: "你也想在電腦上封鎖分心內容嗎？",
    organize_tasks_using_ai: "使用 AI 整理你的任務",
    organize_tasks_using_ai_tooltip: "Focus Bear 可以使用 AI 整理你的任務",
    what_are_you_hoping_focus_bear_can_do: "你希望 Focus Bear 能做什麼？",
    what_are_you_hoping_focus_bear_can_do_placeholder: "告訴我們你希望 Focus Bear 能做什麼",
    explore_the_app_first: "先探索應用程式",
    setup_habits: "設定習慣",
    setup_habits_question: "你想現在設定習慣（大約 3 分鐘）還是先探索應用程式？",
    featureRequestReceived: "感謝你的回饋！你的想法幫助我們讓 Focus Bear 變得更好。",
  },
  goalsSteps: {
    goals: "目標",
    routine: "例行公事",
    timing: "時間",
  },
  habit: {
    habitPack: "選擇你的習慣",
    autostart: "自動啟動",
    habitAutoStart: "於 {countdown} 後開始",
    habitSkipForToday: "Habit skipped for today",
  },
  setupTime: {
    fineIfLaterOrSooner: "如果你比這個時間早起或晚起一點也沒關係 - 只要填個大概時間就好",
    morningRitualStart: "你的早晨儀式將在那時開始",
    setStartupTime: "選擇你的開始時間",
    chooseTheAbsoluteEarliest: "你幾點起床？",
    setShutdownTime: "你什麼時候結束工作/學習？",
    setSleepTime: "你想幾點睡覺？",
    focusBearWillTakeOver: "Focus Bear 會暫停封鎖\n讓你可以放鬆！",
    subDescriptionFocusBearWillTakeOver: "晚間例行公事在 {sleep_time} 開始\n（包含 30 分鐘緩衝時間）",
    focusBearWillTakeOverToolTip:
      "在下一個畫面，你會選擇想要睡覺的時間。Focus Bear 會在你睡前再次封鎖分心內容，讓你睡得好。",
    sleepTimeDesc: "{shutdown_time} - {sleep_time}：自由時間",
    subDescriptionTextKey: "{sleep_time} - {buffer_sleep_time}：晚間儀式然後睡覺",
    subDescriptionTooltipText: "{sleep_time} - {startup_time}：手機宵禁（睡眠時間）",
    distractionBlockDesc: "分心內容已封鎖 - 準備睡覺",
    techCurfewQuestion: "你想在晚上設定科技宵禁讓你睡得更好嗎？",
    techCurfewTooltip: "Focus Bear 可以在晚上封鎖手機上令人分心的應用程式，讓你睡得更好",
    bedtimeForScreens: "螢幕的就寢時間？",
    bedtimeForScreensSubtitle: "我們要讓你的手機早點休息，好讓你可以休息嗎？",
    noThanks: "不用了，謝謝",
    yesPhoneWrecksSleep: "好 - 我的手機毀了我的睡眠！",
    whatTimeGetOffTech: "你想在晚上幾點停止使用科技？",
  },
  blockList: {
    title: "在習慣/專注時段期間讓你的手機安全",
    subTitleAndroidBlockList: "選擇在進行習慣或專注時要封鎖的令人分心的應用程式",
    buttonAndroidBlockList: "選擇分心內容",
    subTitleIos: "選擇在進行習慣或專注時要封鎖的令人分心的應用程式",
    buttonIos: "選擇分心內容",
  },
  editFriction: {
    frictionTooltipDescription:
      "你當然是一個非常自律的人，但偶爾你可能會一時衝動想跳過習慣或停止封鎖分心內容。你可以設定額外的「阻力」來幫助減緩那些衝動的想法。如果你啟用高阻力模式，它會要求你等待幾秒鐘才能停止封鎖分心內容。",
    frictionForSkippingHabits: "跳過習慣的阻力",
    reallyEasy: "非常簡單 - 我想能夠快速跳過習慣/休息",
    makeItHardToSkip: "讓跳過變困難 - 否則我最終會大部分時間都跳過習慣和休息",
    appBlocking: "封鎖分心內容",
    blockDuringDaytime: "在工作日期間封鎖令人分心的應用程式",
    reallyEasyDescription: "你將能夠立即停止封鎖分心內容",
    makeItHardToSkipDescription:
      "為了避免衝動關閉封鎖，Focus Bear 可以顯示一個短暫的倒數計時器，鼓勵你重新考慮是否應該存取令人分心的應用程式。",
  },
  strictness: {
    setPassword: "設定密碼",
    setPasswordDescription: "如果你很難堅持習慣，讓室友/伴侶設定一個密碼。沒有密碼你將無法跳過習慣。",
    enterConfirmPasswordHint: "確認密碼",
    askForPassword: "要求輸入密碼",
    whenRequirePasswordDescription: "你想在什麼時候要求輸入密碼",
    changingSettings: "變更設定",
    postponingMorningRoutine: "延後/跳過早晨例行公事",
    postponingEveningRoutine: "延後/跳過晚間例行公事",
    postponingAfterCuttOffTime: "在截止時間後延後/跳過晚間例行公事",
    usingPhoneLateNight: "深夜使用手機",
    relaxFocusMode: "允許使用放鬆專注模式",
    suggestion: "建議",
  },
  subscription: {
    upgrade: "升級",
    restorePurchases: "恢復購買",
    restorePurchasesError: "收據遺失",
    restorePurchasesError2: "發生錯誤。請稍後再試。",
    personalizedHabit: "個人化習慣例行公事",
    productivityBoosting: "提升生產力的休息",
    customizedFocus: "可自訂的專注模式",
    automaticGoals: "自動目標追蹤",
    cancel: "取消自動續訂",
    subscription: "訂閱",
    trialActive: "你的試用期還剩 {day} 天。別擔心，試用期結束時不會向你收費，也不需要預先提供信用卡",
    trialActiveShort: "試用期：剩餘 {day} 天",
    getSubscriptionPlan: "取得我們的訂閱方案以使用應用程式並解鎖所有功能",
    subscriptionPlanPrice: "只需 <bold>{amount}</bold>/月即可繼續",
    benefit: "月費方案包含",
    doesSubscriptionAutoRenew: "我的訂閱會自動續訂嗎？",
    subscriptionAutoRenew:
      "此月費方案會自動續訂，除非在當前期間結束前至少 24 小時關閉自動續訂。你的帳號將在當前期間結束前 24 小時內以訂閱價格（{amount}）收取續訂費用。你可以隨時透過商店中的帳號設定管理或取消訂閱。",
    thankYouForSubscribing:
      "感謝你的訂閱，你現在可以使用 Focus Bear 的所有功能\n\n你的訂閱將在 <bold>{day}</bold> 天後到期",
    thankYouForSubscribingGuestMode:
      "感謝你的訂閱！要繼續使用 Focus Bear 訂閱的所有功能，請登入並在此畫面恢復你的訂閱。",
    thanksForSubscribingShort: "感謝你的支持 🎉",
  },
  editHabit: {
    okay: "好的",
    error: "錯誤",
    unableToSaveSettings:
      "發生錯誤。非常抱歉。我們的工程團隊已收到通知，我們會盡快修復。如果你在 24 小時內沒有收到我們的消息，請發送電子郵件至 support@focusbear.io，我們會為你解決問題。",
    goingBack: "你即將返回設定選單。如果你有任何變更，請點擊「儲存習慣」按鈕。",
    continue: "繼續",
    cancel: "取消",
    warning: "警告",
    restartingIn: "Focus Bear 將在 {seconds} 秒後重新啟動...",
    settingsSavedSuccessfully: "習慣已儲存",
  },
  shareLogs: {
    pleaseWriteFeedback: "請撰寫回饋訊息",
    enterFeedBack: "輸入你的回饋",
    logsShared: "謝謝！你的回饋報告已分享給支援團隊。",
    submitAnother: "提交另一個",
    errorUploading: "上傳記錄時發生錯誤。請確保你有穩定的網路連線並重試。$t(networkError.ifTheProblemPersists)",
    errorZipCreation: "處理檔案時發生問題。請重試。$t(networkError.ifTheProblemPersists)",
  },
  impact_reporting: {
    title: "分析你的睡眠和情緒",
    description:
      "你想追蹤你的睡眠和情緒，看看 Focus Bear 是否對你的生活產生正面影響嗎？這也會透過提供我們（匿名）應用程式影響數據來幫助我們。",
    subtitle: "我們將收集的數據",
    bulletPoints: "● 睡眠時數\n● 你的情緒和精力水平\n● 你在一天結束時感覺有多有效率",
    okSure: "好的",
    noThanks: "不用了，謝謝",
  },
  privacyModal: {
    heading: "隱私與安全",
    notShareData: "我們非常重視你的隱私和安全。我們永遠不會分享你的數據。",
    doNotLog: "• 我們不會記錄你訪問的網站或應用程式。",
    chooseToBlock:
      "• 但是，如果你想封鎖令人分心的應用程式，我們需要在資料庫中儲存這些應用程式的名稱，以便你的設定可以在所有裝置間同步。",
    dataEncrypted: "• 你的數據是加密的，我們不會讓任何人看到它。",
    moreDetails: "如需更多詳情，請參閱我們的<bold>隱私政策</bold>或隨時發送電子郵件至 support@focusbear.io",
    accept: "接受",
  },
  pushNotiPermission: {
    title: "允許通知",
    description: "我們可以提醒你保持習慣進度，並準時參加會議。",
  },
  distractionBlockingReason: {
    notLoggedIn: "封鎖已停用：你尚未登入",
    postponeActivated: "封鎖已停用：延後已啟用",
    focusModeActivated: "封鎖已啟用：專注模式已啟用",
    firstDay: "封鎖已停用：第一天 - 例行公事尚未啟用",
    otherReason: "封鎖已啟用：是時候進行你的例行公事了",
    daytimeBlockingEnabled: "封鎖已啟用：早晨例行公事已完成但日間封鎖已啟用",
    blockedBySchedule: "已啟用封鎖：封鎖排程正在生效",
    defaultCase: "封鎖已停用：分心封鎖已停用",
    withinCutoffTimeAndShutdownTime: "封鎖已停用：你有自由時間直到 {cutoff_time}",
    permissionNotGranted: "封鎖已停用：權限未授予（點擊這裡修復）",
    afterCutoffTime: "封鎖已啟用：是時候在睡前放鬆了",
    afterCutoffTimeAndEveningRoutineFinished: "封鎖已啟用：是時候睡覺了",
    detailedCutOffSleepTimeBlockingReason:
      "從 {cutoff_time} 開始封鎖分心內容，讓你可以睡覺。你的早晨例行公事設定在 {startup_time} 開始。完成早晨例行公事後，封鎖會停止。",
  },
  blocking: {
    blockingType: "封鎖類型",
    allowList: "允許清單",
    blockList: "封鎖清單",
    allowListDescription: "選擇在進行習慣或專注時允許使用的應用程式。其他所有應用程式都會被封鎖。",
    blockListDescription: "選擇在進行習慣或專注時應該封鎖的令人分心的應用程式。其他所有應用程式都會被允許。",
    appBlockList: "應用程式封鎖清單",
    appAllowList: "應用程式允許清單",
    blockAtLeastOne: "請至少選擇一個應用程式來防止自己分心",
    socialFilterTitle: "社交",
    newsFilterTitle: "新聞",
    gamesFilterTitle: "遊戲",
    miscFilterTitle: "其他",
    recommendedSectionListTitle: "建議封鎖的應用程式",
    otherSectionListTitle: "其他應用程式",
    freeAppLimitTitle: "抱歉，免費版最多只能封鎖 5 個應用程式",
    freeAppLimitDesc:
      "在免費版本中，你只能選擇 5 個應用程式來封鎖。購買 Focus Bear Pro 可以支持我們的開發，讓我們可以建立新功能來提升你的生產力 🙂",
    Success: "設定已儲存",
    saveSuccess: "應用程式偏好設定已成功儲存",
  },
  permissionExplanation: {
    distractionGetBlockedWhen: "分心內容會在以下情況被封鎖：",
    title: "設定分心封鎖的權限",
    description: "Focus Bear 可以在你工作、睡覺和進行習慣時封鎖分心內容",
    workTask: "• 你在工作/學習時，讓你完成事情 ⚒️",
    routineTask: "• 你在進行早晨和晚間例行公事時，讓你完成習慣 🧘",
    sleepTask: "• 你在睡覺時，讓你真正入睡 😴",
    toggleOption: "預設情況下，你可以隨時關閉分心封鎖。",
    friendOption: "（但你也可以選擇讓朋友設定密碼來增加難度）",
    necessaryPermission: "使用權限：用於偵測你是否開啟令人分心的應用程式\n\n覆蓋權限：這是執行分心封鎖的功能",
  },
  grantPermission: {
    title: "我們需要權限來封鎖應用程式",
    description: "別擔心，你可以隨時暫停分心封鎖",
    needHelp: "需要幫助？",
  },
  ignoreBatteryOptimization: {
    titleAndroid: "保持封鎖啟用",
    description: "透過移除電池優化，允許 Focus Bear 在背景中持續封鎖應用程式。",
    warning: "這會稍微增加電池使用量（但不會很多）。",
    keepFocusBearPoweredUp: "保持 Focus Bear 運作",
  },
  launcher: {
    title: "應用程式",
    morning: "🔆 早晨",
    evening: "🌙 晚間",
    play: "🥳 娛樂",
    work: "🔨 工作",
    setAppLabel: "為 {appName} 選擇類別",
    search: "搜尋應用程式",
    noAppsFound: "找不到應用程式",
    setAsDefaultLauncher: "預設啟動器",
    restricted: "已限制",
    restrictedMessage: "{appName} 正在被限制，請專注於你的例行公事",
    stopBlocking: "暫停封鎖",
    openAppMenuToolTip: "點擊這裡開啟應用程式選單",
  },
  DND: {
    duringFocusSessions: "在專注時段期間",
    duringHabits: "在習慣和睡眠期間",
  },
  bearsona: {
    explanation: "你想要什麼類型的熊來激勵你？Focus Bear 會相應地改變語氣",
    title: "熊角色",
    choose: "選擇熊角色",
    useCustomLanguage: "使用 {customLanguage}",
    useCustomLanguageConfirmation: "使用 {customLanguage} 作為你的語言？",
    useCustomLanguageConfirmationDesc: "警告：這很有趣但可能會有點令人困惑",
    confirmUseCustomLanguage: "用英語跟我說話",
    cancelUseCustomLanguage: "我改變主意了",
    name: {
      default: "原版熊",
      pirate: "船長熊",
      focus: "專注熊",
      jester: "小丑熊",
      sassy: "俏皮熊",
      cheerleader: "啦啦隊熊",
    },
    description: {
      default: "你友善的熊助手",
      pirate: "呀！船長熊為你服務",
      focus: "專注是我的超能力",
      jester: "小丑熊準備好玩耍了",
      sassy: "俏皮熊來這裡大展身手",
      cheerleader: "啦啦隊熊為你加油！",
    },
  },
  blockUrl: {
    addSomeSuggestedUrls: "我們在這裡新增了一些大多數人覺得令人分心的建議網站。如果需要的話可以刪除它們",
    unblockableUrlTitle: "無法封鎖網址",
    unblockableUrlMessage: "此網址無法封鎖。請輸入其他網址來封鎖。",
    freemiumLimit: "在免費版本中你只能封鎖 3 個網址。",
    freemiumLimitDescription: "升級到 Pro 版本以封鎖無限網址。",
    title: "封鎖網站",
    description: "你在哪些網站上浪費時間？",
    inputPlaceholder: "輸入要封鎖的網址...",
    urlExistsTitle: "網址已存在",
    urlExistsMessage: "請輸入其他網址來封鎖。",
    invalidUrlTitle: "無效的網址",
    invalidUrlMessage: "請輸入有效的網址來封鎖。",
    saveSuccess: "已封鎖的網址已成功儲存。",
    saveError: "儲存已封鎖的網址失敗。請重試。",
  },
  accessibility: {
    title: "無障礙權限",
    howToEnableAccessibility: "如何啟用無障礙權限",
    enableAccessibility: "啟用無障礙",
    permissionRequired: "需要無障礙權限",
    permissionDescription:
      "網站可能和應用程式一樣令人分心。如果你啟用無障礙權限，Focus Bear 也可以封鎖網站。你的手機會顯示警告 - 這是正常的！",
    whatWeDo: "這是我們做的事：",
    checkSites: "檢查你的封鎖清單",
    checkSitesDescription: "我們檢查網站是否在你設定的封鎖清單中。",
    zeroDataTracked: "就這樣。零追蹤，零數據儲存。",
  },
  passwordRules: {
    passwordRequirements: "密碼必須包含至少一個數字、一個大寫字母和一個特殊字元",
    minLength: "最少 8 個字元",
    includeNumbers: "包含數字",
    includeLowerCase: "包含小寫字母",
    includeUpperCase: "包含大寫字母",
    includeSpecialChars: "包含特殊字元",
  },
  permissions: {
    privacyFirst: "我們非常重視你的隱私",
    notTracked: "Focus Bear <bold>不會</bold>追蹤：",
    anythingType: "你輸入的任何內容",
    anythingTypeDescription: "密碼、訊息、電子郵件",
    browserHistory: "你的瀏覽記錄",
    browserHistoryDescription: "我們從不查看或儲存你訪問的網站",
    helpStayFocused: "我們在這裡幫助你保持專注！",
    revokeHealthPermission: "撤銷健康權限",
    revokeHealthPermissionDescription:
      "抱歉，由於 Apple 的限制，我們無法撤銷健康權限。如果你想撤銷它，請前往「健康」應用程式並從那裡撤銷。",
    healthGroup: "健康與睡眠",
    healthGroupDescription:
      "Focus Bear 可以追蹤你的健康和睡眠數據，幫助你改善健康和睡眠。這些數據用於幫助你改善健康和睡眠。",
    areYouSure: "你確定要撤銷此權限嗎？",
    revokePermissionDescription: "這將撤銷應用程式的權限。",
    experimentalGroup: "實驗性功能",
    experimentalDescription:
      "將 Focus Bear 設定為你的預設主畫面/啟動器應用程式，這樣當你打開手機時就能立即看到你的習慣。它還會讓令人分心的應用程式不那麼明顯。",
    blockingAppsGroup: "用於封鎖應用程式",
    routineUpdatesGroup: "用於例行公事更新",
    routineUpdatesGroupDescription: "Focus Bear 會在你的早晨或晚間例行公事時間到時發送通知給你",
    urlBlockingGroup: "用於封鎖網址",
    urlBlockingGroupDescription:
      "如果你想封鎖網站，Focus Bear 需要無障礙權限來偵測你何時訪問令人分心的網站並將你重新導向。",
  },
  breathingExercise: {
    title: "呼吸練習",
    description: "在你開啟這個令人分心的應用程式之前，做一個快速的正念練習。",
    dontWantToOpen: "不想開啟 {appName}",
    wantToOpen: "繼續前往 {appName}",
    motivational: "哎呀！你確定要開啟 {appName} 嗎？",
  },
  byPassTimePicker: {
    title: "暫停封鎖以開啟 {app}",
    duration: "{count} 分鐘",
    intention: "你想在 {app} 中達成什麼？",
    intentionInfo: "打開令人分心的應用程式時容易迷失方向。我會提醒你記住目標。",
    intentionRequiredError: "請在繼續之前輸入您的意圖。",
  },
  loading: {
    loading: "載入中",
    breathingExercise: "在等待時，試試箱式呼吸練習。吸氣 3 秒，屏住 3 秒，呼氣 3 秒，屏住 3 秒。",
    loadingHabit: "正在載入習慣庫",
    pleaseWaitLoadHabit:
      "我們會根據對你重要的事情推薦習慣。根據你的目標，我們會從精選習慣庫中建議有幫助的習慣來幫助你開始。",
  },
  appUsage: {
    noAppsDetected: "未偵測到應用程式",
    seeMore: "查看更多",
    close: "關閉",
    usage: "統計",
    title: "統計",
    longTitle: "應用程式與健康統計",
    lowQualityAppDetected: "偵測到低品質應用程式。你想將此應用程式新增到封鎖清單嗎？",
    yes: "是",
    no: "否",
    ignore: "忽略",
    dailyAppUsage: "應用程式螢幕使用時間",
    totalTimeUsed: "總使用時間",
    doingGreat: "你做得很好！繼續保持！",
    todayBlockCount: "今日封鎖次數",
    focusBearUsage: "Focus Bear 使用情況",
    topBlockedApps: "最常被封鎖的應用程式",
    blockedAppsUsage: "被封鎖應用程式使用情況",
    timeBlocked: "被封鎖次數",
    timeSpent: "花費時間",
    lastUsed: "上次使用",
    noAppsBlocked: "沒有應用程式被封鎖",
    noData: "做得好！你還沒有使用任何應用程式",
    noPermission: "如果你授予我們應用程式使用權限，我們可以顯示一些很酷的螢幕使用時間統計",
    grantPermission: "授予使用權限",
    overLimit: "哎呀！你超過限制了",
    lowQualityScreenTime: "低品質螢幕使用時間",
    highQualityScreenTime: "高品質螢幕使用時間",
    timeUsedAfterCutoff:
      "你昨晚在睡眠時段使用手機 <bold>{duration}</bold>。\n\n想要增加阻力等級來幫助你在睡覺時遠離科技嗎？",
    timeUsedAfterCutoffTitle: "睡眠時段後的使用時間",
    dontShowAgain: "不再顯示",
    howDistractingIsThisApp: "這個應用程式有多令人分心？",
    dragToEdit: "拖動以編輯",
    save: "儲存",
    learnMore: "了解更多",
    qualityLabel: {
      extremelyDistracting: "極度令人分心",
      veryDistracting: "非常令人分心",
      slightlyDistracting: "稍微令人分心",
      neutral: "中性",
      slightlyProductive: "稍微有生產力",
      productive: "有生產力",
      veryProductive: "非常有生產力",
    },
    qualityDescription: {
      veryDistracting: "不斷爭奪注意力、經常讓你偏離任務的應用程式被認為是非常令人分心的。",
      distracting: "容易讓你從重要工作中分心並消耗大量時間的應用程式被認為是令人分心的。",
      slightlyDistracting: "可能偶爾打斷你的專注但可以透過一些自律來管理的應用程式被認為是稍微令人分心的。",
      neutral: "服務於實際目的而不會顯著影響你生產力的應用程式被認為是中性的。",
      slightlyProductive: "有助於你的健康、學習或個人成長的應用程式被認為是稍微有生產力的。",
      productive: "幫助你完成任務、保持組織和高效工作的應用程式被認為是有生產力的。",
      veryProductive: "對你的工作、健康或關鍵日常功能來說是必要工具的應用程式被認為是非常有生產力的。",
    },
    loadingMessage: {
      harvesting: "正在收集使用數據",
      removingGremlins: "正在移除統計小精靈",
      crunchingFormulas: "正在計算專注公式",
      assemblingMetrics: "正在組裝進度指標",
    },
  },
  healthMetrics: {
    title: "健康統計",
    tapToView: "點擊查看你的健康指標",
    tapToCollapse: "點擊收合",
    healthPermissionsRequired: "需要健康權限",
    tapToGrantPermissions: "點擊授予健康權限以查看你的指標",
    sleep: "睡眠",
    activeMinutes: "活動分鐘數",
    steps: "步數",
    loadingHealthData: "正在載入健康數據...",
    error: "錯誤：{error}",
    physicalActivityPermissionsRequired: "需要身體活動權限",
    tapToGrantPhysicalActivityPermissions: "點擊授予身體活動權限以查看你的指標",
  },
  participantCode: {
    exitUnicaesStudy: "退出 UNICAES 研究",
    enrolUnicaesStudy: "加入 UNICAES 研究",
    consentFormTitle: "同意書",
    consentFormDesc: "請閱讀同意書並同意參與研究",
    whatsappConsent: "我同意每週接收一次關於研究更新的 WhatsApp 訊息",
    invalidPhoneNumber: "請輸入有效的電話號碼",
    phoneNumber: "電話號碼",
    enterYourPhoneNumber: "輸入你的電話號碼",
    unicasStudy: "UNICAES 研究",
    syncManually: "手動同步",
    facultyOfBusiness: "商學院",
    facultyOfEngineering: "工程與建築學院",
    facultyOfHumanities: "科學與人文學院",
    facultyOfHealth: "健康科學學院",
    yearLevel1: "一年級",
    yearLevel2: "二年級",
    yearLevel3: "三年級",
    yearLevel4: "四年級",
    yearLevel5: "五年級",
    wrongEmail: "參與者代碼與你的電子郵件地址不符。請聯繫 support@focusbear.io",
    invalidName: "請輸入你的姓名",
    invalidEmail: "請輸入有效的 UNICAES 電子郵件地址",
    invalidFaculty: "請選擇你的學院",
    invalidYearLevel: "請選擇你的年級",
    emailAlreadyExists: "此電子郵件已註冊參與研究",
    pleaseCheckEmail: "請檢查你的電子郵件以獲取參與者代碼",
    register: "註冊",
    invalidCode: "無效的代碼",
    email: "電子郵件",
    name: "姓名",
    faculty: "學院",
    yearLevel: "年級",
    enterYourName: "輸入你的全名",
    enterYourEmail: "輸入你的 UNICAES 電子郵件",
    selectFaculty: "選擇你的學院",
    selectYearLevel: "選擇你的年級",
    applicationForm: "申請表",
    title: "Focus Bear",
    description:
      "我們目前正在接受 UNICAES 試驗研究的參與者。如果你想幫助我們並加入研究，請在下方申請。如果你想了解更多關於研究的資訊，<hereLink>請點擊這裡</hereLink>或聯繫我們 {email}。",
    moreInfoLink: "請點擊這裡",
    contactEmail: "support@focusbear.io",
    applyButton: "申請參與",
    hasParticipantCode: "我有參與者代碼",
    enterYourCode: "輸入你的代碼",
    continue: "繼續",
    back: "返回",
    permissionNeededTitle: "需要權限",
    permissionNeededDescription:
      "為了參與此研究，我們需要你開啟數據追蹤權限。你可以隨時透過解除安裝 Focus Bear 來退出研究。",
    uploadScreenshot: "上傳螢幕截圖",
    thankYouForJoining:
      "感謝你加入我們的研究，目前我們只是在收集數據，以便在給你完整存取 Focus Bear 功能之前了解你如何使用手機。如果你想退出研究，請解除安裝 Focus Bear。如果你需要聯繫支援，請發送電子郵件至：<email>support@focusbear.io</email>",
    screenshotUploadReminder:
      "螢幕使用時間，是時候上傳你的螢幕截圖了。請按照以下說明操作。如果你需要任何支援，請聯繫我們：support@focusbear.io\n\n說明：\n\n1. 截取過去一週的應用程式使用情況\n2. 點擊上傳螢幕截圖按鈕\n3. 選擇圖片並上傳",
    usageDataLastSynced: "使用數據上次同步：{date}",
    whatTimeDoYouGoToSleep: "你幾點睡覺？",
    whatTimeDoYouSleepDescription: "我們會使用這個資訊並追蹤你在睡眠時段後的手機使用情況。",
    setupPermissions: "需要設定",
    setupPermissionsTitle: "授予應用程式權限",
    setupPermissionsDesc: "允許 Focus Bear 幫助你保持專注",
    studyTasks: "研究任務",
    flankerTaskTitle: "完成 Flanker 任務",
    flankerTaskDesc: "測試你的注意力和專注力",
    questionnaireTitle: "完成問卷",
    questionnaireDesc: "幫助我們了解你的體驗",
    screenTime: "是時候上傳你的螢幕使用時間了",
    screenshotUploadSuccess: "上傳成功",
    imageProcessing: "正在檢查使用數據...",
    imageProcessed: "螢幕截圖處理成功",
    imageProcessingFailed: "處理螢幕截圖失敗",
    checkingStatus: "正在檢查狀態",
  },
  flankerGame: {
    title: "Flanker 熊遊戲",
    welcome: "歡迎來到 Flanker 熊遊戲！這個遊戲測試你的注意力和專注力。",
    instruction1: "1. 你會看到一排箭頭",
    instruction2: "2. 專注於中間的箭頭",
    instruction3: "3. 按下與中間箭頭方向相符的按鈕",
    instruction4: "4. 盡量快速且準確（每次測試 3 秒）",
    play: "開始",
    practiceStart: "讓我們做個快速熱身，讓你知道它是如何運作的！",
    mainStart: "太棒了！現在真正的測試開始了。",
    testProgress: "測試 {current} / {total}",
    ok: "好的",
    timeout: "😢",
    complete: "全部完成！",
    completeMessage: "謝謝！這幫助我們了解你的注意力是如何運作的。",
    practiceComplete: "練習完成！",
    mainInstructions: "現在讓我們進行真正的測試。你有 2 秒鐘來回應每次測試。",
    startMain: "開始正式測試",
    continue: "繼續",
  },
  questionnaire: {
    title: "問卷",
    loadingQuestionnaire: "正在載入問卷",
  },
  routineSuggestion: {
    title: "例行公事建議",
    generatingRoutine: "正在生成例行公事",
    loading: "載入中",
    breathingExercise: "在等待時，看看這個影片了解 Focus Bear 如何幫助你建立習慣。",
    error: "發生意外錯誤",
    successTitle: "例行公事已生成！",
    successMessage: "我們根據你的目標建立了一些範例習慣。",
    errorTitle: "哎呀！發生錯誤了",
    errorMessage: "我們現在無法生成你的例行公事。你可以重試或繼續手動設定你的時間。",
    errorMessageGoals: "我們遇到了一些問題，無法生成你的習慣，請告訴我們你的目標是什麼",
    updateGoals: "告訴我們你的目標",
    noHabitsTitle: "還沒有習慣",
    noHabitsMessage: "我們從你的匯入中找不到任何習慣。讓我們為你生成一些個人化的習慣！",
    morningRoutine: "早晨例行公事",
    eveningRoutine: "晚間例行公事",
    totalDuration: "總計：{duration}",
    noActivities: "此例行公事中沒有習慣",
    addActivity: "新增習慣",
    editActivity: "編輯習慣",
    adjustWithAI: "使用 AI 調整",
    createWithAI: "使用 AI 建立",
    adjust: "調整",
    create: "建立",
    aiPrompt: "🐻 這些習慣看起來如何？告訴我你想要什麼變更。",
    aiCreatePrompt: "描述你想從頭建立的例行公事。例如：「建立一個早晨開始的例行公事」",
    aiPlaceholder: "例如：「讓冥想更具體」或「新增一個快速運動」",
    aiError: "調整習慣失敗。請重試。",
    adjusting: "正在調整你的習慣...",
    creating: "正在用 AI 建立...",
    aiSuccessMessage: "習慣調整成功。",
    deleteActivityTitle: "刪除習慣",
    deleteActivityMessage: "你確定要刪除「{activityName}」嗎？",
    activityName: "習慣名稱",
    enterActivityName: "輸入習慣名稱",
    duration: "持續時間",
    minutes: "分鐘",
    seconds: "秒",
    errors: {
      nameRequired: "習慣名稱為必填",
      nameTooShort: "習慣名稱必須至少 2 個字元",
      invalidTime: "請輸入有效的時間",
      timeTooShort: "持續時間必須至少 5 秒",
    },
    tapToEdit: "點擊以編輯",
  },
  juniorBearConversation: {
    messageNormalStep1: "你好，我是 Focus Bear 小熊！被召喚來幫助你專注。",
    messageNormalStep2: "其實我不太擅長專注 😢 我有 ADHD，總是會分心。",
    messageNormalStep2_5: "哦！好的，專注大師。有什麼你需要幫助的嗎？",
    messageNormalStep3: "有這麼多有趣的……我是說令人分心的！應用程式在手機上，很難專注。想要組隊嗎？我們可以一起專注！",
    messageNormalStep4: "太棒了！你想一起做什麼？",
    messageNormalStep5: "太好了。想要設定一個帳號，這樣我們可以在你的電腦和手機上一起工作嗎？",
    messagePirateStep1: "被召喚來幫你專注的嗎？船長熊聽候差遣。",
    messagePirateStep1_5: "你讓我的侄子哭得像個水手。所以現在換我了——船長熊。站直了，你這個小流氓。",
    messagePirateStep2: "說實話……我有 ADHD，就像許多優秀的海盜一樣。我的思緒像沒有錨的船一樣漂泊。",
    messagePirateStep2_5: "哈！我看你頭腦很靈光。你還需要什麼幫助？",
    messagePirateStep3: "啊，那些閃亮的應用程式比醉酒的鸚鵡還吵！想要組隊嗎？我們可以互相防止掉進海裡！",
    messagePirateStep4: "啊，兩隻手都在甲板上！你想要馴服什麼麻煩？",
    messagePirateStep5: "太好了！要設定一個帳號，這樣我們可以在你的電腦和手機上一起航行嗎？",
    buttonNormalStep1Primary: "你好",
    buttonNormalStep1Secondary: "啊，我希望你是海盜……",
    buttonNormalStep2Primary: "我也是！",
    buttonNormalStep2Secondary: "我從來沒有這個問題",
    buttonNormalStep2_5Option1: "堅持健康習慣",
    buttonNormalStep2_5Option2: "整理任務",
    buttonNormalStep2_5Option3: "走開！我不喜歡小孩！",
    buttonNormalStep3Primary: "開始吧！",
    buttonNormalStep3Secondary: "走開！我不喜歡小孩！",
    buttonNormalStep4Primary: "下一步",
    buttonNormalStep5Primary: "幫我註冊吧！",
    buttonNormalStep5Secondary: "不用了，謝謝，我想保持匿名",
    buttonPirateStep1Primary: "嗨",
    buttonPirateStep1Secondary: "船長好",
    buttonPirateStep1_5Primary: "抱歉，船長。我會保持平衡的",
    buttonPirateStep2Primary: "是的……我經常找不到我的錨",
    buttonPirateStep2Secondary: "不是我，他們叫我腦袋鬍子",
    buttonPirateStep2_5Option1: "建立更堅固的水手習慣",
    buttonPirateStep2_5Option2: "讓我的任務井井有條",
    buttonPirateStep3Primary: "好的，開始吧！",
    buttonPirateStep3Secondary: "啊，讓大海決定我的命運",
    buttonPirateStep4Primary: "下一步",
    buttonPirateStep5Primary: "升起風帆——幫我註冊！",
    buttonPirateStep5Secondary: "我會繼續當海上的幽靈",
    focusAreaBlockDistractionsNormal: "封鎖分心內容",
    focusAreaBlockDistractionsPirate: "在舵手位置磨練我的專注力",
    focusAreaHealthyHabitsNormal: "堅持健康習慣",
    focusAreaHealthyHabitsPirate: "建立更堅固的水手習慣",
    focusAreaOrganiseTasksNormal: "整理你的任務",
    focusAreaOrganiseTasksPirate: "讓我的任務井井有條",
  },
  streakCelebration: {
    title: "{streakTypeName}連續記錄！",
    morning: "早晨例行公事",
    evening: "晚間例行公事",
    focus: "專注時段",
    message: "你太厲害了！繼續保持。",
    day: "天",
    days: "天",
  },
  lateNoMore: {
    title: "會議提醒",
    calendarIntegration: "行事曆整合",
    calendarTooltip: "若要啟用會議偵測，可以連結手機行事曆或 Google 行事曆",
    googleCalendar: "Google 行事曆",
    connected: "已連線",
    notConnected: "未連線",
    enableReminders: "提醒通知",
    calendarPermission: "裝置行事曆",
    calendarPermissionAlreadyGranted: "已連線裝置行事曆。你可以隨時在手機設定中撤銷存取權",
    calendarPermissionDenied: "請在手機設定中授予行事曆存取權限",
    openSettings: "開啟設定",
    addReminder: "新增提醒",
    durationBefore: "提前 {duration}",
    whenMeetingStarts: "會議開始時",
    requireMeetingUrl: "僅限含會議的行程",
    requireMeetingUrlDescription: "僅包含附有會議連結的行程",
    notification1: "會議即將開始！🐻",
    notification2: "準備好前往你的會議！⏰",
    notification3: "會議快到了！🚀",
    notificationBody: "「{title}」將於 {time} 開始",
    now: "現在",
    yourMeetingStartsIn: "距離會議還有 <highlight>{countdown}</highlight>。準備一下吧！",
    yourMeetingIsOngoing: "會議正在進行中。<highlight>現在</highlight>加入吧！",
    upcomingMeeting: "即將到來的行程",
    mentallyPrepare: "1. 為會議做好心理準備",
    howDoYouWantToShowUp: "你想以什麼狀態參與？",
    placeholderHowToShowUp: "冷靜、傾聽、開放、協作……",
    joinOnTime: "2. 準時加入",
    ignoreMeeting: "忽略會議",
    startMeeting: "加入會議",
    noUpcomingMeetings: "沒有即將開始的會議",
    noMeetingsDescription: "我們在接下來幾小時內找不到已排定的會議。",
    googleCalendarSource: "來源：Google 行事曆",
    deviceCalendarSource: "來源：裝置行事曆",
  },
  stats: {
    title: "統計",
    tabs: {
      screentime: "螢幕使用時間",
      otherStats: "其他統計",
    },
  },
  streak: {
    title: "連續記錄來了！",
    howItWorks: "每天開始一次<bold>專注時段</bold>，或<bold>完成一個晨間或晚間習慣</bold>，即可保持你的連續記錄。",
    activeStreak: "活躍連續記錄",
    activeStreakDesc: "你今天使用了Focus Bear。",
    dueStreak: "連續記錄岌岌可危",
    dueStreakDesc: "你昨天使用了Focus Bear。今天使用它來維持記錄吧。",
    inactiveStreak: "非活躍連續記錄",
    inactiveStreakDesc: "你昨天沒有使用Focus Bear。",
    motivationTip: "堅持比每次時間長更重要。",
    morningStreak: "晨間連續記錄",
    eveningStreak: "晚間連續記錄",
    focusModeStreak: "專注模式連續記錄",
    streakIconTitle: "圖示含義",
    day_zero: "0",
    day_one: "{count}天",
    day_other: "{count}天",
    morning: "早晨",
    evening: "晚上",
    focus: "專注",
    days: "天",
  },
  widget: {
    defaultRoutine: "無例程",
    noReasonProvided: "準備就緒！",
    noNextHabit: "沒有安排",
    whatsNext: "接下來：",
    streakTitle: "連續記錄",
    motivationalQuotes: [
      "「成功是日復一日微小努力的總和。」 – 羅伯特·科利爾",
      "「領先的秘訣就是開始。」 – 馬克·吐溫",
      "「自律是在你現在想要的和你最想要的之間做出選擇。」 – 亞伯拉罕·林肯",
      "「你的未來是由你今天所做的事創造的，而不是明天。」 – 羅伯特·清崎",
      "「在完成之前，一切看起來都是不可能的。」 – 納爾遜·曼德拉",
    ],
  },
};
