export const FORGOT_PASSWORD_ERROR_TYPES = {
  OAUTH_ACCOUNT_THIRD_PARTY: "OAUTH_ACCOUNT",
  UNVERIFIED_EMAIL: "UNVERIFIED_EMAIL",
  EMAIL_DOES_NOT_EXIST: "EMAIL_DOES_NOT_EXIST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED",
};

export const FRICTION_PASSWORD_RESET_COOLDOWN_SECONDS = 24 * 60 * 60;
