import COLOR, { FONTFAMILY } from "@/constants/color";
import { StyleSheet } from "react-native";

export const styles = (colors) =>
  StyleSheet.create({
    container: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.background,
    },
    checkBoxContainerStyle: {
      backgroundColor: colors.background,
      marginRight: 0,
      marginBottom: 0,
      marginTop: 0,
    },
    textField: {
      flex: 1,
      height: 50,
      backgroundColor: colors.card,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: 10,
      alignSelf: "center",
      paddingHorizontal: 12,
      paddingRight: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    flatListContainer: {
      flex: 1,
      width: "100%",
      height: "100%",
      paddingHorizontal: 20,
    },
    listEmptyContainer: { alignContent: "center", alignSelf: "center", justifyContent: "center", marginTop: 20 },
    listEmptyText: {
      color: colors.text,
      fontSize: 16,
      textAlign: "center",
    },
    appItemContainer: {
      marginVertical: 8,
      flexDirection: "row",
      alignItems: "center",
    },
    image_style: {
      height: 32,
      width: 32,
    },
    itemLabel: {
      paddingLeft: 8,
      color: colors.text,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      alignContent: "center",
      marginTop: 12,
      paddingLeft: 8,
      paddingRight: 16,
    },
    backButton: {
      paddingRight: 8,
    },
    lockedApp: {
      position: "absolute",
      color: COLOR.BLACK,
      backgroundColor: COLOR.BLACK,
      opacity: 0.6,
      width: 32,
      height: 32,
      alignContent: "center",
      justifyContent: "center",
      alignItems: "center",
    },
    appIconContainer: {
      borderRadius: 400,
      width: 32,
      height: 32,
      alignContent: "center",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    openAppMenuButton: {
      width: 50,
      height: 50,
      position: "absolute",
      top: 0,
      right: 0,
      backgroundColor: colors.primary,
      margin: 8,
      borderRadius: 1000,
      alignItems: "center",
      justifyContent: "center",
    },
    square: {
      width: 10,
      height: 10,
      backgroundColor: COLOR.ALTERNATIVE_ACTION,
      position: "absolute",
      right: 7,
      top: -4,
      transform: [{ rotate: "45deg" }],
    },
    tooltip: {
      height: 30,
      width: 220,
      backgroundColor: COLOR.ALTERNATIVE_ACTION,
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      right: 15,
      top: 60,
    },
    textStyle: {
      fontSize: 10,
      fontFamily: FONTFAMILY.FENWICK,
    },
    itemNameContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      flex: 1,
    },
    modalView: {
      margin: 20,
      borderRadius: 8,
      padding: 20,
      alignItems: "center",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
      width: "90%",
      borderWidth: 1,
      borderColor: colors.border,
    },
    setAppLabelHeader: {
      fontSize: 20,
      fontWeight: "bold",
      fontFamily: FONTFAMILY.FENWICK,
      paddingBottom: 16,
    },
    modalText: {
      fontSize: 16,
      paddingBottom: 8,
    },
    labelContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
    },
    labelFilterContainer: { flexDirection: "row", justifyContent: "space-around", padding: 10 },
    labelFilterItemContainer: {
      paddingVertical: 8,
      alignItems: "center",
      borderRadius: 8,
    },
    labelFilterChipSelected: {
      backgroundColor: colors.primary,
    },
    labelFilterChipUnselected: {
      backgroundColor: colors.card,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    labelFilterChipTextSelected: {
      color: colors.white,
    },
    labelFilterChipTextUnselected: {
      color: colors.text,
    },
    textInputContainer: {
      color: colors.text,
      flex: 1,
    },
  });
